<!--
Copyright 2024 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <file-drop-zone id="entity-upload-file-select" :disabled="disabled"
    @drop="$emit('change', $event.dataTransfer.files[0])">
    <div id="entity-upload-file-select-heading">
      <p v-if="errors !== 0">{{ $tcn('errors', errors) }}</p>
      <p v-else-if="dataTemplate">{{ $t('upload') }}</p>

      <div>
        <i18n-t keypath="text.full">
          <template #chooseFile>
            <!-- eslint-disable-next-line vuejs-accessibility/form-control-has-label -->
            <input v-show="false" ref="input" type="file" accept=".csv,.tsv"
              @change="changeInput">
            <button type="button" class="btn btn-outlined" :aria-disabled="disabled"
              @click="input.click()">
              {{ $t('text.chooseFile') }}
            </button>
          </template>
        </i18n-t>
        <template v-if="dataTemplate">
          <sentence-separator/>
          <entity-upload-data-template/>
        </template>
      </div>
      <div v-show="parsing"><spinner inline/>{{ $t('parsing') }}</div>
    </div>
  </file-drop-zone>
</template>

<script setup>
import { ref } from 'vue';

import EntityUploadDataTemplate from './data-template.vue';
import FileDropZone from '../../file-drop-zone.vue';
import SentenceSeparator from '../../sentence-separator.vue';
import Spinner from '../../spinner.vue';

defineOptions({
  name: 'EntityUploadFileSelect'
});
defineProps({
  // `true` to render EntityUploadDataTemplate; `false` not to.
  dataTemplate: Boolean,
  // Number of errors
  errors: {
    type: Number,
    default: 0
  },
  disabled: Boolean,
  parsing: Boolean
});
const emit = defineEmits(['change']);

const input = ref(null);
const changeInput = (event) => {
  emit('change', event.target.files[0]);
  input.value.value = '';
};
</script>

<style lang="scss">
#entity-upload-file-select {
  background-color: transparent;
  border-radius: 12px;
  margin-top: 20px;
  padding: 30px 20px;

  &.disabled { opacity: 1; }
}

#entity-upload-file-select-heading {
  margin-bottom: 1px;
  position: relative;

  .disabled > & > :not(:last-child) { opacity: 0.09; }

  > p:first-child {
    font-size: 16px;
    font-weight: bold;
    margin-bottom: 20px;
  }

  // Spinner container
  > :last-child {
    position: absolute;
    left: 50%;
    transform: translateX(-50%);

    font-size: 16px;
  }

  .spinner {
    margin-right: 6px;
    top: 1px;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "upload": "Upload a .csv file",
    "errors": "{count} error must be fixed before appending Entities | {count} errors must be fixed before appending Entities",
    "text": {
      "full": "Drag and drop a .csv file here, or {chooseFile}",
      "chooseFile": "choose a file"
    },
    "parsing": "Reading data…"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "text": {
      "full": "Fügen Sie hier eine Datei mit Drag-and-Drop ein, oder {chooseOne} zum Hochladen.",
      "chooseOne": "eine auswählen"
    },
    "parsing": "Daten lesen..."
  },
  "es": {
    "text": {
      "full": "Arrastre un archivo .csv aquí, o {chooseOne} para subir.",
      "chooseOne": "elige uno"
    },
    "parsing": "Leyendo datos..."
  },
  "fr": {
    "text": {
      "full": "Glissez un fichier .csv ici, ou {chooseOne} pour l'importer.",
      "chooseOne": "Choisissez en un"
    },
    "parsing": "Lecture des données..."
  },
  "it": {
    "text": {
      "full": "Trascina un file .csv qui, o {chooseOne} per caricarlo.",
      "chooseOne": "scegli uno"
    },
    "parsing": "Lettura dei dati…"
  },
  "pt": {
    "text": {
      "full": "Arraste um arquivo .csv aqui ou {chooseOne} para importar.",
      "chooseOne": "escolha um"
    },
    "parsing": "Lendo dados…"
  },
  "zh": {
    "text": {
      "full": "请将.csv文件拖拽至此，或者{chooseOne}进行导入",
      "chooseOne": "请选择一个"
    },
    "parsing": "读取数据..."
  },
  "zh-Hant": {
    "text": {
      "full": "拖曳一個 .csv 檔案到這，或者 {chooseOne}進行匯入。",
      "chooseOne": "選擇一個檔案"
    },
    "parsing": "讀取資料..."
  }
}
</i18n>
