<!--
Copyright 2024 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="entity-upload-popup">
    <div id="entity-upload-popup-heading" v-tooltip.text>{{ filename }}</div>
    <div id="entity-upload-popup-count">{{ $tcn('rowCount', count) }}</div>
    <div id="entity-upload-popup-status">
      <spinner inline/><span>{{ status }}</span>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import Spinner from '../../spinner.vue';

defineOptions({
  name: 'EntityUploadPopup'
});
const props = defineProps({
  filename: {
    type: String,
    required: true
  },
  count: {
    type: Number,
    required: true
  },
  progress: {
    type: Number,
    required: true
  }
});
defineEmits(['clear']);

const { t, n } = useI18n();
const status = computed(() => (props.progress < 1
  ? t('status.sending', { percentUploaded: n(props.progress, 'percent') })
  : t('status.processing')));
</script>

<style lang="scss">
@use 'sass:color';
@import '../../../assets/scss/mixins';

#entity-upload-popup {
  background-color: $color-subpanel-background;
  border: 2px solid $color-action-foreground;
  border-radius: 6px;
  bottom: 80px;
  outline: 5px solid #{color.change($color-action-foreground, $alpha: 0.15)};
  padding: 15px;
  position: absolute;
  right: 15px;
  width: 305px;
}

#entity-upload-popup-heading {
  @include text-overflow-ellipsis;
  font-size: 18px;
  font-weight: bold;
}

#entity-upload-popup-status {
  margin-bottom: 5px;
  margin-top: 15px;

  .spinner + span {
    font-weight: bold;
    margin-left: 6px;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "rowCount": "{count} data row found | {count} data rows found",
    "status": {
      // This text is shown while a file is being uploaded to the server.
      "sending": "Sending file… ({percentUploaded})",
      // This text is shown after a file has been uploaded to the server, but
      // before the server has finished processing it.
      "processing": "Processing file…"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "rowCount": "{count} Datenzeile gefunden | {count} Datenzeilen gefunden",
    "status": {
      "sending": "Datei senden... ({percentUploaded})",
      "processing": "Datei verarbeiten..."
    }
  },
  "es": {
    "rowCount": "{count} fila de datos encontradas | {count} filas de datos encontradas | {count} filas de datos encontradas",
    "status": {
      "sending": "Enviando archivo… ({percentUploaded})",
      "processing": "Procesando archivo…"
    }
  },
  "fr": {
    "rowCount": "{count} ligne de données trouvée | {count} lignes de données trouvées | {count} lignes de données trouvées",
    "status": {
      "sending": "Envoi du fichier...({percentUploaded})",
      "processing": "Traitement du fichier..."
    }
  },
  "it": {
    "rowCount": "{count} riga di dati trovata | {count} righe di dati trovate | {count} righe di dati trovate",
    "status": {
      "sending": "Inviando il file...({percentUploaded})",
      "processing": "Processando il file..."
    }
  },
  "pt": {
    "rowCount": "{count} linha de dados encontrada | {count} linhas de dados encontradas | {count} linhas de dados encontradas",
    "status": {
      "sending": "Enviando arquivo… ({percentUploaded})",
      "processing": "Processando arquivo…"
    }
  },
  "zh": {
    "rowCount": "找到{count}行数据",
    "status": {
      "sending": "传送文件...({percentUploaded})",
      "processing": "处理文件..."
    }
  },
  "zh-Hant": {
    "rowCount": "找到{count}行資料",
    "status": {
      "sending": "傳送檔案… ({percentUploaded})",
      "processing": "處理檔案…"
    }
  }
}
</i18n>
