<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div v-if="!oidcEnabled" id="odata-data-access">
    <button id="odata-data-access-analyze-button" type="button"
      class="btn btn-default" :aria-disabled="analyzeDisabled"
      v-tooltip.aria-describedby="analyzeDisabled ? analyzeDisabledMessage : null"
      @click="$emit('analyze')">
      <span class="icon-bar-chart"></span>{{ $t('action.connectData') }}
    </button>
  </div>
</template>

<script setup>
import { inject } from 'vue';

defineOptions({
  name: 'OdataDataAccess'
});
defineProps({
  analyzeDisabled: Boolean,
  analyzeDisabledMessage: String
});
defineEmits(['analyze']);

const { oidcEnabled } = inject('config');
</script>

<style lang="scss">
#odata-data-access-analyze-button { margin-left: 5px; }
</style>

<i18n lang="json5">
{
  "en": {
    "action": {
      "connectData": "Connect Data"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "action": {
      "connectData": "Daten verbinden"
    }
  },
  "es": {
    "action": {
      "connectData": "Conectar datos"
    }
  },
  "fr": {
    "action": {
      "connectData": "Se connecter aux données"
    }
  },
  "it": {
    "action": {
      "connectData": "Collegare Dati"
    }
  },
  "pt": {
    "action": {
      "connectData": "Dados de conexão"
    }
  },
  "zh": {
    "action": {
      "connectData": "连接数据"
    }
  },
  "zh-Hant": {
    "action": {
      "connectData": "連接資料"
    }
  }
}
</i18n>
