<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="form-draft-abandon" :state="state" :hideable="!awaitingResponse"
    backdrop @hide="$emit('hide')">
    <template #title>
      {{ published ? $t('title.abandon') : $t('title.deleteForm') }}
    </template>
    <template #body>
      <div class="modal-introduction">
        <template v-if="published">
          <p>{{ $t('introduction.abandon[0]') }}</p>
          <p>{{ $t('introduction.abandon[1]') }}</p>
        </template>
        <template v-else>
          <p>{{ $t('introduction.deleteForm[0]') }}</p>
        </template>
        <p>{{ $t('common.areYouSure') }}</p>
      </div>
      <div class="modal-actions">
        <button type="button" class="btn btn-link" :aria-disabled="awaitingResponse"
          @click="$emit('hide')">
          {{ $t('action.cancel') }}
        </button>
        <button type="button" class="btn btn-danger"
          :aria-disabled="awaitingResponse" @click="abandon">
          {{ published ? $t('action.abandon') : $t('action.delete') }}
          <spinner :state="awaitingResponse"/>
        </button>
      </div>
    </template>
  </modal>
</template>

<script>
import Modal from '../modal.vue';
import Spinner from '../spinner.vue';

import useRequest from '../../composables/request';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';
import { useRequestData } from '../../request-data';

export default {
  name: 'FormDraftAbandon',
  components: { Modal, Spinner },
  props: {
    state: {
      type: Boolean,
      default: false
    }
  },
  emits: ['hide', 'success'],
  setup() {
    const { project, form } = useRequestData();
    const { request, awaitingResponse } = useRequest();
    return { project, form, request, awaitingResponse };
  },
  computed: {
    published() {
      return this.form.dataExists && this.form.publishedAt != null;
    }
  },
  methods: {
    abandon() {
      this.request({
        method: 'DELETE',
        url: this.form.publishedAt != null
          ? apiPaths.formDraft(this.form.projectId, this.form.xmlFormId)
          : apiPaths.form(this.form.projectId, this.form.xmlFormId)
      })
        .then(() => {
          if (this.form.publishedAt == null) this.project.forms -= 1;
          this.$emit('success');
        })
        .catch(noop);
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up.
    "title": {
      "abandon": "Abandon Draft",
      // @transifexKey component.FormDelete.title
      "deleteForm": "Delete Form"
    },
    "introduction": {
      "abandon": [
        "You are about to permanently delete the Draft version of this Form. This means that the draft Form definition, any draft Form Attachments you have uploaded, and all test Submissions will be removed.",
        "Your published Form definition, its Form Attachments, and Submissions will not be affected."
      ],
      "deleteForm": [
        "You are about to delete this draft Form definition, along with any draft Form Attachments you have uploaded, and all test Submissions. Because you have not yet published it, this entire Form will be deleted and moved to the Trash."
      ]
    },
    "action": {
      "abandon": "Abandon"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": {
      "abandon": "Opustit koncept",
      "deleteForm": "Odstranit formulář"
    },
    "introduction": {
      "abandon": [
        "Chystáte se trvale odstranit pracovní verzi tohoto formuláře. To znamená, že definice návrhu formuláře, všechny vámi nahrané přílohy návrhu formuláře a všechna testovací podání budou odstraněna.",
        "Vaše zveřejněná definice formuláře, jeho přílohy a podání nebudou ovlivněny."
      ],
      "deleteForm": [
        "Chystáte se odstranit tento návrh definice formuláře spolu se všemi nahranými návrhy příloh formuláře a všemi testovacími podáními. Protože jste jej ještě nezveřejnili, bude celý tento Formulář odstraněn a přesunut do koše."
      ]
    },
    "action": {
      "abandon": "Opustit"
    }
  },
  "de": {
    "title": {
      "abandon": "Entwurf verwerfen",
      "deleteForm": "Formulare löschen"
    },
    "introduction": {
      "abandon": [
        "Sie sind dabei, die Entwurfsversion dieses Formulars zu löschen. Das bedeutet, dass das Formular, hochgeladene dazugehörige Formularanhänge und alle Test-Übermittlungen entfernt werden.",
        "Ihre veröffentlichte Formulardefinition, ihre Formularanhänge und Übermittlungen sind davon nicht betroffen."
      ],
      "deleteForm": [
        "Sie sind im Begriff, diese Definition des Formularentwurfes zusammen mit allen Entwürfen von Formularanhängen, die Sie hochgeladen haben, und allen Testübermittlungen zu löschen. Da Sie dieses Formular noch nicht veröffentlicht haben, wird dieses gesamte Formular gelöscht und in den Papierkorb verschoben."
      ]
    },
    "action": {
      "abandon": "Ja, Löschen"
    }
  },
  "es": {
    "title": {
      "abandon": "Abandonar borrador",
      "deleteForm": "Borrar formulario"
    },
    "introduction": {
      "abandon": [
        "Está a punto de borrar permanentemente la versión borrador de este formulario. Esto significa que se eliminarán el borrador de la definición del formulario, cualquier archivo adjunto del borrador del formulario que haya cargado y todos los envíos de prueba.",
        "Su definición de formulario publicado, sus adjuntos de formulario y envíos no se verán afectados."
      ],
      "deleteForm": [
        "Está a punto de eliminar este borrador de definición de formulario, junto con cualquier borrador de archivos adjuntos de formulario que haya cargado y todos los envíos de prueba. Debido a que aún no lo ha publicado, este Formulario completo se eliminará y se moverá a la Papelera."
      ]
    },
    "action": {
      "abandon": "Abandonar"
    }
  },
  "fr": {
    "title": {
      "abandon": "Abandonner l'ébauche",
      "deleteForm": "Supprimer le formulaire"
    },
    "introduction": {
      "abandon": [
        "Vous êtes sur le point de supprimer définitivement l'ébauche de ce formulaire. Cela signifie que sa définition, les pièces jointes associées que vous avez téléchargées et toutes les soumissions de test seront supprimées.",
        "Votre définition de Formulaire publiée, ses Fichiers joints, et les Soumissions ne seront pas affectés."
      ],
      "deleteForm": [
        "Vous êtes sur le point de supprimer la définition de cette ébauche de Formulaire, ainsi que chaque Fichier joint envoyés, et toutes les Soumissions de test. Parce-que vous ne l'avez pas encore publié, tout le formulaire sera supprimé et déplacé à la corbeille."
      ]
    },
    "action": {
      "abandon": "Abandonner"
    }
  },
  "id": {
    "title": {
      "abandon": "Buang Draf",
      "deleteForm": "Hapus Formulir"
    },
    "action": {
      "abandon": "Buang"
    }
  },
  "it": {
    "title": {
      "abandon": "Abbandona bozza",
      "deleteForm": "Cancellare il formulario"
    },
    "introduction": {
      "abandon": [
        "Stai per eliminare definitivamente la versione bozza di questo formulario. Ciò significa che la bozza di definizione del formulario, qualsiasi bozza di allegati che hai caricato e tutti gli invii di prova verranno rimossi.",
        "La definizione del formulario è stata pubblicata, i suoi allegati al formulario e gli invii non saranno interessati."
      ],
      "deleteForm": [
        "Stai per eliminare questa bozza di definizione del formulario, insieme a qualsiasi bozza di allegati che hai caricato e tutti gli invii di prova. Poiché non l'hai ancora pubblicato, l'intero formualrio verrà eliminato e spostato nel Cestino."
      ]
    },
    "action": {
      "abandon": "Annulla"
    }
  },
  "ja": {
    "title": {
      "abandon": "下書きの削除",
      "deleteForm": "フォームの削除"
    },
    "action": {
      "abandon": "削除"
    }
  },
  "pt": {
    "title": {
      "abandon": "Abandonar rascunho",
      "deleteForm": "Excluir formulário"
    },
    "introduction": {
      "abandon": [
        "Você está prestes a excluir permanentemente a versão Rascunho deste Formulário. Isso significa que a definição de Formulário de rascunho, quaisquer Anexos do Formulário de rascunho que você carregou e todas as Respostas de teste serão removidos.",
        "Sua definição de Formulário publicada, seus Anexos de Formulário e suas Respostas não serão afetados."
      ],
      "deleteForm": [
        "Você está prestes a excluir esta definição de Formulário de rascunho, juntamente com todos os Anexos de Formulário de rascunho que você carregou e todos as Respostas de teste. Como você ainda não o publicou, este Formulário será totalmente excluído e movido para a Lixeira."
      ]
    },
    "action": {
      "abandon": "Abandonar"
    }
  },
  "sw": {
    "title": {
      "abandon": "acha rasimu",
      "deleteForm": "Futa Fomu"
    },
    "introduction": {
      "abandon": [
        "Unakaribia kufuta kabisa Rasimu ya toleo la Fomu hii. Hii ina maana kwamba ufafanuzi wa Fomu ya rasimu, Viambatisho vya Fomu vya rasimu ambavyo umepakia, na Mawasilisho yote ya majaribio yataondolewa.",
        "Ufafanuzi wako wa Fomu uliochapishwa, Viambatisho vyake vya Fomu, na Mawasilisho hayataathiriwa."
      ],
      "deleteForm": [
        "Unakaribia kufuta ufafanuzi wa Fomu hii ya rasimu, pamoja na Viambatisho vyovyote vya rasimu ambavyo umepakia, na Mawasilisho yote ya majaribio. Kwa sababu bado hujaichapisha, Fomu hii yote itafutwa na kuhamishiwa kwenye tupio."
      ]
    },
    "action": {
      "abandon": "Achana"
    }
  },
  "zh": {
    "title": {
      "abandon": "放弃草稿",
      "deleteForm": "删除表单"
    },
    "introduction": {
      "abandon": [
        "您即将永久删除此表单的草稿版本。这将清除：当前的草稿表单定义、所有已上传的草稿附件以及全部测试提交数据。",
        "您已发布的表单定义、表单附件及提交数据将不受影响。"
      ],
      "deleteForm": [
        "您即将删除此草稿表单的设置、所有已上传的草稿附件及全部测试提交数据。由于该表单尚未发布，整个表单将被删除并移至回收站。"
      ]
    },
    "action": {
      "abandon": "放弃"
    }
  },
  "zh-Hant": {
    "title": {
      "abandon": "放棄草稿",
      "deleteForm": "刪除表單"
    },
    "introduction": {
      "abandon": [
        "您將永久刪除此表單的草稿版本。這意味著草稿表單定義、您上傳的任何草稿表單附件以及所有測試提交都將被刪除。",
        "您發布的表單定義、其表單附件和提交內容不會受到影響。"
      ],
      "deleteForm": [
        "您將刪除此草稿的表單定義以及您已上傳的任何附件以及所有測試提交。由於您尚未發布該表單，因此整個表單將被刪除並移至垃圾桶。"
      ]
    },
    "action": {
      "abandon": "放棄"
    }
  }
}
</i18n>
