<!--
Copyright 2024 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <qr-panel class="form-draft-qr-panel">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="clearfix">
        <collect-qr v-if="formDraft.dataExists" :settings="settings"
        error-correction-level="Q" :cell-size="3" draft/>
        <i18n-t keypath="introduction.full" tag="p">
          <template #temporaryCode>
            <strong>{{ $t('introduction.temporaryCode') }}</strong>
          </template>
        </i18n-t>
        <p>{{ $t('stopsWorking') }}</p>
        <p>{{ $t('instructions') }}</p>
        <i18n-t keypath="codesForUsers.full" tag="p">
          <template #appUsers>
            <router-link :to="projectPath('app-users')">
              {{ $t('codesForUsers.appUsers') }}
            </router-link>
          </template>
        </i18n-t>
      </div>
    </template>
  </qr-panel>
</template>

<script setup>
import { computed, inject } from 'vue';
import { useI18n } from 'vue-i18n';

import CollectQr from '../collect-qr.vue';
import QrPanel from '../qr-panel.vue';

import useRoutes from '../../composables/routes';
import { apiPaths } from '../../util/request';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'FormDraftQrPanel'
});

const { resourceView } = useRequestData();
const formDraft = resourceView('formDraft', (data) => data.get());

const { t } = useI18n();
const projectId = inject('projectId');
const xmlFormId = inject('xmlFormId');
const settings = computed(() => {
  const { draftToken } = formDraft;
  const url = apiPaths.serverUrlForFormDraft(draftToken, projectId, xmlFormId);
  return {
    general: {
      server_url: `${window.location.origin}${url}`,
      form_update_mode: 'match_exactly',
      autosend: 'wifi_and_cellular'
    },
    project: {
      name: t('collectProjectName', { name: formDraft.nameOrId }),
      icon: '📝'
    },
    // Collect requires the settings to have an `admin` property.
    admin: {}
  };
});

const { projectPath } = useRoutes();
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up. "Code" refers to a QR code.
    "title": "Testing Code",
    // @transifexKey component.FormDraftTesting.collectProjectName
    // This text will be shown in ODK Collect when testing a Draft Form. {name}
    // is the title of the Draft Form.
    "collectProjectName": "[Draft] {name}",
    "introduction": {
      // This is shown next to a QR code.
      "full": "This is a {temporaryCode}.",
      // "Code" refers to a QR code.
      "temporaryCode": "Temporary Testing Code"
    },
    // "It" refers to a temporary testing code.
    "stopsWorking": "It will stop working when you publish this Draft.",
    // The table is a table of test Submissions.
    "instructions": "Scan this QR code to configure Collect on a device for testing and submitting data to this test table.",
    "codesForUsers": {
      // "Codes" refers to "QR codes".
      "full": "To create codes to distribute to users, please see the {appUsers} page.",
      "appUsers": "App Users"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "collectProjectName": "[Návrh] {name}"
  },
  "de": {
    "title": "Test-Code",
    "introduction": {
      "full": "Das ist ein {temporaryCode}.",
      "temporaryCode": "Vorläufiger Testcode"
    },
    "stopsWorking": "Wenn Sie diesen Entwurf veröffentlichen, funktioniert er nicht mehr.",
    "collectProjectName": "[Entwurf] {name}"
  },
  "es": {
    "title": "Código de prueba",
    "introduction": {
      "full": "Este es un {temporaryCode}.",
      "temporaryCode": "Código de prueba temporal"
    },
    "stopsWorking": "Dejará de funcionar cuando publiques este borrador.",
    "instructions": "Escanee este código QR para configurar Collect en un dispositivo para realizar pruebas y enviar datos a esta tabla de pruebas.",
    "codesForUsers": {
      "full": "Para crear códigos para distribuir a los usuarios, consulte la página {appUsers}.",
      "appUsers": "Usuarios de Aplicación"
    },
    "collectProjectName": "borrador {name}"
  },
  "fr": {
    "title": "Code de Test",
    "introduction": {
      "full": "Ceci est un {temporaryCode}",
      "temporaryCode": "Code de Test Temporaire"
    },
    "stopsWorking": "Il cessera de fonctionner quand vous publierez cette ébauche.",
    "instructions": "Scannez ce QR code pour configurer Collect sur un appareil pour tester et soumettre des données à cette table de test.",
    "codesForUsers": {
      "full": "Pour créer des codes à distribuer aux utilisateurs, merci de visiter la page {appUsers}.",
      "appUsers": "Utilisateurs mobiles"
    },
    "collectProjectName": "[Brouillon] {name}"
  },
  "id": {
    "collectProjectName": "[Draf]{name}"
  },
  "it": {
    "title": "Codice di test.",
    "introduction": {
      "full": "Questo è un {temporaryCode}.",
      "temporaryCode": "Codice di test temporaneo"
    },
    "stopsWorking": "Smetterà di funzionare quando pubblicherete questa bozza.",
    "instructions": "Scansionare questo codice QR per configurare Collect su un dispositivo per i test e inviare i dati a questa tabella di test.",
    "codesForUsers": {
      "full": "Per creare codici da distribuire agli utenti, consultare la pagina {appUsers}.",
      "appUsers": "Utenti dell'applicazione"
    },
    "collectProjectName": "[Draft] {name}"
  },
  "ja": {
    "collectProjectName": "[下書き] {name}"
  },
  "sw": {
    "collectProjectName": "[Rasimu] {name}"
  },
  "zh-Hant": {
    "collectProjectName": "[草稿] {name}"
  }
}
</i18n>
