<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div>
    <page-section id="form-draft-testing-info">
      <template #heading>
        <span>{{ $t('title') }}</span>
      </template>
      <template #body>
        <div v-if="formDraft.entityRelated" class="panel-dialog">
          <div class="panel-heading">
            <span class="panel-title">
              <span class="icon-database"></span>
              {{ $t('entitiesTesting.title') }}
            </span>
          </div>
          <div class="panel-body">
            <p>
              {{ $t('entitiesTesting.body[0]') }}
            </p>
            <p>
              {{ $t('entitiesTesting.body[1]') }}
            </p>
          </div>
        </div>
        <p>
          <span>{{ $t('introduction') }}</span>
          <sentence-separator/>
          <i18n-t keypath="moreInfo.helpArticle.full">
            <template #helpArticle>
              <doc-link to="central-forms/#working-with-form-drafts">{{ $t('moreInfo.helpArticle.helpArticle') }}</doc-link>
            </template>
          </i18n-t>
        </p>
      </template>
    </page-section>
    <loading :state="keys.initiallyLoading"/>
    <submission-list v-show="keys.dataExists" :project-id="projectId"
      :xml-form-id="xmlFormId" draft @fetch-keys="fetchKeys"
      @toggle-qr="togglePopover"/>

    <popover :target="popoverData.target" placement="right" @hide="hidePopover">
      <form-draft-qr-panel/>
    </popover>
  </div>
</template>

<script setup>
import { provide, shallowReactive } from 'vue';

import DocLink from '../doc-link.vue';
import FormDraftQrPanel from './qr-panel.vue';
import Loading from '../loading.vue';
import PageSection from '../page/section.vue';
import Popover from '../popover.vue';
import SentenceSeparator from '../sentence-separator.vue';
import SubmissionList from '../submission/list.vue';

import useSubmissions from '../../request-data/submissions';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'FormDraftTesting'
});
const props = defineProps({
  projectId: {
    type: String,
    required: true
  },
  xmlFormId: {
    type: String,
    required: true
  }
});
provide('projectId', props.projectId);
provide('xmlFormId', props.xmlFormId);

const { resourceView, createResource } = useRequestData();
const formDraft = resourceView('formDraft', (data) => data.get());
// SubmissionList expects submission stores to be created!
useSubmissions();

const keys = createResource('keys');
const fetchKeys = () => {
  // We do not reconcile `keys` and formDraft.keyId.
  keys.request({
    url: apiPaths.submissionKeys(props.projectId, props.xmlFormId, true)
  }).catch(noop);
};
fetchKeys();

const popoverData = shallowReactive({ target: null });
const togglePopover = (button) => {
  popoverData.target = popoverData.target == null ? button : null;
};
const hidePopover = () => { popoverData.target = null; };
</script>

<style lang="scss">
#form-draft-testing-info { margin-bottom: 25px; }
</style>

<i18n lang="json5">
{
  "en": {
    // This is a title shown above a section of the page.
    "title": "Draft Testing",
    // @transifexKey component.FormDraftTesting.body.1
    "introduction": "Draft Submissions go into the test table below, where you can preview and download them. When you publish this Draft Form, its test Submissions will be permanently removed.",
    // @transifexKey component.FormDraftTesting.datasetsPreview
    "entitiesTesting": {
      "title": "This Form can update Entities",
      "body": [
        "Entities are only updated for published Forms. In a future release of Central, you will be able to test Entity functionality in a Draft state.",
        "For now, we recommend trying your Form definition in Draft state to verify its logic. Before publishing, you can verify that it updates all of the desired properties."
      ]
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Testování konceptu",
    "introduction": "Pro koncept příspěvku přejděte do níže uvedené testovací tabulky, kde si ho můžete prohlédnout a stáhnout. Při publikování tohoto konceptu formuláře budou jeho testovací příspěvky trvale odstraněny.",
    "entitiesTesting": {
      "title": "Tento formulář může aktualizovat entity.",
      "body": [
        "Entity jsou aktualizovány pouze pro publikované formuláře. V budoucí verzi Central budete moci testovat funkčnost Entity ve stavu Koncept.",
        "Prozatím doporučujeme vyzkoušet definici formuláře ve stavu Návrh a ověřit její logiku. Před publikováním můžete ověřit, zda aktualizuje všechny požadované vlastnosti."
      ]
    }
  },
  "de": {
    "title": "Entwurfs-Test",
    "introduction": "Entwurfs-Übermittlungen werden in der Testtabelle unten dargestellt. Sie können Sie dort ansehen und herunterladen. Wenn Sie dieses Entwurfsformular veröffentlichen, werden die Test-Übermittlungen irreversibel entfernt.",
    "entitiesTesting": {
      "title": "Dieses Formular kann Objekte aktualisieren.",
      "body": [
        "Objekte werden nur für veröffentlichte Formulare aktualisiert. In einer zukünftigen Version von Central können Sie die Funktionalität von Objekten im Entwurfsstatus testen.",
        "Derzeit empfehlen wir, Ihre Formdefinition im Entwurfszustand zu überprüfen, um deren Logik zu überprüfen. Bevor Sie sie veröffentlichen, können Sie sicherstellen, dass sie alle gewünschten Eigenschaften aktualisiert."
      ]
    }
  },
  "es": {
    "title": "Prueba de borrador",
    "introduction": "El borrador de los envíos van a la tabla de prueba a continuación, donde puede obtener una vista previa y descargar. Cuando publique este borrador de Formulario, sus envíos de prueba se eliminarán permanentemente.",
    "entitiesTesting": {
      "title": "Este Formulario puede actualizar Entidades",
      "body": [
        "Las entidades solo se actualizan para Formularios publicados. En una futura versión de Central, podrás probar la funcionalidad de Entidades en estado de Borrador.",
        "Por ahora, recomendamos probar la definición de su Formulario en estado Borrador para verificar su lógica. Antes de publicar, puede verificar que actualice todas las propiedades deseadas."
      ]
    }
  },
  "fr": {
    "title": "Test de l'ébauche",
    "introduction": "Les soumissions de test vont dans le tableau ci-dessous où vous pouvez les prévisualiser et télécharger. Quand vous publierez cette ébauche, ses soumissions de test seront définitivement supprimées.",
    "entitiesTesting": {
      "title": "Ce formulaire peut mettre à jour des Entités.",
      "body": [
        "Les entités ne peuvent être mises à jour qu'avec des formulaires publiés. Dans une future version de Central, vous pourrez tester la mise à jour des entités avec des ébauches de formulaires.",
        "Pour le moment, nous vous conseillons de tester la définition de votre formulaire à l'état d'ébauche pour vérifier sa logique. Avant de le publier, vous pouvez vérifier qu'il met à jour les propriétés désirées."
      ]
    }
  },
  "id": {
    "title": "Pengujian Draf",
    "introduction": "Draf kiriman data akan mucnul pada tabel tes di bawah, di mana Anda juga bisa melihat pratinjau dan mengunduhnya. Ketika formulir draf diterbitkan, tes kiriman data akan dihapus secara permanen."
  },
  "it": {
    "title": "Testando la bozza",
    "introduction": "Le bozze inviate vanno nella tabella di prova sottostante, dove puoi visualizzarle in anteprima e scaricarle. Quando pubblichi questa bozza di formulario, i suoi Invii di prova verranno rimossi in modo permanente.",
    "entitiesTesting": {
      "title": "Questo Formulario può aggiornare Entità",
      "body": [
        "Le entità vengono aggiornate solo per i Moduli pubblicati. In una futura versione di Central, sarà possibile testare la funzionalità delle entità in uno stato di bozza.",
        "Per ora, ti consigliamo di provare la definizione del formulario nello stato Bozza per verificarne la logica. Prima della pubblicazione, puoi verificare che aggiorni tutte le proprietà desiderate."
      ]
    }
  },
  "ja": {
    "title": "下書きのテスト",
    "introduction": "下書きにテスト提出されたフォームは、以下の表に示されます。ここではデータのプレビューやダウンロードが可能です。この下書きフォームを公開した場合、テスト提出済フォームは永久に削除されます。"
  },
  "sw": {
    "title": "Mtihani wa Rasimu",
    "introduction": "Rasimu ya Mawasilisho huenda kwenye jedwali la majaribio hapa chini, ambapo unaweza kuhakiki na kupakua. Unapochapisha Rasimu ya Fomu hii, Mawasilisho yake ya majaribio yataondolewa kabisa."
  },
  "zh-Hant": {
    "title": "草稿測試",
    "introduction": "草稿提交進入下面的測試表，您可以在其中預覽和下載它們。當您發布此表單草稿時，其測試提交內容將會永久刪除。",
    "entitiesTesting": {
      "title": "該表單可以更新實體",
      "body": [
        "實體僅針對已發布的表單進行更新。在 Central 的未來版本中，您將能夠在草稿狀態下測試實體功能。",
        "目前，我們建議在草稿狀態下嘗試表單定義以驗證其邏輯。在發布之前，您可以驗證它是否更新了所有所需的屬性。"
      ]
    }
  }
}
</i18n>
