<!--
Copyright 2022 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div v-if="backupsConfig.isDefined()" id="backup-deprecation">
    <p>
      <span>{{ $t('text') }}</span>
      <sentence-separator/>
      <i18n-t keypath="moreInfo.clickHere.full">
        <template #clickHere>
          <a href="https://forum.getodk.org/t/backups-to-google-drive-from-central-will-stop-working-after-jan-31st/38895" target="_blank">{{ $t('moreInfo.clickHere.clickHere') }}</a>
        </template>
      </i18n-t>
    </p>
  </div>
</template>

<script>
export default {
  name: 'BackupDeprecation'
};
</script>
<script setup>
import SentenceSeparator from '../sentence-separator.vue';

import { useRequestData } from '../../request-data';

// The component assumes that this data will exist when the component is
// created.
const { backupsConfig } = useRequestData();
</script>

<style lang="scss">
@import '../../assets/scss/variables';

#backup-deprecation {
  background-color: $color-warning-light;
  margin-bottom: 20px;
  padding: 15px;

  p {
    margin-bottom: 0;
    // Provide a little more width so that the text fits on one line in English.
    &:lang(en) { max-width: 82ch; }
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "text": "On January 31st, 2023, backups to Google Drive will stop working."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "text": "31. ledna 2023 přestane fungovat zálohování na Disk Google."
  },
  "fr": {
    "text": "Le 31 janvier 2023, les sauvegardes sur Google Drive cesseront de fonctionner"
  },
  "it": {
    "text": "Il 31 gennaio 2023 i backup su Google Drive smetteranno di funzionare."
  }
}
</i18n>
