<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div>
    <loading :state="initiallyLoading"/>
    <template v-if="dataExists">
      <backup-deprecation/>
      <backup-status @terminate="showModal('terminate')"/>
      <page-section v-if="audits.length !== 0">
        <template #heading>
          <span>{{ $t('auditsTitle') }}</span>
        </template>
        <template #body>
          <audit-table/>
        </template>
      </page-section>
    </template>
    <backup-terminate v-bind="terminate" @hide="hideModal('terminate')"
      @success="afterTerminate"/>
  </div>
</template>

<script>
import AuditTable from '../audit/table.vue';
import BackupDeprecation from './deprecation.vue';
import BackupStatus from './status.vue';
import BackupTerminate from './terminate.vue';
import Loading from '../loading.vue';
import PageSection from '../page/section.vue';

import modal from '../../mixins/modal';
import useBackups from '../../request-data/backups';
import { apiPaths } from '../../util/request';
import { useRequestData } from '../../request-data';

export default {
  name: 'BackupList',
  components: {
    AuditTable,
    BackupDeprecation,
    BackupStatus,
    BackupTerminate,
    Loading,
    PageSection
  },
  mixins: [modal()],
  inject: ['alert'],
  setup() {
    const { backupsConfig, audits } = useBackups();
    const { resourceStates } = useRequestData();
    return {
      backupsConfig, audits, ...resourceStates([backupsConfig, audits])
    };
  },
  data() {
    return {
      terminate: {
        state: false
      }
    };
  },
  created() {
    this.fetchData();
  },
  methods: {
    fetchData() {
      Promise.allSettled([
        this.backupsConfig.request({
          url: '/v1/config/backups',
          fulfillProblem: ({ code }) => code === 404.1
        }),
        // A backup audit log entry does not have an actor or actee, so we do
        // not need to request extended metadata.
        this.audits.request({
          url: apiPaths.audits({ action: 'backup', limit: 10 })
        })
      ]);
    },
    afterTerminate() {
      this.hideModal('terminate');
      this.alert.success(this.$t('alert.terminate'));
      this.backupsConfig.setToNone();
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is a title shown above a section of the page.
    "auditsTitle": "Latest Backups",
    "alert": {
      "terminate": "Your automatic backups were terminated."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "auditsTitle": "Nejnovější zálohy",
    "alert": {
      "terminate": "Vaše automatické zálohování je ukončeno."
    }
  },
  "de": {
    "auditsTitle": "Letzte Sicherheitskopien"
  },
  "es": {
    "auditsTitle": "Últimas copias de seguridad"
  },
  "fr": {
    "auditsTitle": "Dernières Sauvegardes",
    "alert": {
      "terminate": "Vos sauvegardes automatiques ont été interrompues."
    }
  },
  "id": {
    "auditsTitle": "Data Cadangan Terakhir"
  },
  "it": {
    "auditsTitle": "Ultimo backup",
    "alert": {
      "terminate": "I tuoi backup automatici sono stati interrotti."
    }
  },
  "ja": {
    "auditsTitle": "最新のバックアップ"
  },
  "sw": {
    "auditsTitle": "Hifadhi Nakala za Hivi Punde"
  }
}
</i18n>
