<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="backup-terminate" :state="state" :hideable="!awaitingResponse"
    backdrop @hide="$emit('hide')">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="modal-introduction">
        <p>{{ $t('introduction[0]') }}</p>
        <p>
          <span>{{ $t('introduction[1]') }}</span>
          <sentence-separator/>
          <i18n-t keypath="moreInfo.clickHere.full">
            <template #clickHere>
              <a href="https://forum.getodk.org/t/backups-to-google-drive-from-central-will-stop-working-after-jan-31st/38895" target="_blank">{{ $t('moreInfo.clickHere.clickHere') }}</a>
            </template>
          </i18n-t>
        </p>
      </div>
      <div class="modal-actions">
        <button type="button" class="btn btn-danger"
          :disabled="awaitingResponse" @click="terminate">
          {{ $t('action.yesProceed') }} <spinner :state="awaitingResponse"/>
        </button>
        <button type="button" class="btn btn-link" :disabled="awaitingResponse"
          @click="$emit('hide')">
          {{ $t('action.noCancel') }}
        </button>
      </div>
    </template>
  </modal>
</template>

<script>
import Modal from '../modal.vue';
import SentenceSeparator from '../sentence-separator.vue';
import Spinner from '../spinner.vue';

import request from '../../mixins/request';
import { noop } from '../../util/util';

export default {
  name: 'BackupTerminate',
  components: { Modal, SentenceSeparator, Spinner },
  mixins: [request()],
  props: {
    state: {
      type: Boolean,
      default: false
    }
  },
  emits: ['hide', 'success'],
  data() {
    return {
      awaitingResponse: false
    };
  },
  methods: {
    terminate() {
      this.request({ method: 'DELETE', url: '/v1/config/backups' })
        .then(() => {
          this.$emit('success');
        })
        .catch(noop);
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up.
    "title": "Terminate Automatic Backups",
    "introduction": [
      "Are you sure you want to terminate your automatic backups?",
      "If you terminate your automatic backups, you will not be able to start them again. Automatic backups are a deprecated feature, but there are other ways to back up the data on the server."
    ]
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Ukončit automatické zálohování",
    "introduction": [
      "Opravdu chcete ukončit automatické zálohování?",
      "Pokud automatické zálohování ukončíte, nebude možné je znovu spustit. Automatické zálohování je zastaralá funkce, ale existují jiné způsoby zálohování dat na serveru."
    ]
  },
  "de": {
    "title": "Automatische Sicherungskopien beenden",
    "introduction": [
      "Sind Sie sicher, dass Sie die automatischen Sicherungskopien beenden möchten?"
    ]
  },
  "es": {
    "title": "Terminar copias de seguridad automáticas",
    "introduction": [
      "¿Está seguro que quiere terminar sus copias de seguridad automáticas?"
    ]
  },
  "fr": {
    "title": "Terminer les Sauvegardes Automatiques",
    "introduction": [
      "Êtes-vous sûr de vouloir mettre fin à vos sauvegardes automatiques ?",
      "Si vous interrompez vos sauvegardes automatiques, vous ne pourrez plus les redémarrer. Les sauvegardes automatiques est une fonctionnalité dépréciée, mais il y a d'autres moyens de sauvegarder les données du serveur."
    ]
  },
  "id": {
    "title": "Putuskan Data Cadangan Otomatis",
    "introduction": [
      "Apakah Anda yakin ingin memutus data cadangan otomatis?"
    ]
  },
  "it": {
    "title": "Termina i backup automatici",
    "introduction": [
      "Sei sicuro di voler terminare i tuoi backup automatici?",
      "Se interrompi i backup automatici, non sarai in grado di riavviarli. I backup automatici sono una funzionalità deprecata, ma esistono altri modi per eseguire il backup dei dati sul server."
    ]
  },
  "ja": {
    "title": "自動バックアップの停止",
    "introduction": [
      "自動バックアップを本当に停止しますか？"
    ]
  },
  "sw": {
    "title": "Sitisha Hifadhi Nakala za Kiotomatiki",
    "introduction": [
      "Je, una uhakika kuwa ungependa kusitisha hifadhi rudufu zako otomatiki?"
    ]
  }
}
</i18n>
