<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="user-edit-basic-details" class="panel panel-simple">
    <div class="panel-heading">
      <h1 class="panel-title">{{ $t('title') }}</h1>
    </div>
    <div class="panel-body">
      <form @submit.prevent="submit">
        <form-group v-model.trim="email" type="email"
          :placeholder="$t('field.email')" required
          :aria-disabled="emailDisabled"
          :tooltip="emailDisabled ? $t('emailDisabled') : null"
          autocomplete="off"/>
        <form-group v-model.trim="displayName" type="text"
          :placeholder="$t('field.displayName')" required autocomplete="off"/>
        <button type="submit" class="btn btn-primary"
          :aria-disabled="awaitingResponse">
          {{ $t('action.update') }}<spinner :state="awaitingResponse"/>
        </button>
      </form>
    </div>
  </div>
</template>

<script setup>
import { computed, inject, ref } from 'vue';
import { equals } from 'ramda';
import { useI18n } from 'vue-i18n';

import FormGroup from '../../form-group.vue';
import Spinner from '../../spinner.vue';

import { apiPaths } from '../../../util/request';
import { noop } from '../../../util/util';
import { useRequestData } from '../../../request-data';

defineOptions({
  name: 'UserEditBasicDetails'
});

// The component assumes that this data will exist when the component is
// created.
const { currentUser, user } = useRequestData();
const { awaitingResponse } = user.toRefs();

const email = ref(user.email);
const displayName = ref(user.displayName);

const config = inject('config');
const emailDisabled = computed(() =>
  config.oidcEnabled && !currentUser.can('user.update'));

const { t } = useI18n();
const alert = inject('alert');
const submit = () => {
  user.request({
    method: 'PATCH',
    url: apiPaths.user(user.id),
    data: { email: email.value, displayName: displayName.value },
    patch: ({ data }) => {
      user.email = data.email;
      user.displayName = data.displayName;
      user.updatedAt = data.updatedAt;
    },
    problemToAlert: ({ code, details }) =>
      (code === 409.3 && equals(details.fields, ['email', 'deleted'])
        ? t('problem.409_3', { email: details.values[0] })
        : null)
  })
    .then(() => { alert.success(t('alert.success')); })
    .catch(noop);
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is a title shown above a section of the page.
    "title": "Basic Details",
    "emailDisabled": "Your email address cannot be changed. It is used between Central and your login server to ensure your identity.",
    "action": {
      "update": "Update details"
    },
    "problem": {
      "409_3": "You cannot change your email to {email} because this account already exists. Please try another email address."
    },
    "alert": {
      "success": "User details saved!"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Základní podrobnosti",
    "emailDisabled": "Vaši e-mailovou adresu nelze změnit. Používá se mezi serverem Central a přihlašovacím serverem k zajištění vaší identity.",
    "action": {
      "update": "Aktualizovat podrobnosti"
    },
    "alert": {
      "success": "Detaily uživatele uloženy!"
    }
  },
  "de": {
    "title": "Basisinformationen",
    "emailDisabled": "Ihre E-Mail-Adresse kann nicht geändert werden. Sie wird zwischen Central und Ihrem Anmeldeserver verwendet, um Ihre Identität sicherzustellen.",
    "action": {
      "update": "Details aktualisieren"
    },
    "problem": {
      "409_3": "Sie können Ihre E-Mail-Adresse nicht in {email} ändern, da dieses Konto bereits existiert. Bitte versuchen Sie eine andere E-Mailadresse."
    },
    "alert": {
      "success": "Benutzerinformationen gespeichert!"
    }
  },
  "es": {
    "title": "Información básica",
    "emailDisabled": "Su dirección de correo electrónico no se puede cambiar. Se utiliza entre Central y su servidor de inicio de sesión para garantizar su identidad.",
    "action": {
      "update": "Actualizar información"
    },
    "problem": {
      "409_3": "No puede cambiar su correo electrónico a {email} porque esta cuenta ya existe. Por favor, intente con otra dirección de correo electrónico."
    },
    "alert": {
      "success": "Información de usuario guardada!"
    }
  },
  "fr": {
    "title": "Détails de base",
    "emailDisabled": "Votre adresse de courriel ne peut être changée. Elle est utilisée entre Central et votre serveur de connexion pour vérifier votre identité.",
    "action": {
      "update": "Mettre à jour les détails"
    },
    "problem": {
      "409_3": "Vous ne pouvez pas changer votre adresse de courriel pour {email} car ce compte existe déjà. Merci d'essayer une autre adresse."
    },
    "alert": {
      "success": "Détails de l'utilisateur sauvegardées !"
    }
  },
  "id": {
    "title": "Rincian Dasar",
    "action": {
      "update": "Rincian Pembaruan"
    },
    "alert": {
      "success": "Rincian pengguna tersimpan!"
    }
  },
  "it": {
    "title": "Dettagli di base",
    "emailDisabled": "L'indirizzo e-mail non può essere modificato. Viene utilizzato tra Central e il server di login per garantire l'identità dell'utente.",
    "action": {
      "update": "Aggiornare dettagli"
    },
    "problem": {
      "409_3": "Non puoi cambiare la tua email in {email} perché questo account esiste già. Per favore, prova un altro indirizzo email."
    },
    "alert": {
      "success": "Dettagli utente salvati!"
    }
  },
  "ja": {
    "title": "基本詳細",
    "action": {
      "update": "詳細の更新"
    },
    "alert": {
      "success": "ユーザー詳細の保存完了！"
    }
  },
  "sw": {
    "title": "Maelezo ya Msingi",
    "emailDisabled": "Anwani yako ya barua pepe haiwezi kubadilishwa. Inatumika kati ya Central na seva yako ya kuingia ili kuhakikisha utambulisho wako.",
    "action": {
      "update": "Sasisha maelezo"
    },
    "alert": {
      "success": "Maelezo ya mtumiaji yamehifadhiwa!"
    }
  },
  "zh-Hant": {
    "title": "基本訊息",
    "emailDisabled": "您的電子郵件地址無法變更。它在 Central 和您的登入伺服器之間使用，以確保您的身分。",
    "action": {
      "update": "更新詳情"
    },
    "problem": {
      "409_3": "您無法將電子郵件變更為 {email}，因為此帳戶已存在。請嘗試其他電子郵件地址。"
    },
    "alert": {
      "success": "用戶詳細資料已儲存！"
    }
  }
}
</i18n>
