<!--
Copyright 2023 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <page-section id="entity-basic-details">
    <template #heading><span>{{ $t('common.basicInfo') }}</span></template>
    <template #body>
      <dl v-if="entity.dataExists">
        <div>
          <dt>{{ $t('entity.entityId') }}</dt>
          <dd>{{ entity.uuid }}</dd>
        </div>
        <div v-if="instanceId != null">
          <dt>{{ $t('creatingSubmission') }}</dt>
          <dd id="entity-basic-details-creating-submission">
            <router-link v-if="submission != null"
              :to="submissionPath(projectId, submission.xmlFormId, instanceId)">
              {{ submission.currentVersion.instanceName ?? instanceId }}
            </router-link>
            <template v-else>
              <span class="icon-trash" v-tooltip.sr-only></span>
              <span>{{ instanceId }}</span>
              <span class="sr-only">&nbsp;{{ $t('submissionDeleted') }}</span>
            </template>
          </dd>
        </div>
        <div>
          <dt>{{ $t('header.createdAt') }}</dt>
          <dd><date-time :iso="entity.createdAt"/></dd>
        </div>
        <div>
          <dt>{{ $t('header.createdBy') }}</dt>
          <dd><actor-link :actor="entity.creator"/></dd>
        </div>
      </dl>
    </template>
  </page-section>
</template>

<script setup>
import { inject, ref, watchEffect } from 'vue';

import ActorLink from '../actor-link.vue';
import DateTime from '../date-time.vue';
import PageSection from '../page/section.vue';

import useRoutes from '../../composables/routes';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'EntityBasicDetails'
});

const projectId = inject('projectId');

// The component does not assume that this data will exist when the component is
// created.
const { entity, audits } = useRequestData();

// Using `ref` and watchEffect() for instanceId and `submission` rather than
// `computed` so that they don't change whenever `audits` is refreshed.
const instanceId = ref(undefined);
const submission = ref(undefined);
watchEffect(() => {
  if (instanceId.value !== undefined || !audits.dataExists) return;
  const audit = audits.find(({ action }) => action === 'entity.create');
  // `audit` should always exist in production, but it doesn't always exist in
  // testing.
  if (audit == null) return;
  const { submissionCreate } = audit.details;
  if (submissionCreate != null) {
    instanceId.value = submissionCreate.details.instanceId;
    submission.value = audit.details.submission;
  } else {
    instanceId.value = null;
  }
});
const { submissionPath } = useRoutes();
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

#entity-basic-details {
  margin-bottom: 35px;

  dd { @include text-overflow-ellipsis; }
  .icon-trash { margin-right: $margin-right-icon; }
}
</style>

<i18n lang="json5">
{
  "en": {
    // This is shown above the Submission that created the Entity.
    "creatingSubmission": "Creating Submission",
    "submissionDeleted": "This Submission has been deleted."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "creatingSubmission": "Vytvoření podání",
    "submissionDeleted": "Toto podání bylo smazáno."
  },
  "de": {
    "creatingSubmission": "Übermittlung erstellen",
    "submissionDeleted": "Diese Übermittlungen wurde gelöscht."
  },
  "es": {
    "creatingSubmission": "Creando envío",
    "submissionDeleted": "Este envío ha sido borrado."
  },
  "fr": {
    "creatingSubmission": "Soumission à l'origine de l'entité",
    "submissionDeleted": "La Soumission a été supprimée."
  },
  "id": {
    "creatingSubmission": "Membuat Kiriman Data"
  },
  "it": {
    "creatingSubmission": "Creando invio",
    "submissionDeleted": "Questo invio è stato eliminato."
  },
  "sw": {
    "creatingSubmission": "Kuunda Uwasilishaji"
  }
}
</i18n>
