<!--
Copyright 2023 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <page-section id="entity-data">
    <template #heading>
      <span>{{ $t('title') }}</span>
      <button v-if="rendersUpdateButton" id="entity-data-update-button"
        type="button" class="btn btn-default" @click="$emit('update')">
        <span class="icon-pencil"></span>{{ $t('action.edit') }}
      </button>
    </template>
    <template #body>
      <loading :state="dataset.initiallyLoading"/>
      <dl v-if="dataExists">
        <div v-for="{ name } of dataset.properties" :key="name">
          <dt><span v-tooltip.text>{{ name }}</span></dt>
          <dd v-if="data[name] == null || data[name] === ''" class="empty">
            {{ $t('common.emptyValue') }}
          </dd>
          <dd v-else v-tooltip.text>{{ data[name] }}</dd>
        </div>
      </dl>
    </template>
  </page-section>
</template>

<script setup>
import { computed } from 'vue';

import Loading from '../loading.vue';
import PageSection from '../page/section.vue';

import { useRequestData } from '../../request-data';

defineOptions({
  name: 'EntityData'
});
defineEmits(['update']);

// The component does not assume that this data will exist when the component is
// created.
const { project, dataset, entity, resourceStates } = useRequestData();
const { dataExists } = resourceStates([dataset, entity]);

const rendersUpdateButton = computed(() => project.dataExists &&
  project.permits('entity.update') && dataset.dataExists);
const data = computed(() => entity.currentVersion.data);
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

#entity-data {
  margin-bottom: 35px;

  dt { @include text-overflow-ellipsis; }

  dd {
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 3;
    display: -webkit-box;
    overflow: hidden;
    overflow-wrap: break-word;
    white-space: break-spaces;
  }

  .empty {
    color: #888;
    font-style: italic;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    // This is a title shown above a section of the page.
    "title": "Entity Data"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "title": "Entitätsdaten"
  },
  "es": {
    "title": "Datos de la entidad"
  },
  "fr": {
    "title": "Données de l'entité"
  },
  "id": {
    "title": "Data Entitas"
  },
  "it": {
    "title": "Dati Entità"
  },
  "sw": {
    "title": "Data ya Huluki"
  }
}
</i18n>
