<!--
Copyright 2023 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <a id="entity-download-button" class="btn btn-primary" :href="href">
    <span class="icon-arrow-circle-down"></span>{{ text }}
  </a>
</template>

<script setup>
import { computed, inject } from 'vue';
import { useI18n } from 'vue-i18n';

import { apiPaths } from '../../util/request';
import { useI18nUtils } from '../../util/i18n';
import { useRequestData } from '../../request-data';

const props = defineProps({
  odataFilter: String
});

const projectId = inject('projectId');
const datasetName = inject('datasetName');

const href = computed(() =>
  apiPaths.entities(projectId, datasetName, '.csv', { $filter: props.odataFilter }));

const { dataset, odataEntities } = useRequestData();
const { t } = useI18n();
const { tn } = useI18nUtils();
const text = computed(() => (props.odataFilter == null
  ? (dataset.dataExists
    ? tn('action.download.unfiltered', dataset.entities)
    : '') // The button is not visible in this case.
  : (odataEntities.dataExists
    ? tn('action.download.filtered.withCount', odataEntities.count)
    : t('action.download.filtered.withoutCount'))));
</script>

<i18n lang="json5">
{
  "en": {
    "action": {
      // @transifexKey component.EntityList.action.download
      "download": {
        "unfiltered": "Download {count} Entity | Download {count} Entities",
        "filtered": {
          "withCount": "Download {count} matching Entity | Download {count} matching Entities",
          // This is the text of a button. This text is shown when the number of
          // matching Entities is unknown.
          "withoutCount": "Download matching Entities"
        }
      }
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "action": {
      "download": {
        "filtered": {
          "withoutCount": "Stáhnout odpovídající entity"
        }
      }
    }
  },
  "de": {
    "action": {
      "download": {
        "unfiltered": "{count} Entität herunterladen | {count} Entitäten herunterladen",
        "filtered": {
          "withCount": "{count} passende Entität herunterladen | {count} passende Entitäten herunterladen",
          "withoutCount": "Passende Entitäten herunterladen"
        }
      }
    }
  },
  "es": {
    "action": {
      "download": {
        "unfiltered": "Descargar {count} Entidad | Descargar {count} Entidades | Descargar {count} Entidades",
        "filtered": {
          "withCount": "Descargar {count} entidad coincidente | Descargar {count} entidades coincidentes | Descargar {count} entidades coincidentes",
          "withoutCount": "Descargar entidades coincidentes"
        }
      }
    }
  },
  "fr": {
    "action": {
      "download": {
        "unfiltered": "Télécharger {count} entité | Télécharger {count} entités | Télécharger {count} entités",
        "filtered": {
          "withCount": "Télécharger {count} Entité correspondante | Télécharger {count} Entités correspondantes | Télécharger {count} Entités correspondantes",
          "withoutCount": "Télécharger les Entités correspondantes"
        }
      }
    }
  },
  "id": {
    "action": {
      "download": {
        "unfiltered": "Unduh {count} Entitas"
      }
    }
  },
  "it": {
    "action": {
      "download": {
        "unfiltered": "Scarica {count} entità | Scarica {count} entità | Scarica {count} entità",
        "filtered": {
          "withCount": "Scarica {count} Entità corrispondenti | Scarica {count} Entità corrispondenti | Scarica {count} Entità corrispondenti",
          "withoutCount": "Scarica Entità corrispondenti"
        }
      }
    }
  },
  "sw": {
    "action": {
      "download": {
        "unfiltered": "Pakua shirika {count} | Pakua Mashirika {count}",
        "filtered": {
          "withCount": "Pakua Huluki {count} inayolingana | Pakua huluki {count} zinazolingana",
          "withoutCount": "Pakua Huluki zinazolingana"
        }
      }
    }
  },
  "zh-Hant": {
    "action": {
      "download": {
        "unfiltered": "下載{count} 組實體",
        "filtered": {
          "withCount": "下載{count}個相符的實體",
          "withoutCount": "下載相符的實體"
        }
      }
    }
  }
}
</i18n>
