<!--
Copyright 2023 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <span id="entity-filters">
    <entity-filters-creator :model-value="creatorId"
      :disabled="disabled" :disabled-message="disabledMessage"
      @update:model-value="$emit('update:creatorId', $event)"/>
    <date-range-picker :model-value="creationDate"
      :label="$t('header.createdAt')"
      :disabled="disabled" :disabled-message="disabledMessage"
      :placeholder="$t('allCreationDateSelected')"
      @update:model-value="$emit('update:creationDate', $event)"/>
    <entity-filters-conflict :model-value="conflict" :disabled="disabled"
      :disabled-message="disabledMessage" @update:model-value="$emit('update:conflict', $event)"/>
     <button type="button" class="btn btn-link btn-reset"
      :aria-disabled="disabled" v-tooltip.aria-describedby="disabledMessage"
      @click="$emit('resetClick')">
      {{ $t('action.reset') }}
    </button>
  </span>
</template>

<script setup>
import EntityFiltersConflict from './filters/conflict.vue';
import EntityFiltersCreator from './filters/creator.vue';
import DateRangePicker from '../date-range-picker.vue';

defineOptions({
  name: 'EntityFilters'
});
defineProps({
  conflict: {
    type: Array,
    required: true
  },
  disabled: {
    type: Boolean,
    required: true
  },
  disabledMessage: {
    type: String,
    required: false
  },
  creatorId: {
    type: Array,
    required: false
  },
  creationDate: {
    type: Array,
    required: true
  }
});
defineEmits(['update:conflict', 'update:creationDate', 'update:creatorId', 'resetClick']);

</script>

<style lang="scss">
#entity-filters {
  margin-left: 10px;
}
</style>

<i18n lang="json5">
{
  "en": {
    // @transifexKey component.SubmissionFilters.allSubmissionDateSelected
    "allCreationDateSelected": "All time"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "allCreationDateSelected": "Alle Zeit"
  },
  "es": {
    "allCreationDateSelected": "Todos los tiempos"
  },
  "fr": {
    "allCreationDateSelected": "Tout temps"
  },
  "it": {
    "allCreationDateSelected": "Per tutto il tempo"
  },
  "pt": {
    "allCreationDateSelected": "Todas as datas"
  },
  "zh": {
    "allCreationDateSelected": "所有时间"
  },
  "zh-Hant": {
    "allCreationDateSelected": "全部時間"
  }
}
</i18n>
