<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <map-view ref="view" :odata="odataEntities" :url="geojsonUrl"
    :loading="$t('loading')">
    <template #popup="{ feature, odata: odataElement, listeners }">
      <entity-map-popup :uuid="feature?.id" :odata="odataElement"
        :awaiting-response="awaitingResponses.has(feature?.id)"
        v-on="{ ...listeners, ...reemitters }"/>
    </template>
    <template #overlap="{ features, listeners }">
      <map-overlap-popup :features="features" :odata-url="overlapUrl"
        v-on="listeners">
        <template #title>
          {{ $tcn('overlapTitle', features != null ? features.length : 0) }}
        </template>
        <template #feature="{ odata: odataElement }">
          {{ odataElement.label }}
        </template>
      </map-overlap-popup>
    </template>
  </map-view>
</template>

<script setup>
import { computed, inject, ref } from 'vue';

import EntityMapPopup from './map-popup.vue';
import MapOverlapPopup from '../map/overlap-popup.vue';
import MapView from '../map/view.vue';

import { apiPaths } from '../../util/request';
import { noop, reemit, reexpose } from '../../util/util';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'EntityMapView'
});
const props = defineProps({
  filter: String,
  searchTerm: String,
  awaitingResponses: {
    type: Set,
    required: true
  }
});
const emit = defineEmits(['update', 'resolve', 'delete']);

const projectId = inject('projectId');
const datasetName = inject('datasetName');

const { odataEntities } = useRequestData();

const geojsonUrl = computed(() => {
  const query = { $filter: props.filter, $search: props.searchTerm };
  return apiPaths.entities(projectId, datasetName, '.geojson', query);
});
const overlapUrl = (query) =>
  apiPaths.odataEntities(projectId, datasetName, query);

const reemitters = reemit(emit, ['update', 'resolve', 'delete']);

const view = ref(null);
defineExpose({
  ...reexpose(view, ['fetchData', 'cancelFetch', 'afterDelete']),
  afterUpdate: noop
});
</script>

<i18n lang="json5">
{
  "en": {
    "loading": "Preparing map. This could take a while.",
    "overlapTitle": "{count} Entity in this area | {count} Entities in this area"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "loading": "Karte wird vorbereitet. Dies kann einen Moment dauern.",
    "overlapTitle": "{count} Entität in diesem Umkreis | {count} Entitäten in diesem Umkreis"
  },
  "es": {
    "loading": "Preparando mapa. Esto puede tardar un poco.",
    "overlapTitle": "{count} Entidad a esta zona | {count} Entidades a esta zona | {count} Entidades a esta zona"
  },
  "fr": {
    "loading": "Préparation de la carte. Cela peut prendre un peu de temps.",
    "overlapTitle": "{count} entité dans cette zone | {count} entités dans cette zone | {count} entités dans cette zone"
  },
  "it": {
    "loading": "Preparazione della mappa. L'operazione potrebbe richiedere alcuni minuti.",
    "overlapTitle": "{count} Entità in quest'area | {count} Entità in quest'area | {count} Entità in quest'area"
  },
  "zh": {
    "loading": "正在准备地图。这可能需要一段时间。",
    "overlapTitle": "此区域内有{count}个实体"
  },
  "zh-Hant": {
    "loading": "正在準備地圖。這可能需要一段時間。",
    "overlapTitle": "此區域內有 {count} 個實體"
  }
}
</i18n>
