<!--
Copyright 2024 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="entity-restore" :state="state" :hideable="!awaitingResponse"
    backdrop @hide="$emit('hide')" @shown="focusCheckbox">
    <template #title>{{ $t('title', { label: entity?.label }) }}</template>
    <template #body>
      <div class="modal-introduction">
        <p>{{ $t('introduction[0]', { label: entity?.label }) }}</p>
        <p>{{ $t('introduction[1]') }}</p>
        <p>{{ $t('introduction[2]') }}</p>
      </div>
      <form v-if="checkbox">
        <div class="checkbox">
          <label>
            <input ref="input" v-model="noConfirm" type="checkbox">
            {{ $t('field.noConfirm') }}
          </label>
        </div>
      </form>
      <div class="modal-actions">
        <button type="button" class="btn btn-link"
          :aria-disabled="awaitingResponse" @click="$emit('hide')">
          {{ $t('action.cancel') }}
        </button>
        <button type="button" class="btn btn-danger"
          :aria-disabled="awaitingResponse" @click="restore">
          {{ $t('action.restore') }} <spinner :state="awaitingResponse"/>
        </button>
      </div>
    </template>
  </modal>
</template>

<script setup>
import { ref, watch } from 'vue';

import Modal from '../modal.vue';
import Spinner from '../spinner.vue';

defineOptions({
  name: 'EntityRestore'
});
const props = defineProps({
  state: Boolean,
  checkbox: Boolean,
  awaitingResponse: Boolean,
  entity: Object
});
const emit = defineEmits(['hide', 'restore']);

const noConfirm = ref(false);
watch(() => props.state, (state) => { if (!state) noConfirm.value = false; });

const input = ref(null);
const focusCheckbox = () => { if (props.checkbox) input.value.focus(); };

const restore = () => {
  if (props.checkbox)
    emit('restore', [props.entity, !noConfirm.value]);
  else
    emit('restore', [props.entity]);
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up. {label} is the label of an
    // Entity.
    "title": "Restore {label}",
    "introduction": [
      // {label} is the label of an Entity.
      "Are you sure you want to restore “{label}”?",
      "The Entity will be restored to its previous state.",
      "If the Entity is deleted again, it will be another 30 days before it is removed."
    ],
    "field": {
      // @transifexKey component.SubmissionRestore.field.noConfirm
      "noConfirm": "Restore immediately without confirmation until I leave the page"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "title": "Wiederherstellen {label}",
    "introduction": [
      "Sind Sie sicher, dass Sie “{label}” wiederherstellen wollen?",
      "Das Objekt wird in ihrem vorherigen Zustand wiederhergestellt.",
      "Wenn das Objekt erneut gelöscht wird, dauert es 30 Tage bis es entfernt wird."
    ],
    "field": {
      "noConfirm": "Sofortige Wiederherstellen ohne Bestätigung, bis ich die Seite verlasse"
    }
  },
  "es": {
    "title": "Restablecer {label}",
    "introduction": [
      "¿Está seguro que desea restablecer “{label}”?",
      "La Entidad volverá a su estado anterior.",
      "Si la Entidad se elimina nuevamente, pasarán otros 30 días antes de que se elimine."
    ],
    "field": {
      "noConfirm": "Restablecer inmediatamente sin confirmación hasta que salga de la página"
    }
  },
  "fr": {
    "title": "Restaurer {label}",
    "introduction": [
      "Êtes vous certain(e) de vouloir restaurer \"{label}\" ?",
      "L'Entité sera restaurée dans son état précédent.",
      "Si l'entité est à nouveau mise à la corbeille, il faudra à nouveau 30 jours avant sa suppression."
    ],
    "field": {
      "noConfirm": "Restaurer immédiatement sans confirmation jusqu'à ce que je quitte la page"
    }
  },
  "it": {
    "title": "Ripristina {label}",
    "introduction": [
      "Sei sicuro di voler ripristinare \"{label}\"?",
      "L'Entità verrà ripristinata al suo stato precedente.",
      "Se L'Entità viene nuovamente eliminata, ci vorranno altri 30 giorni prima che venga rimossa."
    ],
    "field": {
      "noConfirm": "Ripristino immediato senza conferma fino a quando non lascio la pagina"
    }
  },
  "pt": {
    "title": "Recuperar {label}",
    "introduction": [
      "Tem certeza que deseja recuperar \"{label}\"?",
      "A Entidade vai ser restaurada ao seu estado anterior.",
      "Se a Entidade for excluída novamente, serão mais 30 dias até que ela seja removida."
    ],
    "field": {
      "noConfirm": "Recuperar imediatamente sem pedir confirmação até que eu saia desta página"
    }
  },
  "zh": {
    "title": "恢复{label}",
    "introduction": [
      "确定要恢复“{label}”吗？",
      "该实体将恢复至先前状态。",
      "若该实体再次被删除，将再过30天才会被移除。"
    ],
    "field": {
      "noConfirm": "在我离开页面前，无需确认立即恢复"
    }
  },
  "zh-Hant": {
    "title": "恢復{label}",
    "introduction": [
      "您確定要恢復「{label}」嗎？",
      "實體將恢復到先前的狀態。",
      "如果實體再次被刪除，將再過 30 天才能移除。"
    ],
    "field": {
      "noConfirm": "立即還原，無需確認，直到我離開頁面"
    }
  }
}
</i18n>
