<!--
Copyright 2023 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div class="entity-diff-head">
    <div v-if="entityVersion.conflict === 'hard'">
      <span class="icon-warning"></span>
      <p>
        <strong>{{ $t('common.conflict') }}&nbsp;</strong>
        <span>{{ $t('introduction', { version: entityVersion.version - 1, baseVersion: entityVersion.baseVersion }) }}</span>
        <sentence-separator/>
        <span>{{ $t('hardConflict.description') }}</span>
      </p>
    </div>
    <div v-else>
      <span class="icon-info-circle"></span>
      <p>
        <strong>{{ $t('softConflict.title') }}&nbsp;</strong>
        <span>{{ $t('introduction', { version: entityVersion.version - 1, baseVersion: entityVersion.baseVersion }) }}</span>
      </p>
    </div>
    <ul class="nav nav-tabs">
      <li v-for="[diff, version] of tabs" :key="diff"
        :class="{ active: modelValue === diff }" role="presentation">
        <a href="#" role="button" @click.prevent="change(diff)">
          {{ $t(`tab.${diff}`) }}
          <span class="updating">
            {{ $t('tab.updating', { version: $t('common.versionShort', { version }) }) }}
          </span>
        </a>
      </li>
    </ul>
  </div>
</template>

<script setup>
import { inject } from 'vue';

import SentenceSeparator from '../../sentence-separator.vue';

defineOptions({
  name: 'EntityDiffHead'
});
const props = defineProps({
  modelValue: {
    type: String,
    required: true
  }
});
const emit = defineEmits(['update:modelValue']);

const entityVersion = inject('entityVersion');
const tabs = [
  ['baseDiff', entityVersion.baseVersion],
  ['serverDiff', entityVersion.version - 1]
];

const change = (value) => {
  if (value !== props.modelValue) emit('update:modelValue', value);
};
</script>

<style lang="scss">
@import '../../../assets/scss/variables';

.entity-diff-head {
  .entity-diff.hard-conflict & { background-color: $color-danger; }
  .entity-diff.soft-conflict & { background-color: $color-warning-dark; }

  > div {
    color: #fff;
    display: flex;
  }

  p {
    line-height: 1.2;
    margin-bottom: 18px;
    margin-left: $margin-right-icon;
    max-width: none;
  }

  .icon-warning, .icon-info-circle { font-size: 16px; }
  strong { margin-right: 4px; }

  li {
    margin-bottom: 0;
    margin-right: 3px;

    a { font-weight: 600; }
    a, &.active a {
      &, &:hover, &:focus {
        border-bottom: none;
        border-top-left-radius: 3px;
        border-top-right-radius: 3px;
        color: #fff;
        padding-bottom: 5px;
        padding-top: 6px;
      }
    }
    &.active a {
      &, &:hover, &:focus { background-color: $background-color-feed-entry; }
    }
  }
  .entity-diff.hard-conflict & {
    li.active a { color: $color-danger; }
    .entity-feed-entry:hover & li:not(.active) a {
      background-color: $color-danger-lighter;
    }
  }
  .entity-diff.soft-conflict & {
    li.active a { color: $color-warning-dark; }
    .entity-feed-entry:hover & li:not(.active) a {
      background-color: $color-warning;
    }
  }

  .updating { margin-left: 2px; }
}
</style>

<i18n lang="json5">
{
  "en": {
    // {version} and {baseVersion} are version numbers.
    "introduction": "This Submission update was applied to version {version} of this Entity, but it was created based on version {baseVersion}.",
    "hardConflict": {
      "description": "Other updates had already written to the same properties."
    },
    "softConflict": {
      // An update to an Entity that was made at the same time as another update
      "title": "Parallel Update"
    },
    "tab": {
      // A comparison between two versions of an Entity, from the point of view
      // of the data collector (the author)
      "baseDiff": "Author’s View",
      // A comparison between two versions of an Entity, from the point of view
      // of the Central server
      "serverDiff": "Central’s View",
      // This text is shown for an update to an Entity. {version} is a short
      // version identifier, for example, "v3". It is the version that the
      // update was applied to.
      "updating": "(updating {version})"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "softConflict": {
      "title": "Paralelní aktualizace"
    },
    "tab": {
      "baseDiff": "Pohled autora",
      "serverDiff": "Pohled Centralu",
      "updating": "(aktualizace {version})"
    }
  },
  "de": {
    "introduction": "Diese Aktualisierung der Übermittlung wurde auf Version {version} dieses Objekts angewendet, aber sie wurde basierend auf Version {baseVersion} erstellt.",
    "hardConflict": {
      "description": "Andere Updates wurden bereits in die gleichen Eigenschaften geschrieben."
    },
    "softConflict": {
      "title": "Parallel Update"
    },
    "tab": {
      "baseDiff": "Autoren-Ansicht",
      "serverDiff": "Zentrale Ansicht",
      "updating": "(aktualisiere {version})"
    }
  },
  "es": {
    "introduction": "Esta actualización de envío se aplicó a la versión {version} de esta entidad, pero se creó basándose en la versión {baseVersion}.",
    "hardConflict": {
      "description": "Otras actualizaciones ya habían sido escritas en las mismas propiedades."
    },
    "softConflict": {
      "title": "Actualización Paralela"
    },
    "tab": {
      "baseDiff": "Vista del autor",
      "serverDiff": "Vista de Central",
      "updating": "(actualizando {version})"
    }
  },
  "fr": {
    "introduction": "Cette Soumission de mise à jour a été appliquée à la version {version} de cette entité, mais elle a été créée sur la base de la version {baseVersion}.",
    "hardConflict": {
      "description": "D'autres mises à jour ont déjà écrit sur les mêmes propriétés."
    },
    "softConflict": {
      "title": "Mise à jour Parallèle"
    },
    "tab": {
      "baseDiff": "Vue de l'Auteur",
      "serverDiff": "Vue de Central",
      "updating": "(mise à jour {version})"
    }
  },
  "it": {
    "introduction": "Questa modifica di invio è stata applicata alla versione {version} di questa Entità, ma è stata creata sulla base della versione {baseVersion}.",
    "hardConflict": {
      "description": "Altre aggiornamenti erano già stati scritti sulle stesse proprietà."
    },
    "softConflict": {
      "title": "Aggiornamento parallelo"
    },
    "tab": {
      "baseDiff": "Vista dell'autore",
      "serverDiff": "Vista di Central",
      "updating": "(aggiornando {version})"
    }
  },
  "pt": {
    "introduction": "Esta atualização de Resposta foi aplicada à versão {version} desta Entidade, mas foi criada com base na versão {baseVersion}.",
    "hardConflict": {
      "description": "Outras atualizações já foram gravadas nas mesmas propriedades."
    },
    "softConflict": {
      "title": "Atualização paralela"
    },
    "tab": {
      "baseDiff": "Visualização do Autor",
      "serverDiff": "Visualização do Central",
      "updating": "(atualizando {version})"
    }
  },
  "zh": {
    "introduction": "此提交更新已应用于该实体第{version}版，但它是基于第{baseVersion}版创建的。",
    "hardConflict": {
      "description": "其他更新已写入相同属性。"
    },
    "softConflict": {
      "title": "并行更新"
    },
    "tab": {
      "baseDiff": "提交者视图",
      "serverDiff": "Central系统视图",
      "updating": "（{version}更新中）"
    }
  },
  "zh-Hant": {
    "introduction": "此提交更新已套用至該實體的版本 {version}，但它是基於版本{baseVersion}建立的。",
    "hardConflict": {
      "description": "其他更新已寫入相同的屬性。"
    },
    "softConflict": {
      "title": "平行更新"
    },
    "tab": {
      "baseDiff": "由作者的角度",
      "serverDiff": "由Central的角度",
      "updating": "(更新中{version})"
    }
  }
}
</i18n>
