<!--
Copyright 2019 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="project-archive" :state="state" :hideable="!awaitingResponse"
    backdrop @hide="$emit('hide')">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="modal-introduction">
        <p>{{ project.dataExists ? $t('introduction[0]', project) : '' }}</p>
        <i18n-t tag="p" keypath="introduction[1].full">
          <template #noUndo>
            <strong>{{ $t('introduction[1].noUndo') }}</strong>
          </template>
        </i18n-t>
        <p>{{ $t('common.areYouSure') }}</p>
      </div>
      <div class="modal-actions">
        <button type="button" class="btn btn-link" :aria-disabled="awaitingResponse"
          @click="$emit('hide')">
          {{ $t('action.noCancel') }}
        </button>
        <button type="button" class="btn btn-danger"
          :aria-disabled="awaitingResponse" @click="archive">
          {{ $t('action.yesProceed') }} <spinner :state="awaitingResponse"/>
        </button>
      </div>
    </template>
  </modal>
</template>

<script setup>
import Modal from '../modal.vue';
import Spinner from '../spinner.vue';

import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'ProjectArchive'
});
defineProps({
  state: {
    type: Boolean,
    default: false
  }
});
const emit = defineEmits(['hide', 'success']);

const { project } = useRequestData();
const { awaitingResponse } = project.toRefs();
const archive = () => {
  project.request({
    method: 'PATCH',
    url: apiPaths.project(project.id),
    data: { archived: true },
    patch: ({ data }) => {
      project.archived = true;
      project.updatedAt = data.updatedAt;
    }
  })
    .then(() => { emit('success'); })
    .catch(noop);
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up.
    "title": "Archiving Project",
    "introduction": [
      "You are about to archive the Project “{name}”. It will still work as it does now, but it will be sorted to the bottom of the Project List on the Central homepage.",
      {
        "full": "{noUndo}, but the ability to unarchive a Project is planned for a future release.",
        "noUndo": "This action cannot be undone"
      }
    ]
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Archivování projektu",
    "introduction": [
      "Chystáte se archivovat projekt „{name}“. Bude stále fungovat jako nyní, ale bude se řadit na konec seznamu projektů na hlavní domovské stránce.",
      {
        "full": "{noUndo}, ale schopnost vyjmout projekt z archivu je plánována do budoucího vydání.",
        "noUndo": "Tuto akci nelze vrátit zpět"
      }
    ]
  },
  "de": {
    "title": "Projekt wird archiviert",
    "introduction": [
      "Sie sind dabei das Projekt \"{name}\" zu archivieren. Es wird weiterhin wie bisher funktioniern, aber es wird ans Ende der Projektliste auf der Homepage von Central verschoben.",
      {
        "full": "{noUndo}, aber die Möglichkeit ein Projekt zu dearchivieren ist für eine zukünftige Version geplant.",
        "noUndo": "Diese Aktion kann nicht rückgängig gemacht werden"
      }
    ]
  },
  "es": {
    "title": "Archivando proyecto",
    "introduction": [
      "Está a punto de archivar el proyecto \"{name}\". Seguirá funcionando como lo hace ahora, pero se ordenará al final de la lista de proyectos de la página de inicio Central.",
      {
        "full": "{noUndo} pero la posibilidad de desarchivar un proyecto está prevista para una futura versión.",
        "noUndo": "Esta acción no se puede deshacer."
      }
    ]
  },
  "fr": {
    "title": "Archivage du projet",
    "introduction": [
      "Vous êtes sur le point d'archiver le projet “{name}”. Il fonctionnera toujours comme maintenant, mais il sera classé en bas de la liste des projets de la page d'accueil de Central.",
      {
        "full": "{noUndo}, mais la possibilité de \"dés-archiver\" un projet est prévu pour une version future.",
        "noUndo": "Cette action ne peut être annulée"
      }
    ]
  },
  "id": {
    "title": "Mengarsip Proyek",
    "introduction": [
      "Anda hendak mengarsip Proyek \"{name}\". Proyek akan tetap berjalan seperti sekarang, tetapi peletakannya akan berada di bawah Daftar Proyek pada laman utama Central.",
      {
        "full": "{noUndo}, tetapi fungsi untuk membatalkan pengarsipan Proyek akan dirancang untuk pembaruan yang akan datang.",
        "noUndo": "Tindakan ini tidak bisa dibatalkan/dikembalikan"
      }
    ]
  },
  "it": {
    "title": "Archiviando il Progetto",
    "introduction": [
      "Stai per archiviare il Progetto “{name}”. Continuerà a funzionare, ma verrà ordinato in fondo all'elenco dei progetti nella home page di Central.",
      {
        "full": "{noUndo}, ma la possibilità di annullare l'archiviazione di un progetto è prevista per una versione futura.",
        "noUndo": "Quest'azione non può essere annullata"
      }
    ]
  },
  "ja": {
    "title": "プロジェクトのアーカイブ",
    "introduction": [
      "プロジェクト \"{name}\"をアーカイブしようとしています。現在と同様に機能しますが、Centralのトップページのプロジェクトリストの一番下に表示されます。",
      {
        "full": "{noUndo}プロジェクトの非アーカイブ化機能は将来的にリリースされる予定です。",
        "noUndo": "この操作は取り消しできません。"
      }
    ]
  },
  "pt": {
    "title": "Arquivando o projeto",
    "introduction": [
      "Você está prestes a arquivar o projeto \"{name}\". Ele continuará funcionando como está agora, mas será exibido no final da lista de projetos da página principal do Central.",
      {
        "full": "{noUndo}, mas a possibilidade de desarquivar um projeto está planejada para uma versão futura.",
        "noUndo": "Essa ação não pode ser desfeita"
      }
    ]
  },
  "sw": {
    "title": "Mradi wa Kuhifadhi kumbukumbu",
    "introduction": [
      "Unakaribia kuweka Mradi \"{name}\" kwenye kumbukumbu. Bado itafanya kazi kama inavyofanya sasa, lakini itapangwa hadi chini ya Orodha ya Mradi kwenye ukurasa wa nyumbani wa Central",
      {
        "full": "{noUndo}, lakini uwezo wa kutoa Mradi kwenye kumbukumbu umepangwa kutolewa siku zijazo.",
        "noUndo": "Kitendo hiki hakiwezi kutenduliwa"
      }
    ]
  },
  "zh": {
    "title": "正在归档项目",
    "introduction": [
      "您即将归档项目“{name}”。归档后项目功能保持不变，但将在Central首页项目列表中置底显示。",
      {
        "full": "{noUndo}，但项目取消归档功能计划在后续版本中推出。",
        "noUndo": "此操作无法取消"
      }
    ]
  },
  "zh-Hant": {
    "title": "歸檔專案",
    "introduction": [
      "您即將歸檔「{name}」專案。它仍一樣工作，但它將被排序到 Central 主頁項目清單的底部。",
      {
        "full": "{noUndo}，但計劃在未來版本中提供取消專案歸檔的功能。",
        "noUndo": "此操作無法撤銷"
      }
    ]
  }
}
</i18n>
