<!--
Copyright 2019 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="project-edit" class="panel panel-simple">
    <div class="panel-heading">
      <h1 class="panel-title">{{ $t('title') }}</h1>
    </div>
    <div class="panel-body">
      <form @submit.prevent="submit">
        <form-group v-model.trim="name" :placeholder="$t('field.name')" required
          autocomplete="off"/>
        <button type="submit" class="btn btn-primary"
          :disabled="awaitingResponse">
          {{ $t('action.saveSettings') }} <spinner :state="awaitingResponse"/>
        </button>
      </form>
    </div>
  </div>
</template>

<script>
import { inject, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import FormGroup from '../form-group.vue';
import Spinner from '../spinner.vue';

import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';

export default {
  name: 'ProjectEdit',
  components: { FormGroup, Spinner },
  setup() {
    const { requestData, alert } = inject('container');
    const { project } = requestData;
    const name = ref(project.data.name);

    const { t } = useI18n();
    const submit = () => project.request({
      method: 'PATCH',
      url: apiPaths.project(project.data.id),
      data: { name: name.value },
      // Specifying `update` because the response will not include extended
      // metadata.
      update: ({ data }) => { project.update(data); }
    })
      .then(() => { alert.success(t('alert.success')); })
      .catch(noop);

    return { name, submit, awaitingResponse: project.awaitingResponse };
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is a title shown above a section of the page.
    "title": "Basic Details",
    "field": {
      "name": "Project name"
    },
    "alert": {
      "success": "Project settings saved!"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Základní detaily",
    "field": {
      "name": "Název projektu"
    },
    "alert": {
      "success": "Nastavení projektu uloženo."
    }
  },
  "de": {
    "title": "Basisinformationen",
    "field": {
      "name": "Projektname"
    },
    "alert": {
      "success": "Projekteinstellungen wurden gespeichert"
    }
  },
  "es": {
    "title": "Detalles básicos",
    "field": {
      "name": "Nombre del proyecto"
    },
    "alert": {
      "success": "¡Configuración del proyecto guardada!"
    }
  },
  "fr": {
    "title": "Détails basiques",
    "field": {
      "name": "Nom du projet"
    },
    "alert": {
      "success": "Paramètres du projet enregistrés !"
    }
  },
  "id": {
    "title": "Rincian Dasar",
    "field": {
      "name": "Nama Proyek"
    },
    "alert": {
      "success": "Pengaturan proyek tersimpan!"
    }
  },
  "it": {
    "title": "Dettagli di base",
    "field": {
      "name": "Nome del Progetto"
    },
    "alert": {
      "success": "Impostazioni del progetto salvate!"
    }
  },
  "ja": {
    "title": "基本詳細",
    "field": {
      "name": "プロジェクト名"
    },
    "alert": {
      "success": "プロジェクト設定の保存完了！"
    }
  }
}
</i18n>
