<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal :state="state" hideable backdrop @hide="$emit('hide')">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="modal-introduction">
        <p>{{ $t('introduction[0]') }}</p>
        <ul>
          <i18n-t tag="li" keypath="introduction[1].full">
            <template #appUsers>
              <router-link v-if="$route.path !== projectPath('app-users')"
                :to="projectPath('app-users')">
                <strong>{{ $t('introduction[1].appUsers') }}</strong>
              </router-link>
              <a v-else href="#" @click.prevent="$emit('hide')">
                <strong>{{ $t('introduction[1].appUsers') }}</strong>
              </a>
            </template>
            <template #collect>
              <doc-link to="collect-intro/">ODK Collect</doc-link>
            </template>
          </i18n-t>
          <i18n-t tag="li" keypath="introduction[2].full">
            <template #publicLinks>
              <!-- Only render text, not a link, for a project route. -->
              <template v-if="$route.params.xmlFormId == null">
                <strong>{{ $t('introduction[2].publicLinks') }}</strong>
              </template>
              <router-link v-else-if="$route.path !== formPath('public-links')"
                :to="formPath('public-links')">
                <strong>{{ $t('introduction[2].publicLinks') }}</strong>
              </router-link>
              <a v-else href="#" @click.prevent="$emit('hide')">
                <strong>{{ $t('introduction[2].publicLinks') }}</strong>
              </a>
            </template>
          </i18n-t>
          <i18n-t tag="li" keypath="introduction[3].full">
            <template #webUser>
              <link-if-can to="/users">
                <strong>{{ $t('introduction[3].webUser') }}</strong>
              </link-if-can>
            </template>
            <template #dataCollector>
              <router-link :to="projectPath('users')">
                <strong>{{ $t('introduction[3].dataCollector') }}</strong>
              </router-link>
            </template>
          </i18n-t>
        </ul>
      </div>
      <div class="modal-actions">
        <button type="button" class="btn btn-primary" @click="$emit('hide')">
          {{ $t('action.ok') }}
        </button>
      </div>
    </template>
  </modal>
</template>

<script setup>
import DocLink from '../doc-link.vue';
import LinkIfCan from '../link-if-can.vue';
import Modal from '../modal.vue';

import useRoutes from '../../composables/routes';

defineOptions({
  name: 'ProjectSubmissionOptions'
});
defineProps({
  state: Boolean
});
defineEmits(['hide']);

const { projectPath, formPath } = useRoutes();
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up.
    "title": "Submission Options",
    "introduction": [
      // This text is shown above a list of options for submitting data.
      "There are several options for submitting data to ODK Central:",
      {
        // This text is shown in a list of options for submitting data.
        // {collect} is a link whose text is "ODK Collect".
        "full": "Create {appUsers} and use the {collect} Android application. This is most appropriate when data collectors need access to multiple Forms, are offline, or you have a complex Form.",
        "appUsers": "App Users"
      },
      {
        // This text is shown in a list of options for submitting data.
        "full": "Create one or more {publicLinks} to share with respondents who will self-report.",
        "publicLinks": "Public Access Links"
      },
      {
        // This text is shown in a list of options for submitting data.
        "full": "Create a {webUser} with the Role of {dataCollector} for each individual who will be collecting data. These Users will log into Central to fill out this Form in a web browser. Project Managers can also create Submissions from a web browser.",
        "webUser": "Web User",
        "dataCollector": "Data Collector"
      }
    ]
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Možnosti Příspěvků",
    "introduction": [
      "Existuje několik možností pro odesílání dat do ODK Central:",
      {
        "full": "Vytvořte {appUsers} a použijte {collect} aplikaci pro Android. To je nejvhodnější, pokud sběratelé dat potřebují přístup k více formulářům, jsou offline, nebo máte složitý formulář.",
        "appUsers": "Uživatele aplikace"
      },
      {
        "full": "Vytvořte jeden nebo více {publicLinks} a sdílejte je s respondenty, kteří se budou sami reportovat.",
        "publicLinks": "Veřejně přístupných odkazů"
      },
      {
        "full": "Vytvořte {webUser} s rolí {dataCollector} pro každého jednotlivce, který bude shromažďovat data. Tito uživatelé se přihlásí do Central a vyplní tento formulář ve webovém prohlížeči. Projektoví manažeři mohou také vytvářet příspěvky z webového prohlížeče.",
        "webUser": "Webového uživatele",
        "dataCollector": "Sběrač dat"
      }
    ]
  },
  "de": {
    "title": "Übermittlungsoptionen",
    "introduction": [
      "Es gibt mehrere Optionen, um Daten an ODK Central zu übermitteln:",
      {
        "full": "{appUsers} erstellen und die {collect} Android-App benutzen. Dies passt am besten, wenn die Datensammler Zugriff auf mehrere Formulare benötigen, offline sind oder wenn Sie ein komplexes Formular haben.",
        "appUsers": "App-Benutzer"
      },
      {
        "full": "Einen oder mehrere {publicLinks} erstellen, um sie mit Befragten zu teilen, die selbst ausfüllen.",
        "publicLinks": "Öffentlicher Zugangslinks"
      },
      {
        "full": "Erstellen Sie einen {webUser} mit der Rolle eines {dataCollector} für jeden Einzelnen, der Daten sammeln wird. Diese Benutzer werden sich in Central einloggen, um dieses Formular in einem Webbrowser auszufüllen. Projekt-Manager können auch Übermittlungen in einem Webbrowser erstellen.",
        "webUser": "Web-Benutzer",
        "dataCollector": "Datensammler"
      }
    ]
  },
  "es": {
    "title": "Opciones de envío",
    "introduction": [
      "Hay varias opciones para enviar datos a ODK Central:",
      {
        "full": "Crea {appUsers} y usa la aplicación Android {collect}. Esto es más apropiado cuando los recolectores de datos necesitan acceso a múltiples formularios, están fuera de línea o tiene un formulario complejo.",
        "appUsers": "Usuarios móviles"
      },
      {
        "full": "Cree uno o más {publicLinks} para compartir con los encuestados que se auto informarán.",
        "publicLinks": "Enlaces de acceso público"
      },
      {
        "full": "Cree un {webUser} con el rol de {dataCollector} para cada individuo que recopilará datos. Estos usuarios iniciarán sesión en Central para completar este Formulario en un navegador web. Los administradores de proyectos también pueden crear envíos desde un navegador web.",
        "webUser": "Usuario web",
        "dataCollector": "Recolector de datos"
      }
    ]
  },
  "fr": {
    "title": "Méthodes d'envoi de données",
    "introduction": [
      "Il y a plusieurs méthodes pour envoyer des données à ODK Central:",
      {
        "full": "Créez des {appUsers} et utilisez l'application Android {collect}. Cela convient particulièrement bien quand les collecteurs de données doivent accéder à plusieurs formulaires, sont hors-ligne, ou ont des formulaires complexes.",
        "appUsers": "Utilisateurs mobiles"
      },
      {
        "full": "Créez un ou plusieurs {publicLinks} à partager avec des répondants.",
        "publicLinks": "liens d'accès public"
      },
      {
        "full": "Créez un {webUser} avec le rôle de {dataCollector} pour chaque individu qui participera à la collecte de données. Ces utilisateurs accéderont à leurs comptes Central pour remplir ce formulaire depuis leurs navigateurs. Les gestionnaires de projet peuvent également créer des soumissions depuis leurs navigateurs.",
        "webUser": "utilisateur web",
        "dataCollector": "collecteur de données"
      }
    ]
  },
  "id": {
    "title": "Pengaturan Kiriman Data",
    "introduction": [
      "Ada beberapa pengaturan untuk mengirim data ke ODK Central:",
      {
        "full": "Buat {appUsers} dan gunakan aplikasi Android {collect}. Ini akan membantu dan memudahkan pengumpul data membutuhkan akses ke berbagai formulir, sedang offline, atau ketika Anda memiliki formulir yang kompleks.",
        "appUsers": "Pengguna Aplikasi"
      },
      {
        "full": "Buat satu atau lebih {publicLinks} untuk dibagikan dengan responden yang akan melakukan laporan pribadi.",
        "publicLinks": "Tautan Akses Publik"
      },
      {
        "full": "Buat sebuah {webUser} dengan Peran sebagai {dataCollector} untuk setiap invididu yang akan mengumpulkan data. Pengguna ini akan masuk ke Central untuk mengisi formulir lewat web browser. Manajer Proyek juga bisa membuat kiriman data lewat web browser.",
        "webUser": "Pengguna Web",
        "dataCollector": "Pengumpul Data"
      }
    ]
  },
  "it": {
    "title": "Opzioni invio",
    "introduction": [
      "Esistono diverse opzioni per inviare dati a ODK Central:",
      {
        "full": "Creare {appUsers} e utilizzare l'applicazione Android {collect}. Questo è più appropriato quando i raccoglitori di dati devono accedere a più formulari, sono offline o nel caso tu abbia un formulario complesso.",
        "appUsers": "Utenti dell'applicazione"
      },
      {
        "full": "Creane uno o più {publicLinks} da condividere con gli intervistati che si auto-intervisteranno.",
        "publicLinks": "Link con accesso pubblico"
      },
      {
        "full": "Crea un {webUser} con il ruolo di {dataCollector} per ogni individuo che raccoglierà dati. Questi utenti accederanno a Central per compilare questo formulario in un browser web. I project manager possono anche creare invii da un browser web.",
        "webUser": "Utente Web",
        "dataCollector": "Raccoglitore di dati"
      }
    ]
  },
  "ja": {
    "title": "フォーム提出方法の選択肢",
    "introduction": [
      "ODK Centralへのデータ提出方法にはいくつかの選択肢があります。",
      {
        "full": "{appUsers}を作成し、Androidアプリの{collect}を使用して下さい。この方法は、データ収集者が複数のフォームにアクセスする必要がある場合や、オフラインである場合、複雑なフォームを持っている場合などに最適です",
        "appUsers": "アプリユーザー"
      },
      {
        "full": "１つ以上の{publicLinks}を作成し、回答者と共有する。回答者は自身でフォームに入力し、提出する。",
        "publicLinks": "一般公開リンク"
      },
      {
        "full": "データを収集する各個人に、{dataCollector}の役割を持つ{webUser}を作成します。これらのユーザーはCentralにログインし、Webブラウザでこのフォームに入力します。プロジェクトマネージャーもブラウザ経由でフォームが提出できます。",
        "webUser": "Webユーザー",
        "dataCollector": "データ収集者"
      }
    ]
  },
  "pt": {
    "title": "Opções de resposta",
    "introduction": [
      "Existem várias maneiras de enviar respostas para o ODK Central:",
      {
        "full": "Crie {appUsers} e utilize o aplicativo {collect} para Android. Isso é o mais apropriado quando os coletores de dados precisam de acesso a múltiplos formulários, ficam sem internet, ou quando você tem um formulário complexo.",
        "appUsers": "Usuários de aplicativo"
      },
      {
        "full": "Crie um ou mais {publicLinks} para compartilhar com entrevistados que preencherão o formulário de forma autônoma.",
        "publicLinks": "Links de acesso público"
      },
      {
        "full": "Crie um {webUser} com a função de {dataCollector} para cada indivíduo que fará a coleta de dados. Esses usuários poderão fazer login no Central para preencher o formulário em um navegador de internet. Gerentes de projeto também podem preencher formulários a partir do navegador de internet.",
        "webUser": "Usuário da web",
        "dataCollector": "Coletor de dados"
      }
    ]
  },
  "sw": {
    "title": "Chaguzi za Uwasilishaji",
    "introduction": [
      "Kuna chaguo kadhaa za kuwasilisha data kwa ODK Central:",
      {
        "full": "Unda {appUsers} na utumie programu ya Android ya {collect}. Hii inafaa zaidi wakati wakusanyaji wa data wanahitaji ufikiaji wa Fomu nyingi, wako nje ya mtandao, au una Fomu ngumu",
        "appUsers": "Watumiaji wa Programu"
      },
      {
        "full": "Unda {publicLinks} moja au zaidi ili kushiriki na waliojibu ambao watajiripoti.",
        "publicLinks": "Viungo vya Ufikiaji wa Umma"
      },
      {
        "full": "Unda {webUser} na Jukumu la {dataCollector} kwa kila mtu ambaye atakuwa akikusanya data. Watumiaji hawa wataingia katika Kituo Kikuu ili kujaza Fomu hii katika kivinjari cha wavuti. Wasimamizi wa Miradi wanaweza pia kuunda Mawasilisho kutoka kwa kivinjari cha wavuti.",
        "webUser": "Mtumiaji wa Mtandao",
        "dataCollector": "Mkusanya Data"
      }
    ]
  },
  "zh": {
    "title": "提交选项",
    "introduction": [
      "向ODK Central提交数据有以下几种方式：",
      {
        "full": "创建{appUsers}并使用{collect}安卓应用程序。此方式最适合数据收集员需访问多个表单、处于离线状态或使用复杂表单的场景。",
        "appUsers": "APP用户"
      },
      {
        "full": "创建一个或多个{publicLinks}，供受访者自行填报数据。",
        "publicLinks": "公开访问链接"
      },
      {
        "full": "为每位数据收集员创建角色为{dataCollector}的{webUser}。这些用户将登录Central平台，通过网页浏览器填写表单。项目经理也可通过网页浏览器创建提交记录。",
        "webUser": "网页用户",
        "dataCollector": "数据收集者"
      }
    ]
  },
  "zh-Hant": {
    "title": "提交選項",
    "introduction": [
      "有多種選項可用於向 ODK Central 提交資料：",
      {
        "full": "建立 {appUsers} 並使用 {collect} Android 應用程式。當資料收集者需要存取多個表單、處於離線狀態或您有一個複雜的表單時，這是最合適的。",
        "appUsers": "App 使用者"
      },
      {
        "full": "建立一個或多個 {publicLinks} 以與進行自我報告的受訪者分享。",
        "publicLinks": "公共訪問連結"
      },
      {
        "full": "為每個要收集資料的人建立一個角色為 {dataCollector} 的 {webUser}。這些使用者將登入 Central 以在網頁瀏覽器中填寫此表格。專案管理員也可以從網頁瀏覽器建立提交。",
        "webUser": "網路使用者",
        "dataCollector": "資料收集者"
      }
    ]
  }
}
</i18n>
