<!--
Copyright 2024 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <i18n-t tag="span" keypath="text.full">
    <template #downloadTemplate>
      <a class="btn" :class="error ? 'btn-danger' : 'btn-default'" :href="href"
        @click="setFilename">
        <span class="icon-download"></span>{{ $t('text.downloadTemplate') }}
      </a>
    </template>
  </i18n-t>
</template>

<script setup>
import { DateTime } from 'luxon';
import { computed } from 'vue';

import { useRequestData } from '../../../request-data';

defineOptions({
  name: 'EntityUploadDataTemplate'
});
defineProps({
  error: Boolean
});

// The component assumes that this data will exist when the component is
// created.
const { dataset } = useRequestData();

const href = computed(() => {
  const headers = dataset.properties.map(({ name }) => name);
  headers.unshift('label');
  const csv = headers.join(',');
  // \uFEFF is byte-order-mark - fixes getodk/central#721
  return `data:text/csv;charset=UTF-8,\uFEFF${encodeURIComponent(csv)}`;
});
const setFilename = (event) => {
  const now = DateTime.local().toFormat('yyyyMMddHHmmss');
  event.target.setAttribute('download', `${dataset.name} ${now}.csv`);
};
</script>

<i18n lang="json5">
{
  "en": {
    "text": {
      "full": "If you aren’t sure, you can {downloadTemplate}",
      "downloadTemplate": "Download a data template (.csv)"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "text": {
      "full": "Wenn Sie sich nicht sicher sind, können Sie {downloadTemplate} herunterladen.",
      "downloadTemplate": "Downloaden Sie eine Datenvorlage (.csv)"
    }
  },
  "es": {
    "text": {
      "full": "Si no estás seguro, puedes {downloadTemplate}",
      "downloadTemplate": "Descargar una plantilla de datos (.csv)"
    }
  },
  "fr": {
    "text": {
      "full": "Si vous n'êtes pas sûr, vous pouvez {downloadTemplate}",
      "downloadTemplate": "Télécharger un modèle de données (.csv)"
    }
  },
  "it": {
    "text": {
      "full": "Se non sei sicuro, puoi {downloadTemplate}",
      "downloadTemplate": "Scarica un modello di dati (.csv)"
    }
  },
  "pt": {
    "text": {
      "full": "Se não tiver certeza, você pode {downloadTemplate}",
      "downloadTemplate": "Baixar um modelo de dados (.csv)"
    }
  },
  "zh": {
    "text": {
      "full": "如果您不确定，您可以{downloadTemplate}",
      "downloadTemplate": "下载数据模板（.csv）"
    }
  },
  "zh-Hant": {
    "text": {
      "full": "如果您不確定，您可以{downloadTemplate}",
      "downloadTemplate": "下載資料模板 (.csv)"
    }
  }
}
</i18n>
