<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <table-freeze v-if="dataExists" id="public-link-table" :data="publicLinks.data" key-prop="id"
    :frozen-only="actorProperties.length === 0" :divider="actorProperties.length > 0">
    <template #head-frozen>
      <th>{{ $t('header.displayName') }}</th>
      <th>{{ $t('header.once') }}</th>
      <th class="access-link">{{ $t('header.accessLink') }}</th>
      <th>{{ $t('header.createdAtAndActions', { createdAt: $t('header.createdAt'), actions: $t('header.actions') }) }}</th>
    </template>
    <template #head-scrolling>
      <th v-for="property of actorProperties" :key="property.name">
        <span v-tooltip.text>{{ property.name }}</span>
      </th>
    </template>
    <template #data-frozen="{ data: publicLink }">
      <public-link-row :public-link="publicLink" :highlighted="highlighted"
        @revoke="$emit('revoke', $event)"/>
    </template>
    <template #data-scrolling="{ data: publicLink }">
      <custom-props-data-row :actor="publicLink" :highlighted="highlighted"
        :properties="actorProperties"/>
    </template>
  </table-freeze>
</template>

<script setup>
import TableFreeze from '../table/freeze.vue';
import PublicLinkRow from './row.vue';
import CustomPropsDataRow from '../custom-props-data-row.vue';

import { useRequestData } from '../../request-data';

defineOptions({
  name: 'PublicLinkTable'
});
defineProps({
  highlighted: Number
});
defineEmits(['revoke']);

// The component does not assume that this data will exist when the component is
// created.
const { publicLinks, actorProperties, resourceStates } = useRequestData();

const { dataExists } = resourceStates([publicLinks, actorProperties]);
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

#public-link-table {
  .table-freeze-scrolling {
    th, td {
      @include text-overflow-ellipsis;
      max-width: 250px;
    }
  }
  &.frozen-only .table-freeze-frozen {
    width: 100%;
  }
  th.access-link, td.access-link {
    max-width: 350px;
  }
  td {
    height: 52px; // Access link cells has scrollbar
    vertical-align: unset;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "header": {
      "once": "Single Submission",
      "accessLink": "Access Link",
      // Header for the table column that shows the created at date and action buttons.
      "createdAtAndActions": "{createdAt} / {actions}"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "header": {
      "once": "Samostatný příspěvek",
      "accessLink": "Odkaz"
    }
  },
  "de": {
    "header": {
      "once": "Einzelübermittlung",
      "accessLink": "Zugangslink"
    }
  },
  "es": {
    "header": {
      "once": "Envío único",
      "accessLink": "Enlace de acceso"
    }
  },
  "fr": {
    "header": {
      "once": "Soumission unique",
      "accessLink": "Lien d'accès"
    }
  },
  "id": {
    "header": {
      "once": "Kiriman Data Tunggal",
      "accessLink": "Tautan Akses"
    }
  },
  "it": {
    "header": {
      "once": "Invio singolo",
      "accessLink": "Link di accesso"
    }
  },
  "ja": {
    "header": {
      "once": "一回限りのデータ提出機能",
      "accessLink": "アクセスリンク"
    }
  },
  "pt": {
    "header": {
      "once": "Resposta única",
      "accessLink": "Link de acesso"
    }
  },
  "sw": {
    "header": {
      "once": "Uwasilishaji Mmoja",
      "accessLink": "Kiungo cha Ufikiaji"
    }
  },
  "zh": {
    "header": {
      "once": "单次提交",
      "accessLink": "访问链接"
    }
  },
  "zh-Hant": {
    "header": {
      "once": "單次提交",
      "accessLink": "訪問連結"
    }
  }
}
</i18n>
