<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div>
    <div v-if="actorProperties.length > 0" id="public-link-filter-bar">
      <custom-props-filter v-model="filter"
        :actor-properties="actorProperties.data"
        :actors="publicLinks.data"/>
    </div>
    <table-freeze id="public-link-table" :data="filteredPublicLinks" key-prop="id"
      :frozen-only="actorProperties.length === 0" :divider="actorProperties.length > 0">
    <template #head-frozen>
      <th class="col-actions"></th>
      <th>{{ $t('header.displayName') }}</th>
      <th>{{ $t('header.once') }}</th>
      <th class="access-link">{{ $t('header.accessLink') }}</th>
      <th>{{ $t('header.createdAt') }}</th>
    </template>
    <template #head-scrolling>
      <th v-for="property of actorProperties" :key="property.name">
        <span v-tooltip.text>{{ property.name }}</span>
      </th>
    </template>
    <template #data-frozen="{ data: publicLink }">
      <public-link-row :public-link="publicLink" :highlighted="highlighted"
        :show-edit="actorProperties.length > 0"
        @revoke="$emit('revoke', $event)"
        @edit="$emit('edit', $event)"/>
    </template>
    <template #data-scrolling="{ data: publicLink }">
      <custom-props-data-row :actor="publicLink" :highlighted="highlighted"
        :properties="actorProperties"/>
    </template>
  </table-freeze>
  <p v-if="filter != null && filteredPublicLinks.length === 0"
    class="empty-table-message">
    {{ $t('noFilterResults') }}
  </p>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue';

import TableFreeze from '../table/freeze.vue';
import CustomPropsFilter from '../custom-props-filter.vue';
import PublicLinkRow from './row.vue';
import CustomPropsDataRow from '../custom-props-data-row.vue';

import { useRequestData } from '../../request-data';

defineOptions({
  name: 'PublicLinkTable'
});
defineProps({
  highlighted: Number
});
defineEmits(['revoke', 'edit']);

const { publicLinks, actorProperties } = useRequestData();

const filter = ref(null);

const resetFilter = () => { filter.value = null; };
defineExpose({ resetFilter });

const filteredPublicLinks = computed(() => {
  if (!publicLinks.dataExists) return [];
  if (filter.value == null) return publicLinks.data;
  return publicLinks.data.filter(
    pl => pl.properties?.[filter.value.property] === filter.value.value
  );
});
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

#public-link-filter-bar {
  margin-left: 10px;
}

#public-link-table {
  .table-freeze-scrolling {
    th, td {
      @include text-overflow-ellipsis;
      max-width: 250px;
    }
  }
  &.frozen-only .table-freeze-frozen {
    width: 100%;
  }
  th.access-link, td.access-link {
    max-width: 350px;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "noFilterResults": "No Public Access Links match the current filter.",
    "header": {
      "once": "Single Submission",
      "accessLink": "Access Link",
      // This text combines existing translated words. And it is shown on a column on the Public Link table that shows created at and action buttons.
      "createdAtAndActions": "{createdAt} / {actions}"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "header": {
      "once": "Samostatný příspěvek",
      "accessLink": "Odkaz"
    }
  },
  "de": {
    "header": {
      "once": "Einzelübermittlung",
      "accessLink": "Zugangslink"
    }
  },
  "es": {
    "header": {
      "once": "Envío único",
      "accessLink": "Enlace de acceso"
    }
  },
  "fr": {
    "header": {
      "once": "Soumission unique",
      "accessLink": "Lien d'accès",
      "createdAtAndActions": "{createdAt} / {actions}"
    }
  },
  "id": {
    "header": {
      "once": "Kiriman Data Tunggal",
      "accessLink": "Tautan Akses"
    }
  },
  "it": {
    "header": {
      "once": "Invio singolo",
      "accessLink": "Link di accesso"
    }
  },
  "ja": {
    "header": {
      "once": "一回限りのデータ提出機能",
      "accessLink": "アクセスリンク"
    }
  },
  "pt": {
    "header": {
      "once": "Resposta única",
      "accessLink": "Link de acesso"
    }
  },
  "sw": {
    "header": {
      "once": "Uwasilishaji Mmoja",
      "accessLink": "Kiungo cha Ufikiaji"
    }
  },
  "zh": {
    "header": {
      "once": "单次提交",
      "accessLink": "访问链接"
    }
  },
  "zh-Hant": {
    "header": {
      "once": "單次提交",
      "accessLink": "訪問連結"
    }
  }
}
</i18n>
