<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="navbar">
    <nav>
        <div class="navbar-left">
          <router-link to="/" class="navbar-brand">ODK Central</router-link>
          <navbar-links v-if="visiblyLoggedIn"/>
        </div>
        <div class="navbar-right">
           <a v-show="showsAnalyticsNotice" id="navbar-analytics-notice"
              href="#" @click.prevent="analyticsIntroduction.show()">
              {{ $t('analyticsNotice') }}
            </a>
            <ul>
              <navbar-help-dropdown/>
              <navbar-locale-dropdown/>
              <navbar-actions/>
            </ul>
        </div>
    </nav>
    <analytics-introduction v-if="config.loaded && config.showsAnalytics"
      v-bind="analyticsIntroduction" @hide="analyticsIntroduction.hide()"/>
  </div>
</template>

<script>
import { defineAsyncComponent } from 'vue';

import NavbarActions from './navbar/actions.vue';
import NavbarHelpDropdown from './navbar/help-dropdown.vue';
import NavbarLinks from './navbar/links.vue';
import NavbarLocaleDropdown from './navbar/locale-dropdown.vue';

import useRoutes from '../composables/routes';
import { loadAsync } from '../util/load-async';
import { modalData } from '../util/reactivity';
import { useRequestData } from '../request-data';

export default {
  name: 'Navbar',
  components: {
    AnalyticsIntroduction: defineAsyncComponent(loadAsync('AnalyticsIntroduction')),
    NavbarActions,
    NavbarHelpDropdown,
    NavbarLinks,
    NavbarLocaleDropdown
  },
  inject: ['config', 'visiblyLoggedIn'],
  setup() {
    // The component does not assume that this data will exist when the
    // component is created.
    const { currentUser, analyticsConfig } = useRequestData();
    const { canRoute } = useRoutes();
    return { currentUser, analyticsConfig, canRoute };
  },
  data() {
    return {
      analyticsIntroduction: modalData('AnalyticsIntroduction')
    };
  },
  computed: {
    showsAnalyticsNotice() {
      return this.config.loaded && this.config.showsAnalytics && this.visiblyLoggedIn &&
        this.canRoute('/system/analytics') && this.analyticsConfig.dataExists &&
        this.analyticsConfig.isEmpty() &&
        Date.now() - Date.parse(this.currentUser.createdAt) >= /* 14 days */ 1209600000;
    }
  }
};
</script>

<style lang="scss">
@import '../assets/scss/mixins';

$border-height: 3px;

#navbar {
  nav {
    background-color: $color-accent-primary;
    border: none;
    border-top: $border-height solid $color-accent-secondary;
    box-shadow: 0 $border-height 0 #dedede;
    margin-bottom: $border-height;
    display: flex;
    justify-content: space-between;
    font-size: 12px;

    .navbar-brand {
      font-size: $font-size-btn;
      font-weight: bold;
      letter-spacing: -0.02em;
      line-height: 20px;
      padding: 5px 15px;

      &, &:hover, &:focus { color: #fff; }

      &:focus {
        background-color: transparent;
        text-decoration: none;
      }
    }

    .navbar-left, .navbar-right {
      display: flex;
      align-items: center;
      margin: 0px;

      > ul {
        display: flex;
        list-style: none;
        margin: 0;
        padding: 0;

        > li > a {
          padding: 7px 10px;
          color: #fff;
          border-top: transparent solid 3px;
          text-decoration: none;
          transition: 0.25s border-top-color;

          &:hover {
            border-top-color: #ffffffb3;
          }

          &:focus {
            border-top-color: #fff;
            box-shadow: 0 3px 0 transparentize(#000, 0.9);
            outline: none;
            transition-duration: 0s;
          }
        }
      }

      li.active a {
        background-color: #b40066;
        border-top-color: #fff;
      }
    }

    .navbar-left > ul {
      margin-left: 30px;
    }
  }
}


#navbar-analytics-notice {
  @include text-link;
  background-color: #ffed88;
  border: 1px solid #e39941;
  font-size: 10px;
  margin-right: 30px;
  padding: 1px 3px;

  &:hover, &:focus {
    background-color: #ffdc1c;
    border-color: #ffed88;
  }
}

#navbar-actions { margin-left: 10px; }
</style>

<i18n lang="json5">
{
  "en": {
    "analyticsNotice": "Help improve Central!"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "action": {
      "toggle": "Přepnout navigaci"
    },
    "analyticsNotice": "Pomozte zlepšit Central!"
  },
  "de": {
    "action": {
      "toggle": "Navigation umschalten"
    },
    "analyticsNotice": "Hilf Central zu verbessern!"
  },
  "es": {
    "action": {
      "toggle": "Alternar la navegación"
    },
    "analyticsNotice": "Ayuda a mejorar Central"
  },
  "fr": {
    "action": {
      "toggle": "Basculer la navigation"
    },
    "analyticsNotice": "Aidez à améliorer Central !"
  },
  "id": {
    "action": {
      "toggle": "Navigasi Toggle"
    },
    "analyticsNotice": "Bantu Memperbaiki Central!"
  },
  "it": {
    "action": {
      "toggle": "Attiva/disattiva navigazione"
    },
    "analyticsNotice": "Aiuta a migliorare Central"
  },
  "ja": {
    "action": {
      "toggle": "ナビゲーションを有効化"
    },
    "analyticsNotice": "Centralの改善を支援！"
  },
  "pt": {
    "action": {
      "toggle": "Ocultar ou exibir a barra de navegação"
    },
    "analyticsNotice": "Ajude a melhorar o Central!"
  },
  "sw": {
    "action": {
      "toggle": "Geuza urambazaji"
    },
    "analyticsNotice": "Saidia kuboresha Central"
  },
  "zh": {
    "action": {
      "toggle": "切换导航"
    },
    "analyticsNotice": "助力完善Central！"
  },
  "zh-Hant": {
    "action": {
      "toggle": "切換導航鈕"
    },
    "analyticsNotice": "幫忙改善 Central!"
  }
}
</i18n>
