<!--
Copyright 2023 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div v-show="state" id="odata-loading-message">
    <spinner :state="state" inline/>
    <span id="odata-loading-message-text">{{ message }}</span>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import Spinner from './spinner.vue';

import { useI18nUtils } from '../util/i18n';

defineOptions({
  name: 'OdataLoadingMessage'
});

const props = defineProps({
  state: Boolean,
  type: {
    type: String,
    required: true
  },
  filter: Boolean,
  totalCount: Number,
  top: Number
});

const { t } = useI18n();
const { tn } = useI18nUtils();

const message = computed(() => {
  if (!props.state) return null;

  if (props.filter)
    return t(`${props.type}.filtered.withoutCount`);

  if (props.totalCount == null || props.totalCount === 0)
    return t(`${props.type}.withoutCount`);

  if (props.top == null || props.totalCount <= props.top)
    return tn(`${props.type}.all`, props.totalCount);

  return t(`${props.type}.withoutCount`);
});
</script>

<style lang="scss">
#odata-loading-message {
  font-size: 12px;
  padding: 20px 0 38px 28px;
}

#odata-loading-message-text {
  color: #555;
  margin-left: 8px;
}
</style>

<i18n lang="json5">
  {
    "en": {
      // @transifexKey component.SubmissionList.loading
      "submission": {
        // This text is shown when the number of Submissions loading is unknown.
        "withoutCount": "Loading Submissions…",
        "all": "Loading {count} Submission… | Loading {count} Submissions…",
        "filtered": {
          // This text is shown when the number of Submissions loading is unknown.
          "withoutCount": "Loading matching Submissions…"
        }
      },
      "entity": {
        // This text is shown when the number of Entities loading is unknown.
        "withoutCount": "Loading Entities…",
        "all": "Loading {count} Entity… | Loading {count} Entities…",
        "filtered": {
          // This text is shown when the number of Entities loading is unknown.
          "withoutCount": "Loading matching Entities…"
        }
      }
    }
  }
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "entity": {
      "withoutCount": "Načítání entit...",
      "filtered": {
        "withoutCount": "Načítání odpovídajících entit..."
      }
    },
    "submission": {
      "withoutCount": "Načítání příspěvků…",
      "all": "Načítání {count} příspěvku ... | Načítání {count} příspěvků ... | Načítání {count} příspěvků ... | Načítání {count} příspěvků ...",
      "filtered": {
        "withoutCount": "Načítání odpovídajících příspěvků…"
      }
    }
  },
  "de": {
    "entity": {
      "withoutCount": "Lade Objekte ...",
      "all": "Lade {count} Objekt ... | Lade {count} Objekte ...",
      "filtered": {
        "withoutCount": "Lade passende Objekte..."
      }
    },
    "submission": {
      "withoutCount": "Übermittlungen laden...",
      "all": "{count} Übermittlung laden... | {count} Übermittlungen laden...",
      "filtered": {
        "withoutCount": "Lade passende Übermittlungen..."
      }
    }
  },
  "es": {
    "entity": {
      "withoutCount": "Cargando las entidades...",
      "all": "Cargando {count} Entidad... | Cargando {count} Entidades... | Cargando {count} Entidades...",
      "filtered": {
        "withoutCount": "Cargando entidades coincidentes..."
      }
    },
    "submission": {
      "withoutCount": "Cargando los envíos...",
      "all": "Cargando {count} envío... | Cargando {count} envíos... | Cargando {count} envíos...",
      "filtered": {
        "withoutCount": "Cargando envíos coincidentes…"
      }
    }
  },
  "fr": {
    "entity": {
      "withoutCount": "Chargement des entités...",
      "all": "Chargement de {count} entité... | Chargement de {count} entités... | Chargement de {count} entités...",
      "filtered": {
        "withoutCount": "Chargement des Entités correspondantes..."
      }
    },
    "submission": {
      "withoutCount": "Chargement des soumissions...",
      "all": "Chargement de {count} soumission... | Chargement de {count} soumissions... | Chargement de {count} soumissions...",
      "filtered": {
        "withoutCount": "Chargement des soumissions correspondantes..."
      }
    }
  },
  "id": {
    "submission": {
      "withoutCount": "Memuat kiriman data...",
      "all": "Memuat {count} kiriman data...",
      "filtered": {
        "withoutCount": "Memuat Pengiriman yang cocok..."
      }
    }
  },
  "it": {
    "entity": {
      "withoutCount": "Caricando le Entità...",
      "all": "Cricando {count} Entità... | Cricando {count} Entità... | Caricando {count} Entità...",
      "filtered": {
        "withoutCount": "Caricando Entità corrispondenti..."
      }
    },
    "submission": {
      "withoutCount": "Caricando invii...",
      "all": "Cricando {count} invio... | Cricando {count} invii... | Caricando {count} invii...",
      "filtered": {
        "withoutCount": "Caricando invii corrispondenti..."
      }
    }
  },
  "ja": {
    "submission": {
      "withoutCount": "提出済フォームの読み込み中...",
      "all": "{count}の提出済フォームを読み込み中...",
      "filtered": {
        "withoutCount": "照合できる提出済フォームの読み込み中..."
      }
    }
  },
  "pt": {
    "entity": {
      "withoutCount": "Carregando Entidades…",
      "all": "Carregando {count} Entidades… | Carregando {count} Entidades… | Carregando {count} Entidades…",
      "filtered": {
        "withoutCount": "Carregando Entidades correspondentes…"
      }
    },
    "submission": {
      "withoutCount": "Carregando respostas...",
      "all": "Carregando {count} resposta... | Carregando {count} respostas... | Carregando {count} respostas...",
      "filtered": {
        "withoutCount": "Carregando respostas encontradas..."
      }
    }
  },
  "sw": {
    "entity": {
      "withoutCount": "Inapakia Huluki...",
      "all": "Inapakia Shirika {count}... | Inapakia Huluki {count}...",
      "filtered": {
        "withoutCount": "Inapakia Huluki zinazolingana..."
      }
    },
    "submission": {
      "withoutCount": "Inapakia Mawasilisho...",
      "all": "Inapakia Mawasilisho {count}... | Inapakia Mawasilisho {count}...",
      "filtered": {
        "withoutCount": "Inapakia Mawasilisho yanayolingana..."
      }
    }
  },
  "zh": {
    "entity": {
      "withoutCount": "正在加载实体…",
      "all": "正在加载{count}个实体…",
      "filtered": {
        "withoutCount": "正在加载匹配的实体…"
      }
    },
    "submission": {
      "withoutCount": "正在加载提交内容...",
      "all": "正在加载{count}个提交内容...",
      "filtered": {
        "withoutCount": "正在加载符合的提交..."
      }
    }
  },
  "zh-Hant": {
    "entity": {
      "withoutCount": "載入實體…",
      "all": "正在載入 {count} 個實體...",
      "filtered": {
        "withoutCount": "正在載入符合的實體..."
      }
    },
    "submission": {
      "withoutCount": "正在加載提交內容...",
      "all": "正在載入 {count} 個提交內容...",
      "filtered": {
        "withoutCount": "正在載入符合的提交內容..."
      }
    }
  }
}
</i18n>
