<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="form-delete" :state="state" :hideable="!awaitingResponse" backdrop
    @hide="$emit('hide')">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="modal-introduction">
        <i18n-t tag="p" keypath="introduction[0]">
          <template #name>
            <strong>{{ form.nameOrId }}</strong>
          </template>
        </i18n-t>
        <p>{{ $t('introduction[1]') }}</p>
        <p v-if="form.dataExists && form.entityRelated">
          {{ $t('noDeleteEntities') }}
        </p>
      </div>
      <div class="modal-actions">
        <button type="button" class="btn btn-danger"
          :disabled="awaitingResponse" @click="del">
          {{ $t('action.yesProceed') }} <spinner :state="awaitingResponse"/>
        </button>
        <button type="button" class="btn btn-link" :disabled="awaitingResponse"
          @click="$emit('hide')">
          {{ $t('action.noCancel') }}
        </button>
      </div>
    </template>
  </modal>
</template>

<script>
import Modal from '../modal.vue';
import Spinner from '../spinner.vue';

import request from '../../mixins/request';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';
import { useRequestData } from '../../request-data';

export default {
  name: 'FormDelete',
  components: { Modal, Spinner },
  mixins: [request()],
  props: {
    state: {
      type: Boolean,
      default: false
    }
  },
  emits: ['hide', 'success'],
  setup() {
    // The component does not assume that this data will exist when the
    // component is created.
    const { form } = useRequestData();
    return { form };
  },
  data() {
    return {
      awaitingResponse: false
    };
  },
  methods: {
    del() {
      this.delete(apiPaths.form(this.form.projectId, this.form.xmlFormId))
        .then(() => {
          // project.forms and project.lastSubmission may now be out-of-date. If
          // the user navigates to ProjectOverview, project.forms should be
          // updated. project.lastSubmission is not used within ProjectShow.
          this.$emit('success');
        })
        .catch(noop);
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up.
    "title": "Delete Form",
    "introduction": [
      "Are you sure you want to delete the Form {name} and all of its Submissions?",
      "This action will move the Form to the Trash. After 30 days in the Trash, it will be permanently purged, but it can be undeleted before then."
    ],
    "noDeleteEntities": "Any Entities created by this Form’s Submissions will not be deleted. In a future version of Central, it will be possible to delete Entities."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Odstranit formulář",
    "introduction": [
      "Opravdu chcete odstranit formulář {name} a všechny jeho odeslání?",
      "Tato akce přesune formulář do koše. Po 30 dnech v koši bude trvale vymazán, ale předtím jej lze zrušit."
    ],
    "noDeleteEntities": "Subjekty vytvořené na základě podání tohoto formuláře nebudou vymazány. V některé z budoucích verzí Centralu bude možné Entity odstranit."
  },
  "de": {
    "title": "Formulare löschen",
    "introduction": [
      "Sind Sie sicher, dass Sie das Formular {name} und alle dazugehörigen Übermittlungen löschen wollen?",
      "Diese Aktion verschiebt das Formular in den Papierkorb. Nach 30 Tagen im Papierkorb wird es dauerhaft gelöscht, kann aber vorher wiederhergestellt werden."
    ]
  },
  "es": {
    "title": "Borrar formulario",
    "introduction": [
      "¿Está seguro que desea eliminar el formulario {name} y todos sus envíos?",
      "Esta acción moverá el Formulario a la Papelera. Después de 30 días en la Papelera, se eliminará de forma permanente, pero se puede recuperar antes de esa fecha."
    ]
  },
  "fr": {
    "title": "Supprimer le formulaire",
    "introduction": [
      "Êtes vous sûr de vouloir supprimer le formulaire {name} et toutes les données soumises ?",
      "Cette action va envoyer le formulaire à la corbeille. Après 30 jours dans la corbeille, il sera purgé de manière permanente, mais il peut être restauré avant ce délai."
    ],
    "noDeleteEntities": "Chaque entité crée par cette Soumission de formulaire ne sera pas supprimée. Dans une version future, il sera possible de supprimer des Entités."
  },
  "id": {
    "title": "Hapus Formulir",
    "introduction": [
      "Apakah Anda yakin ingin menghapus Formulir {name} dan semua kiriman data di dalamnya?"
    ]
  },
  "it": {
    "title": "Cancellare il formulario",
    "introduction": [
      "Sei sicuro di voler eliminare il formulario {name} e tutti i suoi invii?",
      "Questa azione sposterà il formulario nel Cestino. Dopo 30 giorni nel Cestino, verrà eliminato definitivamente, ma prima di allora può essere ripristinato."
    ]
  },
  "ja": {
    "title": "フォームの削除",
    "introduction": [
      "フォーム{name}および、その提出済フォームが削除されます。 本当に削除してもよろしいですか？",
      "この操作はフォームをゴミ箱に移動します。ゴミ箱に入れた30日後、完全に削除されますが、それ以前であれば削除を取り消せます。"
    ]
  },
  "sw": {
    "title": "Futa Fomu",
    "introduction": [
      "Je, una uhakika ungependa kufuta Fomu ya {name} na Mawasilisho yake yote?",
      "kitendo hiki kitahamisha Fomu hadi kwenye Tupio. Baada ya siku 30 kwenye Tupio, itasafishwa kabisa, lakini inaweza kufutwa kabla ya wakati huo."
    ]
  }
}
</i18n>
