<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="form-overview">
    <div class="row">
      <div class="col-xs-6">
        <form-overview-right-now v-if="form.dataExists"
          @view-xml="showModal('viewXml')"/>
      </div>
      <div v-if="formDraft.dataExists" id="form-overview-draft" class="col-xs-6">
        <page-section v-if="formDraft.isDefined()">
          <template #heading>
            <span>{{ $t('common.currentDraft') }}</span>
          </template>
          <template #body>
            <summary-item icon="file-o">
              <template #heading>
                <form-version-string :version="formDraft.get().version"/>
              </template>
              <template #body>
                <i18n-t tag="p" keypath="draft.any.versionCaption.full">
                  <template #draftVersion>
                    <strong>{{ $t('draft.any.versionCaption.draftVersion') }}</strong>
                  </template>
                </i18n-t>
                <div>
                  <form-version-standard-buttons :version="formDraft.get()"
                    @view-xml="showModal('viewXml')"/>
                </div>
              </template>
            </summary-item>
            <form-draft-checklist/>
          </template>
        </page-section>
        <page-section v-else>
          <template #heading>
            <span>{{ $t('draft.none.title') }}</span>
          </template>
          <template #body>
            <p>{{ $t('draft.none.body') }}</p>
          </template>
        </page-section>
      </div>
    </div>
    <form-version-view-xml v-bind="viewXml" @hide="hideModal('viewXml')"/>
  </div>
</template>

<script>
import { defineAsyncComponent } from 'vue';

import FormDraftChecklist from '../form-draft/checklist.vue';
import FormOverviewRightNow from './overview/right-now.vue';
import FormVersionStandardButtons from '../form-version/standard-buttons.vue';
import FormVersionString from '../form-version/string.vue';
import PageSection from '../page/section.vue';
import SummaryItem from '../summary-item.vue';

import modal from '../../mixins/modal';
import { loadAsync } from '../../util/load-async';
import { useRequestData } from '../../request-data';

export default {
  name: 'FormOverview',
  components: {
    FormDraftChecklist,
    FormOverviewRightNow,
    FormVersionStandardButtons,
    FormVersionString,
    FormVersionViewXml: defineAsyncComponent(loadAsync('FormVersionViewXml')),
    PageSection,
    SummaryItem
  },
  mixins: [modal({ viewXml: 'FormVersionViewXml' })],
  props: {
    projectId: {
      type: String,
      required: true
    },
    xmlFormId: {
      type: String,
      required: true
    }
  },
  setup() {
    const { form, formDraft } = useRequestData();
    return { form, formDraft };
  },
  data() {
    return {
      // Modals
      viewXml: {
        state: false
      }
    };
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/variables';

#form-overview-draft {
  background-color: #ddd;
  margin-top: -$margin-top-page-body;
  padding-top: $margin-top-page-body;

  .page-section-heading > span:first-child {
    color: $color-accent-secondary;
  }

  .btn-default {
    background-color: #ccc;

    &:hover, &:focus, &:active:focus {
      background-color: #bbb;
      &[disabled] { background-color: #ccc; }
    }
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "draft": {
      "none": {
        // This is a title shown above a section of the page.
        "title": "No Current Draft",
        "body": "There is not currently a Draft version of this Form. If you want to make changes to the Form or its Attachments, start by creating a Draft using the button above."
      },
      "any": {
        "versionCaption": {
          "full": "{draftVersion} of this Form.",
          "draftVersion": "Draft version"
        }
      }
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "draft": {
      "none": {
        "title": "Žádný aktuální koncept",
        "body": "V současné době neexistuje návrh tohoto formuláře. Pokud chcete provést změny ve formuláři nebo jeho přílohách, začněte vytvořením návrhu pomocí výše uvedeného tlačítka."
      },
      "any": {
        "versionCaption": {
          "full": "{draftVersion} tohoto formuláře.",
          "draftVersion": "Verze konceptu"
        }
      }
    }
  },
  "de": {
    "draft": {
      "none": {
        "title": "Kein aktueller Entwurf"
      },
      "any": {
        "versionCaption": {
          "full": "{draftVersion} von diesem Formular.",
          "draftVersion": "Entwurfsversion"
        }
      }
    }
  },
  "es": {
    "draft": {
      "none": {
        "title": "Sin borrador actual"
      },
      "any": {
        "versionCaption": {
          "full": "{draftVersion} de este formulario.",
          "draftVersion": "Versión borrador"
        }
      }
    }
  },
  "fr": {
    "draft": {
      "none": {
        "title": "Pas d'ébauche en cours"
      },
      "any": {
        "versionCaption": {
          "full": "{draftVersion} de ce formulaire.",
          "draftVersion": "Version d'ébauche"
        }
      }
    }
  },
  "id": {
    "draft": {
      "none": {
        "title": "Belum ada draf"
      },
      "any": {
        "versionCaption": {
          "full": "{draftVersion} dari formulir ini.",
          "draftVersion": "Versi draf"
        }
      }
    }
  },
  "it": {
    "draft": {
      "none": {
        "title": "Nessuna bozza corrente"
      },
      "any": {
        "versionCaption": {
          "full": "{draftVersion} di questo formulario.",
          "draftVersion": "Versione bozza"
        }
      }
    }
  },
  "ja": {
    "draft": {
      "none": {
        "title": "現在、下書きはありません。"
      },
      "any": {
        "versionCaption": {
          "full": "このフォームの{draftVersion}",
          "draftVersion": "下書きバージョン"
        }
      }
    }
  },
  "sw": {
    "draft": {
      "none": {
        "title": "Hakuna Rasimu ya Sasa"
      },
      "any": {
        "versionCaption": {
          "full": "{draftVersion} ya Fomu hii",
          "draftVersion": "Toleo la rasimu"
        }
      }
    }
  }
}
</i18n>
