<!--
Copyright 2021 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="form-restore" :state="state" :hideable="!awaitingResponse" backdrop
    @hide="$emit('hide')">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div v-if="form" class="modal-introduction">
        <i18n-t tag="p" keypath="introduction[0]">
          <template #name>
            <strong>{{ form.nameOrId }}</strong>
          </template>
        </i18n-t>
        <p>{{ $t('introduction[1]') }}</p>
        <p>{{ $t('introduction[2]') }}</p>
      </div>
      <div class="modal-actions">
        <button type="button" class="btn btn-danger"
          :disabled="awaitingResponse" @click="doRestore">
          {{ $t('action.yesProceed') }} <spinner :state="awaitingResponse"/>
        </button>
        <button type="button" class="btn btn-link" :disabled="awaitingResponse"
          @click="$emit('hide')">
          {{ $t('action.noCancel') }}
        </button>
      </div>
    </template>
  </modal>
</template>

<script>
import Modal from '../modal.vue';
import Spinner from '../spinner.vue';
import request from '../../mixins/request';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';

export default {
  name: 'FormRestore',
  components: { Modal, Spinner },
  mixins: [request()],
  props: {
    state: Boolean,
    form: Object
  },
  emits: ['hide', 'success'],
  data() {
    return {
      awaitingResponse: false
    };
  },
  methods: {
    doRestore() {
      this.post(apiPaths.restoreForm(this.form.projectId, this.form.id))
        .then(() => {
          this.$emit('success');
        })
        .catch(noop);
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up.
    "title": "Undelete Form",
    "introduction": [
      "Are you sure you want to undelete the Form {name}?",
      "The Form will be restored to its previous state, including all data, settings, and permissions.",
      "If the Form is deleted again, it will be another 30 days before it is removed."
    ]
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Zrušit smazání formuláře",
    "introduction": [
      "Opravdu chcete formulář {name} smazat ?",
      "Formulář bude obnoven do předchozího stavu včetně všech dat, nastavení a oprávnění.",
      "Pokud je formulář opět smazán, bude trvat dalších 30 dní, než bude odstraněn."
    ]
  },
  "de": {
    "title": "Form löschen rückgängig machen",
    "introduction": [
      "Sind Sie sicher dass Sie das Formular {name} wiederherstellen möchten?",
      "Das Formular wird in seinem vorherigen Zustand wiederhergestellt, einschließlich aller Daten, Einstellungen und Berechtigungen.",
      "Wenn das Formular erneut gelöscht wird, dauert es 30 Tage bis es entfernt wird."
    ]
  },
  "es": {
    "title": "Restaurar el formulario",
    "introduction": [
      "¿Está seguro que desea recuperar el formulario {name}?",
      "El formulario se restaurará a su estado anterior, incluidos todos los datos, configuraciones y permisos.",
      "Si el formulario se elimina nuevamente, pasarán otros 30 días antes de que se elimine."
    ]
  },
  "fr": {
    "title": "Restaurer le formulaire",
    "introduction": [
      "Êtes vous sûr de vouloir restaurer le formulaire {name} ?",
      "Le formulaire sera restauré dans son état précédent, incluant toutes les données, paramètres et permissions.",
      "Si le formulaire est à nouveau supprimé, il faudra attendre à nouveau 30 jours avant qu'il ne soit retiré."
    ]
  },
  "it": {
    "title": "Ripristina il formulario",
    "introduction": [
      "Sei sicuro di voler ripristinare il formulario {name} ?",
      "Il Formulario verrà ripristinato allo stato precedente, inclusi tutti i dati, le impostazioni e le autorizzazioni.",
      "Se il Formulario viene nuovamente eliminato, ci vorranno altri 30 giorni prima che venga rimosso."
    ]
  },
  "ja": {
    "title": "フォームの復元",
    "introduction": [
      "フォーム{name}を本当に復元しますか？",
      "全てのデータ、設定、権限を含んだ以前のフォームの状態に復元されます",
      "フォームを再削除した場合、完全に削除されるまで、さらに30日を要します。"
    ]
  },
  "sw": {
    "title": "Ondoa kufuta fomu",
    "introduction": [
      "Je, una uhakika unataka kutengua Fomu ya {name}?",
      "Fomu itarejeshwa katika hali yake ya awali, ikijumuisha data, mipangilio na ruhusa zote.",
      "Ikiwa Fomu itafutwa tena, itapita siku 30 kabla ya kuondolewa."
    ]
  }
}
</i18n>
