<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div>
    <loading :state="keys.initiallyLoading"/>
    <page-section v-show="keys.dataExists">
      <template #heading>
        <span>{{ $t('resource.submissions') }}</span>
        <enketo-fill v-if="rendersEnketoFill" :form-version="form">
          <span class="icon-plus-circle"></span>{{ $t('action.createSubmission') }}
        </enketo-fill>
        <odata-data-access :analyze-disabled="analyzeDisabled"
          :analyze-disabled-message="analyzeDisabledMessage"
          @analyze="analyzeModal.show()"/>
      </template>
      <template #body>
        <submission-list :project-id="projectId" :xml-form-id="xmlFormId" @fetch-keys="fetchData"/>
      </template>
    </page-section>
    <odata-analyze v-bind="analyzeModal" :odata-url="odataUrl"
      @hide="analyzeModal.hide()"/>
  </div>
</template>

<script>
import EnketoFill from '../enketo/fill.vue';
import Loading from '../loading.vue';
import PageSection from '../page/section.vue';
import OdataAnalyze from '../odata/analyze.vue';
import OdataDataAccess from '../odata/data-access.vue';
import SubmissionList from '../submission/list.vue';

import { apiPaths } from '../../util/request';
import { modalData } from '../../util/reactivity';
import { noop } from '../../util/util';
import { useRequestData } from '../../request-data';

export default {
  name: 'FormSubmissions',
  components: {
    EnketoFill,
    Loading,
    PageSection,
    OdataAnalyze,
    OdataDataAccess,
    SubmissionList
  },
  props: {
    projectId: {
      type: String,
      required: true
    },
    xmlFormId: {
      type: String,
      required: true
    }
  },
  setup() {
    const { project, form, createResource } = useRequestData();
    const keys = createResource('keys');
    return { project, form, keys, analyzeModal: modalData() };
  },
  computed: {
    rendersEnketoFill() {
      return this.project.dataExists &&
        this.project.permits('submission.create') && this.form.dataExists;
    },
    /*
    Disable the "Analyze via OData" button if:

      - There are encrypted submissions, or
      - There are no submissions yet, but the form is encrypted. In that case,
        there will never be decrypted submissions available to OData (as long as
        the form remains encrypted).
    */
    analyzeDisabled() {
      if (this.keys.dataExists && this.keys.length !== 0) return true;
      if (this.form.dataExists && this.form.keyId != null &&
        this.form.submissions === 0)
        return true;
      return false;
    },
    analyzeDisabledMessage() {
      return this.$t('analyzeDisabled');
    },
    odataUrl() {
      if (!this.form.dataExists) return '';
      const path = apiPaths.odataSvc(this.projectId, this.xmlFormId);
      return `${window.location.origin}${path}`;
    }
  },
  created() {
    this.fetchData();
  },
  methods: {
    fetchData() {
      this.keys.request({
        url: apiPaths.submissionKeys(this.projectId, this.xmlFormId)
      }).catch(noop);
    }
  }
};
</script>

<style lang="scss">
#odata-data-access { float: right; }
</style>

<i18n lang="json5">
  {
    "en": {
      "analyzeDisabled": "OData access is unavailable due to Form encryption"
    }
  }
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "analyzeDisabled": "Přístup k OData není dostupný kvůli šifrování formuláře"
  },
  "de": {
    "analyzeDisabled": "OData-Zugriff ist wegen Formularverschlüsselung nicht verfügbar."
  },
  "es": {
    "analyzeDisabled": "El acceso a OData no está disponible debido al cifrado de Formulario"
  },
  "fr": {
    "analyzeDisabled": "L'accès à OData n'est pas disponible en raison du chiffrement du formulaire"
  },
  "it": {
    "analyzeDisabled": "L'accesso OData non è disponibile a causa della crittografia del formulario"
  },
  "sw": {
    "analyzeDisabled": "Ufikiaji wa OData haupatikani kwa sababu ya usimbaji fiche wa Fomu"
  },
  "zh-Hant": {
    "analyzeDisabled": "由於表單加密，OData 存取不可用"
  }
}
</i18n>
