<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <table v-if="project.dataExists && showTable" class="table form-table">
    <thead>
      <template v-if="showClosed">
        <tr>
           <th colspan="7">{{ $t('header.closedForms') }}</th>
        </tr>
      </template>
      <template v-else>
        <tr>
          <th>{{ $t('header.name') }}</th>
          <th class="review-state" colspan="3">{{ $t('header.reviewStates') }}</th>
          <th class="last-submission">{{ $t('header.latest') }}</th>
          <th class="total-submissions">{{ $t('common.total') }}</th>
          <th v-if="showActions" class="actions">{{ $t('header.actions') }}</th>
        </tr>
      </template>
    </thead>
    <tbody v-if="forms.dataExists">
      <form-row v-for="form of formsToShow" :key="form.xmlFormId" :form="form"
        :show-actions="showActions"/>
    </tbody>
  </table>
</template>

<script>
import FormRow from './row.vue';

import { useRequestData } from '../../request-data';

export default {
  name: 'FormTable',
  components: { FormRow },
  props: {
    sortFunc: {
      type: Function,
      required: true
    },
    showClosed: {
      type: Boolean,
      default: false
    }
  },
  setup() {
    const { project, forms } = useRequestData();
    // The component does not assume that this data will exist when the
    // component is created.
    return { project, forms };
  },
  computed: {
    showActions() {
      return this.project.permits('project.update') || this.project.permits('submission.create');
    },
    showTable() {
      // Show the table (incluidng header) if there are forms, or if it is the
      // non-closed form table.
      // In the case that there are no (non-closed) forms, a loading message
      // or "no forms" message will be shown below the header.
      return this.formsToShow.length > 0 || !this.showClosed;
    },
    formsToShow() {
      if (!this.forms.dataExists)
        return [];
      // Hide any form without a published version from a Data Collector.
      const filteredForms = this.showClosed
        ? this.forms.filter(form => form.state === 'closed')
        : this.forms.filter(form => form.state !== 'closed');
      filteredForms.sort(this.sortFunc);
      return this.project.permits('submission.list') && this.project.permits('form.update')
        ? filteredForms
        : filteredForms.filter(form => form.publishedAt != null);
    }
  }
};
</script>


<style lang="scss">
.form-table {
  margin-bottom: 0px;

  .review-state, .last-submission, .total-submissions, .not-published {
    text-align: right;
  }

  th.review-state {
    background-color: #ccc;
    box-shadow: inset 0em -2px #aaa;
  }
}

</style>

<i18n lang="json5">
{
  "en": {
    "header": {
      // This is the text of a column header in a table of Forms.
      "closedForms": "Closed Forms",
      // This is text of a column header in a table of Forms
      "reviewStates": "Review States",
      // This is the text of a column header referring to how recent
      // a Form's latest submission was.
      "latest": "Latest",
      // This is the text of a column header in a table of Forms. The column
      // shows the ID of each Form, as well as the name of its primary version.
      "idAndVersion": "ID and Version"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "header": {
      "closedForms": "Zavřené formuláře",
      "reviewStates": "Přehled stavů",
      "latest": "Poslední",
      "idAndVersion": "ID a Verze"
    }
  },
  "de": {
    "header": {
      "closedForms": "Geschlossene Formulare",
      "reviewStates": "Überprüfungsstaaten",
      "latest": "Letzte",
      "idAndVersion": "ID und Version"
    }
  },
  "es": {
    "header": {
      "closedForms": "Formularios cerrados",
      "reviewStates": "Estados de revisión",
      "latest": "Más reciente",
      "idAndVersion": "ID y versión"
    }
  },
  "fr": {
    "header": {
      "closedForms": "Formulaires fermés",
      "reviewStates": "États de révision",
      "latest": "Plus ancien",
      "idAndVersion": "Identifiant et version"
    }
  },
  "id": {
    "header": {
      "idAndVersion": "ID dan Versi"
    }
  },
  "it": {
    "header": {
      "closedForms": "Formulari chiusi",
      "reviewStates": "Stati Revisione",
      "latest": "Ultimo",
      "idAndVersion": "ID e Versione"
    }
  },
  "ja": {
    "header": {
      "idAndVersion": "フォームIDとバージョン"
    }
  },
  "sw": {
    "header": {
      "idAndVersion": "Kitambulisho na Toleo"
    }
  }
}
</i18n>
