<!--
Copyright 2021 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div v-if="count > 0" id="form-trash-list">
    <div id="form-trash-list-header">
      <span id="form-trash-list-title">
        <span class="icon-trash"></span>
        <span>{{ $t('title') }}</span>
      </span>
      <span id="form-trash-list-count">{{ $t('trashCount', { count: $n(count, 'default') }) }}</span>
      <span id="form-trash-list-note">{{ $t('message') }}</span>
    </div>
    <table id="form-trash-list-table" class="table">
      <tbody>
        <form-trash-row v-for="form of sortedDeletedForms" :key="form.id" :form="form"
          @start-restore="showRestore"/>
      </tbody>
    </table>
    <form-restore :state="restoreForm.state" :form="restoreForm.form" @hide="hideRestore" @success="afterRestore"/>
  </div>
</template>

<script>
import { ascend, sortWith } from 'ramda';

import FormTrashRow from './trash-row.vue';
import FormRestore from './restore.vue';

import modal from '../../mixins/modal';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';
import { useRequestData } from '../../request-data';

export default {
  name: 'FormTrashList',
  components: { FormTrashRow, FormRestore },
  mixins: [modal()],
  inject: ['alert'],
  emits: ['restore'],
  setup() {
    // The component does not assume that this data will exist when the
    // component is created.
    const { project, deletedForms } = useRequestData();
    return { project, deletedForms };
  },
  data() {
    return {
      restoreForm: {
        state: false,
        form: null
      }
    };
  },
  computed: {
    count() {
      return (this.deletedForms.dataExists ? this.deletedForms.length : 0);
    },
    sortedDeletedForms() {
      const sortByDeletedAt = sortWith([ascend(entry => entry.deletedAt)]);
      return sortByDeletedAt(this.deletedForms.data);
    }
  },
  created() {
    this.fetchDeletedForms(false);
  },
  methods: {
    fetchDeletedForms(resend) {
      this.deletedForms.request({
        url: apiPaths.deletedForms(this.project.id),
        extended: true,
        resend
      }).catch(noop);
    },
    showRestore(form) {
      this.restoreForm.form = form;
      this.showModal('restoreForm');
    },
    hideRestore() {
      this.hideModal('restoreForm');
    },
    afterRestore() {
      this.hideRestore();
      this.alert.success(this.$t('alert.restore', { name: this.restoreForm.form.name }));
      this.restoreForm.form = null;

      // refresh trashed forms list
      this.fetchDeletedForms(true);

      // tell parent component (project overview) to refresh regular forms list
      // (by emitting event to that component's parent)
      this.$emit('restore');
    }
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

#form-trash-list-header {
  display: flex;
  align-items: baseline;

  .icon-trash {
    padding-right: 8px;
  }

  .trash-count {
    font-weight: normal;
    color: black;
  }

  #form-trash-list-title {
    font-size: 26px;
    font-weight: 700;
    color: $color-danger;
  }

  #form-trash-list-count {
    font-size: 20px;
    color: #888;
    padding-left: 4px;
  }

  #form-trash-list-note {
    margin-left: auto;
    color: #888
  }
}

</style>

<i18n lang="json5">
{
  "en": {
    "title": "Trash",
    // {count} is the number of Forms in the trash.
    "trashCount": "({count})",
    "alert": {
      "restore": "The Form “{name}” has been undeleted."
    },
    "message": "Forms and Form-related data are deleted after 30 days in the Trash"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Koš",
    "trashCount": "({count})",
    "alert": {
      "restore": "Formuláři \"{name}\" bylo zrušeno smazání."
    },
    "message": "Formuláře a data související s formuláři jsou po 30 dnech odstraněny do koše."
  },
  "de": {
    "title": "Papierkorb",
    "trashCount": "{count}",
    "alert": {
      "restore": "Das Formular {name} wurde wiederhergestellt."
    },
    "message": "Formulare und formularbezogene Daten werden nach 30 Tagen im Papierkorb gelöscht"
  },
  "es": {
    "title": "Papelera",
    "trashCount": "({count})",
    "alert": {
      "restore": "El formulario {name} fue recuperado."
    },
    "message": "Los formularios y los datos relacionados con los formularios se eliminan después de 30 días en la Papelera"
  },
  "fr": {
    "title": "Corbeille",
    "trashCount": "({count})",
    "alert": {
      "restore": "Le formulaire “{name}” a été restauré."
    },
    "message": "Le formulaire et les données associées sont supprimés après 30 jours passés dans la corbeille"
  },
  "it": {
    "title": "Cestino",
    "trashCount": "({count})",
    "alert": {
      "restore": "Il formulario “{name}” è stato ripristinato."
    },
    "message": "I formulari e i dati relativi ai formulari vengono eliminati dopo 30 giorni nel Cestino"
  },
  "ja": {
    "title": "ゴミ箱",
    "trashCount": "({count})",
    "alert": {
      "restore": "フォーム”{name}”は復元されました。"
    },
    "message": "フォームとフォームに関連したデータは30日後に削除されます。"
  },
  "sw": {
    "title": "Takataka",
    "trashCount": "({count})",
    "alert": {
      "restore": "Fomu \"{name}\" imetenguliwa"
    },
    "message": "Fomu na data inayohusiana na Fomu hufutwa baada ya siku 30 kwenye Tupio"
  }
}
</i18n>
