<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal :state="state" :hideable="!form.awaitingResponse" backdrop
  @hide="$emit('hide')">
    <template v-if="webformsEnabled" #banner>
      <img
        srcset="../../assets/images/form/web-forms-settings-confirmation/banner@1x.png, ../../assets/images/form/web-forms-settings-confirmation/banner@2x.png 2x"
        src="../../assets/images/form/web-forms-settings-confirmation/banner@1x.png"
        alt="Modal banner image showing sample Web Form UI.">
    </template>
    <template v-if="webformsEnabled" #title>ODK Web Forms</template>
    <template v-else #title>Enketo</template>

    <template v-if="webformsEnabled" #body>
      <p>
        {{ $t('webformsConfirmation.intro') }}
      </p>
      <i18n-t tag="p" keypath="webformsConfirmation.description.full">
        <template #seeSupportedFeatures>
          <a href="https://github.com/getodk/web-forms?tab=readme-ov-file#feature-matrix"
            target="_blank">
            {{ $t('webformsConfirmation.description.seeSupportedFeatures') }}
          </a>
        </template>
        <template #previewYourForm>
          <router-link :to="previewPath" target="_blank">
            {{ $t('webformsConfirmation.description.previewYourForm') }}
          </router-link>
        </template>
      </i18n-t>
      <div class="modal-actions">
        <button class="btn btn-link" type="button" @click="$emit('hide')">
          {{ $t('action.cancel') }}
        </button>
        <button type="button" class="btn btn-primary"
          :aria-disabled="form.awaitingResponse" @click="setWebformsEnabled">
          {{ $t('webformsConfirmation.useOdkWebForms') }} <spinner :state="form.awaitingResponse"/>
        </button>
      </div>
    </template>
    <template v-else #body>
      <p>
        {{ $t('enketoConfirmation.description') }}
      </p>
      <div class="modal-actions">
        <button class="btn btn-link" type="button" @click="$emit('hide')">
          {{ $t('action.cancel') }}
        </button>
        <button type="button" class="btn btn-primary"
          :aria-disabled="form.awaitingResponse" @click="setWebformsEnabled">
          {{ $t('enketoConfirmation.useEnketo') }} <spinner :state="form.awaitingResponse"/>
        </button>
      </div>
    </template>
  </modal>
</template>

<script setup>
import { computed } from 'vue';
import Modal from '../modal.vue';
import Spinner from '../spinner.vue';
import useRoutes from '../../composables/routes';
import { useRequestData } from '../../request-data';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';

const { form } = useRequestData();
const { formPath } = useRoutes();

defineOptions({
  name: 'FormWebFormsSettingsConfirmation'
});

const props = defineProps({
  state: Boolean,
  webformsEnabled: Boolean
});

const emit = defineEmits(['hide', 'success']);

const previewPath = computed(() => formPath(
  form.projectId,
  form.xmlFormId,
  'preview'
));

const setWebformsEnabled = () => {
  form.request({
    method: 'PATCH',
    url: apiPaths.form(form.projectId, form.xmlFormId),
    data: { webformsEnabled: props.webformsEnabled },
    patch: ({ data }) => {
      form.updatedAt = data.updatedAt;
      form.webformsEnabled = data.webformsEnabled;
    }
  })
    .then(() => {
      emit('success');
    })
    .catch(noop);
};
</script>

<i18n lang="json5">
  {
    "en": {
      "webformsConfirmation": {
        // The words "ODK Web Forms" should not be translated
        "useOdkWebForms": "Use ODK Web Forms",
        "intro": "We’re building a new web-forms experience designed to be fast and user-friendly!",
        "description": {
          "full": "Some functionality might be lost; {seeSupportedFeatures} for details and {previewYourForm} before opting in.",
          "seeSupportedFeatures": "see supported features",
          "previewYourForm": "preview your form"
        }
      },
      "enketoConfirmation": {
        // The words "Enketo" and "ODK Web Forms" should not be translated
        "description": "Are you sure you want to switch from ODK Web Forms to Enketo?",
        // The word "Enketo" should not be translated
        "useEnketo": "Use Enketo"
      }
    }
  }
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "webformsConfirmation": {
      "useOdkWebForms": "ODK Web-Formulare verwenden",
      "intro": "Wir bauen ein neues Web-Formularsystem auf, das schnell und benutzerfreundlich sein soll!"
    },
    "enketoConfirmation": {
      "description": "Sind Sie sicher, dass Sie von ODK Web-Formulare zu Enketo wechseln wollen?",
      "useEnketo": "Enketo verwenden"
    }
  },
  "es": {
    "webformsConfirmation": {
      "useOdkWebForms": "Utilizar Formularios web ODK",
      "intro": "Estamos construyendo una nueva experiencia de formularios web diseñada para ser rápida y fácil de usar.",
      "description": {
        "full": "Es posible que se pierda parte de la funcionalidad; {seeSupportedFeatures} para más detalles y {previewYourForm} antes de optar por él.",
        "seeSupportedFeatures": "ver funciones compatibles",
        "previewYourForm": "previsualice su formulario"
      }
    },
    "enketoConfirmation": {
      "description": "¿Está seguro de que desea cambiar de ODK Web Forms a Enketo?",
      "useEnketo": "Utilice Enketo"
    }
  },
  "fr": {
    "webformsConfirmation": {
      "useOdkWebForms": "Utiliser les Web Forms d'ODK",
      "intro": "Nous construisons une nouvelle experience de formulaires web conçus pour être rapides et faciles à utiliser !",
      "description": {
        "full": "Certaines fonctionnalité peuvent être perdues ; {seeSupportedFeatures} pour détail et {previewYourForm} avant de choisir cette option.",
        "seeSupportedFeatures": "voir les fonctionnalités supportées",
        "previewYourForm": "Prévisualiser votre formulaire"
      }
    },
    "enketoConfirmation": {
      "description": "Êtes vous sûr de vouloir passer d'ODK Web Forms à Enketo ?",
      "useEnketo": "Utiliser Enketo"
    }
  },
  "it": {
    "webformsConfirmation": {
      "useOdkWebForms": "Utilizza ODK Web Forms",
      "intro": "Stiamo costruendo una nuova esperienza di web-forms progettata per essere veloce e facile da usare!",
      "description": {
        "full": "Alcune funzionalità potrebbero andare perse; {seeSupportedFeatures} per dettagli e {previewYourForm} prima di accettare.",
        "seeSupportedFeatures": "vedere le funzioni supportate",
        "previewYourForm": "anteprima del tuo formulario"
      }
    },
    "enketoConfirmation": {
      "description": "Siete sicuri di voler passare da ODK Web Forms a Enketo?",
      "useEnketo": "Usa Enketo"
    }
  }
}
</i18n>
