<template>
  <dl v-if="fields.dataExists && submission.dataExists" class="submission-data">
    <div v-for="field of fields.selectable" :key="field.path">
      <dl-data :value="field.binary !== true ? formatValue(submission.data, field, $i18n) : null">
        <template #name>
          <span v-if="field.path === mappedFieldPath" class="icon-check-circle mapped-field-icon"
            v-tooltip.sr-only></span>
          <span v-tooltip.no-aria="field.header" class="field-name">{{ field.name }}</span>
          <span v-if="field.path === mappedFieldPath" class="sr-only">&nbsp;{{ $t('mappedField') }}</span>
        </template>
        <template v-if="field.binary === true && getValue(submission.data, field) != null"
          #value>
          <submission-attachment-link :project-id="projectId"
            :xml-form-id="xmlFormId" :instance-id="instanceId"
            :attachment-name="getValue(submission.data, field)"/>
        </template>
      </dl-data>
    </div>
  </dl>
</template>

<script setup>
import DlData from '../dl-data.vue';
import SubmissionAttachmentLink from './attachment-link.vue';

import { getValue, formatValue } from '../../util/submission';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'SubmissionData'
});
defineProps({
  projectId: String,
  xmlFormId: String,
  instanceId: String,
  mappedFieldPath: String
});

const { fields, submission } = useRequestData();
</script>

<style lang="scss">
@import '../../assets/scss/variables';

.submission-data {
  .mapped-field-icon {
    margin-right: 2px;
    color: $color-success;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    // @transifexKey component.SubmissionMapPopup.mappedField
    // Message of the tooltip of checkmark icon, which is shown next of the fieldname that is used to plot pins on the map
    "mappedField": "Map references this field"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "mappedField": "Karte verweist auf dieses Feld."
  },
  "es": {
    "mappedField": "El mapa hace referencia a este campo."
  },
  "fr": {
    "mappedField": "Carte utilise ce champ"
  },
  "it": {
    "mappedField": "La mappa fa riferimento a questo campo."
  },
  "zh": {
    "mappedField": "地图引用此字段"
  },
  "zh-Hant": {
    "mappedField": "地圖參照此欄位"
  }
}
</i18n>
