<template>
  <dropdown class="submission-def-dropdown">
    <template #toggle="{ toggle, attrs }">
      <button type="button" class="btn btn-default"
        v-bind="attrs" @click="toggle">
        <span class="icon-code"></span>
        <span>{{ $t('action.def') }}</span>
        <span class="caret"></span>
      </button>
    </template>
    <template #menu>
      <li>
        <a href="#" @click.prevent="$emit('view-xml')">{{ $t('action.viewXml') }}</a>
      </li>
      <li>
        <a :href="xmlPath" :download="`${instanceId}.xml`">
          {{ $t('action.downloadXml') }}
        </a>
      </li>
    </template>
  </dropdown>
</template>

<script setup>
import { computed } from 'vue';

import Dropdown from '../dropdown.vue';

import { apiPaths } from '../../util/request';

defineOptions({ name: 'SubmissionDefDropdown' });

const props = defineProps({
  projectId: {
    type: String,
    required: true
  },
  xmlFormId: {
    type: String,
    required: true
  },
  instanceId: {
    type: String,
    required: true
  }
});

defineEmits(['view-xml']);

const xmlPath = computed(() =>
  apiPaths.submissionXml(props.projectId, props.xmlFormId, props.instanceId));
</script>

<i18n lang="json5">
{
  "en": {
    "action": {
      // @transifexKey component.FormVersionDefDropdown.action.def
      "def": "Definition",
      // @transifexKey component.FormVersionDefDropdown.action.viewXml
      "viewXml": "View XML in browser",
      "downloadXml": "Download XML"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "action": {
      "def": "Definice",
      "viewXml": "Zobrazit XML v prohlížeči"
    }
  },
  "de": {
    "action": {
      "def": "Definition",
      "viewXml": "XML im Browser ansehen"
    }
  },
  "es": {
    "action": {
      "def": "Definición",
      "viewXml": "Ver el XML en el navegador"
    }
  },
  "fr": {
    "action": {
      "downloadXml": "Télécharger XML",
      "def": "Définition",
      "viewXml": "Aperçu XML"
    }
  },
  "id": {
    "action": {
      "def": "Definisi",
      "viewXml": "Lihat XML di browser"
    }
  },
  "it": {
    "action": {
      "def": "Definizione",
      "viewXml": "Vedi l'XML nel browser"
    }
  },
  "ja": {
    "action": {
      "def": "定義フォーム",
      "viewXml": "XMLをブラウザで表示する"
    }
  },
  "pt": {
    "action": {
      "def": "Definição",
      "viewXml": "Exibir XML no browser"
    }
  },
  "sw": {
    "action": {
      "def": "Ufafanuzi",
      "viewXml": "Tazama XML kwenye kivinjari"
    }
  },
  "zh": {
    "action": {
      "def": "定义",
      "viewXml": "在浏览器中查看XML"
    }
  },
  "zh-Hant": {
    "action": {
      "def": "定義",
      "viewXml": "在瀏覽器中查看 XML"
    }
  }
}
</i18n>
