<!--
Copyright 2019 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <table-freeze v-if="project.dataExists && form.dataExists" id="submission-table" ref="table"
    :data="chunkyOData" key-prop="__id" :frozen-only="fields == null" divider
    @action="handleActions">
    <template #head-frozen>
      <th><span class="sr-only">{{ $t('common.rowNumber') }}</span></th>
      <th v-if="!draft">{{ $t('header.submitterName') }}</th>
      <th>{{ $t('header.submissionDate') }}</th>
      <th v-if="!draft && !deleted">{{ $t('header.stateAndActions') }}</th>
      <th v-if="!draft && deleted" class="col-deleted-at">{{ $t('header.deletedAt') }}</th>
    </template>
    <template #head-scrolling>
      <template v-if="fields != null">
        <th v-for="field of fields" :key="field.path">
          <span v-tooltip.text>{{ field.header }}</span>
        </th>
      </template>
      <th>{{ $t('header.instanceId') }}</th>
    </template>

    <template #data-frozen="{ data }">
      <submission-metadata-row :project-id="projectId" :xml-form-id="xmlFormId"
        :draft="draft" :submission="data" :deleted="deleted" :awaiting-response="awaitingDeletedResponses.has(data.__id)"
        :row-number="data.__system.rowNumber" :verbs="project.verbs"/>
    </template>
    <template #data-scrolling="{ data }">
      <submission-data-row :project-id="projectId" :xml-form-id="xmlFormId"
        :draft="draft" :submission="data" :fields="fields" :deleted="deleted"/>
    </template>
  </table-freeze>
</template>

<script setup>
import { computed, ref } from 'vue';

import SubmissionDataRow from './data-row.vue';
import SubmissionMetadataRow from './metadata-row.vue';
import TableFreeze from '../table/freeze.vue';

import useChunkyArray from '../../composables/chunky-array';
import { markRowsChanged, markRowsDeleted } from '../../util/dom';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'SubmissionTable'
});
defineProps({
  projectId: {
    type: String,
    required: true
  },
  xmlFormId: {
    type: String,
    required: true
  },
  deleted: {
    type: Boolean,
    default: false
  },
  draft: Boolean,
  fields: Array,
  awaitingDeletedResponses: {
    type: Set,
    required: true
  }
});
const emit = defineEmits(['review', 'delete', 'restore']);

// The component does not assume that this data will exist when the component is
// created.
const { project, form, odata } = useRequestData();

const chunkyOData = useChunkyArray(computed(() => odata.value));

const handleActions = ({ target, data }) => {
  if (target.classList.contains('review-button')) emit('review', data);
  if (target.classList.contains('delete-button')) emit('delete', data);
  if (target.classList.contains('restore-button')) emit('restore', data);
};
const table = ref(null);
const findIndex = (instanceId) =>
  odata.value.findIndex(submission => submission.__id === instanceId);
const afterReview = (instanceId) => {
  markRowsChanged(table.value.getRowPair(findIndex(instanceId)));
};
const afterDelete = (instanceId) => {
  const index = findIndex(instanceId);
  markRowsDeleted(table.value.getRowPair(index));
  odata.value.splice(index, 1);
};
defineExpose({ afterReview, afterDelete });
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

#submission-table {
  table:has(tbody:empty) { display: none; }

  .table-freeze-scrolling {
    th, td {
      @include text-overflow-ellipsis;
      max-width: 250px;
      &:last-child { max-width: 325px; }
    }
  }

  th.col-deleted-at { color: $color-danger; }
}
</style>

<i18n lang="json5">
{
  "en": {
    "header": {
      "stateAndActions": "State and actions",
      // Heading of the column that shows Submission deletion timestamp
      "deletedAt": "Deleted at"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "header": {
      "stateAndActions": "Stav a akce"
    }
  },
  "de": {
    "header": {
      "stateAndActions": "Status und Aktionen",
      "deletedAt": "Gelöscht am"
    }
  },
  "es": {
    "header": {
      "stateAndActions": "Estado y acciones",
      "deletedAt": "Suprimido el"
    }
  },
  "fr": {
    "header": {
      "stateAndActions": "État et actions",
      "deletedAt": "Supprimé à"
    }
  },
  "id": {
    "header": {
      "stateAndActions": "Status dan tindakan"
    }
  },
  "it": {
    "header": {
      "stateAndActions": "Stato e azioni",
      "deletedAt": "Eliminato il"
    }
  },
  "ja": {
    "header": {
      "stateAndActions": "レビュー・ステータスと操作"
    }
  },
  "pt": {
    "header": {
      "stateAndActions": "Status e ações",
      "deletedAt": "Excluída em"
    }
  },
  "sw": {
    "header": {
      "stateAndActions": "Hali na vitendo"
    }
  },
  "zh": {
    "header": {
      "stateAndActions": "状态与操作",
      "deletedAt": "删除于"
    }
  },
  "zh-Hant": {
    "header": {
      "stateAndActions": "狀態和動作",
      "deletedAt": "刪除於"
    }
  }
}
</i18n>
