<!--
Copyright 2021 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <form id="submission-comment" @submit.prevent="submit">
    <div v-if="editWithoutComment" role="alert">
      <span class="icon-pencil"></span>{{ $t('editWithoutComment') }}
    </div>
    <div class="form-group">
      <textarea v-model.trim="body" class="form-control"
        :placeholder="$t('field.comment')" :aria-label="$t('field.comment')"
        required rows="2">
      </textarea>
    </div>
    <div v-show="body !== '' || awaitingResponse || editWithoutComment"
      id="submission-comment-actions">
      <a href="https://commonmark.org/help/" class="external-help-link" target="_blank" rel="noopener">{{ $t('markdownSupported') }} </a>
      <button type="submit" class="btn btn-primary"
        :disabled="awaitingResponse">
        {{ $t('action.comment') }} <spinner :state="awaitingResponse"/>
      </button>
    </div>
  </form>
</template>

<script>
import Spinner from '../spinner.vue';

import request from '../../mixins/request';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';
import { requestData } from '../../store/modules/request';

export default {
  name: 'SubmissionComment',
  components: { Spinner },
  mixins: [request()],
  props: {
    projectId: {
      type: String,
      required: true
    },
    xmlFormId: {
      type: String,
      required: true
    },
    instanceId: {
      type: String,
      required: true
    },
    feed: Array
  },
  data() {
    return {
      awaitingResponse: false,
      body: ''
    };
  },
  computed: {
    ...requestData(['currentUser']),
    editWithoutComment() {
      if (this.feed == null) return false;
      for (const entry of this.feed) {
        if (entry.actorId === this.currentUser.id) {
          if (entry.body != null) return false;
          if (entry.action === 'submission.update.version') return true;
        }
      }
      return false;
    }
  },
  methods: {
    submit() {
      this.request({
        method: 'POST',
        url: apiPaths.submissionComments(
          this.projectId,
          this.xmlFormId,
          this.instanceId
        ),
        data: { body: this.body }
      })
        .then(() => {
          this.$emit('success');
          this.body = '';
        })
        .catch(noop);
    }
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/variables';
@import '../../assets/scss/mixins';

#submission-comment {
  margin-bottom: 15px;

  [role="alert"] {
    background-color: $color-action-foreground;
    color: #fff;
    font-size: 18px;
    padding: 15px;

    .icon-pencil { margin-right: 10px; }
  }

  .form-group {
    margin-bottom: 0;
    padding-bottom: 5px;
  }

  textarea {
    border-bottom-color: #aaa;
  }

  .btn { float: right; }
}

#submission-comment-actions {
  @include clearfix;
  animation-duration: 0.4s;
  animation-iteration-count: 1;
  animation-name: expand;
  animation-timing-function: $ease-extreme-out;
  margin-top: 5px;
}

@keyframes expand {
  0% { margin-bottom: -12px; }
  100% { margin-bottom: 0; }
}

.external-help-link {
  color: #999;
  font-size: 12px;
  text-decoration: underline;
  text-decoration-style: dotted;
  padding: 10px;
}

</style>

<i18n lang="json5">
{
  "en": {
    "editWithoutComment": "You have made edits to this data. Please describe the changes you made.",
    // This is a link to an external website with Markdown style guidelines
    "markdownSupported": "Markdown supported"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "editWithoutComment": "Provedli jste úpravy těchto údajů. Popište prosím provedené změny.",
    "markdownSupported": "Podporován formát Markdown"
  },
  "de": {
    "editWithoutComment": "Sie haben die Daten geändert. Bitte beschreiben Sie die Änderungen, die Sie gemacht haben.",
    "markdownSupported": "unterstützt durch Markdown"
  },
  "es": {
    "editWithoutComment": "Ha realizado modificaciones en estos datos. Describe los cambios que hiciste.",
    "markdownSupported": "soporte Markdown"
  },
  "fr": {
    "editWithoutComment": "Vous avez édité cette soumission. Veuillez décrire vos changements.",
    "markdownSupported": "Markdown disponible"
  },
  "it": {
    "editWithoutComment": "Hai apportato modifiche a questi dati. Per favore descrivi le modifiche apportate.",
    "markdownSupported": "Markdown supportato"
  },
  "ja": {
    "editWithoutComment": "データが編集されました。あなたが実施した変更について説明して下さい。",
    "markdownSupported": "Markdown形式をサポートしています。"
  }
}
</i18n>
