<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <span id="submission-data-access">
    <a class="btn btn-default"
      href="https://odkcentral.docs.apiary.io/#reference/odata-endpoints"
      target="_blank" rel="noopener">
      <span class="icon-plug"></span>{{ $t('action.apiAccess') }}
    </a>
    <button id="submission-data-access-analyze-button" type="button"
      class="btn btn-default" :disabled="analyzeDisabled"
      :title="analyzeDisabled ? $t('analyzeDisabled') : null"
      @click="$emit('analyze')">
      <span class="icon-bar-chart"></span>{{ $t('action.analyze') }}&hellip;
    </button>
  </span>
</template>

<script>
import Form from '../../presenters/form';
import { requestData } from '../../store/modules/request';

export default {
  name: 'SubmissionDataAccess',
  props: {
    formVersion: Form // eslint-disable-line vue/require-default-prop
  },
  computed: {
    // The component does not assume that this data will exist when the
    // component is created.
    ...requestData(['keys']),
    analyzeDisabled() {
      // If an encrypted form has no submissions, then there will never be
      // decrypted submissions available to OData (as long as the form remains
      // encrypted).
      if (this.formVersion != null && this.formVersion.keyId != null &&
        this.formVersion.submissions === 0)
        return true;
      if (this.keys != null && this.keys.length !== 0) return true;
      return false;
    }
  }
};
</script>

<style lang="scss">
#submission-data-access-analyze-button { margin-left: 5px; }
</style>

<i18n lang="json5">
{
  "en": {
    "action": {
      "apiAccess": "API access",
      "analyze": "Analyze via OData"
    },
    "analyzeDisabled": "OData access is unavailable due to Form encryption"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{}
</i18n>
