<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <span id="submission-data-access">
    <a class="btn btn-default"
      href="https://odkcentral.docs.apiary.io/#reference/odata-endpoints"
      target="_blank" rel="noopener">
      <span class="icon-plug"></span>{{ $t('action.apiAccess') }}
    </a>
    <button id="submission-data-access-analyze-button" type="button"
      class="btn btn-default" :disabled="analyzeDisabled"
      :title="analyzeDisabled ? $t('analyzeDisabled') : null"
      @click="$emit('analyze')">
      <span class="icon-bar-chart"></span>{{ $t('action.analyze') }}&hellip;
    </button>
  </span>
</template>

<script>
import { useRequestData } from '../../request-data';

export default {
  name: 'SubmissionDataAccess',
  props: {
    formVersion: Object
  },
  emits: ['analyze'],
  setup() {
    // The component does not assume that this data will exist when the
    // component is created.
    const { keys } = useRequestData();
    return { keys };
  },
  computed: {
    analyzeDisabled() {
      // If an encrypted form has no submissions, then there will never be
      // decrypted submissions available to OData (as long as the form remains
      // encrypted).
      if (this.formVersion.dataExists && this.formVersion.keyId != null &&
        this.formVersion.submissions === 0)
        return true;
      if (this.keys != null && this.keys.length !== 0) return true;
      return false;
    }
  }
};
</script>

<style lang="scss">
#submission-data-access-analyze-button { margin-left: 5px; }
</style>

<i18n lang="json5">
{
  "en": {
    "action": {
      "apiAccess": "API access",
      "analyze": "Analyze via OData"
    },
    "analyzeDisabled": "OData access is unavailable due to Form encryption"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "action": {
      "apiAccess": "API přístup",
      "analyze": "Analyzujte pomocí OData"
    },
    "analyzeDisabled": "Přístup OData není k dispozici kvůli šifrování formuláře"
  },
  "de": {
    "action": {
      "apiAccess": "API-Zugriff",
      "analyze": "Mittels OData analysieren"
    },
    "analyzeDisabled": "OData-Zugriff ist wegen Formularverschlüsselung nicht verfügbar."
  },
  "es": {
    "action": {
      "apiAccess": "Acceso API",
      "analyze": "Analizar a través de OData"
    },
    "analyzeDisabled": "El acceso a OData no está disponible debido al cifrado de Formulario"
  },
  "fr": {
    "action": {
      "apiAccess": "Accès via l'API",
      "analyze": "Analyser via OData"
    },
    "analyzeDisabled": "L'accès via OData n'est ps disponible du fait du chiffrement du formulaire"
  },
  "id": {
    "action": {
      "apiAccess": "Akses API",
      "analyze": "Analisa lewat OData"
    },
    "analyzeDisabled": "Akses OData tidak tersedia karena enkripsi Formulir"
  },
  "it": {
    "action": {
      "apiAccess": "accesso attraverso API",
      "analyze": "Analizzare attraverso OData"
    },
    "analyzeDisabled": "L'accesso OData non è disponibile a causa della crittografia del formulario"
  },
  "ja": {
    "action": {
      "apiAccess": "APIアクセス",
      "analyze": "OData経由で解析"
    },
    "analyzeDisabled": "フォームの暗号化のため、ODataによるアクセスは利用できません"
  },
  "sw": {
    "action": {
      "apiAccess": "Ufikiaji wa API",
      "analyze": "Changanua kupitia OData"
    },
    "analyzeDisabled": "Ufikiaji wa OData haupatikani kwa sababu ya usimbaji fiche wa Fomu"
  }
}
</i18n>
