<!--
Copyright 2024 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="submission-delete" :state="state" :hideable="!awaitingResponse"
    backdrop @hide="$emit('hide')" @shown="focusCheckbox">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="modal-introduction">
        <p>{{ $t('introduction[0]') }}</p>
        <p>{{ $t('introduction[1]') }}</p>
      </div>
      <form v-if="checkbox">
        <div class="checkbox">
          <label>
            <input ref="input" v-model="noConfirm" type="checkbox">
            {{ $t('field.noConfirm') }}
          </label>
        </div>
      </form>
      <div class="modal-actions">
        <button type="button" class="btn btn-link"
          :aria-disabled="awaitingResponse" @click="$emit('hide')">
          {{ $t('action.cancel') }}
        </button>
        <button type="button" class="btn btn-danger"
          :aria-disabled="awaitingResponse" @click="del">
          {{ $t('action.delete') }} <spinner :state="awaitingResponse"/>
        </button>
      </div>
    </template>
  </modal>
</template>

<script setup>
import { ref, watch } from 'vue';

import Modal from '../modal.vue';
import Spinner from '../spinner.vue';

defineOptions({
  name: 'SubmissionDelete'
});
const props = defineProps({
  state: Boolean,
  checkbox: Boolean,
  awaitingResponse: Boolean,
  submission: Object
});
const emit = defineEmits(['hide', 'delete']);

const noConfirm = ref(false);
watch(() => props.state, (state) => { if (!state) noConfirm.value = false; });

const input = ref(null);
const focusCheckbox = () => { if (props.checkbox) input.value.focus(); };

const del = () => {
  if (props.checkbox)
    emit('delete', [props.submission, !noConfirm.value]);
  else
    emit('delete', [props.submission]);
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of Submission delete pop-up.
    "title": "Delete Submission",
    "introduction": [
      "Are you sure you want to delete this Submission?",
      "This action will move the Submission to the Trash. After 30 days in the Trash, it will be permanently purged, but it can be restored before then."
    ],
    "field": {
      // @transifexKey component.EntityDelete.field.noConfirm
      "noConfirm": "Delete immediately without confirmation until I leave the page"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "title": "Übermittlung löschen",
    "introduction": [
      "Sind Sie sicher, dass Sie diese Übermittlung löschen möchten?",
      "Diese Aktion verschiebt die Übermittlung in den Papierkorb. Nach 30 Tagen im Papierkorb wird es dauerhaft gelöscht, kann aber vorher wiederhergestellt werden."
    ],
    "field": {
      "noConfirm": "Sofortiges Löschen ohne Bestätigung, bis ich die Seite verlasse"
    }
  },
  "es": {
    "title": "Borrar envío",
    "introduction": [
      "¿Está seguro de que desea eliminar este envío?",
      "Esta acción moverá el Envío a la Papelera. Después de 30 días en la Papelera, se purgará permanentemente, pero puede deshacerse su eliminación antes de ese plazo."
    ],
    "field": {
      "noConfirm": "Borrar inmediatamente sin confirmación hasta que salga de la página"
    }
  },
  "fr": {
    "title": "Supprimer la Soumission",
    "introduction": [
      "Etes vous sûr de vouloir supprimer cette Soumission ?",
      "Cette action va déplacer les Soumissions dans la Corbeille. Après 30 jours dans la Corbeille, elles seront purgées de manière permanente, mais elles peuvent être restaurées avant ce délai."
    ],
    "field": {
      "noConfirm": "Supprimer immédiatement sans confirmation jusqu'à ce que je quitte la page"
    }
  },
  "it": {
    "title": "Elimina invio",
    "introduction": [
      "Sei sicuro di voler cancellare questo invio?",
      "Questa azione sposterà il formulario nel Cestino. Dopo 30 giorni nel Cestino, verrà eliminato definitivamente, ma prima di allora può essere ripristinato."
    ],
    "field": {
      "noConfirm": "Elimina immediatamente senza conferma finché non lascio la pagina"
    }
  },
  "pt": {
    "title": "Deletar Resposta",
    "introduction": [
      "Você tem certeza que quer deletar esta Resposta?",
      "Essa ação irá mover a Resposta para a Lixeira. Após 30 dias na Lixeira, ela será excluída de forma permanente, ela poderá ser recuperada antes disso."
    ],
    "field": {
      "noConfirm": "Excluir imediatamente sem confirmação até que eu saia da página"
    }
  },
  "zh": {
    "title": "删除提交内容",
    "introduction": [
      "您确定要删除此条提交吗？",
      "此操作将把提交数据移至回收站。数据在回收站保留30天后将被永久清除，但在此之前可随时恢复。"
    ],
    "field": {
      "noConfirm": "在离开本页面前，无需确认，立即删除。"
    }
  },
  "zh-Hant": {
    "title": "刪除提交內容",
    "introduction": [
      "您確定要刪除此提交嗎？",
      "此操作會將提交內容移至垃圾箱。在垃圾箱中保留 30 天后，它將被永久清除，但在此之前可以還原。"
    ],
    "field": {
      "noConfirm": "立即刪除，無需確認，直到我離開頁面"
    }
  }
}
</i18n>
