<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <button id="submission-download-button" type="button" class="btn btn-primary"
    @click="$emit('download')">
    <span class="icon-arrow-circle-down"></span>
    <span>{{ text }}&hellip;</span>
  </button>
</template>

<script>
import { requestData } from '../../store/modules/request';

export default {
  // Ideally, this component would be named SubmissionDownloadButton, but that
  // would cause messages to be moved in Transifex.
  name: 'SubmissionDownloadDropdown',
  props: {
    formVersion: Object,
    filtered: Boolean
  },
  computed: {
    ...requestData(['odataChunk']),
    text() {
      if (!this.filtered) {
        if (this.formVersion == null) return '';
        return this.$tcn(
          'action.download.unfiltered',
          this.formVersion.submissions
        );
      }

      if (this.odataChunk == null)
        return this.$t('action.download.filtered.withoutCount');
      return this.$tcn(
        'action.download.filtered.withCount',
        this.odataChunk['@odata.count']
      );
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    "action": {
      "download": {
        "unfiltered": "Download {count} record | Download {count} records",
        "filtered": {
          // This is the text of a button. This text is shown when the number of
          // matching records is unknown.
          "withoutCount": "Download matching records",
          "withCount": "Download {count} matching record | Download {count} matching records"
        }
      }
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "action": {
      "download": {
        "unfiltered": "Stáhnout {count} záznam | Stáhout {count} záznamy | Stáhnout {count} záznamů | Stáhnout {count} záznamů",
        "filtered": {
          "withoutCount": "Stáhnout odpovídající záznamy",
          "withCount": "Stáhnout {count} odpovídající záznam | Stáhnout {count} odpovídající záznamy | Stáhnout {count} odpovídajících záznamů | Stáhnout {count} odpovídající záznamy"
        },
        "withMedia": "Všechna data a mediální soubory (.zip)",
        "withoutMedia": "Všechna data bez mediálních souborů (.zip)",
        "primaryDataTable": "Data bez opakování (.csv)"
      }
    }
  },
  "de": {
    "action": {
      "download": {
        "unfiltered": "{count} Datensatz herunterladen | {count} Datensätze herunterladen",
        "filtered": {
          "withoutCount": "Passende Datensätze herunterladen",
          "withCount": "{count} passenden Datensatz herunterladen | {count} passende Datensätze herunterladen"
        },
        "withMedia": "Alle Daten und Mediendateien (.zip)",
        "withoutMedia": "Alle Daten ohne Mediendateien (.zip)",
        "primaryDataTable": "Daten ohne Wiederholungen (.csv)"
      }
    }
  },
  "es": {
    "action": {
      "download": {
        "unfiltered": "Descargar {count} registros | Descargar {count} registros",
        "filtered": {
          "withoutCount": "Descargar registros coincidentes",
          "withCount": "Descargar {count} registros coincidentes. | Descargar {count} registros coincidentes"
        },
        "withMedia": "Todos los datos y archivos multimedia (.zip)",
        "withoutMedia": "Todos los datos sin archivos multimedia (.zip)",
        "primaryDataTable": "Datos sin grupos de repetición (.csv)"
      }
    }
  },
  "fr": {
    "action": {
      "download": {
        "unfiltered": "Télécharger {count} soumission | Télécharger {count} soumissions",
        "filtered": {
          "withoutCount": "Télécharger les enregistrements correspondants",
          "withCount": "Télécharger {count} enregistrement(s) correspondant(s) | Télécharger {count} enregistrement(s) correspondant(s)"
        },
        "withMedia": "Toutes les données et fichiers médias (.zip)",
        "withoutMedia": "Toutes les données sans fichiers médias",
        "primaryDataTable": "Données sans \"repeats\" (.csv)"
      }
    }
  },
  "id": {
    "action": {
      "download": {
        "unfiltered": "Unduh {count} pencatatan",
        "filtered": {
          "withoutCount": "Unduh pencatatan yang cocok",
          "withCount": "Unduh {count} pencatatan yang cocok"
        },
        "withMedia": "Semua data dan berkas media (.zip)",
        "withoutMedia": "Semua data tanpa berkas media (.zip)",
        "primaryDataTable": "Data tanpa perulangan (.csv)"
      }
    }
  },
  "it": {
    "action": {
      "download": {
        "unfiltered": "Scarica {count} record | Scarica {count} records",
        "filtered": {
          "withoutCount": "Scarica records corrispondenti",
          "withCount": "Scarica {count} record corrispondente | Scarica {count} records corrispondenti"
        },
        "withMedia": "Tutti i dati e file multimediali (.zip)",
        "withoutMedia": "Tutti i dati senza file multimediali (.zip)",
        "primaryDataTable": "Data senza repeats (.csv)"
      }
    }
  },
  "ja": {
    "action": {
      "download": {
        "unfiltered": "{count}件のレコードのダウンロード",
        "filtered": {
          "withoutCount": "照合されたレコードのダウンロード",
          "withCount": "{count}件の該当レコードのダウンロード"
        },
        "withMedia": "全データとメディアファイルの保存（.zip形式）",
        "withoutMedia": "メディアファイルを除く、全データの保存（.zip形式）",
        "primaryDataTable": "繰返し質問の回答を含まないデータ（.csv形式）"
      }
    }
  }
}
</i18n>
