<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="submission-download-button" class="dropdown">
    <button type="button" class="btn btn-primary"
      :data-toggle="filtered ? 'dropdown' : null"
      v-bind="$attrs"
      @click="download">
      <span class="icon-arrow-circle-down"></span>
      <span>{{ $t('action.download') }}</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-right">
      <li>
        <button type="button" class="btn btn-link dropdown-item"
          @click="$emit('downloadFiltered')">
          <span>{{ downloadFiltered }}</span>
        </button>
      </li>
      <li v-if="formVersion.dataExists">
        <button type="button" class="btn btn-link dropdown-item"
          @click="$emit('download')">
          <span>{{ $tcn('action.download.unfiltered', formVersion.submissions) }}</span>
        </button>
      </li>
    </ul>
</div>
</template>

<script>
import { useRequestData } from '../../request-data';

export default {
  name: 'SubmissionDownloadButton',
  props: {
    formVersion: Object,
    filtered: Boolean
  },
  emits: ['download', 'downloadFiltered'],
  setup() {
    const { odata } = useRequestData();
    return { odata };
  },
  computed: {
    downloadFiltered() {
      return !this.odata.dataExists
        ? this.$t('action.download.filtered.withoutCount')
        : this.$tcn('action.download.filtered.withCount', this.odata.count);
    }
  },
  methods: {
    download() {
      if (!this.filtered) {
        this.$emit('download');
      }
    }
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/variables';

#submission-download-button{
  .btn-primary {
    display: block;
  }

  .dropdown-item {
    width: 100%;
    text-align: left;
    color: $color-text;

    &:hover {
      color: #262626;
      text-decoration: none;
      background-color: #f5f5f5;
    }
  }
}
</style>

<i18n lang="json5">
{
  // @transifexKey component.SubmissionDownloadDropdown
  "en": {
    "action": {
      "download": {
        "unfiltered": "Download {count} Submission | Download all {count} Submissions",
        "filtered": {
          // This is the text of a button. This text is shown when the number of
          // matching Submissions is unknown.
          "withoutCount": "Download all Submissions matching the filter",
          "withCount": "Download {count} Submission matching the filter | Download {count} Submissions matching the filter"
        }
      }
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "action": {
      "download": {
        "filtered": {
          "withoutCount": "Stáhnout odpovídající příspěvky"
        }
      }
    }
  },
  "de": {
    "action": {
      "download": {
        "unfiltered": "{count} Übermittlung herunterladen | {count} Übermittlungen herunterladen",
        "filtered": {
          "withoutCount": "Passende Übermittlungen herunterladen",
          "withCount": "{count} passende Übermittlung herunterladen | {count} passende Übermittlungen herunterladen"
        }
      }
    }
  },
  "es": {
    "action": {
      "download": {
        "unfiltered": "Descargar {count} envío | Descargar {count} envíos | Descargar {count} envíos",
        "filtered": {
          "withoutCount": "Descargar envíos coincidentes.",
          "withCount": "Descargar {count} envío coincidente | Descargar {count} envíos coincidentes | Descargar {count} envíos coincidentes"
        }
      }
    }
  },
  "fr": {
    "action": {
      "download": {
        "unfiltered": "Télécharger {count} soumission | Télécharger {count} soumissions | Télécharger {count} soumission(s)",
        "filtered": {
          "withoutCount": "Télécharger les soumissions correspondantes",
          "withCount": "Télécharger {count} soumission correspondant | Télécharger {count} soumissions correspondantes | Télécharger {count} souission(s) correspondant(s)"
        }
      }
    }
  },
  "id": {
    "action": {
      "download": {
        "unfiltered": "Unduh {count} Kiriman",
        "filtered": {
          "withoutCount": "Unduh Kiriman yang cocok",
          "withCount": "Unduh {count} Kiriman yang cocok"
        }
      }
    }
  },
  "it": {
    "action": {
      "download": {
        "unfiltered": "Scarica {count} Invio | Scarica {count} Invii | Scarica {count} Invii",
        "filtered": {
          "withoutCount": "Scarica invii corrispondenti.",
          "withCount": "Scarica {count} invio corrispondente. | Scarica {count} invii corrispondenti. | Scarica {count} invii corrispondenti."
        }
      }
    }
  },
  "pt": {
    "action": {
      "download": {
        "unfiltered": "Baixar {count} Resposta | Baixar {count} Respostas | Baixar {count} Respostas",
        "filtered": {
          "withoutCount": "Baixar Respostas correspondentes",
          "withCount": "Baixar {count} Resposta correspondente | Baixar {count} Respostas correspondentes | Baixar {count} Respostas correspondentes"
        }
      }
    }
  },
  "sw": {
    "action": {
      "download": {
        "unfiltered": "Pakua wasilisho {count} | Pakua Mawasilisho {count}",
        "filtered": {
          "withoutCount": "Pakua Mawasilisho yanayolingana",
          "withCount": "Pakua wasilisho {count} inayolingana | Pakua Mawasilisho {count} yanayolingana"
        }
      }
    }
  },
  "zh-Hant": {
    "action": {
      "download": {
        "unfiltered": "下載{count} 個提交資料",
        "filtered": {
          "withoutCount": "下載符合的提交資料",
          "withCount": "下載{count}個相符提交"
        }
      }
    }
  }
}
</i18n>
