<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <multiselect id="submission-field-dropdown" :model-value="modelValue"
    :options="options" :label="$t('field.columns')" :placeholder="placeholder"
    :all="$t('action.select.all')" :none="$t('action.select.none')"
    :search="$t('field.search')"
    @update:model-value="$emit('update:modelValue', $event)">
    <template #after-list="{ selected }">
      <template v-if="selected.size > 100">
        <span class="icon-exclamation-triangle"></span>{{ $t('warning') }}
      </template>
    </template>
  </multiselect>
</template>

<script>
export default {
  name: 'SubmissionFieldDropdown'
};
</script>
<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import Multiselect from '../multiselect.vue';
import { useRequestData } from '../../request-data';

defineProps({
  modelValue: {
    type: Array,
    required: true
  }
});
defineEmits(['update:modelValue']);

// The component assumes that this data will exist when the component is
// created.
const { fields } = useRequestData();
const options = computed(() => fields.selectable.map(field => ({
  value: field,
  key: field.path,
  text: field.name,
  title: field.header
})));
const { t } = useI18n();
const placeholder = (counts) => t('placeholder', counts);
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

#submission-field-dropdown {
  select {
    background-color: #777;
    color: #fff;
  }

  .dropdown-menu { width: 275px; }
  .after-list {
    background-color: $color-warning-light;
    font-size: 14px;

    .icon-exclamation-triangle { margin-right: $margin-right-icon; }
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    // This is the text of a dropdown that allows the user to select which
    // columns to display in a table. {selected} is the number of columns
    // selected; {total} is the total number of columns.
    "placeholder": "{selected} of {total}",
    "field": {
      // This is shown beneath text that indicates the number of columns that
      // the user has selected to display in a table. For example, that text may
      // read "10 of 100", where 10 is the number of columns selected, and 100
      // is the total number of columns.
      "columns": "Columns shown",
      "search": "Search columns…"
    },
    "action": {
      "select": {
        /* This text is shown in a dropdown that allows the user to select which
        columns to display in a table. It will be inserted where {all} is in the
        following text:

        Select {all} / {none} */
        "all": "All",
        /* This text is shown in a dropdown that allows the user to select which
        columns to display in a table. It will be inserted where {none} is in
        the following text:

        Select {all} / {none} */
        "none": "None"
      }
    },
    "warning": "Selecting too many columns might slow down your computer."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "placeholder": "{selected} z {total}",
    "field": {
      "columns": "Zobrazené sloupce",
      "search": "Hledat sloupce…"
    },
    "disabled": "Nelze vybrat více než 100 sloupců.",
    "action": {
      "select": {
        "full": "Vybrat {all} / {none}",
        "all": "Vše",
        "none": "Nic"
      }
    }
  },
  "de": {
    "placeholder": "{selected} von {total}",
    "field": {
      "columns": "angezeigte Spalten",
      "search": "Spalten suchen..."
    },
    "disabled": "Mehr als 100 Spalten können nicht ausgewählt werden.",
    "action": {
      "select": {
        "full": "{all} / {none} auswählen",
        "all": "Alle",
        "none": "Keine"
      }
    }
  },
  "es": {
    "placeholder": "{selected} de {total}",
    "field": {
      "columns": "Se muestran las columnas",
      "search": "Buscar columnas…"
    },
    "disabled": "No se pueden seleccionar más de 100 columnas.",
    "action": {
      "select": {
        "full": "Seleccionar {all} / {none}",
        "all": "Todas",
        "none": "Ninguna"
      }
    }
  },
  "fr": {
    "placeholder": "{selected} sur {total}",
    "field": {
      "columns": "Colonnes affichées",
      "search": "Chercher des colonnes"
    },
    "disabled": "Impossible de sélectionner plus de 100 colonnes.",
    "action": {
      "select": {
        "full": "Sélectionner {all} / {none}",
        "all": "Tous/toutes",
        "none": "Aucun(e)"
      }
    }
  },
  "id": {
    "placeholder": "{selected} dari {total}",
    "field": {
      "columns": "Kolom terlihat",
      "search": "Mencari kolom..."
    },
    "disabled": "Tidak bisa memilih lebih dari 100 kolom.",
    "action": {
      "select": {
        "full": "Pilih {all} / {none}",
        "all": "Semua",
        "none": "Jangan Semua"
      }
    }
  },
  "it": {
    "placeholder": "{selected} di {total}",
    "field": {
      "columns": "Colonne mostrate",
      "search": "Cerca colonne..."
    },
    "disabled": "Non puoi selezionare piu' di 100 colonne.",
    "action": {
      "select": {
        "full": "Seleziona {all} / {none}",
        "all": "Tutto",
        "none": "Nessuno/a"
      }
    }
  },
  "ja": {
    "placeholder": "{total}列の内{selected}列",
    "field": {
      "columns": "表示された列",
      "search": "列を検索"
    },
    "disabled": "100以上の列は選択できません。",
    "action": {
      "select": {
        "full": "選択設定 {all}/{none}",
        "all": "全て",
        "none": "なし"
      }
    }
  },
  "sw": {
    "placeholder": "{selected} kati ya {total}",
    "field": {
      "columns": "Safu wima zimeonyeshwa",
      "search": "Tafuta safu wima..."
    },
    "disabled": "Haiwezi kuchagua zaidi ya safu wima 100.",
    "action": {
      "select": {
        "full": "Chagua {all} / {none}",
        "all": "zote",
        "none": "hakuna"
      }
    }
  }
}
</i18n>
