 <!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <span id="submission-filters">
    <submission-filters-submitter :model-value="submitterId"
      :disabled="disabled" :disabled-message="disabledMessage"
      @update:model-value="$emit('update:submitterId', $event)"/>
    <date-range-picker :model-value="submissionDate"
      :label="$t('field.submissionDate')"
      :disabled="disabled" :disabled-message="disabledMessage"
      :placeholder="$t('allSubmissionDateSelected')"
      @update:model-value="$emit('update:submissionDate', $event)"/>
    <submission-filters-review-state :model-value="reviewState"
      :disabled="disabled" :disabled-message="disabledMessage"
      @update:model-value="$emit('update:reviewState', $event)"/>
    <button type="button" class="btn btn-link btn-reset"
      :aria-disabled="disabled" v-tooltip.aria-describedby="disabledMessage"
      @click="$emit('resetClick')">
      {{ $t('action.reset') }}
    </button>
  </span>
</template>

<script>
import DateRangePicker from '../date-range-picker.vue';
import SubmissionFiltersReviewState from './filters/review-state.vue';
import SubmissionFiltersSubmitter from './filters/submitter.vue';

export default {
  name: 'SubmissionFilters',
  components: {
    DateRangePicker,
    SubmissionFiltersReviewState,
    SubmissionFiltersSubmitter
  },
  props: {
    submitterId: {
      type: Array,
      required: true
    },
    submissionDate: {
      type: Array,
      required: true
    },
    reviewState: {
      type: Array,
      required: true
    },
    disabled: {
      type: Boolean,
      required: true
    },
    disabledMessage: {
      type: String,
      required: false
    }
  },
  emits: ['update:submitterId', 'update:submissionDate', 'update:reviewState', 'resetClick']
};
</script>

<i18n lang="json5">
{
  "en": {
    "field": {
      // This is the text of a form field that allows the user to filter
      // Submissions by a date range.
      "submissionDate": "Submitted at"
    },
    // Text shown when in date filter when records for all dates are shown
    "allSubmissionDateSelected": "All time"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "field": {
      "submissionDate": "Odesláno v"
    }
  },
  "de": {
    "field": {
      "submissionDate": "Übermittelt um"
    },
    "allSubmissionDateSelected": "Alle Zeit"
  },
  "es": {
    "field": {
      "submissionDate": "Enviado a"
    },
    "allSubmissionDateSelected": "Todos los tiempos"
  },
  "fr": {
    "field": {
      "submissionDate": "Soumis à"
    },
    "allSubmissionDateSelected": "Tout temps"
  },
  "id": {
    "field": {
      "submissionDate": "Terkirim pada"
    }
  },
  "it": {
    "field": {
      "submissionDate": "Inviato alle"
    },
    "allSubmissionDateSelected": "Per tutto il tempo"
  },
  "ja": {
    "field": {
      "submissionDate": "フォームの送信日"
    }
  },
  "pt": {
    "field": {
      "submissionDate": "Enviado em"
    },
    "allSubmissionDateSelected": "Todas as datas"
  },
  "sw": {
    "field": {
      "submissionDate": "Imewasilishwa kwa"
    }
  },
  "zh": {
    "field": {
      "submissionDate": "上传于："
    },
    "allSubmissionDateSelected": "所有时间"
  },
  "zh-Hant": {
    "field": {
      "submissionDate": "提交於"
    },
    "allSubmissionDateSelected": "全部時間"
  }
}
</i18n>
