<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <span id="submission-filters">
    <div class="form-group">
      <span class="icon-filter"></span><span>{{ $t('common.filter') }}</span>
    </div>
    <submission-filters-submitter :model-value="submitterId"
      @update:model-value="$emit('update:submitterId', $event)"/>
    <date-range-picker :model-value="submissionDate"
      :placeholder="$t('field.submissionDate')"
      @update:model-value="$emit('update:submissionDate', $event)"/>
    <submission-filters-review-state :model-value="reviewState"
      @update:model-value="$emit('update:reviewState', $event)"/>
  </span>
</template>

<script>
import DateRangePicker from '../date-range-picker.vue';
import SubmissionFiltersReviewState from './filters/review-state.vue';
import SubmissionFiltersSubmitter from './filters/submitter.vue';

export default {
  name: 'SubmissionFilters',
  components: {
    DateRangePicker,
    SubmissionFiltersReviewState,
    SubmissionFiltersSubmitter
  },
  props: {
    submitterId: {
      type: Array,
      required: true
    },
    submissionDate: {
      type: Array,
      required: true
    },
    reviewState: {
      type: Array,
      required: true
    }
  },
  emits: ['update:submitterId', 'update:submissionDate', 'update:reviewState']
};
</script>

<i18n lang="json5">
{
  "en": {
    "field": {
      // This is the text of a form field that allows the user to filter by a
      // date range.
      "submissionDate": "Submitted at"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "field": {
      "submissionDate": "Odesláno v"
    }
  },
  "de": {
    "field": {
      "submissionDate": "Übermittelt um"
    }
  },
  "es": {
    "field": {
      "submissionDate": "Enviado a"
    }
  },
  "fr": {
    "field": {
      "submissionDate": "Soumis à"
    }
  },
  "id": {
    "field": {
      "submissionDate": "Terkirim pada"
    }
  },
  "it": {
    "field": {
      "submissionDate": "Inviato alle"
    }
  },
  "ja": {
    "field": {
      "submissionDate": "フォームの送信日"
    }
  },
  "sw": {
    "field": {
      "submissionDate": "Imewasilishwa kwa"
    }
  }
}
</i18n>
