<!--
Copyright 2021 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="markdown-textarea" :class="activeBorderClass">
    <div class="form-group">
      <textarea :value="value" class="form-control"
        :placeholder="defaultText" :aria-label="defaultText"
        required rows="2" @input="update">
      </textarea>
    </div>
    <div v-if="value !== '' && previewMode" id="preview-container">
      <p class="heading">Preview</p>
      <!-- eslint-disable-next-line vue/no-v-html -->
      <div v-html="valueMarkdown"></div>
    </div>
    <div v-show="value !== '' || showFooter" id="submission-comment-actions">
      <a href="https://commonmark.org/help/" class="external-help-link" target="_blank" rel="noopener">{{ $t('markdownSupported') }} </a>
      <span class="push"></span>
      <button class="btn md-preview-btn" @click.prevent="toggleViewMode">
        {{ previewButtonText }}
      </button>
      <slot></slot>
    </div>
  </div>
</template>

<script>
import marked from 'marked';

export default {
  name: 'MarkdownTextarea',
  props: {
    value: {
      type: String,
      required: true
    },
    showFooter: {
      type: Boolean,
      default: false
    },
    defaultText: {
      type: String,
      default: ''
    }
  },
  data() {
    return {
      valueMarkdown: '',
      previewMode: false
    };
  },
  computed: {
    previewButtonText() {
      return this.previewMode ? this.$t('hidePreview') : this.$t('preview');
    },
    activeBorderClass() {
      if (this.showFooter || this.value !== '')
        return 'active-border';
      return null;
    }
  },
  methods: {
    update(event) {
      this.valueMarkdown = marked(event.target.value);
      this.$emit('input', event.target.value);
    },
    toggleViewMode() {
      this.previewMode = !this.previewMode;
    }
  }
};
</script>

<style lang="scss">

#markdown-textarea {
  &.active-border {
    border: 1px solid #31708f;
  }

  background: #eaeaea;

  .form-group {
    margin-bottom: 0;
    padding-bottom: 0px;
  }

  textarea {
    border-bottom-color: #aaa;
    resize: vertical;
  }

  #preview-container {
    padding: 10px;

    .heading {
      font-weight: bold;
      margin-bottom: 5px;
    }
  }

  .md-preview-btn {
    background-color: #999;
    color: white;
  }

  #submission-comment-actions {
    display: flex;
    align-content: stretch;
    align-items: center;
  }

  #submission-comment-actions > .btn {
    margin: 3px;
  }

  .push {
    margin-left: auto;
  }

  .external-help-link {
    color: #888;
    font-size: 12px;
    text-decoration: underline;
    text-decoration-style: dotted;
    padding: 10px;
  }
}

</style>

<i18n lang="json5">
{
  "en": {
    // This is a link to an external website with Markdown style guidelines
    "markdownSupported": "Markdown supported",
    "preview": "Preview",
    "hidePreview": "Hide Preview"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "markdownSupported": "Podporován formát Markdown"
  },
  "de": {
    "markdownSupported": "unterstützt durch Markdown"
  },
  "es": {
    "markdownSupported": "soporte Markdown"
  },
  "fr": {
    "markdownSupported": "Markdown disponible"
  },
  "it": {
    "markdownSupported": "Markdown supportato"
  },
  "ja": {
    "markdownSupported": "Markdown形式をサポートしています。"
  }
}
</i18n>
