<!--
Copyright 2024 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="submission-restore" :state="state" :hideable="!awaitingResponse"
    backdrop @hide="$emit('hide')" @shown="focusCheckbox">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="modal-introduction">
        <p>{{ $t('introduction[0]') }}</p>
        <p>{{ $t('introduction[1]') }}</p>
        <p>{{ $t('introduction[2]') }}</p>
      </div>
      <form v-if="checkbox">
        <div class="checkbox">
          <label>
            <input ref="input" v-model="noConfirm" type="checkbox">
            {{ $t('field.noConfirm') }}
          </label>
        </div>
      </form>
      <div class="modal-actions">
        <button type="button" class="btn btn-link"
          :aria-disabled="awaitingResponse" @click="$emit('hide')">
          {{ $t('action.cancel') }}
        </button>
        <button type="button" class="btn btn-danger"
          :aria-disabled="awaitingResponse" @click="restore">
          {{ $t('action.restore') }} <spinner :state="awaitingResponse"/>
        </button>
      </div>
    </template>
  </modal>
</template>

<script setup>
import { ref, watch } from 'vue';

import Modal from '../modal.vue';
import Spinner from '../spinner.vue';

defineOptions({
  name: 'SubmissionRestore'
});
const props = defineProps({
  state: Boolean,
  checkbox: Boolean,
  awaitingResponse: Boolean,
  submission: Object
});
const emit = defineEmits(['hide', 'restore']);

const noConfirm = ref(false);
watch(() => props.state, (state) => { if (!state) noConfirm.value = false; });

const input = ref(null);
const focusCheckbox = () => { if (props.checkbox) input.value.focus(); };

const restore = () => {
  if (props.checkbox)
    emit('restore', [props.submission, !noConfirm.value]);
  else
    emit('restore', [props.submission]);
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of Submission restore pop-up.
    "title": "Restore Submission",
    "introduction": [
      "Are you sure you want to restore this Submission?",
      "The Submission will be restored to its previous state, including associated data like comments.",
      "If the Submission is deleted again, it will be another 30 days before it is removed."
    ],
    "field": {
      "noConfirm": "Restore immediately without confirmation until I leave the page"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "title": "Übermittlung wiederherstellen",
    "introduction": [
      "Sind Sie sicher, dass Sie diese Übermittlung wiederherstellen wollen?",
      "Die Übermittlung wird in seinem vorherigen Zustand wiederhergestellt, einschliesslich zugehöriger Daten wie Kommentare.",
      "Wenn die Übermittlung erneut gelöscht wird, dauert es 30 Tage bis es entfernt wird."
    ],
    "field": {
      "noConfirm": "Sofortige Wiederherstellen ohne Bestätigung, bis ich die Seite verlasse"
    }
  },
  "es": {
    "title": "Restablecer el envío",
    "introduction": [
      "¿Estás seguro de que quieres restablecer este Envío?",
      "El envío se restablecerá a su estado anterior, incluidos los datos asociados, como los comentarios.",
      "Si el envío se vuelve a borrar, pasarán otros 30 días hasta que se elimine."
    ],
    "field": {
      "noConfirm": "Restablecer inmediatamente sin confirmación hasta que salga de la página"
    }
  },
  "fr": {
    "title": "Restaurer la Soumission",
    "introduction": [
      "Êtes vous certain(e) de vouloir restaurer cette soumission ?",
      "La Soumission sera restaurée dans son état précédent, y compris les données associées comme les commentaires.",
      "Si la soumission est à nouveau supprimée, il faudra attendre à nouveau 30 jours avant qu'elle ne soit retirée."
    ],
    "field": {
      "noConfirm": "Restaurer immédiatement sans confirmation jusqu'à ce que je quitte la page"
    }
  },
  "it": {
    "title": "Ripristino invio",
    "introduction": [
      "Sei sicuro di voler ripristinare questo invio?",
      "L'invio verrà ripristinato allo stato precedente, compresi i dati associati come i commenti.",
      "Se l'invio viene nuovamente cancellato, passeranno altri 30 giorni prima che venga rimosso."
    ],
    "field": {
      "noConfirm": "Ripristino immediato senza conferma fino a quando non lascio la pagina"
    }
  },
  "pt": {
    "title": "Recuperar Resposta",
    "introduction": [
      "Você tem certeza que quer recuperar essa Resposta?",
      "A Resposta vai ser restaurada ao seu estado anterior, incluindo dados associados, como comentários.",
      "Se a Resposta foi excluída novamente, haverá um novo prazo de 30 dias até que seja removida."
    ],
    "field": {
      "noConfirm": "Recuperar imediatamente sem pedir confirmação até que eu saia desta página"
    }
  },
  "zh": {
    "title": "恢复提交",
    "introduction": [
      "您确定要恢复此条提交数据吗？",
      "该提交数据将恢复至先前状态，包括标注等相关数据也将一并还原。",
      "若再次删除此提交数据，系统将在30天后执行永久清除。"
    ],
    "field": {
      "noConfirm": "在我离开页面前，无需确认立即恢复"
    }
  },
  "zh-Hant": {
    "title": "恢復提交內容",
    "introduction": [
      "您確定要還原此提交嗎？",
      "提交內容將恢復到先前的狀態，包括評論等相關資料。",
      "如果提交內容再次被刪除，則需要 30 天後才會被刪除。"
    ],
    "field": {
      "noConfirm": "立即還原，無需確認，直到我離開頁面"
    }
  }
}
</i18n>
