<!--
Copyright 2019 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div>
    <!-- This table element contains the frozen columns of the submissions
    table, which display metadata about each submission. -->
    <table id="submission-table1" class="table table-frozen">
      <thead>
        <tr>
          <th><!-- Row number --></th>
          <th v-if="showsSubmitter">{{ $t('header.submitterName') }}</th>
          <th>{{ $t('header.submissionDate') }}</th>
        </tr>
      </thead>
      <tbody>
        <submission-row v-for="(submission, index) in submissions"
          :key="submission.__id" :submission="submission"
          :row-number="originalCount - index"
          :shows-submitter="showsSubmitter"/>
      </tbody>
    </table>
    <!-- The next table element displays the data and instance ID of each
    submission. -->
    <div class="table-container">
      <table id="submission-table2" class="table">
        <thead>
          <tr>
            <!-- Adding a title attribute in case the column header is so long
            that it is truncated. -->
            <th v-for="field of fields" :key="field.path"
              :title="field.header()">
              {{ field.header() }}
            </th>
            <th>{{ $t('header.instanceId') }}</th>
          </tr>
        </thead>
        <tbody>
          <submission-row v-for="submission of submissions"
            :key="submission.__id" :base-url="baseUrl" :submission="submission"
            :fields="fields"/>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import SubmissionRow from './row.vue';

export default {
  name: 'SubmissionTable',
  components: { SubmissionRow },
  props: {
    baseUrl: {
      type: String,
      required: true
    },
    submissions: {
      type: Array,
      required: true
    },
    fields: {
      type: Array,
      required: true
    },
    originalCount: {
      type: Number,
      required: true
    },
    showsSubmitter: {
      type: Boolean,
      default: false
    }
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

#submission-table1 {
  box-shadow: 3px 0 0 rgba(0, 0, 0, 0.04);
  position: relative;
  // Adding z-index so that the background color of the other table's thead does
  // not overlay the box shadow.
  z-index: 1;

  th:last-child { border-right: $border-bottom-table-heading; }
  td:last-child { border-right: $border-top-table-data; }
}

#submission-table2 {
  width: auto;

  th, td {
    @include text-overflow-ellipsis;
    max-width: 250px;
    &:last-child { max-width: 300px; }
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "header": {
      "submitterName": "Submitted by",
      "submissionDate": "Submitted at",
      "instanceId": "Instance ID"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "header": {
      "submitterName": "Odesláno od",
      "submissionDate": "Odesláno na",
      "instanceId": "Instance ID"
    }
  },
  "de": {
    "header": {
      "submitterName": "Übermittelt von",
      "submissionDate": "Übermittelt um",
      "instanceId": "Instanz-ID"
    }
  },
  "es": {
    "header": {
      "submitterName": "Enviado por",
      "submissionDate": "Enviado el",
      "instanceId": "ID de la Instancia"
    }
  },
  "fr": {
    "header": {
      "submitterName": "Soumis par",
      "submissionDate": "Soumis à",
      "instanceId": "ID de l'instance"
    }
  },
  "id": {
    "header": {
      "submitterName": "Dikirim oleh",
      "submissionDate": "Dikirim pada",
      "instanceId": "ID Instansi"
    }
  }
}
</i18n>
