<!--
Copyright 2019 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div>
    <table id="submission-table-metadata" class="table table-frozen">
      <thead>
        <tr>
          <th><!-- Row number --></th>
          <th v-if="!draft">{{ $t('header.submitterName') }}</th>
          <th>{{ $t('header.submissionDate') }}</th>
          <th v-if="!draft">{{ $t('header.stateAndActions') }}</th>
        </tr>
      </thead>
      <tbody ref="metadataBody">
        <submission-metadata-row v-for="(submission, index) in submissions"
          :key="submission.__id" :project-id="projectId"
          :xml-form-id="xmlFormId" :draft="draft" :submission="submission"
          :row-number="originalCount - index" :can-update="canUpdate"/>
      </tbody>
    </table>
    <div class="table-container">
      <table id="submission-table-data" class="table">
        <thead>
          <tr v-if="fields != null">
            <!-- Adding a title attribute in case the column header is so long
            that it is truncated. -->
            <th v-for="field of fields" :key="field.path"
              :title="field.header()">
              {{ field.header() }}
            </th>
            <th>{{ $t('header.instanceId') }}</th>
          </tr>
        </thead>
        <tbody ref="dataBody">
          <template v-if="fields != null">
            <submission-data-row v-for="(submission, index) in submissions"
              :key="submission.__id" :project-id="projectId"
              :xml-form-id="xmlFormId" :draft="draft" :submission="submission"
              :fields="fields" :data-index="index + 1"/>
          </template>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import SubmissionDataRow from './data-row.vue';
import SubmissionMetadataRow from './metadata-row.vue';

import { requestData } from '../../store/modules/request';

export default {
  name: 'SubmissionTable',
  components: { SubmissionDataRow, SubmissionMetadataRow },
  props: {
    projectId: {
      type: String,
      required: true
    },
    xmlFormId: {
      type: String,
      required: true
    },
    draft: Boolean,
    submissions: {
      type: Array,
      required: true
    },
    fields: Array,
    originalCount: {
      type: Number,
      required: true
    }
  },
  computed: {
    // The component does not assume that this data will exist when the
    // component is created.
    ...requestData(['project']),
    canUpdate() {
      return this.project != null && this.project.permits('submission.update');
    }
  },
  mounted() {
    let index;
    let metadataRow;
    const mouseover = (event) => {
      const { dataset } = event.target.closest('tr');
      if (dataset.index !== index) {
        if (index != null) metadataRow.classList.remove('actions-shown');
        index = dataset.index; // eslint-disable-line prefer-destructuring
        metadataRow = this.$refs.metadataBody.querySelector(`tr:nth-child(${index})`);
        // The SubmissionMetadataRow element does not have a class binding, so I
        // think we can add this class without Vue removing it.
        metadataRow.classList.add('actions-shown');
      }
    };
    const mouseleave = () => {
      if (index != null) {
        metadataRow.classList.remove('actions-shown');
        index = null;
        metadataRow = null;
      }
    };
    const { dataBody } = this.$refs;
    dataBody.addEventListener('mouseover', mouseover);
    dataBody.addEventListener('mouseleave', mouseleave);
    this.$once('hook:beforeDestroy', () => {
      dataBody.removeEventListener('mouseover', mouseover);
      dataBody.removeEventListener('mouseleave', mouseleave);
    });
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

#submission-table-metadata {
  box-shadow: 3px 0 0 rgba(0, 0, 0, 0.04);
  position: relative;
  // Adding z-index so that the background color of the other table's thead does
  // not overlay the box shadow.
  z-index: 1;

  th:last-child { border-right: $border-bottom-table-heading; }
  td:last-child { border-right: $border-top-table-data; }
}

#submission-table-data {
  width: auto;

  th, td {
    @include text-overflow-ellipsis;
    max-width: 250px;
    &:last-child { max-width: 325px; }
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "header": {
      "submitterName": "Submitted by",
      "submissionDate": "Submitted at",
      "stateAndActions": "State and actions",
      "instanceId": "Instance ID"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "header": {
      "submitterName": "Odesláno od",
      "submissionDate": "Odesláno na",
      "instanceId": "Instance ID"
    }
  },
  "de": {
    "header": {
      "submitterName": "Übermittelt von",
      "submissionDate": "Übermittelt um",
      "instanceId": "Instanz-ID"
    }
  },
  "es": {
    "header": {
      "submitterName": "Enviado por",
      "submissionDate": "Enviado el",
      "instanceId": "ID de la Instancia"
    }
  },
  "fr": {
    "header": {
      "submitterName": "Soumis par",
      "submissionDate": "Soumis à",
      "instanceId": "ID de l'instance"
    }
  },
  "id": {
    "header": {
      "submitterName": "Dikirim oleh",
      "submissionDate": "Dikirim pada",
      "instanceId": "ID Instansi"
    }
  }
}
</i18n>
