<!--
Copyright 2019 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <table-freeze id="submission-table" ref="table" :data="chunkyOData"
    key-prop="__id" :frozen-only="fields == null" divider @action="review">
    <template #head-frozen>
      <th><!-- Row number --></th>
      <th v-if="!draft">{{ $t('header.submitterName') }}</th>
      <th>{{ $t('header.submissionDate') }}</th>
      <th v-if="!draft">{{ $t('header.stateAndActions') }}</th>
    </template>
    <template #head-scrolling>
      <template v-if="fields != null">
        <th v-for="field of fields" :key="field.path">
          <span v-tooltip.text>{{ field.header }}</span>
        </th>
      </template>
      <th>{{ $t('header.instanceId') }}</th>
    </template>

    <template #data-frozen="{ data, index }">
      <submission-metadata-row :project-id="projectId" :xml-form-id="xmlFormId"
        :draft="draft" :submission="data"
        :row-number="odata.originalCount - index" :can-update="canUpdate"/>
    </template>
    <template #data-scrolling="{ data }">
      <submission-data-row :project-id="projectId" :xml-form-id="xmlFormId"
        :draft="draft" :submission="data" :fields="fields"/>
    </template>
  </table-freeze>
</template>

<script setup>
import { computed, ref } from 'vue';

import SubmissionDataRow from './data-row.vue';
import SubmissionMetadataRow from './metadata-row.vue';
import TableFreeze from '../table-freeze.vue';

import useChunkyArray from '../../composables/chunky-array';
import { markRowsChanged } from '../../util/dom';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'SubmissionTable'
});
defineProps({
  projectId: {
    type: String,
    required: true
  },
  xmlFormId: {
    type: String,
    required: true
  },
  draft: Boolean,
  fields: Array
});
const emit = defineEmits(['review']);

// The component does not assume that this data will exist when the component is
// created.
const { project, odata } = useRequestData();

const chunkyOData = useChunkyArray(computed(() => odata.value));
const canUpdate = computed(() =>
  project.dataExists && project.permits('submission.update'));

const review = ({ target, data }) => {
  if (target.classList.contains('review-button')) emit('review', data);
};
const table = ref(null);
const afterReview = (index) => { markRowsChanged(table.value.getRowPair(index)); };
defineExpose({ afterReview });
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

#submission-table .table-freeze-scrolling {
  th, td {
    @include text-overflow-ellipsis;
    max-width: 250px;
    &:last-child { max-width: 325px; }
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "header": {
      "stateAndActions": "State and actions"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "header": {
      "stateAndActions": "Stav a akce"
    }
  },
  "de": {
    "header": {
      "stateAndActions": "Status und Aktionen"
    }
  },
  "es": {
    "header": {
      "stateAndActions": "Estado y acciones"
    }
  },
  "fr": {
    "header": {
      "stateAndActions": "État et actions"
    }
  },
  "id": {
    "header": {
      "stateAndActions": "Status dan tindakan"
    }
  },
  "it": {
    "header": {
      "stateAndActions": "Stato e azioni"
    }
  },
  "ja": {
    "header": {
      "stateAndActions": "レビュー・ステータスと操作"
    }
  },
  "sw": {
    "header": {
      "stateAndActions": "Hali na vitendo"
    }
  }
}
</i18n>
