<!--
Copyright 2019 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="user-retire" :state="state" :hideable="!awaitingResponse" backdrop
    @hide="$emit('hide')">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="modal-introduction">
        <p v-if="user != null">{{ $t('introduction[0]', user) }}</p>
        <i18n-t tag="p" keypath="introduction[1].full">
          <template #noUndo>
            <strong>{{ $t('introduction[1].noUndo') }}</strong>
          </template>
        </i18n-t>
        <p>{{ $t('common.areYouSure') }}</p>
      </div>
      <div class="modal-actions">
        <button type="button" class="btn btn-link" :aria-disabled="awaitingResponse"
          @click="$emit('hide')">
          {{ $t('action.noCancel') }}
        </button>
        <button type="button" class="btn btn-danger"
          :aria-disabled="awaitingResponse" @click="retire">
          {{ $t('action.yesProceed') }} <spinner :state="awaitingResponse"/>
        </button>
      </div>
    </template>
  </modal>
</template>

<script>
import Modal from '../modal.vue';
import Spinner from '../spinner.vue';

import useRequest from '../../composables/request';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';

export default {
  name: 'UserRetire',
  components: { Modal, Spinner },
  props: {
    state: Boolean,
    user: Object
  },
  emits: ['hide', 'success'],
  setup() {
    const { request, awaitingResponse } = useRequest();
    return { request, awaitingResponse };
  },
  methods: {
    retire() {
      this.request({ method: 'DELETE', url: apiPaths.user(this.user.id) })
        .then(() => {
          this.$emit('success', this.user);
        })
        .catch(noop);
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up. An Administrator can use the
    // pop-up to retire another Web User.
    "title": "Retiring User",
    "introduction": [
      "You are about to retire the user account “{displayName}” \u003c{email}>. That user will be immediately barred from performing any actions and logged out.",
      {
        "full": "{noUndo}, but a new account can always be created for that person with the same email address.",
        "noUndo": "This action cannot be undone"
      }
    ]
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Uspaný uživatel",
    "introduction": [
      "Chystáte se uspat uživatelský účet „{displayName}“ \u003c{email}>. Tomuto uživateli bude okamžitě zakázáno provádět jakékoli akce a bude odhlášen.",
      {
        "full": "{noUndo}, ale pro tuto osobu lze vždy vytvořit nový účet se stejnou e-mailovou adresou.",
        "noUndo": "Tuto akci nelze vrátit zpět"
      }
    ]
  },
  "de": {
    "title": "User deaktivieren",
    "introduction": [
      "Sie sind dabei das Benutzerkonto \"{displayName}\" \u003c{email}> zu deaktivieren. Dieser Benutzer wird sofort am Ausführen von Aktionen gehindert und ausgeloggt.",
      {
        "full": "{noUndo}, aber es kann immer ein neues Konto mit derselben E-Mail-Adresse für diese Person angelegt werden.",
        "noUndo": "Diese Aktion kann nicht rückgängig gemacht werden."
      }
    ]
  },
  "es": {
    "title": "Retirando usuario",
    "introduction": [
      "Esta a punto de retirar el usuario \"{displayName}\"\u003c{email}> . El usuario será removido inmediatamente y se restringirá cualquier tipo de actividad en el proyecto.",
      {
        "full": "{noUndo}, sin embargo, siempre puede crear una nueva cuenta para esa persona con el mismo correo electrónico.",
        "noUndo": "Esta acción no puede ser realizada"
      }
    ]
  },
  "fr": {
    "title": "Supprimer utilisateur",
    "introduction": [
      "Vous êtes sur le point de supprimer le compte \"{displayName}\" \u003c{email}>. Cet usager sera immédiatement déconnecté et empêché d'agir sur le site.",
      {
        "full": "{noUndo}, mais un nouveau compte peut toujours être créé pour cette personne avec la même adresse de courriel.",
        "noUndo": "Cette action ne peut être annulée"
      }
    ]
  },
  "id": {
    "title": "Pengguna yang sudah Berhenti",
    "introduction": [
      "Anda hendak memberhentikan akun pengguna \"{displayName}\" \u003c{email}>. Pengguna tersebut tidak akan bisa melakukan tindakan apapun dan keluar.",
      {
        "full": "{noUndo}, tetapi sebuah akun baru akan selalu dapat dibuat untuk pengguna tersebut dengan alamat email yang sama.",
        "noUndo": "Tindakan ini tidak bisa dibatalkan/dikembalikan"
      }
    ]
  },
  "it": {
    "title": "Ritirando utente",
    "introduction": [
      "Stai per ritirare l'account per l'utente “{displayName}” \u003c{email}>. A tale utente verrà immediatamente impedito di eseguire qualsiasi azione e verrà disconnesso.",
      {
        "full": "{noUndo}, ma è sempre possibile creare un nuovo account per quella persona con lo stesso indirizzo email.",
        "noUndo": "Quest'azione non può essere annullata"
      }
    ]
  },
  "ja": {
    "title": "除外されたユーザー",
    "introduction": [
      "ユーザーアカウント\"{displayName}\"\u003c{email}>を除外しようとしています。このユーザーは、即座にいかなるアクションも実行できなくなり、ログアウトされます。",
      {
        "full": "{noUndo}が、新しいアカウントは同じメールアドレスでいつでも再作成することができます。",
        "noUndo": "この操作は取り消しできません"
      }
    ]
  },
  "pt": {
    "title": "Desativando usuário",
    "introduction": [
      "Você está prestes a desativar a conta de usuário \"{displayName}\" \u003c{email}>. Essa conta será imediatamente impedida de realizar qualquer ação e sairá do sistema.",
      {
        "full": "{noUndo}, mas uma nova conta sempre poderá ser criada para aquela pessoa com o mesmo endereço de email.",
        "noUndo": "Essa ação não pode ser desfeita"
      }
    ]
  },
  "sw": {
    "title": "Mtumiaji Anayestaafu",
    "introduction": [
      "Unakaribia kustaafu akaunti ya mtumiaji \"{displayName}\" \u003c{email}>. Mtumiaji huyo atazuiwa mara moja kufanya vitendo vyovyote na kuondoka",
      {
        "full": "{noUndo}, lakini akaunti mpya inaweza kufunguliwa kwa ajili ya mtu huyo kwa kutumia anwani sawa ya barua pepe.",
        "noUndo": "Kitendo hiki hakiwezi kutenduliwa"
      }
    ]
  },
  "zh": {
    "title": "停用使用者",
    "introduction": [
      "您即将停用用户账户 “{displayName}” \u003c{email}>。该用户将立即被禁止执行任何操作并强制退出登录。",
      {
        "full": "此操作{noUndo}，但随时可使用该邮箱地址为相关用户新建账户。",
        "noUndo": "此操作无法取消"
      }
    ]
  },
  "zh-Hant": {
    "title": "停用使用者",
    "introduction": [
      "您即將停用使用者帳號「{displayName}」\u003c{email}>。該用戶將被立即禁止執行任何操作並註銷。",
      {
        "full": "{noUndo}，但可以使用相同的電子郵件地址，為該人建立一個新帳戶。",
        "noUndo": "此操作無法取消"
      }
    ]
  }
}
</i18n>
