<!--
Copyright 2022 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <span v-if="version !== ''" class="form-version-string" v-tooltip.text>{{ version }}</span>
  <span v-else class="form-version-string blank-version">{{ $t('blank') }}</span>
</template>

<script>
export default {
  name: 'FormVersionString',
  props: {
    version: {
      type: String,
      required: true
    }
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/variables';

.form-version-string {
  font-family: $font-family-monospace;
  &.blank-version { font-family: inherit; }
}
</style>

<i18n lang="json5">
{
  "en": {
    // This is shown for a Form with a blank version name.
    "blank": "(blank)"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "blank": "(prázdný)"
  },
  "de": {
    "blank": "(leer)"
  },
  "es": {
    "blank": "(vacío)"
  },
  "fr": {
    "blank": "(vierge)"
  },
  "id": {
    "blank": "(kosong)"
  },
  "it": {
    "blank": "(vuoto)"
  },
  "ja": {
    "blank": "(未設定)"
  },
  "pt": {
    "blank": "(em branco)"
  },
  "sw": {
    "blank": "(tupu)"
  },
  "zh": {
    "blank": "（空）"
  },
  "zh-Hant": {
    "blank": "(空白)"
  }
}
</i18n>
