<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <table-scroll id="form-attachment-table">
    <table class="table">
      <thead>
        <tr>
          <th>{{ $t('header.type') }}</th>
          <th>{{ $t('header.name') }}</th>
          <th>{{ $t('header.uploaded') }}</th>
          <th></th>
        </tr>
      </thead>
      <tbody v-if="form.dataExists && draftAttachments.dataExists">
        <form-attachment-row v-for="attachment of draftAttachments.values()"
          :key="attachment.name" :attachment="attachment"
          :file-is-over-drop-zone="fileIsOverDropZone"
          :dragover-attachment="dragoverAttachment"
          :planned-uploads="plannedUploads"
          :updated-attachments="updatedAttachments"
          :linkable="attachment.type === 'file' && dsHashset.has(attachment.name.replace(/\.[^.]+$/i, ''))"
          @link="$emit('link', $event)"/>
      </tbody>
    </table>
  </table-scroll>
</template>

<script setup>
import { computed } from 'vue';

import FormAttachmentRow from './row.vue';
import TableScroll from '../table/scroll.vue';

import { useRequestData } from '../../request-data';

defineOptions({
  name: 'FormAttachmentTable'
});
defineProps({
  fileIsOverDropZone: Boolean,
  dragoverAttachment: Object,
  plannedUploads: {
    type: Array,
    required: true
  },
  updatedAttachments: {
    type: Set,
    required: true
  }
});
defineEmits(['link']);

const { form, draftAttachments, datasets } = useRequestData();

const dsHashset = computed(() =>
  (datasets.dataExists ? new Set(datasets.map(d => `${d.name}`)) : new Set()));
</script>

<style lang="scss">
@import '../../assets/scss/variables';

#form-attachment-table {
  margin-bottom: 10px;
  max-height: 70vh;

  table { table-layout: fixed; }

  th:first-child { width: 125px; }
  th:nth-child(2) { width: 250px; }
  th:last-child { width: #{200px + $padding-left-table-data + $padding-right-table-data}; }
}
</style>

<i18n lang="json5">
{
  "en": {
    // @transifexKey component.FormAttachmentList.header
    "header": {
      // This is the text of a table column header. The column shows when each
      // Media File was uploaded.
      "uploaded": "Uploaded"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "header": {
      "uploaded": "Nahráno"
    }
  },
  "de": {
    "header": {
      "uploaded": "Hochgeladen"
    }
  },
  "es": {
    "header": {
      "uploaded": "Subido"
    }
  },
  "fr": {
    "header": {
      "uploaded": "Téléversés"
    }
  },
  "id": {
    "header": {
      "uploaded": "Diunggah"
    }
  },
  "it": {
    "header": {
      "uploaded": "Caricati"
    }
  },
  "ja": {
    "header": {
      "uploaded": "アップロード済"
    }
  },
  "pt": {
    "header": {
      "uploaded": "Carregado"
    }
  },
  "sw": {
    "header": {
      "uploaded": "Imepakiwa"
    }
  },
  "zh": {
    "header": {
      "uploaded": "已上传"
    }
  },
  "zh-Hant": {
    "header": {
      "uploaded": "已上傳"
    }
  }
}
</i18n>
