<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="account-claim" class="row">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6">
      <div class="panel panel-default panel-main">
        <div class="panel-heading">
          <h1 class="panel-title">{{ $t('title.setPassword') }}</h1>
        </div>
        <div class="panel-body">
          <form @submit.prevent="submit">
            <!-- Chrome displays a message in the console indicating that there
            should be a username input (even if it is hidden). However, we do
            not know the user's email address on this page. -->
            <form-group ref="password" v-model="password" type="password"
              :placeholder="$t('field.newPassword')" required
              autocomplete="new-password"/>
            <div class="panel-footer">
              <button type="submit" class="btn btn-primary"
                :aria-disabled="awaitingResponse">
                {{ $t('action.set') }} <spinner :state="awaitingResponse"/>
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import FormGroup from '../form-group.vue';
import Spinner from '../spinner.vue';

import useRequest from '../../composables/request';
import { noop } from '../../util/util';

export default {
  name: 'AccountClaim',
  components: { FormGroup, Spinner },
  inject: ['alert'],
  setup() {
    const { request, awaitingResponse } = useRequest();
    return { request, awaitingResponse };
  },
  data() {
    return {
      password: ''
    };
  },
  mounted() {
    this.$refs.password.focus();
  },
  methods: {
    submit() {
      if (this.password.length < 10) {
        this.alert.danger(this.$t('alert.passwordTooShort'));
        return;
      }

      const headers = {};
      const { token } = this.$route.query;
      if (typeof token === 'string') headers.Authorization = `Bearer ${token}`;
      this.request({
        method: 'POST',
        url: '/v1/users/reset/verify',
        headers,
        data: { new: this.password },
        problemToAlert: (problem) =>
          (problem.code === 401.2 ? this.$t('problem.401_2', problem) : null)
      })
        .then(() => {
          const message = this.$t('alert.success');
          return this.$router.push({ path: '/login', query: { source: 'claim' } })
            .then(() => { this.alert.success(message); });
        })
        .catch(noop);
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    "action": {
      "set": "Set password"
    },
    "problem": {
      // {message} is an error message from the server.
      "401_2": "{message} The link in your email may have expired, and a new email may have to be sent."
    },
    "alert": {
      "success": "Password successfully reset."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "action": {
      "set": "Nastavit heslo"
    },
    "problem": {
      "401_2": "{message} Platnost odkazu ve vašem e-mailu pravděpodobně skončila a možná bude nutné zaslat nový e-mail."
    }
  },
  "de": {
    "action": {
      "set": "Passwort festlegen"
    },
    "problem": {
      "401_2": "{message} Der Hyperlink in Ihrer E-Mail könnte abgelaufen sein und vielleicht sollte eine neue E-Mail gesendet werden."
    },
    "alert": {
      "success": "Passwort erfolgreich zurückgesetzt."
    }
  },
  "es": {
    "action": {
      "set": "Establecer contraseña"
    },
    "problem": {
      "401_2": "{message} Es posible que el enlace de su correo electrónico haya expirado y tenga que enviarse un nuevo correo electrónico."
    },
    "alert": {
      "success": "Contraseña restablecida correctamente."
    }
  },
  "fr": {
    "action": {
      "set": "Définir le mot de passe"
    },
    "problem": {
      "401_2": "{message} Le lien présent dans votre courriel a probablement expiré, et un nouveau courriel a dû vous être envoyé."
    },
    "alert": {
      "success": "Le mot de passe a été réinitialisé."
    }
  },
  "id": {
    "action": {
      "set": "Atur kata sandi"
    },
    "problem": {
      "401_2": "{message} Tautan menuju email Anda sudah kedaluwarsa, Anda harus mengirimkan email baru."
    }
  },
  "it": {
    "action": {
      "set": "Configurare la password"
    },
    "problem": {
      "401_2": "{message} Il link nella tua e-mail potrebbe essere scaduto e potrebbe essere necessario inviare una nuova e-mail."
    },
    "alert": {
      "success": "Password ristabilita con successo."
    }
  },
  "ja": {
    "action": {
      "set": "パスワードの設定"
    },
    "problem": {
      "401_2": "{message} メールに記載されているリンクの有効期限が切れている可能性があり、新たにメールを送信する必要があるようです。"
    }
  },
  "pt": {
    "action": {
      "set": "Definir senha"
    },
    "problem": {
      "401_2": "{message} O link de seu email expirou e um novo link precisa ser enviado."
    },
    "alert": {
      "success": "Senha redefinida com sucesso."
    }
  },
  "sw": {
    "action": {
      "set": "Weka nenosiri"
    },
    "problem": {
      "401_2": "{message} Huenda muda wa kiungo katika barua pepe yako umeisha, na huenda barua pepe mpya ikatumwa."
    }
  },
  "zh": {
    "action": {
      "set": "设置密码"
    },
    "problem": {
      "401_2": "{message}您邮件中的链接可能已失效，需要重新发送邮件。"
    },
    "alert": {
      "success": "密码重设成功"
    }
  },
  "zh-Hant": {
    "action": {
      "set": "設定密碼"
    },
    "problem": {
      "401_2": "{message} 您電子郵件中的連結可能已過期，可能需要發送新電子郵件。"
    },
    "alert": {
      "success": "密碼重設成功。"
    }
  }
}
</i18n>
