<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="account-reset-password">
    <h1>{{ $t('title') }}</h1>
    <p>{{ $t('subtitle') }}</p>
    <form @submit.prevent="submit">
      <form-group ref="email" v-model.trim="email" type="email"
        :placeholder="$t('field.email')" required autocomplete="off"/>
      <div>
        <button type="submit" class="btn btn-primary"
          :aria-disabled="awaitingResponse">
          {{ $t('action.resetPassword') }} <spinner :state="awaitingResponse"/>
        </button>
        <router-link v-slot="{ navigate }" to="/login" custom>
          <button type="button" class="btn btn-link" @click="navigate">
            {{ $t('action.cancel') }}
          </button>
        </router-link>
      </div>
    </form>
  </div>
</template>

<script>
import FormGroup from '../form-group.vue';
import Spinner from '../spinner.vue';

import useRequest from '../../composables/request';
import { noop } from '../../util/util';

export default {
  name: 'AccountResetPassword',
  components: { FormGroup, Spinner },
  inject: ['alert'],
  setup() {
    const { request, awaitingResponse } = useRequest();
    return { request, awaitingResponse };
  },
  data() {
    return {
      email: ''
    };
  },
  mounted() {
    this.$refs.email.focus();
  },
  methods: {
    submit() {
      const { email } = this;
      this.request({
        method: 'POST',
        url: '/v1/users/reset/initiate',
        data: { email }
      })
        .then(() => {
          const message = this.$t('alert.success', { email });
          return this.$router.push('/login')
            .then(() => { this.alert.success(message); });
        })
        .catch(noop);
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    "title": "Reset your password",
    "subtitle": "Enter your email to reset your password",
    "alert": {
      "success": "An email has been sent to {email} with further instructions."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "alert": {
      "success": "Byl odeslán e-mail na {email} s dalšími pokyny."
    }
  },
  "de": {
    "title": "Passwort zurücksetzen",
    "subtitle": "Gib deine E-Mail-Adresse ein, um dein Passwort zurückzusetzen",
    "alert": {
      "success": "Eine E-Mail mit weiteren Anweisungen wurde an {email} gesendet."
    }
  },
  "es": {
    "title": "Restablece tu contraseña",
    "subtitle": "Introduce tu correo electrónico para restablecer tu contraseña",
    "alert": {
      "success": "Se ha enviado un correo electrónico {email} con más instrucciones"
    }
  },
  "fr": {
    "alert": {
      "success": "Un courriel a été envoyé à {email} avec de plus amples instructions"
    }
  },
  "id": {
    "alert": {
      "success": "Email sudah dikirimkan ke {email} dengan instruksi lebih lanjut."
    }
  },
  "it": {
    "title": "Reimposta la tua password",
    "subtitle": "Inserisci il tuo indirizzo e-mail per reimpostare la password",
    "alert": {
      "success": "È stata inviata un'email a {email} con ulteriori istruzioni."
    }
  },
  "ja": {
    "alert": {
      "success": "{email}に詳細の対応についての情報が記されたメールが送信されました。"
    }
  },
  "pt": {
    "alert": {
      "success": "Um email foi enviado para {email} com mais instruções."
    }
  },
  "sw": {
    "alert": {
      "success": "Barua pepe imetumwa kwa {email} ikiwa na maagizo zaidi."
    }
  },
  "zh": {
    "title": "重置密码",
    "subtitle": "输入您的电子邮件以重置密码",
    "alert": {
      "success": "已向{email}发送邮件，内含后续操作说明。"
    }
  },
  "zh-Hant": {
    "alert": {
      "success": "一封電子郵件已發送至 {email} 並附有進一步說明。"
    }
  }
}
</i18n>
