<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <a v-if="disabledDescription == null" class="enketo-preview btn" :class="btnClass" :href="previewPath"
    target="_blank">
    <span class="icon-eye"></span>{{ $t('action.showPreview') }}
  </a>
  <button v-else type="button" class="enketo-preview btn" :class="btnClass" aria-disabled="true"
    v-tooltip.aria-describedby="disabledDescription">
    <span class="icon-eye"></span>{{ $t('action.showPreview') }}
  </button>

  <router-link class="btn btn-web-form" :class="btnClass" :to="webFormsPath"
    target="_blank">
    <span class="icon-eye"></span>{{ $t('action.newPreview') }}
  </router-link>
</template>

<script>
import useRoutes from '../../composables/routes';
import { queryString } from '../../util/request';

export default {
  name: 'EnketoPreview',
  props: {
    formVersion: {
      type: Object,
      required: true
    },
    outlined: Boolean
  },
  setup() {
    const { formPath, formPreviewPath } = useRoutes();
    return { formPath, formPreviewPath };
  },
  computed: {
    disabledDescription() {
      if (this.formVersion.webformsEnabled) return null;
      if (this.formVersion.publishedAt != null &&
        this.formVersion.state !== 'open')
        return this.$t('disabled.notOpen');
      if (this.formVersion.enketoId == null)
        return this.$t('disabled.processing');
      return null;
    },
    btnClass() {
      return this.outlined ? 'btn-outlined' : 'btn-default';
    },
    previewPath() {
      return this.formPreviewPath(
        this.formVersion.projectId,
        this.formVersion.xmlFormId,
        !this.formVersion.publishedAt
      );
    },
    webFormsPath() {
      return `${this.formPreviewPath(
        this.formVersion.projectId,
        this.formVersion.xmlFormId,
        !this.formVersion.publishedAt
      )}${queryString({ webforms: true })}`;
    }
  }
};
</script>

<style lang="scss">
.btn-web-form {
  display: none;
}

// `new-web-forms` class is added to the root of App component when the
// new web form feature is enabled.
.new-web-forms {
  .enketo-preview {
    display: none;
  }

  .btn-web-form {
    display: inline-block;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "disabled": {
      "processing": "Preview has not finished processing for this Form. Please refresh later and try again.",
      "notOpen": "In this version of ODK Central, preview is only available for Forms in the Open state."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "disabled": {
      "processing": "Náhled nedokončil zpracování tohoto formuláře. Aktualizujte prosím později a zkuste to znovu.",
      "notOpen": "V této verzi ODK Central je náhled k dispozici pouze pro formuláře v otevřeném stavu."
    }
  },
  "de": {
    "disabled": {
      "processing": "Die Vorschau für dieses Formular ist noch nicht vollständig erstellt. Bitte aktualieren Sie und versuchen Sie es später noch einmal.",
      "notOpen": "In dieser Version von ODK Central steht die Vorschau nur für Formule im Zustand \"Offen\" zur Verfügung."
    }
  },
  "es": {
    "disabled": {
      "processing": "La vista previa no ha finalizado el procesamiento de este formulario. Por favor actualice más tarde e intente nuevamente.",
      "notOpen": "En esta versión de ODK Central, la vista previa solo está disponible para formularios en estado abierto."
    }
  },
  "fr": {
    "disabled": {
      "processing": "L'aperçu n'a pas fini d'être exécuté pour ce formulaire. Veuillez rafraîchir plus tard et réessayer.",
      "notOpen": "Dans cette version d'ODK Central, l'aperçu n'est disponible que pour les formulaires dont l'état est ouvert."
    }
  },
  "id": {
    "disabled": {
      "processing": "Pratinjau untuk formulir ini masih dalam proses pengerjaan. Silakan muat ulang dan coba lagi nanti.",
      "notOpen": "Pada versi ODK Central ini, pratinjau hanya tersedia untuk formulir dalam kondisi terbuka."
    }
  },
  "it": {
    "disabled": {
      "processing": "L'anteprima non ha terminato l'elaborazione per questo formulario. Per favore riaggiorna più tardi e riprova.",
      "notOpen": "In questa versione di ODK Central, l'anteprima è disponibile solo per i formulari nello stato aperto."
    }
  },
  "ja": {
    "disabled": {
      "processing": "このフォームのプレビュー処理が終了していません。後ほどページを更新し、もう一度試して下さい。",
      "notOpen": "このバージョンのODK Centralでは、プレビューは、公開状態のフォームでのみ利用可能です。"
    }
  },
  "pt": {
    "disabled": {
      "processing": "A visualização prévia não terminou de processar esse formulário. Por favor, atualize a página mais tarde e tente novamente.",
      "notOpen": "Nessa versão do ODK Central, a pré-visualização está disponível apenas para formulários com status aberto."
    }
  },
  "sw": {
    "disabled": {
      "processing": "Onyesho la kuchungulia halijamaliza kuchakata Fomu hii. Tafadhali onyesha upya baadaye na ujaribu tena.",
      "notOpen": "Katika toleo hili la ODK Central, onyesho la kukagua linapatikana kwa Fomu zilizo katika \"OPEN STATE\""
    }
  },
  "zh": {
    "disabled": {
      "processing": "此表单的预览功能尚未处理完成，请稍后刷新重试。",
      "notOpen": "此版本ODK Central中，预览功能仅对“开放”状态的表单开放。"
    }
  },
  "zh-Hant": {
    "disabled": {
      "processing": "預覽尚未完成此表單的處理。請稍後重新載入並重試。",
      "notOpen": "在此版本的 ODK Central 中，預覽僅適用於「開啟」狀態的表單。"
    }
  }
}
</i18n>
