<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="form-attachment-upload-files" :state="state" hideable backdrop
    @hide="$emit('hide')" @shown="$refs.link.focus()">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="modal-introduction">
        <i18n-t tag="p" keypath="introduction[0].full">
          <template #dragAndDrop>
            <strong>{{ $t('introduction[0].dragAndDrop') }}</strong>
          </template>
        </i18n-t>
        <i18n-t tag="p" keypath="introduction[1].full">
          <template #clickHere>
            <!-- eslint-disable-next-line vuejs-accessibility/form-control-has-label -->
            <input v-show="false" ref="input" type="file" multiple
              @change="afterChange">
            <a ref="link" href="#" role="button"
              @click.prevent="$refs.input.click()">
              <span class="icon-folder-open"></span>
              <span>{{ $t('introduction[1].clickHere') }}</span>
            </a>
          </template>
        </i18n-t>
      </div>
      <div class="modal-actions">
        <button type="button" class="btn btn-primary" @click="$emit('hide')">
          {{ $t('action.ok') }}
        </button>
      </div>
    </template>
  </modal>
</template>

<script>
import Modal from '../modal.vue';

export default {
  name: 'FormAttachmentUploadFiles',
  components: { Modal },
  props: {
    state: {
      type: Boolean,
      default: false
    }
  },
  emits: ['hide', 'select'],
  methods: {
    afterChange(event) {
      this.$emit('select', event.target.files);
      this.$refs.input.value = '';
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up.
    "title": "Upload Files",
    "introduction": [
      {
        "full": "To upload files, you can {dragAndDrop} one or more files onto the table on this page.",
        "dragAndDrop": "drag and drop"
      },
      {
        "full": "If you would rather select files from a prompt, ensure that their names match the ones in the table and then {clickHere}.",
        "clickHere": "click here to choose"
      }
    ]
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Nahrát soubory",
    "introduction": [
      {
        "full": "Chcete-li nahrát soubory, můžete {dragAndDrop} do tabulky na této stránce jeden nebo více souborů.",
        "dragAndDrop": "přetáhněte soubory sem"
      },
      {
        "full": "Pokud byste raději vybrali soubory z příkazového řádku, zajistěte, aby se jejich názvy shodovaly se jmény v tabulce a poté {clickHere}.",
        "clickHere": "kliknutím vyberte"
      }
    ]
  },
  "de": {
    "title": "Dateien hochladen",
    "introduction": [
      {
        "full": "Um Dateien hochzuladen, können Sie eine oder mehrere Dateien mit {dragAndDrop} in die Tabelle auf dieser Seite ziehen.",
        "dragAndDrop": "Drag-and-Drop"
      },
      {
        "full": "Wenn Sie Dateien lieber über eine Eingabeaufforderung auswählen, stellen Sie sicher, dass die Namen denen in der Tabelle entsprechen und {clickHere}.",
        "clickHere": "klicken Sie hier"
      }
    ]
  },
  "es": {
    "title": "Subir archivos",
    "introduction": [
      {
        "full": "Para cargar archivos, puede {dragAndDrop} uno o más archivos en la tabla de esta página.",
        "dragAndDrop": "arrastrar y soltar"
      },
      {
        "full": "Si prefiere seleccionar archivos de una solicitud, asegúrese de que sus nombres coincidan con los de la tabla y luego {clickHere}.",
        "clickHere": "haga clic aquí para elegir"
      }
    ]
  },
  "fr": {
    "title": "Téléverser des fichiers",
    "introduction": [
      {
        "full": "Pour téléverser des fichiers, vous pouvez {dragAndDrop} un ou plusieurs fichiers sur le tableau de cette page..",
        "dragAndDrop": "Glisser et déposer"
      },
      {
        "full": "Si vous préférez naviguer vers les fichiers à sélectionner, assurez vous que leurs noms correspondent à ceux mentionnés dans le tableau et {clickHere}.",
        "clickHere": "Cliquez ici pour choisir"
      }
    ]
  },
  "id": {
    "title": "Unggah dokumen",
    "introduction": [
      {
        "full": "Untuk menunggah dokumen, {dragAndDrop} satu atau lebih dokumen ke tabel pada laman ini",
        "dragAndDrop": "seret dan lepas"
      },
      {
        "full": "Apabila Anda ingin memilih dokumen dari prompt, pastikan nama dokumen sudah sama dengan yang ada pada tabel, lalu {clickHere}.",
        "clickHere": "klik di sini untuk memilih"
      }
    ]
  },
  "it": {
    "title": "Caricare files",
    "introduction": [
      {
        "full": "Per caricare file, puoi {dragAndDrop} uno o più file su questa pagina",
        "dragAndDrop": "trascinare e rilasciare"
      },
      {
        "full": "Se preferisci selezionare i file da un prompt, assicurati che i loro nomi corrispondano a quelli nella tabella e poi {clickHere}.",
        "clickHere": "clicca qui per selezionare"
      }
    ]
  },
  "ja": {
    "title": "ファイルのアップロード",
    "introduction": [
      {
        "full": "ファイルのアップロードは、１つまたは複数のファイルをこのページの表に{dragAndDrop}することで可能です。",
        "dragAndDrop": "ドラッグ＆ドロップ"
      },
      {
        "full": "プロンプトからファイルを選択したい場合は、表にあるものとファイル名が一致していることを確認してから、{clickHere}。",
        "clickHere": "こちらをクリックして選択する"
      }
    ]
  },
  "pt": {
    "title": "Carregar arquivos",
    "introduction": [
      {
        "full": "Para carregar arquivos, você pode {dragAndDrop} um ou mais arquivos sobre a tabela nessa página.",
        "dragAndDrop": "arrastar e soltar"
      },
      {
        "full": "Se você preferir selecionar arquivos a partir de uma janela de seleção, certifique-se que os nomes deles correspondem aos que estão na tabela e {clickHere}.",
        "clickHere": "clique aqui para selecionar"
      }
    ]
  },
  "sw": {
    "title": "Pakia Faili",
    "introduction": [
      {
        "full": "Ili kupakia faili, unaweza {dragAndDrop} faili moja au zaidi kwenye jedwali kwenye ukurasa huu.",
        "dragAndDrop": "buruta na udondoshe"
      },
      {
        "full": "ikiwa ungependa kuchagua faili kutoka kwa haraka, hakikisha kwamba majina yao yanalingana na yale yaliyo kwenye jedwali kisha {clickHere}",
        "clickHere": "bonyeza hapa kuchagua"
      }
    ]
  },
  "zh": {
    "title": "上传文件",
    "introduction": [
      {
        "full": "要上传文件，您可以{dragAndDrop}，将一个或多个文件拖拽到本页面的表格中。",
        "dragAndDrop": "拖放"
      },
      {
        "full": "若希望从对话框选择文件，请确保文件名与表格中的名称一致，然后{clickHere}。",
        "clickHere": "点击这里以选择"
      }
    ]
  },
  "zh-Hant": {
    "title": "上傳檔案",
    "introduction": [
      {
        "full": "若要上傳檔案，您可以將一個或多個檔案{dragAndDrop}到此頁面的表格中。",
        "dragAndDrop": "拖放"
      },
      {
        "full": "如果您想從提示中選擇檔案，請確保名稱與表中的名稱相同，然後{clickHere}。",
        "clickHere": "點這裡進行選擇"
      }
    ]
  }
}
</i18n>
