<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="form-delete" :state="state" :hideable="!awaitingResponse" backdrop
    @hide="$emit('hide')">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="modal-introduction">
        <i18n-t tag="p" keypath="introduction[0]">
          <template #name>
            <strong>{{ form.nameOrId }}</strong>
          </template>
        </i18n-t>
        <p>{{ $t('introduction[1]') }}</p>
        <p v-if="form.dataExists && form.entityRelated">
          {{ $t('noDeleteEntities') }}
        </p>
      </div>
      <div class="modal-actions">
        <button type="button" class="btn btn-link" :aria-disabled="awaitingResponse"
          @click="$emit('hide')">
          {{ $t('action.noCancel') }}
        </button>
        <button type="button" class="btn btn-danger"
          :aria-disabled="awaitingResponse" @click="del">
          {{ $t('action.yesProceed') }} <spinner :state="awaitingResponse"/>
        </button>
      </div>
    </template>
  </modal>
</template>

<script>
import Modal from '../modal.vue';
import Spinner from '../spinner.vue';

import useRequest from '../../composables/request';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';
import { useRequestData } from '../../request-data';

export default {
  name: 'FormDelete',
  components: { Modal, Spinner },
  props: {
    state: {
      type: Boolean,
      default: false
    }
  },
  emits: ['hide', 'success'],
  setup() {
    // The component does not assume that this data will exist when the
    // component is created.
    const { project, form } = useRequestData();
    const { request, awaitingResponse } = useRequest();
    return { project, form, request, awaitingResponse };
  },
  methods: {
    del() {
      this.request({
        method: 'DELETE',
        url: apiPaths.form(this.form.projectId, this.form.xmlFormId)
      })
        .then(() => {
          this.project.forms -= 1;
          // project.lastSubmission may now be out-of-date. However,
          // project.lastSubmission is not used within ProjectShow.

          this.$emit('success');
        })
        .catch(noop);
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up.
    "title": "Delete Form",
    "introduction": [
      "Are you sure you want to delete the Form {name} and all of its Submissions?",
      "This action will move the Form to the Trash. After 30 days in the Trash, it will be permanently purged, but it can be restored before then."
    ],
    "noDeleteEntities": "Any Entities created by this Form’s Submissions will not be deleted. In a future version of Central, it will be possible to delete Entities."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Odstranit formulář",
    "introduction": [
      "Opravdu chcete odstranit formulář {name} a všechny jeho odeslání?"
    ],
    "noDeleteEntities": "Subjekty vytvořené na základě podání tohoto formuláře nebudou vymazány. V některé z budoucích verzí Centralu bude možné Entity odstranit."
  },
  "de": {
    "title": "Formulare löschen",
    "introduction": [
      "Sind Sie sicher, dass Sie das Formular {name} und alle dazugehörigen Übermittlungen löschen wollen?",
      "Diese Aktion verschiebt das Formular in den Papierkorb. Nach 30 Tagen im Papierkorb wird es dauerhaft gelöscht, kann aber vorher wiederhergestellt werden."
    ],
    "noDeleteEntities": "Alle durch die Einreichungen dieses Formulars erstellten Objekte werden nicht gelöscht. In einer zukünftigen Version von Central wird es möglich sein, Objekte zu löschen."
  },
  "es": {
    "title": "Borrar formulario",
    "introduction": [
      "¿Está seguro que desea eliminar el formulario {name} y todos sus envíos?",
      "Esta acción moverá el Formulario a la Papelera. Después de 30 días en la Papelera, se eliminará de forma permanente, pero se puede restablecer antes de esa fecha."
    ],
    "noDeleteEntities": "No se eliminará ninguna entidad creada por los envíos de este formulario. En una versión futura de Central, será posible eliminar Entidades."
  },
  "fr": {
    "title": "Supprimer le formulaire",
    "introduction": [
      "Êtes vous sûr de vouloir supprimer le formulaire {name} et toutes les données soumises ?",
      "Cette action va envoyer le formulaire à la corbeille. Après 30 jours dans la Corbeille, il sera purgé de manière permanente, mais il peut être restauré avant ce délai."
    ],
    "noDeleteEntities": "Chaque entité crée par cette Soumission de formulaire ne sera pas supprimée. Dans une version future, il sera possible de supprimer des Entités."
  },
  "id": {
    "title": "Hapus Formulir",
    "introduction": [
      "Apakah Anda yakin ingin menghapus Formulir {name} dan semua kiriman data di dalamnya?"
    ]
  },
  "it": {
    "title": "Cancellare il formulario",
    "introduction": [
      "Sei sicuro di voler eliminare il formulario {name} e tutti i suoi invii?",
      "Questa azione sposterà il formulario nel Cestino. Dopo 30 giorni nel Cestino, verrà eliminato definitivamente, ma prima di allora può essere ripristinato."
    ],
    "noDeleteEntities": "Qualsiasi entità creata dagli invii di questo formulario non verrà eliminata. In una versione futura di Central, sarà possibile eliminare Entità."
  },
  "ja": {
    "title": "フォームの削除",
    "introduction": [
      "フォーム{name}および、その提出済フォームが削除されます。 本当に削除してもよろしいですか？"
    ]
  },
  "pt": {
    "title": "Excluir formulário",
    "introduction": [
      "Você tem certeza que deseja excluir o formulário {name} e todas as suas respostas?"
    ],
    "noDeleteEntities": "Nenhuma Entidade criada pelas Respostas deste Formulário será excluída. Em uma versão futura do Central, será possível excluir Entidades."
  },
  "sw": {
    "title": "Futa Fomu",
    "introduction": [
      "Je, una uhakika ungependa kufuta Fomu ya {name} na Mawasilisho yake yote?"
    ],
    "noDeleteEntities": "Huluki zozote zilizoundwa na Mawasilisho ya Fomu hii hazitafutwa. Katika toleo la baadaye la Kati, itawezekana kufuta Huluki."
  },
  "zh": {
    "title": "删除表单",
    "introduction": [
      "您确定要删除表单{name}以及它的所有提交内容吗？",
      "此操作将把表单移至回收站。表单在回收站保留30天后将被永久清除，但在此之前可以随时恢复。"
    ],
    "noDeleteEntities": "通过本表单提交所创建的任何实体均不会被删除。在今后的Central版本中，将支持实体删除功能。"
  },
  "zh-Hant": {
    "title": "刪除表單",
    "introduction": [
      "您確定要刪除表單{name}及其所有提交內容嗎？",
      "此動作會將表單移至垃圾桶。在垃圾桶中存放 30 天後，該表格將被永久清除，但在此之前可以還原。"
    ],
    "noDeleteEntities": "透過此表單提交建立的任何實體都不會被刪除。在 Central 的未來版本中，將可以刪除實體。"
  }
}
</i18n>
