<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="form-list">
    <form-table :sort-func="sortFunc"/>
    <form-table :sort-func="sortFunc" :show-closed="true"/>
    <loading :state="forms.initiallyLoading"/>
    <p v-if="forms.dataExists && forms.length === 0"
      class="empty-table-message">
      {{ $t('emptyTable') }}
    </p>
  </div>
</template>

<script>
import FormTable from './table.vue';
import Loading from '../loading.vue';

import { useRequestData } from '../../request-data';

export default {
  name: 'FormList',
  components: { FormTable, Loading },
  props: {
    sortFunc: {
      type: Function,
      required: true
    }
  },
  setup() {
    // The component does not assume that this data will exist when the
    // component is created.
    const { forms } = useRequestData();
    return { forms };
  }
};
</script>

<style lang="scss">
#form-list {
  margin-bottom: 35px;

  .empty-table-message{
    margin-top: 20px;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "emptyTable": "There are no Forms to show."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "emptyTable": "Nejsou k dispozici žádné formuláře."
  },
  "de": {
    "emptyTable": "Keine Formulare zum Anzeigen vorhanden."
  },
  "es": {
    "emptyTable": "No hay formularios para mostrar."
  },
  "fr": {
    "emptyTable": "Il n'y a pas de formulaire à montrer."
  },
  "id": {
    "emptyTable": "Tidak ada formulir untuk ditampilkan."
  },
  "it": {
    "emptyTable": "Non ci sono formulari da mostrare."
  },
  "ja": {
    "emptyTable": "表示できるフォームはありません。"
  },
  "pt": {
    "emptyTable": "Não há formulários para exibir."
  },
  "sw": {
    "emptyTable": "hakuna Fomu za kuonyesha"
  },
  "zh": {
    "emptyTable": "暂无表单可显示。"
  },
  "zh-Hant": {
    "emptyTable": "沒有可顯示的表單。"
  }
}
</i18n>
