<template>
  <div id="form-new">
    <page-section>
      <template #heading>
        <span>{{ $t('title') }}</span>
      </template>
      <template #body>
        <form-upload @success="afterCreate"/>
      </template>
    </page-section>
  </div>
</template>

<script setup>
import { inject } from 'vue';
import { useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';

import { useRequestData } from '../../request-data';

import PageSection from '../page/section.vue';
import FormUpload from './upload.vue';
import useRoutes from '../../composables/routes';

defineOptions({
  name: 'FormNewPage'
});

const router = useRouter();
const { t } = useI18n();
const { formPath } = useRoutes();
const alert = inject('alert');
const { project } = useRequestData();

const afterCreate = async (form) => {
  const message = t('alert.create', {
    name: form.name != null ? form.name : form.xmlFormId
  });
  project.forms += 1;
  await router.push(formPath(form.projectId, form.xmlFormId, 'draft'));
  alert.success(message);
};

</script>

<i18n lang="json5">
{
  "en": {
    // @transifexKey component.FormNew.title.create
    // This is the title at the top of a page.
    "title": "Create Form",
    "alert": {
      // @transifexKey component.FormList.alert.create
      "create": "“{name}” has been created as a Form Draft."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Vytvořit formulář"
  },
  "de": {
    "title": "Formular erstellen",
    "alert": {
      "create": "\"{name}\" wurde als Formularentwurf erzeugt."
    }
  },
  "es": {
    "title": "Crear formulario",
    "alert": {
      "create": "\"{name}\" se ha creado como borrador de formulario."
    }
  },
  "fr": {
    "title": "Créer un formulaire",
    "alert": {
      "create": "\"{name}\" a été créé comme ébauche."
    }
  },
  "id": {
    "title": "Buat Formulir"
  },
  "it": {
    "title": "Creare un formulario",
    "alert": {
      "create": "“{name}” è stato creato come bozza di formulario."
    }
  },
  "ja": {
    "title": "フォームの作成"
  },
  "pt": {
    "title": "Criar formulário"
  },
  "sw": {
    "title": "unda fomu"
  },
  "zh": {
    "title": "创建表单",
    "alert": {
      "create": "表单草稿“{name}”已创建。"
    }
  },
  "zh-Hant": {
    "title": "建立表單",
    "alert": {
      "create": "「{name}」已建立為表單草稿。"
    }
  }
}
</i18n>
