<!--
Copyright 2022 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="form-sort">
    <form class="form-inline" @submit.prevent>
      <label class="form-group">
        <span id="form-sort-label">{{ $t('action.sort') }}</span>
        <select :value="modelValue" class="form-control"
          @change="$emit('update:modelValue', $event.target.value)">
          <option value="alphabetical">{{ $t('sortOptions.alphabetical') }}</option>
          <option value="latest">{{ $t('header.lastSubmission') }}</option>
          <option value="newest">{{ $t('sortOptions.newest') }}</option>
        </select>
      </label>
    </form>
  </div>
</template>

<script setup>
defineOptions({
  name: 'FormSort'
});
defineProps({
  modelValue: {
    type: String,
    required: true
  }
});
defineEmits(['update:modelValue']);
</script>

<style lang="scss">
#form-sort {
  float: right;

  #form-sort-label {
    font-size: 14px;
    padding-right: 8px;
    vertical-align: middle;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    // This text is shown as one option in a dropdown menu for choosing how to sort a list of Forms.
    "sortOptions": {
      "alphabetical": "Alphabetical",
      "newest": "Newest"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "sortOptions": {
      "alphabetical": "Abecední",
      "newest": "Nejnovější"
    }
  },
  "de": {
    "sortOptions": {
      "alphabetical": "Alphabetisch",
      "newest": "Neueste"
    }
  },
  "es": {
    "sortOptions": {
      "alphabetical": "Alfabético",
      "newest": "El mas nuevo"
    }
  },
  "fr": {
    "sortOptions": {
      "alphabetical": "Alphabétique",
      "newest": "Plus récent"
    }
  },
  "id": {
    "sortOptions": {
      "newest": "Terbaru"
    }
  },
  "it": {
    "sortOptions": {
      "alphabetical": "Alfabetico",
      "newest": "Il più nuovo"
    }
  },
  "pt": {
    "sortOptions": {
      "alphabetical": "Em ordem alfabética",
      "newest": "Mais recentes"
    }
  },
  "sw": {
    "sortOptions": {
      "alphabetical": "Kialfabeti",
      "newest": "Mpya zaidi"
    }
  },
  "zh": {
    "sortOptions": {
      "alphabetical": "按字母顺序",
      "newest": "最新优先"
    }
  },
  "zh-Hant": {
    "sortOptions": {
      "alphabetical": "按字母順序",
      "newest": "新表單優先"
    }
  }
}
</i18n>
