<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal :state="state" :hideable="!form.awaitingResponse" backdrop
  @hide="$emit('hide')">
    <template v-if="webformsEnabled" #title>ODK Web Forms</template>
    <template v-else #title>Enketo</template>

    <template v-if="webformsEnabled" #body>
      <p>
        {{ $t('webformsConfirmation.description') }}
      </p>
      <div class="modal-actions">
        <button class="btn btn-link" type="button" @click="$emit('hide')">
          {{ $t('action.cancel') }}
        </button>
        <button type="button" class="btn btn-primary"
          :aria-disabled="form.awaitingResponse" @click="setWebformsEnabled">
          {{ $t('webformsConfirmation.useOdkWebForms') }} <spinner :state="form.awaitingResponse"/>
        </button>
      </div>
    </template>
    <template v-else #body>
      <p>
        {{ $t('enketoConfirmation.description') }}
      </p>
      <div class="modal-actions">
        <button class="btn btn-link" type="button"
          :aria-disabled="form.awaitingResponse" @click="$emit('hide')">
          {{ $t('action.cancel') }}
        </button>
        <button type="button" class="btn btn-primary"
          :aria-disabled="form.awaitingResponse" @click="setWebformsEnabled">
          {{ $t('enketoConfirmation.useEnketo') }} <spinner :state="form.awaitingResponse"/>
        </button>
      </div>
    </template>
  </modal>
</template>

<script setup>
import Modal from '../modal.vue';
import Spinner from '../spinner.vue';

import { useRequestData } from '../../request-data';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';

const { form } = useRequestData();

defineOptions({
  name: 'FormWebFormsSettingsConfirmation'
});

const props = defineProps({
  state: Boolean,
  webformsEnabled: Boolean
});

const emit = defineEmits(['hide', 'success']);

const setWebformsEnabled = () => {
  form.request({
    method: 'PATCH',
    url: apiPaths.form(form.projectId, form.xmlFormId),
    data: { webformsEnabled: props.webformsEnabled },
    patch: ({ data }) => {
      form.updatedAt = data.updatedAt;
      form.webformsEnabled = data.webformsEnabled;
    }
  })
    .then(() => {
      emit('success');
    })
    .catch(noop);
};
</script>

<i18n lang="json5">
  {
    "en": {
      "webformsConfirmation": {
        // The words "ODK Web Forms" and "Enketo" should not be translated
        "description": "Are you sure you want to switch from Enketo to ODK Web Forms?",
        // The words "ODK Web Forms" should not be translated
        "useOdkWebForms": "Use ODK Web Forms"
      },
      "enketoConfirmation": {
        // The words "Enketo" and "ODK Web Forms" should not be translated
        "description": "Are you sure you want to switch from ODK Web Forms to Enketo?",
        // The word "Enketo" should not be translated
        "useEnketo": "Use Enketo"
      }
    }
  }
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "webformsConfirmation": {
      "useOdkWebForms": "ODK Web-Formulare verwenden"
    },
    "enketoConfirmation": {
      "description": "Sind Sie sicher, dass Sie von ODK Web-Formulare zu Enketo wechseln wollen?",
      "useEnketo": "Enketo verwenden"
    }
  },
  "es": {
    "webformsConfirmation": {
      "useOdkWebForms": "Utilizar Formularios web ODK"
    },
    "enketoConfirmation": {
      "description": "¿Está seguro de que desea cambiar de ODK Web Forms a Enketo?",
      "useEnketo": "Utilice Enketo"
    }
  },
  "fr": {
    "webformsConfirmation": {
      "description": "Êtes-vous sûr de vouloir passer de Enketo à ODK Web Forms?",
      "useOdkWebForms": "Utiliser les Web Forms d'ODK"
    },
    "enketoConfirmation": {
      "description": "Êtes vous sûr de vouloir passer d'ODK Web Forms à Enketo ?",
      "useEnketo": "Utiliser Enketo"
    }
  },
  "it": {
    "webformsConfirmation": {
      "useOdkWebForms": "Utilizza ODK Web Forms"
    },
    "enketoConfirmation": {
      "description": "Siete sicuri di voler passare da ODK Web Forms a Enketo?",
      "useEnketo": "Usa Enketo"
    }
  },
  "pt": {
    "webformsConfirmation": {
      "useOdkWebForms": "Utilizar ODK Web Forms"
    },
    "enketoConfirmation": {
      "description": "Você tem certeza que deseja mudar do ODK Web Forms para o Enketo?",
      "useEnketo": "Utilizar o Enketo"
    }
  },
  "zh": {
    "webformsConfirmation": {
      "useOdkWebForms": "使用 ODK Web Forms"
    },
    "enketoConfirmation": {
      "description": "确定要从ODK Web表单切换至Enketo吗？",
      "useEnketo": "使用Enketo"
    }
  },
  "zh-Hant": {
    "webformsConfirmation": {
      "useOdkWebForms": "使用 ODK Web Forms"
    },
    "enketoConfirmation": {
      "description": "您確定要從 ODK Web Forms 轉換到 Enketo？",
      "useEnketo": "使用 Enketo"
    }
  }
}
</i18n>
