<template>
  <div id="config-login">
    <page-heading :title="$t('title')"/>
    <loading :state="serverConfig.awaitingResponse"/>
    <div v-if="serverConfig.dataExists" class="row">
      <div class="col-xs-5">
        <config-login-edit/>
      </div>
      <div class="col-xs-6 col-xs-offset-1">
        <config-login-preview/>
      </div>
    </div>
  </div>
</template>

<script setup>
import ConfigLoginEdit from './login/edit.vue';
import ConfigLoginPreview from './login/preview.vue';
import Loading from '../loading.vue';
import PageHeading from '../page/heading.vue';

import { noop } from '../../util/util';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'ConfigLogin'
});

const { serverConfig } = useRequestData();

serverConfig.request({ url: '/v1/config/public' }).catch(noop);
</script>


<i18n lang="json5">
{
  "en": {
    "title": "Login page customization"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "title": "Anmeldeseite"
  },
  "es": {
    "title": "Página de inicio de sesión"
  },
  "fr": {
    "title": "Page de connexion"
  },
  "it": {
    "title": "Pagina di Login"
  },
  "zh": {
    "title": "登录页面"
  }
}
</i18n>
