<!--
Copyright 2022 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <page-section id="home-news" horizontal>
    <template #heading>
      <span>{{ $t('title') }}</span>
    </template>
    <template #body>
      <iframe src="https://getodk.github.io/central/news.html" :title="$t('title')"></iframe>
    </template>
  </page-section>
</template>

<script>
import PageSection from '../page/section.vue';

export default {
  name: 'HomeNews',
  components: { PageSection }
};
</script>

<style lang="scss">
#home-news {
  margin-bottom: 25px;

  iframe {
    border-width: 0;
    height: 40px;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    // This is a title shown above a section of the page.
    "title": "News"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Novinky"
  },
  "de": {
    "title": "Neuigkeiten"
  },
  "es": {
    "title": "Novedades"
  },
  "fr": {
    "title": "Nouvelles"
  },
  "it": {
    "title": "Novità"
  }
}
</i18n>
