<!--
Copyright 2022 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="home-summary-container">
    <div id="home-summary">
      <home-summary-item icon="archive">
        <template #header>
          <template v-if="!projects.initiallyLoading">
            {{ $n(projects.length, 'default') }}
          </template>
          <template v-else>
            <spinner inline/>
          </template>
        </template>
        <template #subheader>{{ $tc('plural.project', projects.length) }}</template>
        <template #body>{{ $t('projects.body') }}</template>
      </home-summary-item>
      <home-summary-item v-if="currentUser.can('user.list')" to="/users" icon="user-circle">
        <template #header>
          <template v-if="!users.initiallyLoading">
            {{ $n(users.length, 'default') }}
          </template>
          <template v-else>
            <spinner inline/>
          </template>
        </template>
        <template #subheader>{{ $tc('plural.user', users.length) }}</template>
        <template #body>{{ $t('users.body') }}</template>
      </home-summary-item>
      <home-summary-item to="https://docs.getodk.org/central-intro/"
        icon="book">
        <template #header>{{ $t('common.docs') }}</template>
        <template #body>{{ $t('docs.body') }}</template>
      </home-summary-item>
      <home-summary-item to="https://forum.getodk.org/" icon="comments-o">
        <template #header>{{ $t('common.forum') }}</template>
        <template #body>{{ $t('forum.body') }}</template>
      </home-summary-item>
    </div>
  </div>
</template>

<script setup>
import HomeSummaryItem from './summary/item.vue';
import Spinner from '../spinner.vue';

import { noop } from '../../util/util';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'HomeSummary'
});

const { currentUser, projects, createResource } = useRequestData();
const users = createResource('users');
if (currentUser.can('user.list'))
  users.request({ url: '/v1/users' }).catch(noop);
</script>

<style lang="scss">
@use 'sass:math';
@import '../../assets/scss/variables';

#home-summary-container {
  background-color: $color-subpanel-background;
  margin-left: -15px;
  margin-right: -15px;
  padding: 20px;
}

#home-summary {
  display: flex;
  gap: 20px;
  margin-left: auto;
  margin-right: auto;
  max-width: $max-width-page-body;
}
</style>

<i18n lang="json5">
{
  "en": {
    "projects": {
      "body": "Central is organized into Projects, each containing its own Forms and related data."
    },
    "users": {
      "body": "Users can be assigned to Projects to manage them, collect data, or review submissions."
    },
    "docs": {
      "body": "A Getting Started Guide and user documentation are available on the ODK Docs website."
    },
    "forum": {
      "body": "Need help? Visit the forum to ask questions or browse past discussions."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "projects": {
      "body": "Central je organizován do Projektů, které obsahují vlastní Formuláře a související data."
    },
    "users": {
      "body": "Uživatelé mohou být přiřazeni k projektům, aby je mohli spravovat nebo shromažďovat či kontrolovat předložená data."
    },
    "docs": {
      "body": "Na webových stránkách ODK Docs je k dispozici úvodní příručka a uživatelská dokumentace."
    },
    "forum": {
      "body": "Vždy můžete získat pomoc od ostatních na fóru, kde můžete také vyhledávat předchozí dotazy."
    }
  },
  "de": {
    "projects": {
      "body": "Central ist in Projekte organisiert, die jeweils ihre eigenen Formulare und zugehörigen Daten enthalten."
    },
    "users": {
      "body": "Benutzer können Projekten zugewiesen werden, um sie zu verwalten oder eingereichte Daten zu sammeln oder zu überprüfen."
    },
    "docs": {
      "body": "Es gibt ein Erste-Schritte-Tutorial und die Benutzerdokumentation auf der ODK Docs Webseite."
    },
    "forum": {
      "body": "Sie können im Forum immer Hilfe von anderen erhalten. Dort können Sie auch nach Antworten auf ähnliche Fragen suchen."
    }
  },
  "es": {
    "projects": {
      "body": "Central está organizado en Proyectos, cada uno de los cuales contiene sus propios Formularios y datos relacionados."
    },
    "users": {
      "body": "Los usuarios pueden asignarse a Proyectos para administrarlos o para recopilar o revisar los datos enviados."
    },
    "docs": {
      "body": "Hay una guía de inicio y documentación del usuario disponibles en el sitio web de ODK Docs."
    },
    "forum": {
      "body": "Siempre puede obtener ayuda de otros en el foro, donde también puede buscar preguntas previas."
    }
  },
  "fr": {
    "projects": {
      "body": "Central est organisé en projets, chacun contenant ses propres formulaires et données associées."
    },
    "users": {
      "body": "Les utilisateurs peuvent être assignés à des projets pour les gérer, ou pour collecter ou réviser les données soumises."
    },
    "docs": {
      "body": "Un guide de démarrage et la documentation utilisateur sont disponibles sur le site internet d'ODK."
    },
    "forum": {
      "body": "Vous pouvez toujours obtenir l'aide d'autres utilisateurs sur le forum, où vous pouvez aussi chercher les questions précédentes."
    }
  },
  "it": {
    "projects": {
      "body": "Central è organizzato in Progetti, ognuno dei quali contiene i propri Formulari e i relativi dati."
    },
    "users": {
      "body": "Gli utenti possono essere assegnati ai progetti per gestirli o per raccogliere o rivedere i dati inviati."
    },
    "docs": {
      "body": "Sul sito Web di ODK Docs sono disponibili una guida introduttiva e una documentazione per l'utente."
    },
    "forum": {
      "body": "Puoi sempre ottenere aiuto dagli altri sul forum, dove puoi anche cercare domande precedenti."
    }
  },
  "pt": {
    "projects": {
      "body": "O Central é organizado em Projetos, cada um contendo seus próprios Formulários e dados relacionados."
    },
    "users": {
      "body": "Usuários podem ser associados a Projetos para gerenciá-los ou para coletar ou revisar dados enviados."
    },
    "docs": {
      "body": "Há um guia de iniciação e uma documentação de usuário disponíveis no website ODK Docs."
    },
    "forum": {
      "body": "Você sempre pode obter ajuda de outras pessoas no fórum, onde também pode pesquisar perguntas anteriores."
    }
  },
  "sw": {
    "projects": {
      "body": "Central imepangwa katika Miradi, ambayo kila moja ina Fomu zake na data zinazohusiana."
    },
    "users": {
      "body": "Watumiaji wanaweza kupewa Miradi ili kuisimamia, au kukusanya au kukagua data iliyowasilishwa."
    },
    "docs": {
      "body": "Kuna mwongozo wa kuanza na hati za mtumiaji zinazopatikana kwenye tovuti ya Hati za ODK."
    },
    "forum": {
      "body": "Unaweza kupata usaidizi kutoka kwa wengine kila wakati kwenye mijadala, ambapo unaweza pia kutafuta maswali yaliyotangulia."
    }
  },
  "zh-Hant": {
    "projects": {
      "body": "Central 以專案為單位組織，每個專案包含其表單與相關數據。"
    },
    "users": {
      "body": "可以將使用者指派到專案來管理它們，或收集或審查提交的資料。"
    },
    "docs": {
      "body": "ODK 文件網站上提供了入門指南和使用者文件。"
    },
    "forum": {
      "body": "您始終可在論壇上獲得其他人的幫助，您也可以在其中搜尋先前的問題。"
    }
  }
}
</i18n>
