<!--
Copyright 2022 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="home-summary">
    <div>
      <loading :state="projects.initiallyLoading"/>
      <home-summary-item v-if="projects.dataExists" icon="archive"
        :count="projects.length">
        <template #title>{{ $tc('plural.project', projects.length) }}</template>
        <template #body>{{ $t('projects.body') }}</template>
      </home-summary-item>
    </div>
    <div v-if="currentUser.can('user.list')">
      <loading :state="users.initiallyLoading"/>
      <home-summary-item v-if="users.dataExists" to="/users" icon="user-circle"
        :count="users.length">
        <template #title>{{ $tc('plural.user', users.length) }}</template>
        <template #body>{{ $t('users.body') }}</template>
      </home-summary-item>
    </div>
    <div>
      <home-summary-item to="https://docs.getodk.org/central-intro/"
        icon="book">
        <template #title>{{ $t('common.docs') }}</template>
        <template #body>{{ $t('docs.body') }}</template>
      </home-summary-item>
    </div>
    <div>
      <home-summary-item to="https://forum.getodk.org/" icon="comments-o">
        <template #title>{{ $t('common.forum') }}</template>
        <template #body>{{ $t('forum.body') }}</template>
      </home-summary-item>
    </div>
  </div>
</template>

<script>
export default {
  name: 'HomeSummary'
};
</script>
<script setup>
import HomeSummaryItem from './summary/item.vue';
import Loading from '../loading.vue';

import { noop } from '../../util/util';
import { useRequestData } from '../../request-data';

const { currentUser, projects, createResource } = useRequestData();
const users = createResource('users');
if (currentUser.can('user.list'))
  users.request({ url: '/v1/users' }).catch(noop);
</script>

<style lang="scss">
@use 'sass:math';
@import '../../assets/scss/variables';

#home-summary {
  background: $color-subpanel-background;
  border-bottom: 2px solid $color-subpanel-border;
  display: flex;
  margin: 0 -15px 35px;
  padding-bottom: 20px;
  padding-left: 15px;
  padding-right: 15px;

  > div {
    $border-width: 1px;
    $padding-left: 20px;
    $padding-right: 12px;
    border-left: $border-width solid $color-subpanel-border;
    box-sizing: content-box;
    padding-bottom: 3px;
    padding-left: $padding-left;
    padding-right: $padding-right;
    // width(#home-summary) = 4 * width(#home-summary > div) + 3 * $padding-right + 3 * $border-width + 3 * $padding-left
    width: calc(25% - #{math.ceil(math.div(3 * $padding-right + 3 * $border-width + 3 * $padding-left, 4))});

    &:first-child {
      border-left: none;
      padding-left: 0;
    }
    &:last-child { padding-right: 0; }
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "projects": {
      "body": "Central is organized into Projects, which each contain their own Forms and related data."
    },
    "users": {
      "body": "Users can be assigned to Projects to manage them, or to collect or review submitted data."
    },
    "docs": {
      "body": "There is a getting started guide and user documentation available on the ODK Docs website."
    },
    "forum": {
      "body": "You can always get help from others on the forum, where you can also search previous questions."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "projects": {
      "body": "Central je organizován do Projektů, které obsahují vlastní Formuláře a související data."
    },
    "users": {
      "body": "Uživatelé mohou být přiřazeni k projektům, aby je mohli spravovat nebo shromažďovat či kontrolovat předložená data."
    },
    "docs": {
      "body": "Na webových stránkách ODK Docs je k dispozici úvodní příručka a uživatelská dokumentace."
    },
    "forum": {
      "body": "Vždy můžete získat pomoc od ostatních na fóru, kde můžete také vyhledávat předchozí dotazy."
    }
  },
  "de": {
    "projects": {
      "body": "Central ist in Projekte organisiert, die jeweils ihre eigenen Formulare und zugehörigen Daten enthalten."
    },
    "users": {
      "body": "Benutzer können Projekten zugewiesen werden, um sie zu verwalten oder eingereichte Daten zu sammeln oder zu überprüfen."
    },
    "docs": {
      "body": "Es gibt ein Erste-Schritte-Tutorial und die Benutzerdokumentation auf der ODK Docs Webseite."
    },
    "forum": {
      "body": "Sie können im Forum immer Hilfe von anderen erhalten. Dort können Sie auch nach Antworten auf ähnliche Fragen suchen."
    }
  },
  "es": {
    "projects": {
      "body": "Central está organizado en Proyectos, cada uno de los cuales contiene sus propios Formularios y datos relacionados."
    },
    "users": {
      "body": "Los usuarios pueden asignarse a Proyectos para administrarlos o para recopilar o revisar los datos enviados."
    },
    "docs": {
      "body": "Hay una guía de inicio y documentación del usuario disponibles en el sitio web de ODK Docs."
    },
    "forum": {
      "body": "Siempre puede obtener ayuda de otros en el foro, donde también puede buscar preguntas previas."
    }
  },
  "fr": {
    "projects": {
      "body": "Central est organisé en projets, chacun contenant ses propres formulaires et données associées."
    },
    "users": {
      "body": "Les utilisateurs peuvent être assignés à des projets pour les gérer, ou pour collecter ou réviser les données soumises."
    },
    "docs": {
      "body": "Un guide de démarrage et la documentation utilisateur sont disponibles sur le site internet d'ODK."
    },
    "forum": {
      "body": "Vous pouvez toujours obtenir l'aide d'autres utilisateurs sur le forum, où vous pouvez aussi chercher les questions précédentes."
    }
  },
  "it": {
    "projects": {
      "body": "Central è organizzato in Progetti, ognuno dei quali contiene i propri Formulari e i relativi dati."
    },
    "users": {
      "body": "Gli utenti possono essere assegnati ai progetti per gestirli o per raccogliere o rivedere i dati inviati."
    },
    "docs": {
      "body": "Sul sito Web di ODK Docs sono disponibili una guida introduttiva e una documentazione per l'utente."
    },
    "forum": {
      "body": "Puoi sempre ottenere aiuto dagli altri sul forum, dove puoi anche cercare domande precedenti."
    }
  }
}
</i18n>
