<!--
Copyright 2022 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="home-summary-container">
    <div id="home-summary">
      <home-summary-item icon="archive">
        <template #header>
          <template v-if="!projects.initiallyLoading">
            {{ $n(projects.length, 'default') }}
          </template>
          <template v-else>
            <spinner inline/>
          </template>
        </template>
        <template #subheader>{{ $tc('plural.project', projects.length ?? 0) }}</template>
        <template #body>{{ $t('projects.body') }}</template>
      </home-summary-item>
      <home-summary-item v-if="currentUser.can('user.list')" to="/users" icon="user-circle">
        <template #header>
          <template v-if="!users.initiallyLoading">
            {{ $n(users.length, 'default') }}
          </template>
          <template v-else>
            <spinner inline/>
          </template>
        </template>
        <template #subheader>{{ $tc('plural.user', users.length ?? 0) }}</template>
        <template #body>{{ $t('users.body') }}</template>
      </home-summary-item>
      <home-summary-item to="https://docs.getodk.org/central-intro/"
        icon="book">
        <template #header>{{ $t('common.docs') }}</template>
        <template #body>{{ $t('docs.body') }}</template>
      </home-summary-item>
      <home-summary-item to="https://forum.getodk.org/" icon="comments-o">
        <template #header>{{ $t('common.forum') }}</template>
        <template #body>{{ $t('forum.body') }}</template>
      </home-summary-item>
    </div>
  </div>
</template>

<script setup>
import HomeSummaryItem from './summary/item.vue';
import Spinner from '../spinner.vue';

import { noop } from '../../util/util';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'HomeSummary'
});

const { currentUser, projects, createResource } = useRequestData();
const users = createResource('users');
if (currentUser.can('user.list'))
  users.request({ url: '/v1/users' }).catch(noop);
</script>

<style lang="scss">
@use 'sass:math';
@import '../../assets/scss/variables';

#home-summary-container {
  background-color: $color-subpanel-background;
  margin-left: -15px;
  margin-right: -15px;
  padding: 20px;
}

#home-summary {
  display: flex;
  flex-wrap: wrap;
  gap: 20px;

  @media (max-width: $screen-sm-min) {
    > * {
      flex: 1 1 calc(50% - 20px);
    }
  }
  margin-left: auto;
  margin-right: auto;
  max-width: $max-width-page-body;
}
</style>

<i18n lang="json5">
{
  "en": {
    "projects": {
      "body": "Central is organized into Projects, each containing its own Forms and related data."
    },
    "users": {
      "body": "Users can be assigned to Projects to manage them, collect data, or review Submissions."
    },
    "docs": {
      "body": "A Getting Started Guide and user documentation are available on the ODK Docs website."
    },
    "forum": {
      "body": "Need help? Visit the forum to ask questions or browse past discussions."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "projects": {
      "body": "Central ist in Projekte organisiert, die jeweils ihre eigenen Formulare und zugehörigen Daten enthalten."
    },
    "users": {
      "body": "Benutzer können Projekten zugewiesen werden, um sie zu verwalten oder eingereichte Daten zu sammeln oder Übermittlungen zu überprüfen."
    },
    "docs": {
      "body": "Es gibt ein Erste-Schritte-Tutorial und die Benutzerdokumentation auf der ODK Docs Webseite."
    },
    "forum": {
      "body": "Brauchen Sie Hilfe? Besuchen Sie das Forum, um Fragen zu stellen oder frühere Diskussionen zu verfolgen."
    }
  },
  "es": {
    "projects": {
      "body": "Central está organizada en Proyectos, cada uno de los cuales contiene sus propios Formularios y datos relacionados."
    },
    "users": {
      "body": "Los usuarios pueden asignarse a Proyectos para administrarlos o para recopilar o revisar los datos enviados."
    },
    "docs": {
      "body": "Hay una guía de inicio y documentación del usuario disponibles en el sitio web de ODK Docs."
    },
    "forum": {
      "body": "¿Necesita ayuda? Visite el foro para hacer preguntas o consultar debates anteriores."
    }
  },
  "fr": {
    "projects": {
      "body": "Central est organisé en Projets, ayant chacun ses propres formulaires et les données associées."
    },
    "users": {
      "body": "Les utilisateurs peuvent être assignés à des Projets pour les gérer, collecter des données ou passer en revue les soumissions."
    },
    "docs": {
      "body": "Un Guide de Démarrage et une documentation utilisateur sont disponibles sur le site web ODK Docs."
    },
    "forum": {
      "body": "Besoin d'aide ? Visitez le forum pour poser des questions ou parcourir les anciennes discussions."
    }
  },
  "it": {
    "projects": {
      "body": "Central è organizzato in Progetti, ognuno dei quali contiene i propri Formulari e i relativi dati."
    },
    "users": {
      "body": "Gli utenti possono essere assegnati ai progetti per gestirli, per raccogliere o rivedere i dati inviati."
    },
    "docs": {
      "body": "Sul sito Web di ODK Docs sono disponibili una guida introduttiva e una documentazione per l'utente."
    },
    "forum": {
      "body": "Avete bisogno di aiuto? Visitate il forum per porre domande o consultare le discussioni precedenti."
    }
  },
  "pt": {
    "projects": {
      "body": "O Central é organizado em Projetos, cada um contendo seus próprios Formulários e os dados relacionados a eles."
    },
    "users": {
      "body": "Usuários podem ser atribuídos a Projetos para gerenciá-los, coletar dados ou revisar Respostas."
    },
    "docs": {
      "body": "Um Guia de Início Rápido e a documentação de usuário estão disponíveis no site ODK Docs."
    },
    "forum": {
      "body": "Precisa de ajuda? Visite o fórum para fazer perguntas ou visualizar discussões existentes."
    }
  },
  "zh": {
    "projects": {
      "body": "Central采用项目制管理，每个项目包含独立的表单及相关数据。"
    },
    "users": {
      "body": "用户可被分配至不同项目，以执行管理、数据收集或提交审核等任务。"
    },
    "docs": {
      "body": "ODK文档网站提供入门指南和用户手册。"
    },
    "forum": {
      "body": "需要帮助？欢迎访问论坛提问或浏览历史讨论。"
    }
  },
  "zh-Hant": {
    "projects": {
      "body": "Central 以專案為單位組織，每個專案包含其表單與相關數據。"
    },
    "users": {
      "body": "使用者可被指派至專案，以管理專案、收集資料或檢閱提交內容。"
    },
    "docs": {
      "body": "ODK 文件網站上提供了入門指南和使用者文件。"
    },
    "forum": {
      "body": "需要協助嗎？訪問論壇提問或瀏覽過去的討論。"
    }
  }
}
</i18n>
