<!--
Copyright 2019 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <page-section>
    <template #heading>
      <span>{{ $t('title') }}</span>
    </template>
    <template #body>
      <i18n tag="p" path="body[0].full">
        <template #accessTo>
          <router-link :to="projectPath('form-access')">{{ $t('body[0].accessTo') }}</router-link>
        </template>
      </i18n>
      <p>
        <i18n :tag="false" path="moreInfo.helpArticle.full">
          <template #helpArticle>
            <doc-link to="central-projects/">{{ $t('moreInfo.helpArticle.helpArticle') }}</doc-link>
          </template>
        </i18n>
        &nbsp;
        <i18n :tag="false" path="body[1].full">
          <template #forumThread>
            <a href="https://forum.getodk.org/t/-/19677" target="_blank">{{ $t('body[1].forumThread') }}</a>
          </template>
        </i18n>
      </p>
    </template>
  </page-section>
</template>

<script>
import DocLink from '../../doc-link.vue';
import PageSection from '../../page/section.vue';
import routes from '../../../mixins/routes';

export default {
  name: 'ProjectOverviewAbout',
  components: { DocLink, PageSection },
  mixins: [routes()]
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is a title shown above a section of the page.
    "title": "About Projects",
    "body": [
      {
        "full": "Projects let you group related Forms and Users. Web Users can be given Roles that let them perform certain actions within this Project, including using a web browser to fill out Forms. App Users for this Project can only see Forms in this Project which they have {accessTo}.",
        "accessTo": "access to"
      },
      {
        "full": "If you have any feedback, please visit {forumThread}.",
        "forumThread": "this forum thread"
      }
    ]
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "es": {
    "title": "Acerca del proyecto"
  }
}
</i18n>
