<!--
Copyright 2021 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div>
    <div class="page-body-heading">
      <p>{{ $t('analytics.alwaysImprove') }}</p>
      <i18n-t tag="p" keypath="analytics.needFeedback.full">
        <template #your>
          <span>{{ $t('analytics.needFeedback.your') }}</span>
        </template>
      </i18n-t>
      <p>{{ $t('heading[0]') }}</p>
    </div>
    <loading :state="initiallyLoading"/>
    <template v-if="dataExists">
      <analytics-form @preview="previewModal.show()"/>
      <page-section v-if="audits.length !== 0">
        <template #heading>
          <span>{{ $t('auditsTitle') }}</span>
        </template>
        <template #body>
          <audit-table/>
        </template>
      </page-section>
    </template>
    <analytics-preview v-bind="previewModal" @hide="previewModal.hide()"/>
  </div>
</template>

<script>
import AnalyticsForm from './form.vue';
import AnalyticsPreview from './preview.vue';
import AuditTable from '../audit/table.vue';
import Loading from '../loading.vue';
import PageSection from '../page/section.vue';

import { apiPaths } from '../../util/request';
import { modalData } from '../../util/reactivity';
import { useRequestData } from '../../request-data';

export default {
  name: 'AnalyticsList',
  components: {
    AnalyticsForm,
    AnalyticsPreview,
    AuditTable,
    Loading,
    PageSection
  },
  setup() {
    const { analyticsConfig, createResource, resourceStates } = useRequestData();
    const audits = createResource('audits');
    return {
      analyticsConfig, audits, ...resourceStates([analyticsConfig, audits]),
      previewModal: modalData()
    };
  },
  created() {
    this.fetchData();
  },
  methods: {
    fetchData() {
      Promise.allSettled([
        this.analyticsConfig.request({
          url: '/v1/config/analytics',
          fulfillProblem: ({ code }) => code === 404.1
        }),
        this.audits.request({
          url: apiPaths.audits({ action: 'analytics', limit: 10 })
        })
      ]);
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    "heading": [
      "Below, you can choose whether this Central server will share anonymous usage information with the Central team. This setting affects the entire server."
    ],
    // This is a title shown above a section of the page.
    "auditsTitle": "Latest Usage Reports"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "heading": [
      "Níže můžete zvolit, zda bude tento server Central sdílet anonymní informace o používání s týmem Central. Toto nastavení ovlivňuje celý server."
    ],
    "auditsTitle": "Nejnovější zprávy o použití"
  },
  "de": {
    "heading": [
      "Weiter unten kannst du auswählen, ob dieser Central-Server anonyme Nutzungsinformationen mit dem Central-Team teilen soll oder nicht. Diese Einstellung gelten für den gesamten Server."
    ],
    "auditsTitle": "Neueste Nutzungsberichte"
  },
  "es": {
    "heading": [
      "A continuación, puede elegir si este servidor Central compartirá información de uso anónima con el equipo Central. Esta configuración afecta a todo el servidor."
    ],
    "auditsTitle": "Últimos informes de uso"
  },
  "fr": {
    "heading": [
      "Ci-dessous, vous pouvez choisir si ce serveur Central partagera les informations d'utilisation anonymisées avec l'équipe de Central. Ce paramètre affecte l'ensemble du serveur."
    ],
    "auditsTitle": "Dernier rapport d'utilisation"
  },
  "it": {
    "heading": [
      "Di seguito, puoi scegliere se questo server Central condividerà le informazioni di utilizzo anonime con il team Central. Questa impostazione interessa l'intero server."
    ],
    "auditsTitle": "Ultimo rapporto di utilizzo"
  },
  "ja": {
    "heading": [
      "以下で、あなたはこのCentralサーバーがCentralチームと匿名化された利用情報を共有するかどうかを選択できます。この設定はサーバー全体の及びます。"
    ],
    "auditsTitle": "最新の利用情報"
  },
  "pt": {
    "heading": [
      "Abaixo, você pode escolher se esse servidor Central irá compartilhar informações de uso anônimas com a equipe do Central. Essa configuração afeta o servidor como um todo."
    ],
    "auditsTitle": "Relatórios de uso mais recentes"
  },
  "sw": {
    "heading": [
      "Hapo chini, unaweza kuchagua kama seva hii ya Central itashiriki maelezo ya matumizi yasiyokutambulisha na timu ya Central. Mpangilio huu unaathiri seva nzima"
    ],
    "auditsTitle": "Ripoti za Matumizi ya Hivi Punde"
  },
  "zh": {
    "heading": [
      "下方可选择是否允许本Central服务器向Central团队共享匿名使用信息。此设置将对整个服务器生效。"
    ],
    "auditsTitle": "最近的使用报告"
  },
  "zh-Hant": {
    "heading": [
      "在下方，您可以選擇此 Central 伺服器是否與 Central 團隊共用匿名使用資訊。此設定會影響整個伺服器。"
    ],
    "auditsTitle": "最新使用報告"
  }
}
</i18n>
