<!--
Copyright 2021 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <table class="table analytics-metrics-table">
    <thead>
      <tr>
        <th>{{ title }}</th>
        <th class="metric-value recent-col">{{ $t('recent') }}</th>
        <th class="metric-value">{{ $t('common.total') }}</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(value, name) in metrics" :key="name">
        <td>{{ $t(`fields.${name}`) }}</td>
        <template v-if="value.recent != null">
          <td class="metric-value">{{ $n(value.recent) }}</td>
          <td class="metric-value">{{ $n(value.total) }}</td>
        </template>
        <template v-else>
          <td colspan="2" class="metric-value">{{ $n(value) }}</td>
        </template>
      </tr>
    </tbody>
  </table>
</template>

<script>
export default {
  name: 'AnalyticsMetricsTable',
  props: {
    title: {
      type: String,
      required: true
    },
    metrics: {
      type: Object,
      required: true
    }
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

.analytics-metrics-table {
  .metric-value {
    text-align: right;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "recent": "in the past 45 days",
    "fields": {
      "num_admins": "Number of Administrators",
      "num_projects_encryption": "Number of Projects with encryption enabled",
      "num_questions_biggest_form": "Number of questions in biggest Form",
      "num_audit_log_entries": "Number of Audit Log entries",
      "backups_configured": "Backups configured",
      "database_size": "System database size",
      "num_managers": "Number of Project Managers",
      "num_viewers": "Number of Project Viewers",
      "num_data_collectors": "Number of Data Collectors",
      "num_app_users": "Number of App Users",
      "num_device_ids": "Number of device IDs",
      "num_public_access_links": "Number of Public Access Links",
      "num_forms": "Number of Forms",
      "num_forms_with_repeats": "Number of Forms with repeats",
      "num_forms_with_geospatial": "Number of Forms with geodata",
      "num_forms_with_encryption": "Number of Forms with encryption",
      "num_forms_with_audits": "Number of Forms with audits",
      "num_submissions_received": "Number of Submissions - Received",
      "num_submissions_approved": "Number of Submissions - Approved",
      "num_submissions_has_issues": "Number of Submissions - Has Issues",
      "num_submissions_rejected": "Number of Submissions - Rejected",
      "num_submissions_edited": "Number of Submissions - Edited",
      "num_submissions_with_edits": "Number of Submissions with edits",
      "num_submissions_with_comments": "Number of Submissions with comments",
      "num_submissions_from_app_users": "Number of Submissions from App Users",
      "num_submissions_from_public_links": "Number of Submissions from Public Links",
      "num_submissions_from_web_users": "Number of Submissions from Web Users"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "es": {
    "recent": "en los últimos 45 días",
    "fields": {
      "num_admins": "Número de Administradores",
      "num_projects_encryption": "Número de proyectos con cifrado habilitado",
      "num_questions_biggest_form": "Número de preguntas en el Formulario más grande",
      "num_audit_log_entries": "Número de entradas del registro de auditoría",
      "backups_configured": "Copias de seguridad configuradas",
      "database_size": "Tamaño de la base de datos del sistema",
      "num_managers": "Número de jefes de proyecto",
      "num_viewers": "Número de observadores del proyecto",
      "num_data_collectors": "Número de recopiladores de datos",
      "num_app_users": "Número de usuarios móviles",
      "num_device_ids": "Número de ID de dispositivo",
      "num_public_access_links": "Número de enlaces de acceso público",
      "num_forms": "Número de formularios",
      "num_forms_with_repeats": "Número de formularios con repeticiones",
      "num_forms_with_geospatial": "Número de formularios con geoespacial",
      "num_forms_with_encryption": "Número de formularios con cifrado",
      "num_forms_with_audits": "Número de formularios con auditorías",
      "num_submissions_received": "Número de envíos recibidos",
      "num_submissions_approved": "Número de envíos aprobados",
      "num_submissions_has_issues": "Número de envíos con problemas",
      "num_submissions_rejected": "Número de envíos rechazados",
      "num_submissions_edited": "Número de envíos en estado editado",
      "num_submissions_with_edits": "Número de envíos con ediciones",
      "num_submissions_with_comments": "Número de envíos con comentarios",
      "num_submissions_from_app_users": "Número de envíos de Usuarios móviles",
      "num_submissions_from_public_links": "Número de envíos de enlaces públicos",
      "num_submissions_from_web_users": "Número de envíos de usuarios web"
    }
  },
  "it": {
    "recent": "Negli ultimi 45 giorni",
    "fields": {
      "num_admins": "Numero di Amministratori",
      "num_projects_encryption": "Numero di progetti con crittografia abilitata",
      "num_questions_biggest_form": "Numero di domande nel questionario più grande",
      "num_audit_log_entries": "Numero di voci del registro di controllo",
      "backups_configured": "Backups configurati.",
      "database_size": "System database size",
      "num_managers": "Numero di responsabili del progetto",
      "num_viewers": "Numero di visualizzatori del progetto",
      "num_data_collectors": "Numero di raccoglitori di dati",
      "num_app_users": "Numero di utenti dell'applicazione",
      "num_device_ids": "Numero di ID dispositivi",
      "num_public_access_links": "Numero di link con accesso pubblico",
      "num_forms": "Numero di formulari",
      "num_forms_with_repeats": "Numero di formulari con repeats all'interno",
      "num_forms_with_geospatial": "Numero di formulari con elementi geospaziali",
      "num_forms_with_encryption": "Numero di formulari con crittografia abilitata",
      "num_forms_with_audits": "Numero di formulari con audit",
      "num_submissions_received": "Numero di invii ricevuti",
      "num_submissions_approved": "Numero di invii approvati",
      "num_submissions_has_issues": "Numero di invii con problemi",
      "num_submissions_rejected": "Numero di invii scartati",
      "num_submissions_edited": "Numero di invii in stato modificato",
      "num_submissions_with_edits": "Numero di invii con modifiche",
      "num_submissions_with_comments": "Numero di invii con commenti",
      "num_submissions_from_app_users": "Numero di invii ricevuti da utenti applicazione",
      "num_submissions_from_public_links": "Numero di invii ricevuti da link pubblici",
      "num_submissions_from_web_users": "Numero di invii ricevuti da utenti web"
    }
  }
}
</i18n>
