<!--
Copyright 2021 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <table class="table analytics-metrics-table">
    <thead>
      <tr>
        <th>{{ title }}</th>
        <th class="metric-value recent-col">{{ $t('recent') }}</th>
        <th class="metric-value total-col">{{ $t('common.total') }}</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(value, name) in metrics" :key="name">
        <td>{{ $t(`fields.${name}`) }}</td>
        <template v-if="value == null">
          <td colspan="2" class="metric-value"></td>
        </template>
        <template v-else-if="value.recent != null">
          <td class="metric-value">{{ $n(value.recent) }}</td>
          <td class="metric-value">{{ $n(value.total) }}</td>
        </template>
        <template v-else>
          <td colspan="2" class="metric-value">{{ $n(value) }}</td>
        </template>
      </tr>
    </tbody>
  </table>
</template>

<script>
export default {
  name: 'AnalyticsMetricsTable',
  props: {
    title: {
      type: String,
      required: true
    },
    metrics: {
      type: Object,
      required: true
    }
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

.analytics-metrics-table {
  .metric-value {
    text-align: right;
  }

  .total-col {
    width: 50px;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "recent": "in the past 45 days",
    "fields": {
      "num_admins": "Number of Administrators",
      "num_projects_encryption": "Number of Projects with encryption enabled",
      "num_questions_biggest_form": "Number of questions in biggest Form",
      "num_audit_log_entries": "Number of Audit Log entries",
      "num_archived_projects": "Number of archived Projects",
      "num_unique_managers": "Number of unique Project Managers",
      "num_unique_viewers": "Number of unique Project Viewers",
      "num_unique_collectors": "Number of unique Data Collectors",
      "database_size": "System database size",
      "uses_external_db": "Server uses an external database",
      "num_managers": "Number of Project Managers",
      "num_viewers": "Number of Project Viewers",
      "num_data_collectors": "Number of Data Collectors",
      "num_app_users": "Number of App Users",
      "num_device_ids": "Number of device IDs",
      "num_public_access_links": "Number of Public Access Links",
      "num_forms": "Number of Forms",
      "num_forms_with_repeats": "Number of Forms with repeats",
      "num_forms_with_geospatial": "Number of Forms with geodata",
      "num_forms_with_encryption": "Number of Forms with encryption",
      "num_forms_with_audits": "Number of Forms with audits",
      "num_forms_webforms_enabled": "Number of Forms with Web Forms enabled",
      "num_reused_form_ids": "Number of reused Form IDs",
      "num_open_forms": "Number of open Forms",
      "num_closing_forms": "Number of closing Forms",
      "num_closed_forms": "Number of closed Forms",
      "num_submissions_received": "Number of Submissions - Received",
      "num_submissions_approved": "Number of Submissions - Approved",
      "num_submissions_has_issues": "Number of Submissions - Has Issues",
      "num_submissions_rejected": "Number of Submissions - Rejected",
      "num_submissions_edited": "Number of Submissions - Edited",
      "num_submissions_with_edits": "Number of Submissions with edits",
      "num_submissions_with_comments": "Number of Submissions with comments",
      "num_submissions_from_app_users": "Number of Submissions from App Users",
      "num_submissions_from_public_links": "Number of Submissions from Public Links",
      "num_submissions_from_web_users": "Number of Submissions from Web Users",
      "description_length": "Length of the Project description",
      "num_properties": "Number of Properties",
      "num_creation_forms": "Number of Forms that update the Entity List",
      "num_followup_forms": "Number of Forms that use the Entity List",
      "num_entities": "Number of Entities in the Entity List",
      "num_failed_entities": "Number of Entity creation errors",
      "num_entity_updates": "Number of Entity updates",
      "num_entity_updates_sub": "Number of Entity updates via Submissions",
      "num_entity_updates_api": "Number of Entity updates via API",
      "num_entities_updated": "Number of modified Entities",
      "num_entity_conflicts": "Number of Entities ever with conflict",
      "num_entity_conflicts_resolved": "Number of Entities with conflict now marked as resolved",
      "num_bulk_create_events": "Number of bulk uploads",
      "biggest_bulk_upload": "Number of rows in biggest bulk upload",
      "sso_enabled": "SSO enabled on server",
      "num_client_audit_attachments": "Number of Client Audit Attachments",
      "num_client_audit_attachments_failures": "Number of Client Audit processing failures",
      "num_client_audit_rows": "Number of Client Audit rows",
      "num_audits_failed": "Number of Audit Log Events that failed at least once",
      "num_audits_failed5": "Number of Audit Log Events that failed completely",
      "num_audits_unprocessed": "Number of Audit Log Events whose processing has been delayed",
      "num_offline_entity_branches": "Number of Offline Entity branches",
      "num_offline_entity_interrupted_branches": "Number of interrupted Offline Entity branches",
      "num_offline_entity_submissions_reprocessed": "Number of reordered Offline Entity submissions",
      "max_entity_submission_delay": "Maximum Entity Submission processing delay",
      "avg_entity_submission_delay": "Average Entity Submission processing delay",
      "uses_external_blob_store": "Server uses external S3-compatible storage",
      "num_offline_entity_submissions_force_processed": "Number of force-processed Offline Entity Submissions",
      "max_entity_branch_delay": "Maximum time to process offline Entity update chain",
      "num_owner_only_datasets": "Number of Entity Lists restricted to Owner Only",
      "num_xml_only_form_defs": "Number of Form Definitions with no associated XLSForm",
      "num_blob_files": "Number of binary files",
      "num_blob_files_on_s3": "Number of binary files currently stored in S3-compatible storage",
      "num_reset_failed_to_pending_count": "Number of times user has reset failed upload to S3-compatible storage",
      "num_entity_creates_sub": "Number of Entities created via Submissions",
      "num_entity_creates_api": "Number of Entities created via API",
      "num_entity_creates_bulk": "Number of Entities created via bulk upload",
      "max_geo_per_form": "Maximum number of Submissions with geo data in a Form",
      "num_entity_bulk_deletes": "Number of bulk Entity delete Audit Log Events",
      "num_datasets_with_geometry": "Number of Entity Lists with geometry property",
      "num_entity_create_forms": "Number of Forms that create Entities",
      "num_repeat_entity_create_forms": "Number of Forms that create Entities in repeats",
      "num_entity_update_forms": "Number of Forms that update Entities",
      "num_repeat_entity_update_forms": "Number of Forms that update Entities in repeats",
      "num_entity_create_update_forms": "Number of Forms that both create and update Entities",
      "num_entities_with_geometry": "Number of Entities with geometry data"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "recent": "v posledních 45 dnech",
    "fields": {
      "num_admins": "Počet správců",
      "num_projects_encryption": "Počet projektů s povoleným šifrováním",
      "num_questions_biggest_form": "Počet otázek v největším formuláři",
      "num_audit_log_entries": "Počet záznamů v protokolu auditů",
      "num_archived_projects": "Počet archivovaných projektů",
      "num_unique_managers": "Number of unique Project Managers",
      "num_unique_viewers": "Počet unikátních diváků projektu",
      "num_unique_collectors": "Počet jedinečných sběračů dat",
      "database_size": "Velikost systémové databáze",
      "uses_external_db": "Server používá externí databázi",
      "num_managers": "Počet projektových manažerů",
      "num_viewers": "Počet diváků projektu",
      "num_data_collectors": "Počet sběračů dat",
      "num_app_users": "Počet uživatelů aplikace",
      "num_device_ids": "Počet ID zařízení",
      "num_public_access_links": "Počet veřejně přístupných odkazů",
      "num_forms": "Počet formulářů",
      "num_forms_with_repeats": "Počet formulářů s opakováním",
      "num_forms_with_geospatial": "Počet formulářů s geodaty",
      "num_forms_with_encryption": "Počet formulářů se šifrováním",
      "num_forms_with_audits": "Počet formulářů s audity",
      "num_reused_form_ids": "Počet opakovaně použitých ID formulářů",
      "num_open_forms": "Počet otevřených formulářů",
      "num_closing_forms": "Počet uzavíraných formulářů",
      "num_closed_forms": "Počet uzavřených formulářů",
      "num_submissions_received": "Počet přijatých podání",
      "num_submissions_approved": "Počet podání - schváleno",
      "num_submissions_has_issues": "Počet podání - Má problémy",
      "num_submissions_rejected": "Počet podání - Zamítnuto",
      "num_submissions_edited": "Počet příspěvků - Upraveno",
      "num_submissions_with_edits": "Počet podání s úpravami",
      "num_submissions_with_comments": "Počet podání s komentáři",
      "num_submissions_from_app_users": "Počet podání od uživatelů aplikace",
      "num_submissions_from_public_links": "Počet podání z veřejných odkazů",
      "num_submissions_from_web_users": "Počet podání od uživatelů webu",
      "description_length": "Délka popisu projektu",
      "num_properties": "Počet vlastností",
      "num_creation_forms": "Počet formulářů, které aktualizují seznam subjektů",
      "num_followup_forms": "Počet formulářů, které používají seznam subjektů",
      "num_entities": "Počet subjektů v seznamu subjektů",
      "num_failed_entities": "Počet chyb při vytváření subjektu",
      "num_entity_updates": "Počet aktualizací entity",
      "num_entity_updates_sub": "Počet aktualizací entity prostřednictvím podání",
      "sso_enabled": "SSO povoleno na serveru",
      "num_client_audit_attachments": "Počet příloh auditu klienta",
      "num_client_audit_attachments_failures": "Počet selhání zpracování auditu klienta",
      "num_client_audit_rows": "Počet řádků auditu klienta",
      "num_audits_failed": "Počet událostí protokolu auditů, které selhaly alespoň jednou",
      "num_audits_failed5": "Počet událostí protokolu auditů, které zcela selhaly",
      "num_audits_unprocessed": "Počet událostí protokolu auditů, jejichž zpracování bylo odloženo",
      "num_blob_files": "Počet binárních souborů",
      "num_blob_files_on_s3": "Počet binárních souborů aktuálně uložených v úložišti kompatibilním s S3",
      "num_reset_failed_to_pending_count": "Počet případů, kdy uživatel resetoval neúspěšné odeslání do úložiště kompatibilního s S3"
    }
  },
  "de": {
    "recent": "in den letzten 45 Tagen",
    "fields": {
      "num_admins": "Anzahl Administratoren",
      "num_projects_encryption": "Anzahl der Projekte mit aktivierter Verschlüsselung",
      "num_questions_biggest_form": "Anzahl Fragen im grössten Formular",
      "num_audit_log_entries": "Anzahl Audit-Log-Einträge",
      "num_archived_projects": "Anzahl archivierter Projekte",
      "num_unique_managers": "Anzahl eindeutiger Projekt-Manager",
      "num_unique_viewers": "Anzahl eindeutiger Projekt-Betrachter",
      "num_unique_collectors": "Anzahl eindeutiger Datensammler",
      "database_size": "Systemdatenbankgröße",
      "uses_external_db": "Der Server verwendet eine externe Datenbank",
      "num_managers": "Anzahl Projekt-Manager",
      "num_viewers": "Anzahl Projekt-Betrachter",
      "num_data_collectors": "Anzahl Datensammler",
      "num_app_users": "Anzahl App-Benutzer",
      "num_device_ids": "Anzahl Geräte-IDs",
      "num_public_access_links": "Anzahl öffentlicher Zugangslinks",
      "num_forms": "Anzahl Formulare",
      "num_forms_with_repeats": "Anzahl Formulare mit Wiederholungen/repeats",
      "num_forms_with_geospatial": "Anzahl Formulare mit Geodata",
      "num_forms_with_encryption": "Anzahl Formulare mit Verschlüsselung",
      "num_forms_with_audits": "Anzahl Formulare mit Audits",
      "num_forms_webforms_enabled": "Anzahl der Formulare mit aktivierten Web-Formularen",
      "num_reused_form_ids": "Anzahl wiederverwendeter Formular-IDs",
      "num_open_forms": "Anzahl offener Formulare",
      "num_closing_forms": "Anzahl schliessender Formulare",
      "num_closed_forms": "Anzahl geschlossener Formulare",
      "num_submissions_received": "Anzahl ausgefüllte Formulare - erhalten",
      "num_submissions_approved": "Anzahl ausgefüllte Formulare - genehmigt",
      "num_submissions_has_issues": "Anzahl ausgefüllte Formulare - mit Problemen",
      "num_submissions_rejected": "Anzahl ausgefüllter Formulare - abgelehnt",
      "num_submissions_edited": "Anzahl ausgefüllter Formulare - geändert",
      "num_submissions_with_edits": "Anzahl ausgefüllte Formulare mit Änderungen",
      "num_submissions_with_comments": "Anzahl ausgefüllter Formulare mit Kommentaren",
      "num_submissions_from_app_users": "Anzahl ausgefüllter Formulare von App-Benutzern",
      "num_submissions_from_public_links": "Anzahl Einreichungen von Zugangslink",
      "num_submissions_from_web_users": "Anzahl Einreichungen von Web Benutzern",
      "description_length": "Länge der Projektbeschreibung",
      "num_properties": "Anzahl der Eigenschaften",
      "num_creation_forms": "Anzahl der Formulare, die die Objektliste aktualisieren",
      "num_followup_forms": "Anzahl der Formulare, die die Objektliste verwenden",
      "num_entities": "Anzahl der Objekte in der Objektliste",
      "num_failed_entities": "Anzahl der Fehler bei der Objekterstellung",
      "num_entity_updates": "Anzahl der Objekterneuerungen",
      "num_entity_updates_sub": "Anzahl der Objektaktualisierungen über Übermittlungen",
      "num_entity_updates_api": "Anzahl der Objektaktualisierungen über API",
      "num_entities_updated": "Anzahl der modifizierten Objekte",
      "num_entity_conflicts": "Anzahl der Objekte, die jemals einen Konflikt hatten",
      "num_entity_conflicts_resolved": "Anzahl der Objekte mit Konflikt jetzt als gelöst markiert",
      "num_bulk_create_events": "Anzahl von Bulk-Uploads",
      "biggest_bulk_upload": "Anzahl der Zeilen im grössten Bulk-Upload",
      "sso_enabled": "SSO auf dem Server aktiviert",
      "num_client_audit_attachments": "Anzahl Client-Audit-Anhänge",
      "num_client_audit_attachments_failures": "Anzahl an Client-Audit-Verarbeitungsfehler",
      "num_client_audit_rows": "Anzahl von Client-Audit-Zeilen",
      "num_audits_failed": "Anzahl mindestens einmal fehlgeschlagener Audit-Log-Events",
      "num_audits_failed5": "Anzahl komplett fehlgeschlagener Audit-Log-Events",
      "num_audits_unprocessed": "Anzahl der Audit-Log-Events, deren Verarbeitung verzögert wurde",
      "num_offline_entity_branches": "Anzahl Offline-Objekte-Zweige",
      "num_offline_entity_interrupted_branches": "Anzahl unterbrochene Offline-Objekt-Zweige",
      "num_offline_entity_submissions_reprocessed": "Anzahl umsortierter Offline-Objekt-Übermittlungen",
      "max_entity_submission_delay": "Maximum Objektübermittlung-Verarbeitungsverzögerung",
      "avg_entity_submission_delay": "Durchschnitt Objektübermittlung-Verarbeitungsverzögerung",
      "uses_external_blob_store": "Der Server verwendet externen S3-kompatiblen Speicher",
      "num_offline_entity_submissions_force_processed": "Anzahl der zwangsverarbeiteten Offline-Entity-Einsendungen",
      "max_entity_branch_delay": "Maximale Zeit für die Verarbeitung der Offline-Objekt-Update-Folge",
      "num_owner_only_datasets": "Anzahl der Objektlisten, die nur dem Eigentümer vorbehalten sind",
      "num_xml_only_form_defs": "Anzahl der Formulardefinitionen ohne zugehöriges XLSFormular",
      "num_blob_files": "Anzahl der Binärdateien",
      "num_blob_files_on_s3": "Anzahl der derzeit in einem S3-kompatiblen Speicher gespeicherten Binärdateien",
      "num_reset_failed_to_pending_count": "Anzahl der Fälle, in denen der Benutzer einen fehlgeschlagenen Upload auf einen S3-kompatiblen Speicher zurückgesetzt hat",
      "num_entity_creates_sub": "Anzahl der durch Übermittlungen erstellten Objekte",
      "num_entity_creates_api": "Anzahl der durch die API erstellten Objekte",
      "num_entity_creates_bulk": "Anzahl der Objekte, die über Massen-Upload erstellt wurden",
      "max_geo_per_form": "Maximale Anzahl von Übermittlungen mit Geodaten in einem Formular",
      "num_entity_bulk_deletes": "Anzahl der Audit-Protokollereignisse zum Löschen von Massenentitäten",
      "num_datasets_with_geometry": "Anzahl der Entitätslisten mit Geometrieeigenschaft",
      "num_entity_create_forms": "Anzahl der Formulare, die Entitäten erstellen",
      "num_repeat_entity_create_forms": "Anzahl der Formulare, die Entitäten in Wiederholungen/repeats erstellen",
      "num_entity_update_forms": "Anzahl der Formulare, die Entitäten aktualisieren",
      "num_repeat_entity_update_forms": "Anzahl der Formulare, die Entitäten in Wiederholungen/repeats aktualisieren",
      "num_entity_create_update_forms": "Anzahl der Formulare, die Entitäten sowohl erstellen als auch aktualisieren",
      "num_entities_with_geometry": "Anzahl der Entitäten mit Geometriedaten"
    }
  },
  "es": {
    "recent": "en los últimos 45 días",
    "fields": {
      "num_admins": "Número de Administradores",
      "num_projects_encryption": "Número de proyectos con cifrado habilitado",
      "num_questions_biggest_form": "Número de preguntas en el Formulario más grande",
      "num_audit_log_entries": "Número de entradas del registro de auditoría",
      "num_archived_projects": "Número de proyectos archivados",
      "num_unique_managers": "Número de Project Managers únicos",
      "num_unique_viewers": "Número de observadores del proyecto unicos",
      "num_unique_collectors": "Número de recopiladores de datos unicos",
      "database_size": "Tamaño de la base de datos del sistema",
      "uses_external_db": "El servidor utiliza una base de datos externa",
      "num_managers": "Número de jefes de proyecto",
      "num_viewers": "Número de observadores del proyecto",
      "num_data_collectors": "Número de recopiladores de datos",
      "num_app_users": "Número de usuarios móviles",
      "num_device_ids": "Número de ID de dispositivo",
      "num_public_access_links": "Número de enlaces de acceso público",
      "num_forms": "Número de formularios",
      "num_forms_with_repeats": "Número de formularios con repeticiones",
      "num_forms_with_geospatial": "Número de formularios con geodatos",
      "num_forms_with_encryption": "Número de formularios con cifrado",
      "num_forms_with_audits": "Número de formularios con auditorías",
      "num_forms_webforms_enabled": "Número de formularios con formularios web activados",
      "num_reused_form_ids": "Número de ID de formulario reutilizados",
      "num_open_forms": "Número de formularios abiertos",
      "num_closing_forms": "Número de formularios de cierre",
      "num_closed_forms": "Número de formularios cerrados",
      "num_submissions_received": "Número de envíos - Recibidos",
      "num_submissions_approved": "Número de envíos - Aprobados",
      "num_submissions_has_issues": "Número de envíos - Con problemas",
      "num_submissions_rejected": "Número de envíos - Rechazados",
      "num_submissions_edited": "Número de envíos - Con ediciones",
      "num_submissions_with_edits": "Número de envíos con ediciones",
      "num_submissions_with_comments": "Número de envíos con comentarios",
      "num_submissions_from_app_users": "Número de envíos de Usuarios móviles",
      "num_submissions_from_public_links": "Número de envíos de enlaces públicos",
      "num_submissions_from_web_users": "Número de envíos de usuarios web",
      "description_length": "Longitud de la descripción del proyecto",
      "num_properties": "Número de Propiedades",
      "num_creation_forms": "Número de formularios que actualizan la lista de entidades",
      "num_followup_forms": "Número de formularios que utilizan la lista de entidades",
      "num_entities": "Número de entidades en la lista de entidades",
      "num_failed_entities": "Número de errores de creación de entidad",
      "num_entity_updates": "Número de actualizaciones de entidad",
      "num_entity_updates_sub": "Número de actualizaciones de entidades a través de envíos",
      "num_entity_updates_api": "Número de actualizaciones de entidades a través de la API",
      "num_entities_updated": "Número de Entidades modificadas",
      "num_entity_conflicts": "Número de entidades que han tenido conflictos en algún momento",
      "num_entity_conflicts_resolved": "Número de entidades con conflicto ahora marcadas como resueltas",
      "num_bulk_create_events": "Número de cargas masivas",
      "biggest_bulk_upload": "Número de filas en la mayor carga masiva",
      "sso_enabled": "SSO habilitado en el servidor",
      "num_client_audit_attachments": "Número de archivos adjuntos de auditoría del cliente",
      "num_client_audit_attachments_failures": "Número de fallas en el procesamiento de auditoría de clientes",
      "num_client_audit_rows": "Número de filas de auditoría de cliente",
      "num_audits_failed": "Número de eventos del registro de auditoría que fallaron al menos una vez",
      "num_audits_failed5": "Número de eventos del registro de auditoría que fallaron por completo",
      "num_audits_unprocessed": "Número de eventos del registro de auditoría cuyo procesamiento se ha retrasado",
      "num_offline_entity_branches": "Número de ramas de entidades fuera de línea",
      "num_offline_entity_interrupted_branches": "Número de ramas de entidades fuera de línea interrumpidas",
      "num_offline_entity_submissions_reprocessed": "Número de envíos de entidades fuera de línea reordenados",
      "max_entity_submission_delay": "Plazo máximo de tramitación de envió de entidades",
      "avg_entity_submission_delay": "Plazo medio de tramitación del envío de entidades",
      "uses_external_blob_store": "El servidor utiliza almacenamiento externo compatible con S3",
      "num_offline_entity_submissions_force_processed": "Número de presentaciones de entidades fuera de línea procesadas por la fuerza",
      "max_entity_branch_delay": "Tiempo máximo para procesar fuera de línea la cadena de actualización de entidades",
      "num_owner_only_datasets": "Número de listas de entidades restringidas sólo al propietario",
      "num_xml_only_form_defs": "Número de definiciones de formulario sin XLSForm asociado",
      "num_blob_files": "Número de archivos binarios",
      "num_blob_files_on_s3": "Número de archivos binarios almacenados actualmente en un almacenamiento compatible con S3",
      "num_reset_failed_to_pending_count": "Número de veces que el usuario ha restablecido una carga fallida en un almacenamiento compatible con S3",
      "num_entity_creates_sub": "Número de entidades creadas a través de envíos",
      "num_entity_creates_api": "Número de entidades creadas a través de la API",
      "num_entity_creates_bulk": "Número de entidades creadas mediante carga masiva",
      "max_geo_per_form": "Número máximo de envíos con datos geográficos en un formulario",
      "num_entity_bulk_deletes": "Número de eventos de registro de auditoría de eliminación masiva de entidades",
      "num_datasets_with_geometry": "Número de listas de entidades con propiedad geométrica",
      "num_entity_create_forms": "Número de formularios que crean entidades",
      "num_repeat_entity_create_forms": "Número de formularios que crean entidades en repeticiones",
      "num_entity_update_forms": "Número de formularios que actualizan entidades",
      "num_repeat_entity_update_forms": "Número de formularios que actualizan entidades en repeticiones",
      "num_entity_create_update_forms": "Número de formularios que crean y actualizan entidades",
      "num_entities_with_geometry": "Número de entidades con datos geométricos"
    }
  },
  "fr": {
    "recent": "au cours des 45 derniers jours",
    "fields": {
      "num_admins": "Nombre d'administrateurs",
      "num_projects_encryption": "Nombre de projets avec le chiffrement activé",
      "num_questions_biggest_form": "Nombre de question dans le plus gros formulaire",
      "num_audit_log_entries": "Nombre d'entrées dans le journal d'audit",
      "num_archived_projects": "Nombre de projets archivés",
      "num_unique_managers": "Nombre de gestionnaires de projets uniques",
      "num_unique_viewers": "Nombre de lecteurs de projets uniques",
      "num_unique_collectors": "Nombre de collecteurs de données uniques",
      "database_size": "Taille de la base de données du système",
      "uses_external_db": "Le serveur utilise une base de données externe",
      "num_managers": "Nombre de gestionnaires de projet",
      "num_viewers": "Nombre de lecteurs de projet",
      "num_data_collectors": "Nombre de collecteurs de données",
      "num_app_users": "Nombre d'utilisateurs mobiles",
      "num_device_ids": "Nombre d'identifiants d'appareils",
      "num_public_access_links": "Nombre de liens d'accès public",
      "num_forms": "Nombre de formulaires",
      "num_forms_with_repeats": "Nombre de formulaires avec répétitions",
      "num_forms_with_geospatial": "Nombre de formulaires avec données géographiques",
      "num_forms_with_encryption": "Nombre de formulaires avec chiffrement",
      "num_forms_with_audits": "Nombre de formulaires avec audits",
      "num_forms_webforms_enabled": "Nombre de Formulaires ayant Web Forms activé",
      "num_reused_form_ids": "Nombre d'ID de formulaires réutilisés",
      "num_open_forms": "Nombre de formulaires ouverts",
      "num_closing_forms": "Nombre de formulaires en cours de fermeture",
      "num_closed_forms": "Nombre de formulaires fermés",
      "num_submissions_received": "Nombre de soumissions - Reçues",
      "num_submissions_approved": "Nombre de soumissions - Approuvées",
      "num_submissions_has_issues": "Nombre de soumissions - Avec problèmes",
      "num_submissions_rejected": "Nombre de soumissions - Rejetées",
      "num_submissions_edited": "Nombre de soumissions - Editées",
      "num_submissions_with_edits": "Nombre de soumissions avec éditions",
      "num_submissions_with_comments": "Nombre de soumissions avec commentaires",
      "num_submissions_from_app_users": "Nombre de soumissions depuis les utilisateurs d'application",
      "num_submissions_from_public_links": "Nombre de soumissions depuis les liens d'accès public",
      "num_submissions_from_web_users": "Nombre de soumissions par des utilisateurs web",
      "description_length": "Longueur de la description du Projet",
      "num_properties": "Nombre de propriétés",
      "num_creation_forms": "Nombre de formulaires qui mettent à jour la liste d'entités",
      "num_followup_forms": "Nombre de formulaires qui utilisent la liste d'entités",
      "num_entities": "Nombre d'entités dans la liste",
      "num_failed_entities": "Nombre d'erreurs de création d'Entité",
      "num_entity_updates": "Nombre de mises à jour de l'entité",
      "num_entity_updates_sub": "Nombre de mises à jour d'Entités par Soumissions.",
      "num_entity_updates_api": "Nombre de mises à jour d'Entités via l'API",
      "num_entities_updated": "Nombre d'Entités modifiées",
      "num_entity_conflicts": "Nombre d'Entités ayant déjà eu un conflit",
      "num_entity_conflicts_resolved": "Nombre d'Entités avec conflit désormais marqué comme résolu",
      "num_bulk_create_events": "Nombre d'envois en masse",
      "biggest_bulk_upload": "Nombre de lignes du plus gros envoi en masse",
      "sso_enabled": "Authentification unique (SSO) activée",
      "num_client_audit_attachments": "Nombre d'audit de client joints",
      "num_client_audit_attachments_failures": "Nombre d'échecs de traitement d'audit de client",
      "num_client_audit_rows": "Nombre de rangées d'audit de client",
      "num_audits_failed": "Nombre d'événements du journal d'audit qui ont échoué au moins une fois",
      "num_audits_failed5": "Nombre d'événements du journal d'audit qui ont entièrement échoué",
      "num_audits_unprocessed": "Nombre d'événements du journal d'audit qui ont été traités à retardement",
      "num_offline_entity_branches": "Nombre de branches d'Entités Hors ligne",
      "num_offline_entity_interrupted_branches": "Nombre de branches d'Entités hors lignes interrompues",
      "num_offline_entity_submissions_reprocessed": "Nombre de soumissions reliées à des Entités hors ligne qui sont arrivées dans le mauvais ordre",
      "max_entity_submission_delay": "Délai maximum de traitement de soumissions reliées à une Entité",
      "avg_entity_submission_delay": "Délai moyen de traitement de soumissions reliées à une Entité",
      "uses_external_blob_store": "Le serveur utilise un service de stockage externe compatible avec S3",
      "num_offline_entity_submissions_force_processed": "Nombre de soumissions reliées à des Entités hors ligne qui ont été traitées par force",
      "max_entity_branch_delay": "Temps maximum pour traiter une série d'Entités modifiées hors ligne",
      "num_owner_only_datasets": "Nombre de listes d'entités avec accès du propriétaire seulement",
      "num_xml_only_form_defs": "Nombre de définitions de formulaires sans XLSForm associées",
      "num_blob_files": "Nombre de fichiers binaires",
      "num_blob_files_on_s3": "Nombre de fichiers binaires stockés dans un service de stockage externe compatible avec S3",
      "num_reset_failed_to_pending_count": "Nombre de fois qu'un utilisateur a réinitialisé un envoi échoué au stockage externe compatible avec S3",
      "num_entity_creates_sub": "Nombre d'Entités créées par soumissions",
      "num_entity_creates_api": "Nombre d'Entités créées par API",
      "num_entity_creates_bulk": "Nombre d'Entités créées par envoi en masse",
      "max_geo_per_form": "Nombre de soumissions maximum ayant des donnés geo dans un formulaire",
      "num_entity_bulk_deletes": "Nombre d'événements de suppression en masse",
      "num_datasets_with_geometry": "Nombre de listes d'entités avec une propriété \"geometry\"",
      "num_entity_create_forms": "Nombre de formulaires qui créent des entités",
      "num_repeat_entity_create_forms": "Nombre de formulaires qui créent des entités avec répétition",
      "num_entity_update_forms": "Nombre de formulaires qui mettent à jour des entités",
      "num_repeat_entity_update_forms": "Nombre de formulaires qui mettent à jour des entités avec répétition",
      "num_entity_create_update_forms": "Nombre de formulaires qui créent et mettent à jour des entités",
      "num_entities_with_geometry": "Nombre d'entités avec données géographiques"
    }
  },
  "id": {
    "recent": "dalam 45 hari terakhir",
    "fields": {
      "num_admins": "Jumlah Administrator",
      "num_unique_viewers": "Jumlah Pemerhati Proyek unik",
      "num_unique_collectors": "Jumlah Pengumpul Data unik",
      "database_size": "Ukuran database sistem",
      "uses_external_db": "Server menggunakan database eksternal",
      "num_managers": "Jumlah Manajer Proyek",
      "num_viewers": "Jumlah Pemerhati Proyek",
      "num_data_collectors": "Jumlah Pengumpul Data",
      "num_app_users": "Jumlah Pengguna Aplikasi",
      "num_forms": "Jumlah Formulir",
      "num_forms_with_repeats": "Jumlah Formulir dengan ulangan",
      "num_forms_with_geospatial": "Jumlah Formulir dengan geodata",
      "num_forms_with_encryption": "Jumlah Formulir dengan enkripsi",
      "num_forms_with_audits": "Jumlah Formulir dengan audit",
      "num_submissions_edited": "Jumlah Kiriman - Diubah",
      "num_submissions_with_edits": "Jumlah Kiriman yang diubah",
      "num_submissions_from_app_users": "Jumlah Kiriman dari Pengguna Aplikasi",
      "num_submissions_from_web_users": "Jumlah Kiriman dari Pengguna Web",
      "num_failed_entities": "Jumlah error pembuatan entitas"
    }
  },
  "it": {
    "recent": "Negli ultimi 45 giorni",
    "fields": {
      "num_admins": "Numero di Amministratori",
      "num_projects_encryption": "Numero di progetti con crittografia abilitata",
      "num_questions_biggest_form": "Numero di domande nel questionario più grande",
      "num_audit_log_entries": "Numero di voci del registro di controllo",
      "num_archived_projects": "Numero di progetti archiviati",
      "num_unique_managers": "Numero di responsabili del progetto unici",
      "num_unique_viewers": "Numero di visualizzatori del progetto unici",
      "num_unique_collectors": "Numero di raccoglitori di dati unici",
      "database_size": "System database size",
      "uses_external_db": "Il server utilizza una base di dati esterna",
      "num_managers": "Numero di responsabili del progetto",
      "num_viewers": "Numero di visualizzatori del progetto",
      "num_data_collectors": "Numero di raccoglitori di dati",
      "num_app_users": "Numero di utenti dell'applicazione",
      "num_device_ids": "Numero di ID dispositivi",
      "num_public_access_links": "Numero di link con accesso pubblico",
      "num_forms": "Numero di formulari",
      "num_forms_with_repeats": "Numero di formulari con repeats all'interno",
      "num_forms_with_geospatial": "Numero di formulari con geodati",
      "num_forms_with_encryption": "Numero di formulari con crittografia abilitata",
      "num_forms_with_audits": "Numero di formulari con audit",
      "num_forms_webforms_enabled": "Numero di formulari con i Formulari Web abilitati",
      "num_reused_form_ids": "Numero di ID formulario riutilizzati",
      "num_open_forms": "Numero di formulari aperti",
      "num_closing_forms": "Numero di formulari in fase di chiusura",
      "num_closed_forms": "Numero di formulari chiusi",
      "num_submissions_received": "Numero di invii - Ricevuti",
      "num_submissions_approved": "Numero di invii - Approvati",
      "num_submissions_has_issues": "Numero di invii - Con problemi",
      "num_submissions_rejected": "Numero di invii - Scartati",
      "num_submissions_edited": "Numero di invii - Modificati",
      "num_submissions_with_edits": "Numero di invii con modifiche",
      "num_submissions_with_comments": "Numero di invii con commenti",
      "num_submissions_from_app_users": "Numero di invii ricevuti da utenti applicazione",
      "num_submissions_from_public_links": "Numero di invii ricevuti da link pubblici",
      "num_submissions_from_web_users": "Numero di invii ricevuti da utenti web",
      "description_length": "Lunghezza della descrizione del progetto",
      "num_properties": "Numero di proprietà",
      "num_creation_forms": "Numero di formulari che aggiornano la Lista di Entità",
      "num_followup_forms": "Numero di formulari che usano Lista di Entità",
      "num_entities": "Numero di Entità nella lista di Entità",
      "num_failed_entities": "Numero di errori nella creazione dell'entità",
      "num_entity_updates": "Numero di aggiornamenti dell'entità",
      "num_entity_updates_sub": "Numero di aggiornamenti dell'entità tramite invii",
      "num_entity_updates_api": "Numero di aggiornamenti dell'entità tramite API",
      "num_entities_updated": "Numero di entità modificate",
      "num_entity_conflicts": "Numero di entità mai in conflitto",
      "num_entity_conflicts_resolved": "Numero di entità con conflitto ora contrassegnato come risolto",
      "num_bulk_create_events": "Numero di caricamenti collettivi",
      "biggest_bulk_upload": "Numero di righe nel caricamento collettivo più grande",
      "sso_enabled": "SSO abilitato sul server",
      "num_client_audit_attachments": "Numero di allegati di audit del client",
      "num_client_audit_attachments_failures": "Numero di errori di elaborazione dell'audit del client",
      "num_client_audit_rows": "Numero di righe di audit client",
      "num_audits_failed": "Numero di eventi del registro di controllo che non sono riusciti almeno una volta",
      "num_audits_failed5": "Numero di eventi del registro di controllo completamente non riusciti",
      "num_audits_unprocessed": "Numero di eventi del registro di controllo la cui elaborazione è stata ritardata",
      "num_offline_entity_branches": "Numero di rami di entità offline",
      "num_offline_entity_interrupted_branches": "Numero di rami di entità offline interrotti",
      "num_offline_entity_submissions_reprocessed": "Numero di invii di entità offline riordinate",
      "max_entity_submission_delay": "Ritardo massimo di elaborazione della trasmissione dell'entità",
      "avg_entity_submission_delay": "Ritardo medio di elaborazione della trasmissione di un'entità",
      "uses_external_blob_store": "Il server utilizza uno storage esterno compatibile con S3",
      "num_offline_entity_submissions_force_processed": "Numero di invii di Entità offline elaborati forzatamente",
      "max_entity_branch_delay": "Tempo massimo di elaborazione della catena di aggiornamento delle Entità offline",
      "num_owner_only_datasets": "Numero di elenchi di entità riservati solo al proprietario",
      "num_xml_only_form_defs": "Numero di Definizioni di formulario senza un XLSForm associato",
      "num_blob_files": "Numero di file binari",
      "num_blob_files_on_s3": "Numero di file binari attualmente memorizzati in uno spazio di archiviazione compatibile con S3",
      "num_reset_failed_to_pending_count": "Numero di volte in cui l'utente ha ripristinato il caricamento fallito su uno storage compatibile con S3",
      "num_entity_creates_sub": "Numero di Entità create attraverso invii",
      "num_entity_creates_api": "Numero di Entità create tramite API",
      "num_entity_creates_bulk": "Numero di Entità create tramite caricamento massivo",
      "max_geo_per_form": "Numero massimo di invii con dati geografici in un modulo",
      "num_entity_bulk_deletes": "Numero di eventi di audit log per cancellazione massiva di Entità",
      "num_datasets_with_geometry": "Numero di elenchi di entità con proprietà geometrica",
      "num_entity_create_forms": "Numero di formulari che creano Entità",
      "num_repeat_entity_create_forms": "Numero di formulari che creano Entità dentro repeats",
      "num_entity_update_forms": "Numero di formulari che aggiornano Entità",
      "num_repeat_entity_update_forms": "Numero di formulari che aggiornano Entità dentro repeats",
      "num_entity_create_update_forms": "Numero di formulari che contemporaneamente creano e aggiornano Entità",
      "num_entities_with_geometry": "Numero di entità con proprietà geometrica"
    }
  },
  "ja": {
    "recent": "過去45日間",
    "fields": {
      "num_admins": "管理者数",
      "num_projects_encryption": "暗号化が有効化されたプロジェクト数",
      "num_questions_biggest_form": "最も大きなフォームの質問数",
      "num_audit_log_entries": "監査ログ数",
      "num_archived_projects": "アーカイブされたプロジェクト数",
      "num_unique_managers": "固有のプロジェクトマネジャー数",
      "num_unique_viewers": "固有のプロジェクト閲覧者数",
      "num_unique_collectors": "固有のデータ収集者数",
      "database_size": "システムのデータベースサイズ",
      "num_managers": "プロジェクト・マネージャー数",
      "num_viewers": "プロジェクト・閲覧者数",
      "num_data_collectors": "データ収集者数",
      "num_app_users": "アプリユーザー数",
      "num_device_ids": "デバイスID数",
      "num_public_access_links": "一般公開リンク数",
      "num_forms": "フォーム数",
      "num_forms_with_repeats": "リピートを有するフォーム数",
      "num_forms_with_geospatial": "ジオデータを有するフォーム数",
      "num_forms_with_encryption": "暗号化されたフォーム数",
      "num_forms_with_audits": "監査を受けたフォーム数",
      "num_reused_form_ids": "再利用されたフォームID数",
      "num_submissions_received": "提出済みフォーム数 ー 受信済み",
      "num_submissions_approved": "提出済みフォーム数 ー 承認済み",
      "num_submissions_has_issues": "提出済みフォーム数 ー 問題有り",
      "num_submissions_rejected": "提出済みフォーム数 ー リジェクト済み",
      "num_submissions_edited": "提出済みフォーム数 ー 編集済み",
      "num_submissions_with_edits": "編集された提出済みフォーム数",
      "num_submissions_with_comments": "コメントのある提出済みフォーム数",
      "num_submissions_from_app_users": "アプリユーザーから提出されたフォーム数",
      "num_submissions_from_public_links": "一般公開リンクから提出されたフォーム数",
      "num_submissions_from_web_users": "Webユーザーから提出されたフォーム数"
    }
  },
  "pt": {
    "recent": "nos últimos 45 dias",
    "fields": {
      "num_admins": "Número de administradores",
      "num_projects_encryption": "Número de projetos com encriptação habilitada",
      "num_questions_biggest_form": "Número de questões no maior formulário",
      "num_audit_log_entries": "Número de entradas no registro de auditoria",
      "num_archived_projects": "Numero de Projetos arquivados",
      "num_unique_managers": "Numero de Gerentes de Projeto únicos",
      "num_unique_viewers": "Número de Observadores do Projeto únicos",
      "num_unique_collectors": "Número de Coletores de Dados únicos",
      "database_size": "Tamanho do banco de dados do sistema",
      "uses_external_db": "O Servidor usa um banco de dados externo",
      "num_managers": "Número de gerentes de projeto",
      "num_viewers": "Número de observadores de projeto",
      "num_data_collectors": "Número de coletores de dados",
      "num_app_users": "Número de usuários de aplicativo",
      "num_device_ids": "Número de identificadores de dispositivos",
      "num_public_access_links": "Número de links de acesso público",
      "num_forms": "Número de formulários",
      "num_forms_with_repeats": "Número de formulários com estruturas de repetição",
      "num_forms_with_geospatial": "Número de formulários com dados de georreferenciamento",
      "num_forms_with_encryption": "Número de formulários com encriptação",
      "num_forms_with_audits": "Número de formulários com auditoria",
      "num_forms_webforms_enabled": "Número de Formulários com Web Forms habilitado",
      "num_reused_form_ids": "Número de IDs de Formulário reutilizados",
      "num_open_forms": "Número de Formulários abertos",
      "num_closing_forms": "Número de Formulários em fechamento",
      "num_closed_forms": "Número de Formulários fechados",
      "num_submissions_received": "Número de respostas - Recebido",
      "num_submissions_approved": "Número de respostas - Aprovado",
      "num_submissions_has_issues": "Número de respostas - Contém erros",
      "num_submissions_rejected": "Número de respostas - Rejeitado",
      "num_submissions_edited": "Número de respostas - Editado",
      "num_submissions_with_edits": "Número de respostas com edição",
      "num_submissions_with_comments": "Número de respostas com comentários",
      "num_submissions_from_app_users": "Número de respostas de usuários de aplicativo",
      "num_submissions_from_public_links": "Número de respostas de links públicos",
      "num_submissions_from_web_users": "Número de respostas de usuários do site",
      "description_length": "Comprimento da descrição do Projeto",
      "num_properties": "Número de Propriedades",
      "num_creation_forms": "Número de Formulários que atualizam a Lista de Entidades",
      "num_followup_forms": "Número de Formulários que usam a Lista de Entidades",
      "num_entities": "Número de Entidades na Lista de Entidades",
      "num_failed_entities": "Número de erros de criação de Entidades",
      "num_entity_updates": "Número de atualizações de Entidades",
      "num_entity_updates_sub": "Número de atualizações de Entidades por meio de Respostas",
      "num_entity_updates_api": "Número de atualizações de Entidades via API",
      "num_entities_updated": "Número de Entidades modificadas",
      "num_entity_conflicts": "Número total de Entidades com conflito",
      "num_entity_conflicts_resolved": "Número de Entidades com conflito agora marcados como resolvidos",
      "num_bulk_create_events": "Número de carregamentos em massa",
      "biggest_bulk_upload": "Número de linhas no maior carregamento em massa",
      "sso_enabled": "SSO habilitado no servidor",
      "num_client_audit_attachments": "Número de Anexos de Auditoria de Cliente",
      "num_client_audit_attachments_failures": "Número de falhas no processamento de Auditoria de Cliente",
      "num_client_audit_rows": "Número de linhas de Auditoria de Cliente",
      "num_audits_failed": "Número de Eventos de Registro de Auditoria que falharam pelo menos uma vez",
      "num_audits_failed5": "Número de Eventos de Registro de Auditoria que falharam completamente",
      "num_audits_unprocessed": "Número de Eventos de Registro de Auditoria cujo processamento foi atrasado",
      "num_offline_entity_branches": "Número de ramificações de Entidade Offline",
      "num_offline_entity_interrupted_branches": "Número de ramificações de Entidade Offline interrompidas",
      "num_offline_entity_submissions_reprocessed": "Número de respostas de Entidade Offline reordenadas",
      "max_entity_submission_delay": "Atraso máximo no processamento de Resposta de Entidade",
      "avg_entity_submission_delay": "Atraso médio no processamento da Resposta da Entidade",
      "uses_external_blob_store": "O servidor utiliza armazenamento externo compatível com S3",
      "num_offline_entity_submissions_force_processed": "Número de Respostas de Entidades offline processadas à força",
      "max_entity_branch_delay": "Tempo máximo para processar cadeia de atualização de Entidades offline",
      "num_owner_only_datasets": "Número de Listas de Entidades restritas apenas ao proprietário",
      "num_xml_only_form_defs": "Número de Definições de Formulário sem nenhum XLSForm associado",
      "num_blob_files": "Número de arquivos binários",
      "num_blob_files_on_s3": "Número de arquivos binários atualmente armazenados em armazenamento compatível com S3",
      "num_reset_failed_to_pending_count": "Número de vezes que o usuário resetou uploads que falharam para armazenamentos compatíveis com S3",
      "num_entity_creates_sub": "Número de Entidades criadas por Respostas",
      "num_entity_creates_api": "Número de Entidades criadas por API",
      "num_entity_creates_bulk": "Número de Entidades criadas por upload em massa"
    }
  },
  "sw": {
    "recent": "katika siku 45 zilizopita",
    "fields": {
      "num_admins": "Idadi ya Wasimamizi",
      "num_projects_encryption": "Idadi ya Miradi ambayo usimbaji fiche umewezeshwa",
      "num_questions_biggest_form": "Idadi ya maswali katika kidato kikubwa zaidi",
      "num_audit_log_entries": "Idadi ya maingizo ya Kumbukumbu ya Ukaguzi",
      "num_archived_projects": "Idadi ya miradi iliyohifadhiwa kwenye kumbukumbu",
      "num_unique_managers": "Idadi ya wasimamizi wa Miradi wa kipekee",
      "num_unique_viewers": "Idadi ya watazamaji wa kipekee wa Mradi",
      "num_unique_collectors": "Idadi ya Wakusanyaji data wa kipekee",
      "database_size": "Saizi ya hifadhidata ya mfumo",
      "uses_external_db": "Seva hutumia hifadhidata ya nje",
      "num_managers": "Idadi ya wasimamizi wa miradi",
      "num_viewers": "Idadi ya watazamaji wa mradi",
      "num_data_collectors": "Idadi ya wakusanyaji data",
      "num_app_users": "Idadi ya watumiaji wa programu",
      "num_device_ids": "Idadi ya vitambulisho vya kifaa",
      "num_public_access_links": "Idadi ya viungo vya ufikiaji wa umma",
      "num_forms": "Idadi ya Fomu",
      "num_forms_with_repeats": "Idadi ya Fomu zilizo na marudio",
      "num_forms_with_geospatial": "Idadi ya Fomu zilizo na jiografia",
      "num_forms_with_encryption": "Idadi ya Fomu zilizo na usimbaji fiche",
      "num_forms_with_audits": "Idadi ya Fomu zilizo na ukaguzi",
      "num_reused_form_ids": "Idadi ya vitambulisho vya fomu vilivyotumika tena",
      "num_open_forms": "Idadi ya Fomu zilizofunguliwa",
      "num_closing_forms": "Idadi ya fomu za kufunga",
      "num_closed_forms": "Idadi ya Fomu zilizofungwa",
      "num_submissions_received": "Idadi ya Mawasilisho - Yaliyopokelewa",
      "num_submissions_approved": "Idadi ya Mawasilisho - Yameidhinishwa",
      "num_submissions_has_issues": "Idadi ya Mawasilisho - Ina Masuala",
      "num_submissions_rejected": "Idadi ya Mawasilisho - Yamekataliwa",
      "num_submissions_edited": "Idadi ya Mawasilisho - Yaliyohaririwa",
      "num_submissions_with_edits": "Idadi ya Mawasilisho yenye mabadiliko",
      "num_submissions_with_comments": "Idadi ya Mawasilisho yenye maoni",
      "num_submissions_from_app_users": "Idadi ya Mawasilisho kutoka kwa Watumiaji wa Programu",
      "num_submissions_from_public_links": "Idadi ya Mawasilisho kutoka kwa Viungo vya Umma",
      "num_submissions_from_web_users": "Idadi ya Mawasilisho kutoka kwa Watumiaji wa Wavuti",
      "description_length": "Urefu wa maelezo ya Mradi",
      "num_properties": "Idadi ya Mali",
      "num_creation_forms": "Idadi ya Fomu zinazosasisha Orodha ya Huluki",
      "num_followup_forms": "Idadi ya Fomu zinazotumia Orodha ya Huluki",
      "num_entities": "Idadi ya Huluki katika Orodha ya Huluki",
      "num_failed_entities": "Idadi ya hitilafu za kuunda Huluki",
      "num_entity_updates": "Idadi ya masasisho ya Huluki",
      "sso_enabled": "SSO imewashwa kwenye seva",
      "num_client_audit_attachments": "Idadi ya Viambatisho vya Ukaguzi wa Mteja",
      "num_client_audit_attachments_failures": "Idadi ya hitilafu za uchakataji wa Ukaguzi wa Wateja",
      "num_client_audit_rows": "Idadi ya safu mlalo za Ukaguzi wa Wateja",
      "num_audits_failed": "Idadi ya Matukio ya Kumbukumbu ya Ukaguzi ambayo hayakufaulu angalau mara moja",
      "num_audits_failed5": "Idadi ya Matukio ya Kumbukumbu ya Ukaguzi ambayo hayakufaulu kabisa",
      "num_audits_unprocessed": "Idadi ya Matukio ya Rekodi za Ukaguzi ambayo uchakataji wake umecheleweshwa"
    }
  },
  "zh": {
    "recent": "最近45天内",
    "fields": {
      "num_admins": "管理员数量",
      "num_projects_encryption": "启用加密的项目数量",
      "num_questions_biggest_form": "最大表单中的问题数量",
      "num_audit_log_entries": "审计条目数量",
      "num_archived_projects": "存档项目数量",
      "num_unique_managers": "项目管理人员数（去重）",
      "num_unique_viewers": "项目复核人数（去重）",
      "num_unique_collectors": "数据收集者人数（去重）",
      "database_size": "系统数据库大小",
      "uses_external_db": "服务器使用外部数据库",
      "num_managers": "项目管理人数",
      "num_viewers": "项目复核人数",
      "num_data_collectors": "数据收集者人数",
      "num_app_users": "App使用人数",
      "num_device_ids": "项目ID数",
      "num_public_access_links": "公开链接数",
      "num_forms": "表单数量",
      "num_forms_with_repeats": "包含重复的表单数量",
      "num_forms_with_geospatial": "包含地理数据的表单数量",
      "num_forms_with_encryption": "启用加密的表单数量",
      "num_forms_with_audits": "有审计的表单数量",
      "num_forms_webforms_enabled": "启用Web表单功能的表单数量",
      "num_reused_form_ids": "重复使用的表单ID数量",
      "num_open_forms": "开放的表单数量",
      "num_closing_forms": "即将关闭的表单数量",
      "num_closed_forms": "已关闭的表单数量",
      "num_submissions_received": "已接收的提交数量",
      "num_submissions_approved": "已批准的提交数量",
      "num_submissions_has_issues": "有问题的提交数量",
      "num_submissions_rejected": "被拒绝的提交数量",
      "num_submissions_edited": "编辑过的提交数量",
      "num_submissions_with_edits": "包含编辑的提交数量",
      "num_submissions_with_comments": "包含评论的提交数量",
      "num_submissions_from_app_users": "App用户的提交数量",
      "num_submissions_from_public_links": "公共链接的提交数量",
      "num_submissions_from_web_users": "网页用户的提交数量",
      "description_length": "项目描述长度",
      "num_properties": "属性数量",
      "num_creation_forms": "更新实体列表的表单数量",
      "num_followup_forms": "使用实体列表的表单数量",
      "num_entities": "在实体列表中的实体数量",
      "num_failed_entities": "实体创建错误数量",
      "num_entity_updates": "实体更新总数",
      "num_entity_updates_sub": "通过提交更新的实体数量",
      "num_entity_updates_api": "通过API更新的实体数量",
      "num_entities_updated": "改动后的实体数量",
      "num_entity_conflicts": "有过冲突的实体个数",
      "num_entity_conflicts_resolved": "当前标记为已解决冲突的实体个数",
      "num_bulk_create_events": "批量更新数量",
      "biggest_bulk_upload": "最大批量上传的行数",
      "sso_enabled": "服务器上已启用SSO",
      "num_client_audit_attachments": "客户端审计附件数量",
      "num_client_audit_attachments_failures": "客户端审计处理失败的数量",
      "num_client_audit_rows": "客户端审计行数",
      "num_audits_failed": "至少出现过一次失败的审计日志事件数量",
      "num_audits_failed5": "完全失败的审计日志事件数量",
      "num_audits_unprocessed": "处理延误的审计日志事件个数",
      "num_offline_entity_branches": "离线实体分支个数",
      "num_offline_entity_interrupted_branches": "中断的离线实体分支数量",
      "num_offline_entity_submissions_reprocessed": "重新排序的离线实体提交数量",
      "max_entity_submission_delay": "最长实体提交处理延迟",
      "avg_entity_submission_delay": "平均实体提交处理延迟",
      "uses_external_blob_store": "服务器使用外部 S3 兼容存储",
      "num_offline_entity_submissions_force_processed": "强制处理的离线实体提交数量",
      "max_entity_branch_delay": "处理离线实体更新链的最长时间",
      "num_owner_only_datasets": "仅限拥有者访问的实体列表数量",
      "num_xml_only_form_defs": "没有关联XLSForm的表单定义数量",
      "num_blob_files": "二进位文件数量",
      "num_blob_files_on_s3": "目前存储在S3兼容空间的二进制文件数量",
      "num_reset_failed_to_pending_count": "用户重置上传到 S3 兼容存储失败的次数",
      "num_entity_creates_sub": "通过提交创建的实体个数",
      "num_entity_creates_api": "通过API创建的实体个数",
      "num_entity_creates_bulk": "通过批量上传创建的实体个数",
      "max_geo_per_form": "表单中含有地理数据的最高提交数量",
      "num_entity_bulk_deletes": "批量实体删除的审计条目数量",
      "num_datasets_with_geometry": "含有地理数据的实体列表数量",
      "num_entity_create_forms": "可创建实体的表单数量",
      "num_repeat_entity_create_forms": "可创建重复实体的表单数量",
      "num_entity_update_forms": "可更新实体的表单数量",
      "num_repeat_entity_update_forms": "可更新重复实体的表单数量",
      "num_entity_create_update_forms": "创建并更新实体的表单数量",
      "num_entities_with_geometry": "含有地理数据的实体数量"
    }
  },
  "zh-Hant": {
    "recent": "在過去 45 天內",
    "fields": {
      "num_admins": "管理員人數",
      "num_projects_encryption": "啟用加密的專案數量",
      "num_questions_biggest_form": "最大表格的問題數量",
      "num_audit_log_entries": "審核日誌條目數",
      "num_archived_projects": "已歸檔專案數量",
      "num_unique_managers": "專案管理員唯一數量",
      "num_unique_viewers": "專案瀏覽者唯一數量",
      "num_unique_collectors": "資料收集員唯一數量",
      "database_size": "系統資料庫大小",
      "uses_external_db": "伺服器使用外部資料庫",
      "num_managers": "專案管理員人數",
      "num_viewers": "專案瀏覽者數量",
      "num_data_collectors": "資料收集員人數",
      "num_app_users": "APP使用者人數",
      "num_device_ids": "ID 裝置數量",
      "num_public_access_links": "公共存取連結數量",
      "num_forms": "表單數量",
      "num_forms_with_repeats": "重複表單數量",
      "num_forms_with_geospatial": "包含地理資料的表單數量",
      "num_forms_with_encryption": "加密的表單數量",
      "num_forms_with_audits": "審核表格數量",
      "num_forms_webforms_enabled": "啟用 Web 表單的表單數量",
      "num_reused_form_ids": "重複使用的表單 ID 數量",
      "num_open_forms": "開啟的表格數量",
      "num_closing_forms": "結案中的表格數量",
      "num_closed_forms": "已結案的表格數量",
      "num_submissions_received": "提交的數量 - 已收到",
      "num_submissions_approved": "提交的數量 - 已批准",
      "num_submissions_has_issues": "提交數量 - 有問題",
      "num_submissions_rejected": "提交數量 - 被拒絕",
      "num_submissions_edited": "提交數量 - 已編輯",
      "num_submissions_with_edits": "經過編輯的提交數量",
      "num_submissions_with_comments": "帶評論的提交數量",
      "num_submissions_from_app_users": "APP用戶提交的數量",
      "num_submissions_from_public_links": "來自公共連結的提交數量",
      "num_submissions_from_web_users": "網路使用者提交的數量",
      "description_length": "專案描述的長度",
      "num_properties": "特性數量",
      "num_creation_forms": "更新實體列表的表格數量",
      "num_followup_forms": "使用實體清單的表單數量",
      "num_entities": "實體清單中的實體數量",
      "num_failed_entities": "實體建立錯誤的數量",
      "num_entity_updates": "實體更新數量",
      "num_entity_updates_sub": "透過提交更新的實體數量",
      "num_entity_updates_api": "透過 API 更新實體的數量",
      "num_entities_updated": "修改實體的數量",
      "num_entity_conflicts": "曾經發生衝突的實體數量",
      "num_entity_conflicts_resolved": "現在標記為已解決的衝突實體數量",
      "num_bulk_create_events": "批次上傳數量",
      "biggest_bulk_upload": "最大批次上傳行數",
      "sso_enabled": "伺服器上啟用 SSO",
      "num_client_audit_attachments": "客戶審核附件數量",
      "num_client_audit_attachments_failures": "客戶審核處理失敗的數量",
      "num_client_audit_rows": "客戶端審核行數",
      "num_audits_failed": "至少失敗一次的審核日誌事件數",
      "num_audits_failed5": "完全失敗的審核日誌事件數",
      "num_audits_unprocessed": "處理已延遲的審核日誌事件數",
      "num_offline_entity_branches": "離線實體分支數量",
      "num_offline_entity_interrupted_branches": "中斷的離線實體分支數量",
      "num_offline_entity_submissions_reprocessed": "重新排序的離線實體提交數量",
      "max_entity_submission_delay": "最大實體提交處理延遲",
      "avg_entity_submission_delay": "平均實體提交處理延遲",
      "uses_external_blob_store": "伺服器使用外部S3相容存儲",
      "num_offline_entity_submissions_force_processed": "強制處理的離線實體提交數量",
      "max_entity_branch_delay": "處理離線實體更新鏈的最長時間",
      "num_owner_only_datasets": "僅限於業主的實體清單數量",
      "num_xml_only_form_defs": "沒有關聯 XLSForm 的表單定義數量",
      "num_blob_files": "二進位檔案數量",
      "num_blob_files_on_s3": "目前儲存在 S3 相容儲存中的二進位檔案數量",
      "num_reset_failed_to_pending_count": "使用者重置上傳到 S3 相容儲存失敗的次數",
      "num_entity_creates_sub": "透過提交創建的實體數量",
      "num_entity_creates_api": "透過API建立的實體數量",
      "num_entity_creates_bulk": "透過批次上傳建立的實體數量"
    }
  }
}
</i18n>
