<!--
Copyright 2021 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <page-body>
    <i18n-t tag="p" keypath="body">
      <template #filename>
        <strong>{{ filename }}</strong>
      </template>
    </i18n-t>
    <!-- eslint-disable-next-line vuejs-accessibility/anchor-has-content -->
    <a v-show="false" ref="link" :href="href" download></a>
  </page-body>
</template>

<script>
import PageBody from './page/body.vue';

export default {
  name: 'Download',
  components: { PageBody },
  computed: {
    filename() {
      const { path } = this.$route;
      return path.slice(path.lastIndexOf('/') + 1);
    },
    href() {
      return this.$route.fullPath.replace('/dl', '/v1');
    }
  },
  watch: {
    $route() {
      this.$nextTick(this.download);
    }
  },
  mounted() {
    this.download();
  },
  methods: {
    download() {
      this.$refs.link.click();
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    "body": "{filename} will begin downloading soon. Once the download begins, you can leave this page."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "body": "{filename} se brzy začne stahovat. Jakmile začne stahování, můžete tuto stránku opustit."
  },
  "de": {
    "body": "{filename} beginnt bald mit dem Download. Sobald der Download begonnen hat, können Sie diese Seite verlassen."
  },
  "es": {
    "body": "{filename} comenzará a descargarse pronto. Una vez que comience la descarga, puede salir de esta página."
  },
  "fr": {
    "body": "Le téléchargement du fichier {filename} va bientôt commencer. Une fois qu'il aura démarré, vous pourrez quitter la page."
  },
  "it": {
    "body": "A breve inizierà il download di {filename}. Una volta avviato il download, puoi lasciare questa pagina."
  },
  "ja": {
    "body": "{filename}はすぐにダウンロードされます。ダウンロードが始めると、このページから移動しても構いません。"
  },
  "sw": {
    "body": "{filename} itaanza kupakuliwa hivi karibuni. Mara tu upakuaji unapoanza, unaweza kuondoka kwenye ukurasa huu"
  }
}
</i18n>
