<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div class="row">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6">
      <div class="panel panel-default panel-main">
        <div class="panel-heading">
          <h1 class="panel-title">{{ $t('title.pageNotFound') }}</h1>
        </div>
        <div class="panel-body">
          <p>{{ $t('body') }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'NotFound'
};
</script>

<i18n lang="json5">
{
  "en": {
    "body": "The page you requested could not be found."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "body": "Požadovanou stránku nelze najít."
  },
  "de": {
    "body": "Die von Ihnen gewünschte Seite wurde nicht gefunden."
  },
  "es": {
    "body": "La página que está solicitando no pudo ser encontrada."
  },
  "fr": {
    "body": "La page demandée ne peut être trouvée."
  },
  "id": {
    "body": "Laman yang Anda minta tidak ditemui."
  },
  "it": {
    "body": "La pagina richiesta non è stata trovata."
  },
  "ja": {
    "body": "リクエストされたページは見つかりません。"
  },
  "sw": {
    "body": "Ukurasa ulioomba haukupatikana."
  }
}
</i18n>
