<template>
  <div v-show="message != null" id="odata-loading-message">
    <div id="odata-loading-spinner-container">
      <spinner :state="message != null"/>
    </div>
    <div id="odata-loading-message-text">{{ message }}</div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import Spinner from './spinner.vue';
import { useI18nUtils } from '../util/i18n';

const { t } = useI18n();
const { tn } = useI18nUtils();

defineOptions({
  name: 'OdataLoadingMessage'
});

const props = defineProps({
  odata: {
    type: Object,
    required: true
  },
  type: {
    type: String,
    required: true
  },
  refreshing: {
    type: Boolean,
    required: true
  },
  filter: {
    type: Boolean,
    default: false
  },
  totalCount: {
    type: Number,
    required: true
  },
  top: {
    type: Number,
    required: true
  }
});



const message = computed(() => {
  if (!props.odata.awaitingResponse || props.refreshing) return null;

  if (!props.odata.dataExists) {
    if (props.filter)
      return t(`${props.type}.filtered.withoutCount`);

    if (props.totalCount === 0)
      return t(`${props.type}.withoutCount`);

    if (props.totalCount <= props.top)
      return tn(`${props.type}.all`, props.totalCount);

    return tn(`${props.type}.first`, props.totalCount, {
      top: props.top
    });
  }

  const pathPrefix = props.filter
    ? `${props.type}.filtered`
    : `${props.type}`;
  const remaining = props.odata.originalCount - props.odata.value.length;
  if (remaining > props.top) {
    return tn(`${pathPrefix}.middle`, remaining, {
      top: props.top
    });
  }
  return remaining > 1
    ? tn(`${pathPrefix}.last.multiple`, remaining)
    : t(`${pathPrefix}.last.one`);
});

</script>

<i18n lang="json5">
  {
    "en": {
      // @transifexKey component.SubmissionList.loading
      "submission": {
        // This text is shown when the number of Submissions loading is unknown.
        "withoutCount": "Loading Submissions…",
        "all": "Loading {count} Submission… | Loading {count} Submissions…",
        // {top} is a number that is either 250 or 1000. {count} may be any number
        // that is at least 250. The string will be pluralized based on {count}.
        "first": "Loading the first {top} of {count} Submission… | Loading the first {top} of {count} Submissions…",
        // {top} is a number that is either 250 or 1000. {count} may be any number
        // that is at least 250. The string will be pluralized based on {count}.
        "middle": "Loading {top} more of {count} remaining Submission… | Loading {top} more of {count} remaining Submissions…",
        "last": {
          "multiple": "Loading the last {count} Submission… | Loading the last {count} Submissions…",
          "one": "Loading the last Submission…"
        },
        "filtered": {
          // This text is shown when the number of Submissions loading is unknown.
          "withoutCount": "Loading matching Submissions…",
          // {top} is a number that is either 250 or 1000. {count} may be any
          // number that is at least 250. The string will be pluralized based on
          // {count}.
          "middle": "Loading {top} more of {count} remaining matching Submission… | Loading {top} more of {count} remaining matching Submissions…",
          "last": {
            "multiple": "Loading the last {count} matching Submission… | Loading the last {count} matching Submissions…",
            "one": "Loading the last matching Submission…"
          }
        }
      },
      "entity": {
        // This text is shown when the number of Entities loading is unknown.
        "withoutCount": "Loading Entities…",
        "all": "Loading {count} Entity… | Loading {count} Entities…",
        // {top} is a number that is either 250 or 1000. {count} may be any number
        // that is at least 250. The string will be pluralized based on {count}.
        "first": "Loading the first {top} of {count} Entity… | Loading the first {top} of {count} Entities…",
        // {top} is a number that is either 250 or 1000. {count} may be any number
        // that is at least 250. The string will be pluralized based on {count}.
        "middle": "Loading {top} more of {count} remaining Entity… | Loading {top} more of {count} remaining Entities…",
        "last": {
          "multiple": "Loading the last {count} Entity… | Loading the last {count} Entities…",
          "one": "Loading the last Entity…"
        }
      }
    }
  }
  </i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "submission": {
      "withoutCount": "Načítání příspěvků…",
      "all": "Načítání {count} příspěvku ... | Načítání {count} příspěvků ... | Načítání {count} příspěvků ... | Načítání {count} příspěvků ...",
      "first": "Načítání prvního {top} z {count} příspěvku… | Načítání prvního {top} ze {count} příspěvků… | Načítání prvního {top} z {count} příspěvků… | Načítání prvního {top} z {count} příspěvků…",
      "middle": "Načítání {top} z dalšího {count} zbývajícího příspěvku… | Načítání {top} z dalších {count} zbývajících příspěvků… | Načítání {top} z dalších {count} zbývajících příspěvků… | Načítání {top} z dalších {count} zbývajících příspěvků…",
      "last": {
        "multiple": "Načítání posledního {count} příspěvku… | Načítání posledních {count} příspěvků… | Načítání posledních {count} příspěvků… | Načítání posledních {count} příspěvků…",
        "one": "Načítání posledního příspěvku…"
      },
      "filtered": {
        "withoutCount": "Načítání odpovídajících příspěvků…",
        "middle": "Načítání {top} z dalších {count} zbývajících odpovídajících příspěvků… | Načítání {top} z dalších {count} zbývajících odpovídajících příspěvků… | Načítání {top} z dalších {count} zbývajících odpovídajících příspěvků… | Načítání {top} z dalších {count} zbývajících odpovídajících příspěvků…",
        "last": {
          "multiple": "Načítání posledního {count} odpovídajícího příspěvku… | Načítání posledních {count} odpovídajících příspěvků… | Načítání posledních {count} odpovídajících příspěvků… | Načítání posledních {count} odpovídajících příspěvků…",
          "one": "Načítání posledního odpovídajícího příspěvku…"
        }
      }
    }
  },
  "de": {
    "submission": {
      "withoutCount": "Übermittlungen laden...",
      "all": "{count} Übermittlung laden... | {count} Übermittlungen laden...",
      "first": "Lade die ersten {top} von {count} Übermittlung... | Lade die ersten {top} von {count} Übermittlungen...",
      "middle": "Lade weitere {top} von {count} übrigen Übermittlung... | Lade weitere {top} von {count} übrigen Übermittlungen...",
      "last": {
        "multiple": "Die letzte {count} Übermittlung laden... | Die letzten {count} Übermittlungen laden...",
        "one": "Letzte Übermittlung laden..."
      },
      "filtered": {
        "withoutCount": "Lade passende Übermittlungen...",
        "middle": "Lade weitere {top} von {count} übrigen passenden Übermittlung... | Lade weitere {top} von {count} übrigen passenden Übermittlungen...",
        "last": {
          "multiple": "Lade die letzte {count} passenden Übermittlung... | Lade die letzten {count} passenden Übermittlungen...",
          "one": "Lade die letzten passenden Übermittlungen..."
        }
      }
    }
  },
  "es": {
    "submission": {
      "withoutCount": "Cargando los envíos...",
      "all": "Cargando {count} envío... | Cargando {count} envíos... | Cargando {count} envíos...",
      "first": "Cargando la primera {top} de {count} envios... | Cargando la primera {top} de {count} envios... | Cargando la primera {top} de {count} envios...",
      "middle": "Cargando {top} más de {count} envíos restantes... | Cargando {top} más de {count} envíos restantes... | Cargando {top} más de {count} envíos restantes...",
      "last": {
        "multiple": "Cargando el último {count} envío... | Cargando los últimos {count} envíos... | Cargando los últimos {count} envíos...",
        "one": "Cargando el último envío..."
      },
      "filtered": {
        "withoutCount": "Cargando envíos coincidentes…",
        "middle": "Cargando {top} más de {count} envíos restantes coincidentes... | Cargando {top} más de {count} envíos restantes coincidentes... | Cargando {top} más de {count} envíos restantes coincidentes...",
        "last": {
          "multiple": "Cargando los últimos {count} envíos coincidentes… | Cargando los últimos {count} envíos coincidentes… | Cargando los últimos {count} envíos coincidentes…",
          "one": "Cargando el último envío coincidente…"
        }
      }
    }
  },
  "fr": {
    "entity": {
      "withoutCount": "Chargement des entités...",
      "all": "Chargement de {count} entité... | Chargement de {count} entités... | Chargement de {count} entités...",
      "first": "Chargement de la premières {top} de {count} entité... | Chargement des premières {top} de {count} entités... | Chargement des premières {top} de {count} entités...",
      "middle": "Chargement de {top} autre des {count} entités restantes... | Chargement de {top} autres des {count} entités restantes... | Chargement de {top} autres des {count} entités restantes...",
      "last": {
        "multiple": "Chargement de la dernière {count} entité... | Chargement des dernières {count} entités... | Chargement des dernières {count} entités...",
        "one": "Chargement de la dernière entité..."
      }
    },
    "submission": {
      "withoutCount": "Chargement des soumissions...",
      "all": "Chargement de {count} soumission... | Chargement de {count} soumissions... | Chargement de {count} soumissions...",
      "first": "Chargement des premières {top} sur {count} soumissions... | Chargement des premières {top} sur {count} soumissions... | Chargement des premières {top} de {count} soumissions...",
      "middle": "Chargement de {top} autres de {count} soumission restante... | Chargement de {top} autres des {count} soumissions restantes... | Chargement de {top} autres des {count} soumissions restantes...",
      "last": {
        "multiple": "Chargement de la {count} dernière soumissions... | Chargement des {count} dernières soumissions... | Chargement des {count} dernières soumissions...",
        "one": "Chargement la dernière soumission..."
      },
      "filtered": {
        "withoutCount": "Chargement des soumissions correspondantes...",
        "middle": "Chargement de {top} autres des {count} soumissions correspondantes restantes... | Chargement de {top} autres des {count} soumissions correspondantes restantes... | Chargement de {top} autres des {count} soumissions correspondantes restantes...",
        "last": {
          "multiple": "Chargement d'{count} dernière soumission correspondante... | Chargement des {count} dernières soumissions correspondantes... | Chargement des {count} dernières soumissions correspondantes...",
          "one": "Chargement de la dernière soumission correspondante..."
        }
      }
    }
  },
  "id": {
    "submission": {
      "withoutCount": "Memuat kiriman data...",
      "all": "Memuat {count} kiriman data...",
      "first": "Memuat yang pertama {top} dari {count} Pengiriman…",
      "middle": "Memuat {top} dari {count} sisa Pengiriman…",
      "last": {
        "multiple": "Memuat {count} kiriman data terakhir...",
        "one": "Memuat kiriman data terakhir..."
      },
      "filtered": {
        "withoutCount": "Memuat Pengiriman yang cocok...",
        "middle": "Memuat {top} dari {count} sisa Pengiriman yang cocok…",
        "last": {
          "multiple": "Memuat sisa {count} Pengiriman yang cocok…",
          "one": "Memuat Pengiriman terakhir yang cocok"
        }
      }
    }
  },
  "it": {
    "submission": {
      "withoutCount": "Caricando invii...",
      "all": "Cricando {count} invio... | Cricando {count} invii... | Caricando {count} invii...",
      "first": "Loading the first {top} of {count} Submission… | Caricando il primo {top} di {count} Invio… | Caricando il primo {top} di {count} Invio…",
      "middle": "Caricamento di {top} in più di {count} invio rimanente... | Caricamento di {top} in più di {count} invii rimanenti... | Caricamento di {top} in più di {count} invii rimanenti...",
      "last": {
        "multiple": "Caricando l'ultimo {count} invio… | Caricando gli ultimi {count} invii… | Caricando gli ultimi {count} invii…",
        "one": "Caricamento dell'ultimo invio in corso..."
      },
      "filtered": {
        "withoutCount": "Caricando invii corrispondenti...",
        "middle": "Caricamento di {top} in più di {count} invio corrispondente rimanente... | Caricamento di {top} in più di {count} invii corrispondenti rimanenti... | Caricamento di {top} in più di {count} invii corrispondenti rimanenti...",
        "last": {
          "multiple": "Caricando l'ultimo {count} invio corrispondente… | Caricando gli ultimi {count} invii corrispondenti… | Caricando gli ultimi {count} invii corrispondenti…",
          "one": "Caricando gli ultimi invii corrispondenti..."
        }
      }
    }
  },
  "ja": {
    "submission": {
      "withoutCount": "提出済フォームの読み込み中...",
      "all": "{count}の提出済フォームを読み込み中...",
      "first": "{count}件の提出済フォームの内、最初の{top}を読み込み中...",
      "middle": "残り{count}件の提出済フォームの内、さらに{top}件を読み込み中...",
      "last": {
        "multiple": "最後の{count}件の提出済フォームを読み込み中...",
        "one": "最後の提出済フォームを読み込み中..."
      },
      "filtered": {
        "withoutCount": "照合できる提出済フォームの読み込み中...",
        "middle": "一致する残り{count}件の提出済フォームの内、さらに{top}件を読み込み中...",
        "last": {
          "multiple": "一致する最後の{count}件の提出済フォームを読み込み中...",
          "one": "最後の照合できる提出済フォームを読み込み中..."
        }
      }
    }
  },
  "sw": {
    "submission": {
      "withoutCount": "Inapakia Mawasilisho...",
      "all": "Inapakia Mawasilisho {count}... | Inapakia Mawasilisho {count}...",
      "first": "Inapakia {top} ya kwanza kati ya Mawasilisho {count}... | Inapakia {top} ya kwanza kati ya Mawasilisho {count}...",
      "middle": "Inapakia {top} zaidi ya Mawasilisho {count} yaliyosalia... | Inapakia {top} zaidi ya Mawasilisho {count} yaliyosalia...",
      "last": {
        "multiple": "Inapakia Mawasilisho {count} ya mwisho... | Inapakia Mawasilisho {count} ya mwisho...",
        "one": "Inapakia Wasilisho la mwisho..."
      },
      "filtered": {
        "withoutCount": "Inapakia Mawasilisho yanayolingana...",
        "middle": "Inapakia {top} zaidi ya Mawasilisho {count} yanayolingana... | Inapakia {top} zaidi ya Mawasilisho {count} yanayolingana...",
        "last": {
          "multiple": "Inapakia Mawasilisho {count} ya mwisho yanayolingana... | Inapakia Mawasilisho {count} ya mwisho yanayolingana...",
          "one": "Inapakia Wasilisho linalolingana la mwisho..."
        }
      }
    }
  }
}
</i18n>
