<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->

<template>
  <div class="table-refresh-bar">
    <span v-if="odata.dataExists">
      {{ $t('dataRefreshTime', { date: formatDate(dataRefreshedAt), time: formatTime(dataRefreshedAt) }) }}
    </span>
    <button id="refresh-button" type="button"
      class="btn btn-link" :aria-disabled="refreshing"
      @click="$emit('refreshClick')">
      <span class="icon-refresh"></span>{{ $t('action.refresh') }}
      <spinner :state="refreshing"/>
    </button>
  </div>
</template>

<script setup>
import { DateTime } from 'luxon';
import { computed } from 'vue';
import { formatDate, formatTime } from '../util/date-time';
import Spinner from './spinner.vue';

const props = defineProps({
  odata: Object,
  refreshing: Boolean
});

defineEmits(['refreshClick']);

const dataRefreshedAt = computed(() => DateTime.fromJSDate(props.odata.setAt));

</script>

<style lang="scss">
.table-refresh-bar {
  display: flex;
  align-items: center;
  margin-bottom: 10px;

  span {
    font-size: 12px;
    margin-right: 10px;
  }
}
</style>

<i18n lang="json5">
  {
  "en": {
    // Text shown above the data tables to tell users when data was last fetched / refreshed.
    // {date} is only the date component and {time} is only the time component.
    "dataRefreshTime": "Data last refreshed on {date} at {time}"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "dataRefreshTime": "Daten zuletzt aktualisiert am {date} um {time}"
  },
  "es": {
    "dataRefreshTime": "Última actualización de los datos el {date} a las {time}"
  },
  "fr": {
    "dataRefreshTime": "Données rafraîchies le {date} à {time}"
  },
  "it": {
    "dataRefreshTime": "Ultimo aggiornamento dei dati il {date} alle {time}"
  },
  "pt": {
    "dataRefreshTime": "Última atualização dos dados em {date} às {time}"
  },
  "zh": {
    "dataRefreshTime": "数据最后更新于{date}日{time}时"
  },
  "zh-Hant": {
    "dataRefreshTime": "資料最後重新整理時間：{date}{time}"
  }
}
</i18n>
