<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<!-- eslint-disable vuejs-accessibility/alt-text -->
<template>
  <modal id="whats-new-modal" :state="isVisible" backdrop :hideable="true" @hide="hideModal">
    <template #banner>
      <img
        srcset="../assets/images/whats-new/banner@1x.png, ../assets/images/whats-new/banner@2x.png 2x"
        src="../assets/images/whats-new/banner@1x.png">
    </template>
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <p class="modal-introduction">
        {{ $t('body') }}
      </p>
      <div class="modal-actions">
        <div v-if="!initialOptIn" class="checkbox">
          <label><input v-model="mailingListOptIn" type="checkbox">{{ $t('analytics.mailingListOptIn') }}</label>
        </div>
        <button type="button" class="btn btn-primary"
          @click="hideModal">
          {{ $t('action.done') }}
        </button>
      </div>
    </template>
  </modal>
</template>

<script setup>
import { inject, ref, watch } from 'vue';

import Modal from './modal.vue';

import { useRequestData } from '../request-data';

defineOptions({
  name: 'WhatsNew'
});

const { openModal } = inject('container');
const { currentUser, projects } = useRequestData();

const isVisible = ref(false);
const initialOptIn = currentUser.preferences.site.mailingListOptIn;
const mailingListOptIn = ref(currentUser.preferences.site.mailingListOptIn !== false);

const currentVersion = '2026.1';

const isOlderVersion = (stored, current) => {
  // compare stored vs. current year & release
  const [sy, sr] = stored.split('.').map(Number);
  const [cy, cr] = current.split('.').map(Number);
  return sy < cy || (sy === cy && sr < cr);
};

watch(() => projects.dataExists, () => {
  const showModal = !currentUser.preferences.site.whatsNewDismissed ||
    isOlderVersion(currentUser.preferences.site.whatsNewDismissed, currentVersion);

  // When updating `canUpdateForm` in the future, consider the *verb* for the audience.
  // For 2025.4, we decided it could be shown to project viewers as well,
  // where the previous modal was only shown to admins and project managers.
  const canUpdateForm = currentUser.can('submission.list') ||
    projects.data.some(project => project.verbs.has('submission.list'));
  if (canUpdateForm && // Check that user is admin or is able to edit forms in at least one project
    !openModal.state && // Check that no other modal (e.g. new project) is open
    showModal) {
    isVisible.value = true;
  }
});

function hideModal() {
  currentUser.preferences.site.whatsNewDismissed = currentVersion;

  // If user was not already opted in and preference changed, then save preference.
  if (!initialOptIn && mailingListOptIn.value !== initialOptIn) {
    currentUser.preferences.site.mailingListOptIn = mailingListOptIn.value;
  }
  isVisible.value = false;
}

</script>

<style lang="scss">
@import '../assets/scss/variables';

#whats-new-modal h4 {
  white-space: wrap;
}

#whats-new-modal .modal-actions {
  display: flex;
  column-gap: 10px;
  align-items: center;

  .checkbox {
    flex: 1;
    margin-bottom: 0px;
    font-size: 12px;

    label {
      display: block;
      text-align: left;
    }

    input[type=checkbox] {
      margin-top: 2px;
    }
  }

  .btn {
    margin-left: auto;
  }
}
</style>

<i18n lang="json5">
  {
    "en": {
      // This is the title at the top of a pop-up.
      "title": "🎨 Branded login pages, Entity List cleanups, and file uploads in Web Forms",
      "body": "Customize the login page with your branding, clean up Entity Lists and Properties when they are no longer needed, and upload any file to your web form."
    }
  }
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "title": "Löschen von Entitäten und Eigenschaften ️🗑️, Erstellung von Entitäten 🪄sowie individuelles Branding auf der Anmeldeseite 🎨",
    "body": "Bereinigen Sie Entitätslisten und Eigenschaften, wenn diese nicht mehr benötigt werden, erstellen Sie Entitäten schnell direkt über die Benutzeroberfläche von Central und passen Sie die Anmeldeseite so an, dass Ihr Server das Corporate Design Ihrer Organisation widerspiegelt und das Vertrauen der Benutzer stärkt."
  },
  "es": {
    "title": "Eliminación de la lista de entidades y de propiedades ️🗑️, Creación de entidades 🪄y personalización de la identidad corporativa en la página de inicio de sesión 🎨",
    "body": "Elimina las listas de entidades y las propiedades cuando ya no sean necesarias, crea rápidamente entidades directamente desde la interfaz de usuario de Central y personaliza la página de inicio de sesión para que tu servidor refleje la imagen de tu organización y genere confianza entre los usuarios."
  },
  "fr": {
    "title": "Suppression de listes d'entités 🗑️, création d'entités 🪄 et personnalisation de la page de connexion 🎨"
  },
  "it": {
    "title": "Eliminazione dell'elenco delle entità e delle proprietà ️🗑️, Creazione di entità 🪄e personalizzazione del branding nella pagina di accesso 🎨",
    "body": "Elimina gli elenchi di entità e le proprietà quando non sono più necessari, crea rapidamente entità direttamente dall'interfaccia utente di Central e personalizza la pagina di accesso in modo che il tuo server rispecchi l'immagine del tuo brand e rafforzi la fiducia degli utenti."
  },
  "zh": {
    "title": "实体列表与属性删除🗑️、实体创建🪄以及登录页面的自定义品牌标识🎨",
    "body": "当实体列表和属性不再需要时进行清理，直接从 Central 用户界面快速创建实体，并自定义登录页面，使您的服务器体现组织品牌形象，建立用户信任。"
  }
}
</i18n>
