<!--
Copyright 2023 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <page-section id="entity-basic-details">
    <template #heading><span><span class="icon-database"></span>{{ $t('entityDetails') }}</span></template>
    <template #body>
      <dl v-if="entity.dataExists">
        <div>
          <dt>{{ $t('entity.entityId') }}</dt>
          <dd>{{ entity.uuid }}</dd>
        </div>
        <div v-if="submission != null">
          <dt>{{ $t('creatingSubmission') }}</dt>
          <dd id="entity-basic-details-creating-submission">
            <submission-link v-if="submission.currentVersion != null"
              :project-id="projectId" :xml-form-id="submission.xmlFormId"
              :submission="submission"/>
            <template v-else>
              <span class="icon-trash" v-tooltip.sr-only></span>
              <span>{{ submission.instanceId }}</span>
              <span class="sr-only">&nbsp;{{ $t('submissionDeleted') }}</span>
            </template>
          </dd>
        </div>
        <div v-else-if="source?.name != null">
          <dt>{{ $t('creatingSource') }}</dt>
          <dd id="entity-basic-details-creating-source">{{ $t('upload') }}</dd>
        </div>
        <div>
          <dt>{{ $t('header.createdAt') }}</dt>
          <dd><date-time :iso="entity.createdAt"/></dd>
        </div>
        <div>
          <dt>{{ $t('header.createdBy') }}</dt>
          <dd><actor-link :actor="entity.creator"/></dd>
        </div>
      </dl>
    </template>
  </page-section>
</template>

<script setup>
import { inject, ref, watchEffect } from 'vue';

import ActorLink from '../actor-link.vue';
import DateTime from '../date-time.vue';
import PageSection from '../page/section.vue';
import SubmissionLink from '../submission/link.vue';

import { useRequestData } from '../../request-data';

defineOptions({
  name: 'EntityBasicDetails'
});

const projectId = inject('projectId');

// The component does not assume that this data will exist when the component is
// created.
const { entity, audits } = useRequestData();

// Using `ref` and watchEffect() for `source` rather than
// `computed` so that it doesn't change whenever `audits` is refreshed.
const source = ref(undefined);
const submission = ref(undefined); // submission is contained within source
watchEffect(() => {
  // if we don't have the audit data yet, or if we have already found the source, return.
  if ((!audits.dataExists || source.value !== undefined)) return;
  const audit = audits.find(({ action }) => action === 'entity.create' || action === 'entity.bulk.create');
  // `audit` should always exist in production, but it doesn't always exist in
  // testing.
  if (audit == null) return;
  submission.value = audit.details.source?.submission;
  source.value = audit.details.source;
});
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

#entity-basic-details {
  .icon-database {
    @include icon-box;
    font-size: 20px;
    margin-right: $margin-right-icon;
  }

  margin-bottom: 35px;

  dd { @include text-overflow-ellipsis; }
  .icon-trash { margin-right: $margin-right-icon; }
}
</style>

<i18n lang="json5">
{
  "en": {
    "entityDetails": "Entity Details",
    // This is shown above the Submission that created the Entity.
    "creatingSubmission": "Creating Submission",
    // This is shown above the source (e.g. a CSV file) that created the entity
    "creatingSource": "Creating source",
    // This describes an "upload" being a generic source of an entity
    "upload": "Upload",
    "submissionDeleted": "This Submission has been deleted."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "creatingSubmission": "Vytvoření podání",
    "submissionDeleted": "Toto podání bylo smazáno."
  },
  "de": {
    "entityDetails": "Objektdetails",
    "creatingSubmission": "Übermittlung erstellen",
    "creatingSource": "Quelle erstellen",
    "upload": "Hochladen",
    "submissionDeleted": "Diese Übermittlungen wurde gelöscht."
  },
  "es": {
    "entityDetails": "Detalles de la entidad",
    "creatingSubmission": "Creando envío",
    "creatingSource": "Creando fuente",
    "upload": "Subir",
    "submissionDeleted": "Este envío ha sido borrado."
  },
  "fr": {
    "entityDetails": "Détail de l'entité",
    "creatingSubmission": "Soumission à l'origine de l'entité",
    "creatingSource": "Création de la source",
    "upload": "Envoi",
    "submissionDeleted": "La Soumission a été supprimée."
  },
  "id": {
    "creatingSubmission": "Membuat Kiriman Data"
  },
  "it": {
    "entityDetails": "Dettaglio Entità",
    "creatingSubmission": "Creando invio",
    "creatingSource": "Creazione della fonte",
    "upload": "Carica",
    "submissionDeleted": "Questo invio è stato eliminato."
  },
  "pt": {
    "entityDetails": "Detalhes da Entidade",
    "creatingSubmission": "Criando Resposta",
    "creatingSource": "Criando fonte",
    "upload": "Fazer upload",
    "submissionDeleted": "Esta Resposta foi excluída."
  },
  "sw": {
    "creatingSubmission": "Kuunda Uwasilishaji",
    "submissionDeleted": "Wasilisho hili limefutwa."
  },
  "zh": {
    "entityDetails": "实体详情",
    "creatingSubmission": "正在创建提交",
    "creatingSource": "正在创建来源",
    "upload": "上传",
    "submissionDeleted": "此提交已被删除。"
  },
  "zh-Hant": {
    "entityDetails": "實體詳細資料",
    "creatingSubmission": "建立提交",
    "creatingSource": "建立來源",
    "upload": "更新",
    "submissionDeleted": "此提交已被刪除"
  }
}
</i18n>
