<!--
Copyright 2023 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <router-link :to="versionPath">{{ text }}</router-link>
</template>

<script setup>
import { computed, inject } from 'vue';
import { useI18n } from 'vue-i18n';

import useRoutes from '../../composables/routes';

defineOptions({
  name: 'EntityVersionLink'
});
const props = defineProps({
  uuid: {
    type: String,
    required: true
  },
  version: {
    type: Object,
    required: true
  }
});

const { entityPath } = useRoutes();
const projectId = inject('projectId');
const datasetName = inject('datasetName');
const versionPath = computed(() => {
  const path = entityPath(projectId, datasetName, props.uuid);
  return `${path}#v${props.version.version}`;
});

const { t } = useI18n();
const text = computed(() => {
  const { source } = props.version;
  const { submission, name } = source;
  if (submission != null) {
    const nameOrId = submission.currentVersion?.instanceName ??
      submission.instanceId;
    return t('submission', { instanceName: nameOrId });
  }
  if (name != null) {
    return t('bulk', { filename: name, name: props.version.creator.displayName });
  }
  return t('api', { name: props.version.creator.displayName });
});
</script>

<i18n lang="json5">
{
  "en": {
    // This text is shown for a Submission. {instanceName} is the instance name
    // of the Submission.
    "submission": "Submission {instanceName}",
    // This refers to an update to an Entity. {name} is the name of a Web User.
    "api": "Update by {name}",
    // This refers to creation of an Entity. {filename} is the name of
    // an uploaded file containing the Entity. {name} is the name of a Web User.
    "bulk": "File {filename} upload by {name}"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "submission": "Odeslání {instanceName}",
    "api": "Aktualizace od {name}"
  },
  "de": {
    "submission": "Übermittlung {instanceName}",
    "api": "Update von {name}",
    "bulk": "Datei {filename} hochgeladen von {name}"
  },
  "es": {
    "submission": "Envío {instanceName}",
    "api": "Actualizar por {name}",
    "bulk": "Archivo {filename} subido por {name}"
  },
  "fr": {
    "submission": "Soumission {instanceName}",
    "api": "Mise à jour par {name}",
    "bulk": "Envoi du fichier {filename} par {name}"
  },
  "it": {
    "submission": "Invio {instanceName}",
    "api": "Aggiornato da {name}",
    "bulk": "File {filename} caricato da {name}"
  },
  "pt": {
    "submission": "Resposta {instanceName}",
    "api": "Atualização por {name}",
    "bulk": "Arquivo {filename} carregado por {name}"
  },
  "zh": {
    "submission": "提交{instanceName}",
    "api": "由{name}更新",
    "bulk": "文件{filename}由{name}上传"
  },
  "zh-Hant": {
    "submission": "提交{instanceName}",
    "api": "由 {name}更新",
    "bulk": "檔案{filename} 由 2{name}上傳"
  }
}
</i18n>
