<!--
Copyright 2021 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <label id="submission-filters-review-state" class="form-group">
    <select v-model="selectValue" class="form-control">
      <option value="">{{ $t('anyState') }}</option>
      <option value="null">{{ $t('reviewState.null') }}</option>
      <option value="'approved'">{{ $t('reviewState.approved') }}</option>
      <option value="'hasIssues'">{{ $t('reviewState.hasIssues') }}</option>
      <option value="'edited'">{{ $t('reviewState.edited') }}</option>
      <option value="'rejected'">{{ $t('reviewState.rejected') }}</option>
    </select>
    <span class="form-label">{{ $t('field.reviewState') }}</span>
  </label>
</template>

<script>
export default {
  name: 'SubmissionFiltersReviewState',
  props: {
    // `value` is an array because at one point, the filter was a
    // <select multiple>. However, the native <select multiple> was a confusing
    // user experience, so we made the filter a single-select. `value` is still
    // an array because the filter will hopefully become a multiselect again at
    // some point (one with an improved user experience).
    value: {
      type: Array,
      required: true
    }
  },
  computed: {
    selectValue: {
      get() {
        return this.value.length !== 0 ? this.value[0] : '';
      },
      set(value) {
        this.$emit('input', value !== '' ? [value] : []);
      }
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    // This text is shown in a dropdown that allows the user to filter to show
    // only Submissions in a particular Review State.
    "anyState": "(Any State)"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "anyState": "(Jakýkoli stav)"
  },
  "de": {
    "anyState": "(Beliebiger Status)"
  },
  "es": {
    "anyState": "(Cualquier estado)"
  },
  "fr": {
    "anyState": "(Tous états)"
  },
  "it": {
    "anyState": "(Qualsiasi Stato)"
  },
  "sw": {
    "anyState": "(hali lolote)"
  }
}
</i18n>
