<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <label id="submission-filters-submitter" class="form-group">
    <select v-if="initiallyLoading" class="form-control" disabled>
      <option value="">{{ $t('common.loading') }}</option>
    </select>
    <select v-else v-model="selectValue" class="form-control">
      <option value="">{{ $t('common.anybody') }}</option>
      <option v-if="unknown" :value="value">{{ $t('unknown') }}</option>
      <option v-for="submitter of submitters" :key="submitter.id"
        :value="submitter.id.toString()">
        {{ submitter.displayName }}
      </option>
    </select>
    <span class="form-label">{{ $t('field.submitter') }}</span>
  </label>
</template>

<script>
import { requestData } from '../../../store/modules/request';

export default {
  name: 'SubmissionFiltersSubmitter',
  props: {
    value: {
      type: String,
      required: true
    }
  },
  emits: ['update:modelValue'],
  computed: {
    // The component does not assume that this data will exist when the
    // component is created.
    ...requestData(['submitters']),
    initiallyLoading() {
      return this.$store.getters.initiallyLoading(['submitters']);
    },
    selectValue: {
      get() {
        return this.value;
      },
      set(value) {
        this.$emit('input', value);
      }
    },
    unknown() {
      return this.value !== '' &&
        !this.submitters.some(submitter => this.value === submitter.id.toString());
    }
  }
};
</script>

<style lang="scss">
#submission-filters-submitter {
  select { width: 201px; }
}
</style>

<i18n lang="json5">
{
  "en": {
    "field": {
      // This is the text of a form field that shows the names of users who have
      // submitted data.
      "submitter": "Submitted by"
    },
    "unknown": "Unknown submitter"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "field": {
      "submitter": "Odesláno od"
    },
    "unknown": "Neznámý odesílatel"
  },
  "de": {
    "field": {
      "submitter": "Übermittelt von"
    }
  },
  "es": {
    "field": {
      "submitter": "Enviado por"
    },
    "unknown": "Remitente desconocido"
  },
  "fr": {
    "field": {
      "submitter": "Soumis par"
    }
  },
  "id": {
    "field": {
      "submitter": "Terkirim oleh"
    }
  },
  "it": {
    "field": {
      "submitter": "Inviato da"
    },
    "unknown": "Utente invio sconosciuto"
  },
  "ja": {
    "field": {
      "submitter": "フォーム送信者"
    }
  },
  "sw": {
    "field": {
      "submitter": "Iliyowasilishwa na"
    }
  }
}
</i18n>
