<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <multiselect id="submission-filters-submitter" :model-value="modelValue"
    :options="options" :loading="submitters.initiallyLoading"
    :label="$t('field.submitter')" :placeholder="placeholder"
    :all="$t('action.select.all')" :none="$t('action.select.none')"
    :search="$t('field.search')" :empty="$t('submission.emptyTable')"
    @update:model-value="update"/>
</template>

<script>
export default {
  name: 'SubmissionFiltersSubmitter'
};
</script>
<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import Multiselect from '../../multiselect.vue';

import { useRequestData } from '../../../request-data';

const props = defineProps({
  modelValue: {
    type: Array,
    required: true
  }
});
const emit = defineEmits(['update:modelValue']);

// The component does not assume that this data will exist when the
// component is created.
const { submitters } = useRequestData();

const { t } = useI18n();
const unknown = computed(() => props.modelValue.reduce(
  (set, id) => (submitters.ids.has(id) ? set : set.add(id)),
  new Set()
));
const options = computed(() => {
  if (!submitters.dataExists) return null;
  const result = submitters.map(({ id, displayName }) =>
    ({ value: id, text: displayName }));
  for (const id of unknown.value)
    result.unshift({ value: id, text: t('unknown') });
  return result;
});

const update = (value) => {
  const withoutUnknown = unknown.value.size === 0
    ? value
    : value.filter(id => !unknown.value.has(id));
  if (withoutUnknown.length !== 0)
    emit('update:modelValue', withoutUnknown);
  // If no submitters or only unknown submitters are selected, then the
  // selection falls back to all submitters. But it could be that that's the
  // selection already, in which case there is no change to emit.
  else if (!(props.modelValue.length === submitters.length &&
    unknown.value.size === 0))
    emit('update:modelValue', [...submitters.ids]);
};

const placeholder = (counts) => t('placeholder', counts);
</script>

<i18n lang="json5">
{
  "en": {
    "field": {
      // This is the text of a form field that shows the names of submitters.
      "submitter": "Submitted by",
      "search": "Search submitters…"
    },
    // This is the text of a dropdown that allows the user to select one or more
    // "submitters". A submitter can be a user, a team of users, a Public Access
    // Link, or an automation. {selected} is the number of submitters selected;
    // {total} is the total number of submitters.
    "placeholder": "{selected} of {total}",
    "action": {
      "select": {
        /* This is the text of a dropdown that allows the user to select one or
        more submitters. It will be inserted where {all} is in the following
        text:

        Select {all} / {none} */
        "all": "All",
        /* This is the text of a dropdown that allows the user to select one or
        more submitters. It will be inserted where {none} is in the following
        text:

        Select {all} / {none} */
        "none": "None"
      }
    },
    "unknown": "Unknown submitter"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "field": {
      "submitter": "Odesláno od"
    },
    "unknown": "Neznámý odesílatel"
  },
  "de": {
    "field": {
      "submitter": "Übermittelt von"
    },
    "unknown": "Unbekannter Einsender"
  },
  "es": {
    "field": {
      "submitter": "Enviado por"
    },
    "unknown": "Remitente desconocido"
  },
  "fr": {
    "field": {
      "submitter": "Soumis par"
    },
    "unknown": "Expéditeur inconnu"
  },
  "id": {
    "field": {
      "submitter": "Terkirim oleh"
    }
  },
  "it": {
    "field": {
      "submitter": "Inviato da"
    },
    "unknown": "Utente invio sconosciuto"
  },
  "ja": {
    "field": {
      "submitter": "フォーム送信者"
    }
  },
  "sw": {
    "field": {
      "submitter": "Iliyowasilishwa na"
    }
  }
}
</i18n>
