<!--
Copyright 2019 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <table id="audit-table" class="table">
    <thead>
      <tr>
        <th class="logged-at">{{ $t('header.time') }}</th>
        <th>{{ $t('header.type') }}</th>
        <th>{{ $t('header.initiator') }}</th>
        <th>{{ $t('header.target') }}</th>
        <th>{{ $t('header.details') }}</th>
      </tr>
    </thead>
    <tbody v-if="audits.dataExists">
      <audit-row v-for="(audit, index) in audits" :key="index" :audit="audit"/>
    </tbody>
  </table>
</template>

<script>
export default {
  name: 'AuditTable'
};
</script>
<script setup>
import AuditRow from './row.vue';

import { useRequestData } from '../../request-data';

const { audits } = useRequestData();
</script>

<style lang="scss">
#audit-table {
  table-layout: fixed;
  th.logged-at { width: 150px; }
}
</style>

<i18n lang="json5">
{
  "en": {
    "header": {
      "initiator": "Initiator",
      "target": "Target",
      "details": "Details"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "header": {
      "initiator": "Iniciátor",
      "target": "Cíl",
      "details": "Detaily"
    }
  },
  "de": {
    "header": {
      "initiator": "Initiator",
      "target": "Ziel",
      "details": "Details"
    }
  },
  "es": {
    "header": {
      "initiator": "Iniciador",
      "target": "Objetivo",
      "details": "Detalles"
    }
  },
  "fr": {
    "header": {
      "initiator": "Initiateur",
      "target": "Cible",
      "details": "Détails"
    }
  },
  "id": {
    "header": {
      "initiator": "Pemrakarsa",
      "target": "Target",
      "details": "Rincian"
    }
  },
  "it": {
    "header": {
      "initiator": "Iniziatore",
      "target": "Obbiettivo",
      "details": "Dettagli"
    }
  },
  "ja": {
    "header": {
      "initiator": "操作者",
      "target": "操作の対象",
      "details": "詳細"
    }
  },
  "sw": {
    "header": {
      "initiator": "Mwanzilishi",
      "target": "Lengo",
      "details": "Maelezo"
    }
  }
}
</i18n>
