<!--
Copyright 2023 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <multiselect id="entity-filters-conflict" :model-value="modelValue"
    :options="options" default-to-all :label="$t('field.conflict')"
    :placeholder="placeholder" :all="$t('action.all')"
    :none="$t('action.none')"
    @update:model-value="$emit('update:modelValue', $event)"/>
</template>

<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import Multiselect from '../../multiselect.vue';

defineOptions({
  name: 'EntityFiltersConflict'
});
defineProps({
  modelValue: {
    type: Array,
    required: true
  }
});
defineEmits(['update:modelValue']);

const { t } = useI18n();
const options = computed(() => [true, false].map(value =>
  ({ value, text: t(`conflict.${value}`) })));
const placeholder = (counts) => {
  if (counts.total === counts.selected) return t('action.all');

  // counts are already localized by multiselect component
  return counts.selected;
};
</script>

<style lang="scss">
#entity-filters-conflict .none {
  font-style: italic;
}
</style>

<i18n lang="json5">
{
  "en": {
    // This is an option in a dropdown that allows the user to select one or
    // more conflict statuses.
    "conflict": {
      "true": "Possible conflict",
      "false": "No conflict"
    },
    "field": {
      "conflict": "Conflict status"
    },
    "action": {
      /*
      This is the text of the button in dropdown menu of conflict statuses filter,
      that allows the user to select all conflict statuses.
      */
      "all": "All",
      /*
        This is the text of the button in dropdown menu of conflict statuses filter,
      that allows the user to unselect all conflict statuses.
      */
      "none": "None"
    },
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "conflict": {
      "true": "Možný konflikt",
      "false": "Žádný konflikt"
    },
    "field": {
      "conflict": "Stav konfliktu"
    }
  },
  "de": {
    "conflict": {
      "true": "Mögliche Konflikte",
      "false": "Kein Konflikt"
    },
    "field": {
      "conflict": "Konfliktstatus"
    },
    "action": {
      "all": "Alle",
      "none": "Keine"
    }
  },
  "es": {
    "conflict": {
      "true": "Posible conflicto",
      "false": "Sin conflicto"
    },
    "field": {
      "conflict": "Estado de conflicto"
    },
    "action": {
      "all": "Todos",
      "none": "Ninguno"
    }
  },
  "fr": {
    "conflict": {
      "true": "Conflit possible",
      "false": "Aucun conflit"
    },
    "field": {
      "conflict": "Statut du conflit"
    },
    "action": {
      "all": "Tous",
      "none": "Aucun"
    }
  },
  "it": {
    "conflict": {
      "true": "Possibilie conflitto",
      "false": "Nessun conflitto"
    },
    "field": {
      "conflict": "Stato sui conflitti"
    },
    "action": {
      "all": "Tutto",
      "none": "Nessuno/a"
    }
  },
  "pt": {
    "conflict": {
      "true": "Possível conflito",
      "false": "Nenhum conflito"
    },
    "field": {
      "conflict": "Status de conflitos"
    },
    "action": {
      "all": "Todos",
      "none": "Nenhum"
    }
  },
  "sw": {
    "conflict": {
      "true": "Mzozo unaowezekana",
      "false": "Hakuna mgongano"
    },
    "field": {
      "conflict": "Hali ya migogoro"
    }
  },
  "zh": {
    "conflict": {
      "true": "可能存在冲突",
      "false": "无冲突"
    },
    "field": {
      "conflict": "冲突状态"
    },
    "action": {
      "all": "全部",
      "none": "无"
    }
  },
  "zh-Hant": {
    "conflict": {
      "true": "可能發生衝突",
      "false": "沒有衝突"
    },
    "field": {
      "conflict": "衝突狀態"
    },
    "action": {
      "all": "全部",
      "none": "無"
    }
  }
}
</i18n>
