<template>
  <multiselect v-if="showViewAs" id="entity-filters-view-as" single :model-value="selectValue"
    :options="options" :loading="fieldKeys.initiallyLoading" :label="$t('viewAs')"
    :placeholder="placeholder" :none="$t('resetToMe')" :search="$t('search')"
    :disabled="disabled" :disabled-message="disabledMessage" @update:model-value="update"/>
</template>

<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRequestData } from '../../../request-data';

import Multiselect from '../../multiselect.vue';

const { t } = useI18n();

defineOptions({
  name: 'EntityFiltersViewAs'
});
const props = defineProps({
  modelValue: {
    type: Number,
    required: false
  },
  disabled: {
    type: Boolean,
    default: false
  },
  disabledMessage: {
    type: String,
    required: false
  }
});
const { dataset, fieldKeys } = useRequestData();

const showViewAs = computed(() =>
  dataset.dataExists && dataset.accessFilter != null);

const options = computed(() => (fieldKeys.dataExists
  ? fieldKeys.data.map(({ id, displayName }) => ({ value: id, text: displayName }))
  : null));
const selectValue = computed(() => {
  if (!fieldKeys.dataExists || props.modelValue == null) return [];
  return fieldKeys.data.some(fieldKey => fieldKey.id === props.modelValue)
    ? [props.modelValue]
    : [];
});

const emit = defineEmits(['update:modelValue']);

const update = (value) => { emit('update:modelValue', value[0] ?? null); };
const placeholder = ({ selectedText }) => selectedText ?? t('noUserSelected');
</script>

<i18n lang="json5">
{
  "en": {
    "noUserSelected": "Me",
    "viewAs": "View As",
    "resetToMe": "Reset to Me",
    "search": "Search App Users…"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "fr": {
    "noUserSelected": "Moi",
    "viewAs": "Voir comme"
  },
  "it": {
    "viewAs": "Vedi come"
  }
}
</i18n>
