#!/bin/bash -eu

log() {
  echo "[check-images] $*"
}

tmpDir="$(mktemp -d)"
cd "$tmpDir"

log "Fetching pngout..."
wget https://www.jonof.id.au/files/kenutils/pngout-20200115-linux.tar.gz

log "Verifying download integrity..."
[[ $(sha256sum pngout-20200115-linux.tar.gz | cut -d" " -f1) = ac38bba6f0de29033de866538c3afa64341319b695bbe388efbc5fd9e830e928 ]]

log "Extracting executable..."
tar -xf pngout-20200115-linux.tar.gz

log "Verifying executable integrity..."
[[ $(sha256sum pngout-20200115-linux/amd64/pngout | cut -d" " -f1) = c509286fccedd7529b32dfdee2b39906f06d35350034df6dfbf75a4c7dc9a0b5 ]]

cd -
log "Shrinking images..."
find src -type f -name '*.png' | xargs -I{} bash -c "
  '$tmpDir'/pngout-20200115-linux/amd64/pngout {}
  if [[ \$? = 1 ]]; then
    exit 1
  else
    exit 0
  fi
"

log "Checking for changes..."
if [[ "$(git status --porcelain)" != "" ]]; then
  git status
  log "!!! Changes detected !!!"
  exit 1
fi

log "Everything looks OK."
