<template>
  <div id="config-login-edit">
    <p class="file-label">{{ $t('logo.label') }}</p>
    <p>{{ $t('logo.help') }}</p>
    <config-login-file-select name="logo"/>

    <p class="file-label">{{ $t('login.heroImage') }}</p>
    <p>{{ $t('hero.help') }}</p>
    <config-login-file-select name="hero-image"/>

    <form>
      <div class="form-group">
        <label for="config-login-edit-title">{{ $t('field.title') }}</label>
        <p id="config-login-edit-title-help">{{ $t('title.help') }}</p>
        <div>
          <input id="config-login-edit-title" v-model.trim="newAppearance.title"
            class="form-control" aria-describedby="config-login-edit-title-help"
            :placeholder="$t('login.defaultTitle')"
            :aria-disabled="awaitingResponse" autocomplete="off"
            @blur="update('title')">
          <spinner :state="updating === 'title'"/>
        </div>
      </div>

      <div class="form-group">
        <label for="config-login-edit-description">{{ $t('description.label') }}</label>
        <p id="config-login-edit-description-help">{{ $t('description.help') }}</p>
        <div>
          <input id="config-login-edit-description" v-model.trim="newAppearance.description"
            class="form-control"
            aria-describedby="config-login-edit-description-help"
            :placeholder="$t('login.defaultDescription')"
            :aria-disabled="awaitingResponse" autocomplete="off"
            @blur="update('description')">
          <spinner :state="updating === 'description'"/>
        </div>
      </div>
    </form>
  </div>
</template>

<script setup>
import { reactive, ref } from 'vue';

import ConfigLoginFileSelect from './file-select.vue';
import Spinner from '../../spinner.vue';

import useRequest from '../../../composables/request';
import { noop } from '../../../util/util';
import { useRequestData } from '../../../request-data';

defineOptions({
  name: 'ConfigLoginEdit'
});

const { serverConfig } = useRequestData();

const newAppearance = reactive({
  title: '',
  description: '',
  ...serverConfig['login-appearance']?.value
});

const { request, awaitingResponse } = useRequest();
// The name of the login-appearance property that the current request is
// updating
const updating = ref(null);
const update = (prop) => {
  if (awaitingResponse.value) return;
  const currentValue = serverConfig['login-appearance']?.value[prop] ?? '';
  if (newAppearance[prop] === currentValue) return;

  updating.value = prop;
  const data = Object.fromEntries(Object.entries(newAppearance)
    .filter(([, value]) => value !== ''));
  request({ method: 'POST', url: '/v1/config/login-appearance', data })
    .then(response => { serverConfig['login-appearance'] = response.data; })
    .catch(noop)
    .finally(() => { updating.value = null; });
};
</script>

<style lang="scss">
#config-login-edit {
  .config-login-file-select, .form-group { margin-bottom: 20px; }

  .file-label, label { font-size: 16px; }
  label { font-weight: normal; }

  .form-group > div {
    display: flex;
    align-items: center;
  }
  .form-control {
    width: auto;
    flex-grow: 1;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "logo": {
      "label": "Logo",
      "help": "We recommend using a PNG logo with transparent background of at least 150x150 pixels."
    },
    "title": {
      "help": "A title for your server login."
    },
    "description": {
      "label": "Subtitle",
      "help": "Instructions for your users, a welcome message or a description of this server."
    },
    "hero": {
      "help": "Upload a vertical image, we recommend a 4:5 crop. Use a visually engaging image that represents your brand or message. The image will be cropped on different screen sizes, so keep important content centered."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "logo": {
      "label": "Logo"
    },
    "title": {
      "help": "Ein Titel für Ihre Server-Anmeldeseite."
    }
  },
  "es": {
    "logo": {
      "label": "Logotipo"
    },
    "title": {
      "help": "Un título para tu inicio de sesión en el servidor."
    }
  },
  "fr": {
    "logo": {
      "label": "Logo",
      "help": "Nous recommandons un logo en format PNG avec un arrière-plan transparent d'au moins 150x150 pixels."
    },
    "title": {
      "help": "Un titre pour la page de connexion."
    },
    "description": {
      "label": "Sous-titre",
      "help": "Instructions pour vos utilisateurs, un message de bienvenue ou une description de ce serveur."
    },
    "hero": {
      "help": "Importez une image verticale ; nous vous recommandons un recadrage au format 4:5. Utilisez une image visuellement attrayante qui représente votre marque ou votre message. L'image sera recadrée en fonction de la taille de l'écran ; veillez donc à centrer les éléments importants."
    }
  },
  "it": {
    "logo": {
      "label": "Logo"
    },
    "title": {
      "help": "Un titolo per il tuo accesso al server."
    }
  },
  "zh": {
    "logo": {
      "label": "标志"
    },
    "title": {
      "help": "您的服务器登录标题。"
    }
  }
}
</i18n>
