<template>
  <div id="config-login-edit">
    <p class="file-label">{{ $t('logo.label') }}</p>
    <p>{{ $t('logo.help') }}</p>
    <config-login-file-select name="logo"/>

    <p class="file-label">{{ $t('login.heroImage') }}</p>
    <p>{{ $t('hero.help') }}</p>
    <config-login-file-select name="hero-image"/>

    <form>
      <div class="form-group">
        <label for="config-login-edit-title">{{ $t('field.title') }}</label>
        <p id="config-login-edit-title-help">{{ $t('title.help') }}</p>
        <div>
          <input id="config-login-edit-title" v-model.trim="newAppearance.title"
            class="form-control" aria-describedby="config-login-edit-title-help"
            :placeholder="$t('login.defaultTitle')"
            :aria-disabled="awaitingResponse" autocomplete="off"
            @blur="update('title')">
          <spinner :state="updating === 'title'"/>
        </div>
      </div>

      <div class="form-group">
        <label for="config-login-edit-description">{{ $t('description.label') }}</label>
        <p id="config-login-edit-description-help">{{ $t('description.help') }}</p>
        <div>
          <input id="config-login-edit-description" v-model.trim="newAppearance.description"
            class="form-control"
            aria-describedby="config-login-edit-description-help"
            :placeholder="$t('login.defaultDescription')"
            :aria-disabled="awaitingResponse" autocomplete="off"
            @blur="update('description')">
          <spinner :state="updating === 'description'"/>
        </div>
      </div>
    </form>
  </div>
</template>

<script setup>
import { reactive, ref } from 'vue';

import ConfigLoginFileSelect from './file-select.vue';
import Spinner from '../../spinner.vue';

import useRequest from '../../../composables/request';
import { noop } from '../../../util/util';
import { useRequestData } from '../../../request-data';

defineOptions({
  name: 'ConfigLoginEdit'
});

const { serverConfig } = useRequestData();

const newAppearance = reactive({
  title: '',
  description: '',
  ...serverConfig['login-appearance']?.value
});

const { request, awaitingResponse } = useRequest();
// The name of the login-appearance property that the current request is
// updating
const updating = ref(null);
const update = (prop) => {
  if (awaitingResponse.value) return;
  const currentValue = serverConfig['login-appearance']?.value[prop] ?? '';
  if (newAppearance[prop] === currentValue) return;

  updating.value = prop;
  const data = Object.fromEntries(Object.entries(newAppearance)
    .filter(([, value]) => value !== ''));
  request({ method: 'POST', url: '/v1/config/login-appearance', data })
    .then(response => { serverConfig['login-appearance'] = response.data; })
    .catch(noop)
    .finally(() => { updating.value = null; });
};
</script>

<style lang="scss">
#config-login-edit {
  .config-login-file-select, .form-group { margin-bottom: 20px; }

  .file-label, label { font-size: 16px; }
  label { font-weight: normal; }

  .form-group > div {
    display: flex;
    align-items: center;
  }
  .form-control {
    width: auto;
    flex-grow: 1;
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "logo": {
      "label": "Logo",
      "help": "We recommend using a PNG logo with transparent background of at least 150x150 pixels."
    },
    "title": {
      "help": "A title for your server login."
    },
    "description": {
      "label": "Subtitle",
      "help": "Instructions for your users, a welcome message or a description of this server."
    },
    "hero": {
      "help": "Upload a vertical image, we recommend a 4:5 crop. Use a visually engaging image that represents your brand or message. The image will be cropped on different screen sizes, so keep important content centered."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "logo": {
      "label": "Logo",
      "help": "Wir empfehlen, ein Bild mit weißem oder transparentem Hintergrund und einer Größe von mindestens 150 x 150 Pixel zu verwenden."
    },
    "title": {
      "help": "Ein Titel für Ihre Server-Anmeldeseite."
    },
    "description": {
      "help": "Eine kurze Beschreibung Ihres Projektbereichs."
    },
    "hero": {
      "label": "Hauptbild",
      "help": "Wir empfehlen die Verwendung eines hochauflösenden Bildes im JPG- oder PNG-Format. Um optimale Ergebnisse zu erzielen, sollten Sie ein ansprechendes Bild wählen, das Ihre Brand oder Botschaft widerspiegelt."
    },
    "alert": {
      "success": "Einstellungen erfolgreich gespeichert."
    }
  },
  "es": {
    "logo": {
      "label": "Logotipo",
      "help": "Recomendamos utilizar una imagen con fondo blanco o transparente de al menos 150 x 150 píxeles."
    },
    "title": {
      "help": "Un título para tu inicio de sesión en el servidor."
    },
    "description": {
      "help": "Una breve descripción de tu espacio de proyectos."
    },
    "hero": {
      "label": "Imagen principal",
      "help": "Recomendamos utilizar una imagen de alta resolución en formato JPG o PNG. Para obtener los mejores resultados, utiliza una imagen atractiva que represente tu empresa o mensaje."
    },
    "alert": {
      "success": "Ajustes guardados correctamente."
    }
  },
  "fr": {
    "alert": {
      "success": "Réglages enregistrés."
    }
  },
  "it": {
    "logo": {
      "label": "Logo",
      "help": "Si consiglia di utilizzare un'immagine con sfondo bianco o trasparente di almeno 150x150 pixel."
    },
    "title": {
      "help": "Un titolo per il tuo accesso al server."
    },
    "description": {
      "help": "Una breve descrizione del vostro spazio dedicato al progetto."
    },
    "hero": {
      "label": "Immagine di copertina",
      "help": "Ti consigliamo di utilizzare un'immagine ad alta risoluzione in formato JPG o PNG. Per ottenere risultati ottimali, scegli un'immagine accattivante che rappresenti il tuo brand o il tuo messaggio."
    },
    "alert": {
      "success": "Impostazioni salvate con successo!"
    }
  },
  "pt": {
    "alert": {
      "success": "Configurações salvas com sucesso."
    }
  },
  "zh": {
    "logo": {
      "label": "标志",
      "help": "我们建议使用背景为白色或透明、尺寸至少为 150x150 像素的图片。"
    },
    "title": {
      "help": "您的服务器登录标题。"
    },
    "description": {
      "help": "您的项目空间的简短描述。"
    },
    "hero": {
      "label": "主视觉图片",
      "help": "我们建议使用高分辨率的 JPG 或 PNG 格式图片。为获得最佳效果，请使用能够代表您品牌或信息的视觉吸引力强的图片。"
    },
    "alert": {
      "success": "设置已成功保存。"
    }
  },
  "zh-Hant": {
    "alert": {
      "success": "設定已成功儲存。"
    }
  }
}
</i18n>
