<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="project-overview">
    <page-heading :title="$t('resource.forms')">
      <form-sort v-model="sortMode"/>
      <router-link v-if="project.dataExists && project.permits('form.create')"
        id="form-list-create-button" :to="projectPath('new-form')"
        class="btn btn-primary">
        <span class="icon-plus-circle"></span>{{ $t('action.create') }}&hellip;
      </router-link>
    </page-heading>
    <form-list :sort-func="sortFunction"/>
    <form-trash-list v-if="rendersTrashList" @restore="$emit('fetch-forms', true)"/>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue';

import FormList from '../form/list.vue';
import FormSort from '../form/sort.vue';
import FormTrashList from '../form/trash-list.vue';
import PageHeading from '../page/heading.vue';

import sortFunctions from '../../util/sort';
import useRoutes from '../../composables/routes';
import { useRequestData } from '../../request-data';

defineOptions({
  // Today, this component only renders forms, so ProjectForms would be an
  // appropriate name for it. It's named ProjectOverview for historical reasons:
  // it used to be the project overview page, rendering additional things beyond
  // forms.
  name: 'ProjectOverview'
});
defineProps({
  projectId: {
    type: String,
    required: true
  }
});
const emit = defineEmits(['fetch-forms']);

const { project } = useRequestData();
const { projectPath } = useRoutes();
emit('fetch-forms', false);

const sortMode = ref('alphabetical');
const sortFunction = computed(() => sortFunctions[sortMode.value]);

const rendersTrashList = computed(() =>
  project.dataExists && project.permits('form.restore'));
</script>

<i18n lang="json5">
{
  "en": {
    "action": {
      // This is the text of a button that is used to create a new Form.
      "create": "New"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "action": {
      "create": "Novy"
    }
  },
  "de": {
    "action": {
      "create": "Neu"
    }
  },
  "es": {
    "action": {
      "create": "Nuevo"
    }
  },
  "fr": {
    "action": {
      "create": "Nouveau"
    }
  },
  "id": {
    "action": {
      "create": "Formulir Baru"
    }
  },
  "it": {
    "action": {
      "create": "Nuovo"
    }
  },
  "ja": {
    "action": {
      "create": "新規作成"
    }
  },
  "pt": {
    "action": {
      "create": "Novo"
    }
  },
  "sw": {
    "action": {
      "create": "Mpya"
    }
  },
  "zh": {
    "action": {
      "create": "更新"
    }
  },
  "zh-Hant": {
    "action": {
      "create": "新增"
    }
  }
}
</i18n>
