<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="field-key-revoke" :state="state" :hideable="!awaitingResponse"
    backdrop @hide="$emit('hide')">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="modal-introduction">
        <i18n-t tag="p" keypath="introduction[0]">
          <template #displayName>
            <strong>{{ fieldKey != null ? fieldKey.displayName : '' }}</strong>
          </template>
        </i18n-t>
        <p>{{ $t('introduction[1]') }}</p>
        <p>{{ $t('common.noUndo') }}</p>
      </div>
      <div class="modal-actions">
        <button type="button" class="btn btn-link" :aria-disabled="awaitingResponse"
          @click="$emit('hide')">
          {{ $t('action.noCancel') }}
        </button>
        <button type="button" class="btn btn-danger"
          :aria-disabled="awaitingResponse" @click="revoke">
          {{ $t('action.yesProceed') }} <spinner :state="awaitingResponse"/>
        </button>
      </div>
    </template>
  </modal>
</template>

<script>
import Modal from '../modal.vue';
import Spinner from '../spinner.vue';

import useRequest from '../../composables/request';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';

export default {
  name: 'FieldKeyRevoke',
  components: { Modal, Spinner },
  props: {
    state: Boolean,
    fieldKey: Object
  },
  emits: ['hide', 'success'],
  setup() {
    const { request, awaitingResponse } = useRequest();
    return { request, awaitingResponse };
  },
  methods: {
    revoke() {
      this.request({
        method: 'DELETE',
        url: apiPaths.session(this.fieldKey.token)
      })
        .then(() => {
          this.$emit('success', this.fieldKey);
        })
        .catch(noop);
    }
  }
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up.
    "title": "Revoke User Access",
    "introduction": [
      // {displayName} is formatted in bold.
      "Are you sure you want to revoke access from the App User {displayName}?",
      "Existing Submissions from this user will remain, but anybody relying on this user will have to create a new one to continue downloading Forms or uploading Submissions."
    ]
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Odebrat přístup uživatele",
    "introduction": [
      "Opravdu chcete odebrat přístup uživateli aplikace {displayName}?",
      "Stávající příspěvky od tohoto uživatele zůstanou, ale kdokoli se na tohoto uživatele obrátí, bude muset vytvořit nové, aby pokračoval ve stahování formulářů nebo odesílání příspěvků."
    ]
  },
  "de": {
    "title": "Zugriffsberechtigung entziehen",
    "introduction": [
      "Wollen Sie dem Benutzer {displayName} wirklich die Zugriffsberechtigung entziehen?",
      "Bestehende Übermittlungen dieses Benutzers bleiben erhalten. Bei jedem Bezug auf diesen Benutzer muss ein neuer erstellt werden, um Formulare herunterzuladen oder Übermittlungen einzureichen."
    ]
  },
  "es": {
    "title": "Revocar acceso de usuario",
    "introduction": [
      "¿Está seguro de que desea revocar el acceso del usuario móvil {displayName}?",
      "Los envíos existentes de este usuario permanecerán, pero cualquiera que confíe en este usuario tendrá que crear uno nuevo para continuar descargando formularios o cargando envíos."
    ]
  },
  "fr": {
    "title": "Révoquer l'accès des utilisateurs",
    "introduction": [
      "Êtes vous sûr de vouloir révoquer l'accès de l'utilisateur mobile {displayName}?",
      "Les soumissions existantes de cet utilisateur seront conservées, mais toute personne s'appuyant sur cet utilisateur devra en créer une nouvelle pour continuer à télécharger des formulaires ou des soumissions."
    ]
  },
  "id": {
    "title": "Cabut Akses Pengguna",
    "introduction": [
      "Apakah Anda yakin ingin mencabut akses dari Pengguna Aplikasi {displayName}?",
      "Kiriman data yang sudah ada dari Pengguna ini akan tetap ada, tetapi siapapun yang bergantung pada Pengguna ini harus membuat akun Pengguna baru untuk melanjutkan pengunduhan formulir atau pengunggahan kiriman data."
    ]
  },
  "it": {
    "title": "Revoca l'accesso utente",
    "introduction": [
      "Sei sicuro di voler revocare l'accesso all'App User {displayName}?",
      "Gli invii esistenti di questo utente rimarranno, ma chiunque faccia affidamento su questo utente dovrà crearne uno nuovo per continuare a scaricare i formulari o caricare invii."
    ]
  },
  "ja": {
    "title": "アプリユーザーのアクセス権の取消",
    "introduction": [
      "アプリユーザー\"{displayName}\"のアクセス権を本当に取り消しますか？",
      "このユーザーからこれまでに提出されたフォームは残りますが、このユーザーに依存している人は、フォームのダウンロードや提出フォームのアップロードを継続するために、新しいユーザーを作成する必要があります。"
    ]
  },
  "pt": {
    "title": "Remover acesso do usuário",
    "introduction": [
      "Você tem certeza que deseja remover o acesso do usuário de aplicativo {displayName}?",
      "Respostas existentes para esse usuário serão mantidas, mas qualquer pessoa utilizando esse usuário precisará criar outro para continuar obtendo formulários e enviando respostas."
    ]
  },
  "sw": {
    "title": "Batilisha Ufikiaji wa Mtumiaji",
    "introduction": [
      "Je, una uhakika unataka kubatilisha ufikiaji kutoka kwa Mtumiaji wa Programu {displayName}?",
      "Mawasilisho yaliyopo kutoka kwa mtumiaji huyu yatasalia, lakini mtu yeyote anayemtegemea mtumiaji huyu atalazimika kuunda upya ili kuendelea kupakua Fomu au kupakia Mawasilisho"
    ]
  },
  "zh": {
    "title": "撤销用户权限",
    "introduction": [
      "您确定要撤销App用户{displayName}的权限吗？",
      "该用户已提交的数据将予以保留，但任何依赖此用户的流程都需创建新用户，以继续下载表单或上传内容。"
    ]
  },
  "zh-Hant": {
    "title": "撤銷使用者存取權限",
    "introduction": [
      "您確定要撤銷APP使用者 {displayName} 的存取權限嗎？",
      "該用戶的現有提交內容將保留，但依賴該用戶的任何人都必須建立一個新提交內容才能繼續下載表格或上傳提交內容。"
    ]
  }
}
</i18n>
