<!--
Copyright 2017 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <tr class="field-key-row" :class="{ success: fieldKey.id === highlighted }">
    <td class="display-name">
      <span v-tooltip.text>{{ fieldKey.displayName }}</span>
    </td>
    <td>
      <a v-if="fieldKey.token != null" ref="popoverLink" href="#"
        class="field-key-row-popover-link" role="button"
        @click.prevent="toggleQr">
        <span class="icon-qrcode"></span>{{ $t('seeCode') }}
      </a>
      <template v-else>
        {{ $t('accessRevoked') }}
      </template>
    </td>
    <td><date-time :iso="fieldKey.createdAt"/></td>
    <td class="created-by">
      <span v-tooltip.text>{{ fieldKey.createdBy.displayName }}</span>
    </td>
    <td class="last-used-and-actions">
      <div class="col-content">
        <date-time :iso="fieldKey.lastUsed"/>
      </div>
      <div class="btn-group">
        <button v-if="fieldKey.token != null && showEdit" type="button"
          class="edit-button btn btn-default"
          :aria-label="$t('action.editAppUser')" v-tooltip.aria-label
          @click="$emit('edit', fieldKey)">
          <span class="icon-pencil"></span>
        </button>
        <button v-if="fieldKey.token != null" type="button"
          class="revoke-button btn btn-default"
          :aria-label="$t('action.revokeAccess')" v-tooltip.aria-label
          @click="$emit('revoke', fieldKey)">
          <span class="icon-ban"></span>
        </button>
      </div>
    </td>
  </tr>
</template>

<script>
import DateTime from '../date-time.vue';

export default {
  name: 'FieldKeyRow',
  components: { DateTime },
  props: {
    fieldKey: {
      type: Object,
      required: true
    },
    highlighted: Number,
    showEdit: Boolean
  },
  emits: ['toggle-qr', 'revoke', 'edit'],
  methods: {
    toggleQr() {
      this.$emit('toggle-qr', this.fieldKey, this.$refs.popoverLink);
    }
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/mixins';
@import '../../assets/scss/variables';

.field-key-row {
  .table tbody & td { vertical-align: middle; }

  .display-name, .created-by {
    @include text-overflow-ellipsis;
    max-width: 250px;
  }

  .last-used-and-actions {
    padding-top: 4px;
    padding-bottom: 4px;
    min-width: 120px;
  }

  .col-content {
    display: flex;
    align-items: flex-start;
    margin-top: 3px;
  }

  .btn-group {
    @include icon-btn-group;
    .icon-ban { color: $color-danger; }
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    // Clicking on this text displays an App User QR code for configuring ODK Collect.
    "seeCode": "See code",
    // This text is shown for an App User whose access has been revoked.
    "accessRevoked": "Access revoked",
    "action": {
      "editAppUser": "Edit App User",
      "revokeAccess": "Revoke access"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "seeCode": "Viz kód",
    "accessRevoked": "Přístup byl zrušen",
    "action": {
      "revokeAccess": "Odebrat přístup"
    }
  },
  "de": {
    "seeCode": "QR-Code",
    "accessRevoked": "Zugriffsberechtigung zurückgezogen",
    "action": {
      "revokeAccess": "Zugriffsberechtigung entziehen"
    }
  },
  "es": {
    "seeCode": "Ver código",
    "accessRevoked": "Acceso revocado",
    "action": {
      "revokeAccess": "Revocar el acceso"
    }
  },
  "fr": {
    "seeCode": "Voir le code",
    "accessRevoked": "Accès retiré",
    "action": {
      "editAppUser": "Modifier utilisateur mobile",
      "revokeAccess": "Retirer l'accès"
    }
  },
  "id": {
    "seeCode": "Lihat kode",
    "accessRevoked": "Akses dicabut",
    "action": {
      "revokeAccess": "Cabut akses"
    }
  },
  "it": {
    "seeCode": "Mostra il codice",
    "accessRevoked": "Accesso revocato",
    "action": {
      "revokeAccess": "Revoca l'accesso utente"
    }
  },
  "ja": {
    "seeCode": "QRコードを表示",
    "accessRevoked": "アクセス権の取消済み",
    "action": {
      "revokeAccess": "アクセス権の取消"
    }
  },
  "pt": {
    "seeCode": "Ver código",
    "accessRevoked": "Acesso removido",
    "action": {
      "revokeAccess": "Remover acesso"
    }
  },
  "sw": {
    "seeCode": "Angalia msimbo",
    "accessRevoked": "Ufikiaji umebatilishwa",
    "action": {
      "revokeAccess": "Batilisha ufikiaji"
    }
  },
  "zh": {
    "seeCode": "查看代码",
    "accessRevoked": "权限已撤销",
    "action": {
      "revokeAccess": "撤销权限"
    }
  },
  "zh-Hant": {
    "seeCode": "查看 QR code",
    "accessRevoked": "存取權限被撤銷",
    "action": {
      "revokeAccess": "撤銷存取權限"
    }
  }
}
</i18n>
