<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <form-edit-section id="form-edit-attachments" icon="paperclip" dotted
    :warning="hasMissing">
    <template #title>{{ $t('resource.attachments') }}</template>
    <template v-if="hasAttachments" #subtitle>
      <template v-if="hasMissing">
        {{ $tcn('missingCount', draftAttachments.missingCount) }}
      </template>
      <template v-else>
        {{ $tcn('count.attachments', draftAttachments.size) }}
      </template>
    </template>
    <template #tag>{{ tag }}</template>
    <template #body>
      <loading :state="draftAttachments.initiallyLoading"/>
      <template v-if="draftAttachments.dataExists">
        <form-attachment-list v-if="hasAttachments"/>
        <p v-else>{{ $t('noAttachments') }}</p>
      </template>
    </template>
  </form-edit-section>
</template>

<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import FormAttachmentList from '../../form-attachment/list.vue';
import FormEditSection from './section.vue';
import Loading from '../../loading.vue';

import { useI18nUtils } from '../../../util/i18n';
import { useRequestData } from '../../../request-data';

const { publishedAttachments, draftAttachments } = useRequestData();

const hasAttachments = computed(() =>
  draftAttachments.dataExists && draftAttachments.size !== 0);
const hasMissing = computed(() =>
  draftAttachments.dataExists && draftAttachments.missingCount !== 0);

const { t } = useI18n();
const { tn, formatList } = useI18nUtils();
const tag = computed(() => {
  if (!(hasAttachments.value && publishedAttachments.dataExists)) return '';

  let newCount = 0;
  let changedCount = 0;
  for (const draftAttachment of draftAttachments.values()) {
    const publishedAttachment = publishedAttachments.get(draftAttachment.name);
    if (publishedAttachment == null)
      newCount += 1;
    else if (draftAttachment.hash !== publishedAttachment.hash ||
      draftAttachment.datasetExists !== publishedAttachment.datasetExists)
      changedCount += 1;
  }

  const parts = [];
  if (newCount !== 0) parts.push(tn('diff.newCount', newCount));
  if (changedCount !== 0) parts.push(tn('diff.changedCount', changedCount));
  return parts.length !== 0
    ? t('diff.summary', { changes: formatList(parts, 'long') })
    : '';
});
</script>

<style lang="scss">
#form-edit-attachments {
  .form-edit-section-body { margin-bottom: 51px; }
  &:has(#form-attachment-list) .form-edit-section-body { margin-bottom: 21px; }
}
</style>

<i18n lang="json5">
{
  "en": {
    // "Definition" refers to a Form Definition, and "attachments" refers to
    // Form Attachments.
    "noAttachments": "This definition requires no attachments, so there is nothing to upload.",
    "missingCount": "{count} missing attachment | {count} missing attachments",
    "diff": {
      "newCount": "{count} new attachment | {count} new attachments",
      "changedCount": "{count} changed attachment | {count} changed attachments",
      // {changes} describes changes that have been made to Form attachments.
      // For example: "1 new attachment and 2 changed attachments"
      "summary": "{changes} since the published version"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "noAttachments": "Diese Definition erfordert keine Anhänge, es muss also nichts hochgeladen werden.",
    "missingCount": "{count} Fehlender Anhang | {count} Fehlende Anhänge",
    "diff": {
      "newCount": "{count} Neue Anhang | {count} Neue Anhänge",
      "changedCount": "{count} geänderte Anhang | {count} geänderte Anhänge",
      "summary": "{changes} seit der veröffentlichten Version"
    }
  },
  "es": {
    "noAttachments": "Esta definición no requiere archivos adjuntos, por lo que no hay nada que «subir».",
    "missingCount": "{count} archivo adjunto que falta | {count} archivos adjuntos que faltan | {count} archivos adjuntos que faltan",
    "diff": {
      "newCount": "{count} nuevo archivo adjunto | {count} nuevos archivos adjuntos | {count} nuevos archivos adjuntos",
      "changedCount": "{count} archivo adjunto modificado | {count} archivos adjuntos modificados | {count} archivos adjuntos modificados",
      "summary": "{changes} desde la versión publicada"
    }
  },
  "fr": {
    "noAttachments": "Cette définition ne requiert aucun fichier joint, il n'y a donc rien à téléverser.",
    "missingCount": "{count} fichier joint manquant | {count} fichiers joints manquants | {count} fichier(s) joint(s) manquant(s)",
    "diff": {
      "newCount": "{count} nouveau fichier joint | {count} nouveaux fichiers joints | {count} nouveaux fichiers joints",
      "changedCount": "{count} fichier joint modifié | {count} fichiers joints modifiés | {count} fichiers joints modifiés",
      "summary": "{changes} depuis la version publiée"
    }
  },
  "it": {
    "noAttachments": "Questa definizione non richiede allegati, quindi non c'è nulla da caricare.",
    "missingCount": "{count} allegato mancante | {count} allegati mancanti | {count} allegati mancanti",
    "diff": {
      "newCount": "{count} nuovo allegato | {count} nuovi allegati | {count} nuovi allegati",
      "changedCount": "{count} allegato modificato | {count} allegati modificati | {count} allegati modificati",
      "summary": "{changes} rispetto alla versione pubblicata"
    }
  },
  "pt": {
    "noAttachments": "Essa definição de formulário não requer anexos, portanto não há nada a ser carregado.",
    "missingCount": "{count} anexo faltando | {count} anexos faltando | {count} anexos faltando",
    "diff": {
      "newCount": "{count} novo anexo | {count} novos anexos | {count} novos anexos",
      "changedCount": "{count} anexo alterado | {count} anexos alterados | {count} anexos alterados",
      "summary": "{changes} desde a versão publicada"
    }
  },
  "zh": {
    "noAttachments": "此定义无需附件，因此无需上传任何文件。",
    "missingCount": "{count}个缺失附件",
    "diff": {
      "newCount": "{count}个新附件",
      "changedCount": "{count}个已修改的附件",
      "summary": "自发布版本以来有{changes}"
    }
  },
  "zh-Hant": {
    "noAttachments": "此定義不需要任何附件，因此沒有任何東西需要上傳。",
    "missingCount": "{count}個遺失附件",
    "diff": {
      "newCount": "{count}個新附件",
      "changedCount": "{count}個變更附件",
      "summary": "{changes}自發布版本以來"
    }
  }
}
</i18n>
