<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <form-edit-section id="form-edit-entities" icon="database">
    <template #title>{{ $t('resource.entities') }}</template>
    <template v-if="datasetDiff.dataExists" #subtitle>
      {{ $tcn('datasetCount', datasetDiff.length) }}
    </template>
    <template #body>
      <template v-if="formDraft.entityRelated">
        <loading :state="datasetDiff.initiallyLoading"/>
        <p v-if="datasetDiff.dataExists && datasetDiff.counts.updatedDatasets !== 0"
          id="form-edit-entities-diff-counts">
          <span>{{ diffCounts }}</span>
          <template v-if="datasetDiff.counts.newProperties !== 0">
            <sentence-separator/>
            <span>{{ $t('cannotDeleteProperties') }}</span>
          </template>
        </p>
        <dataset-summary is-draft/>
      </template>
      <p v-else>
        <span>{{ $t('notEntityRelated') }}</span>
        <sentence-separator/>
        <doc-link to="central-entities/">{{ $t('whatAreEntities') }}</doc-link>
      </p>
    </template>
  </form-edit-section>
</template>

<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import DatasetSummary from '../../dataset/summary.vue';
import DocLink from '../../doc-link.vue';
import FormEditSection from './section.vue';
import Loading from '../../loading.vue';
import SentenceSeparator from '../../sentence-separator.vue';

import { useI18nUtils } from '../../../util/i18n';
import { useRequestData } from '../../../request-data';

defineOptions({
  name: 'FormEditEntities'
});

const { formDraftDatasetDiff: datasetDiff, resourceView } = useRequestData();
const formDraft = resourceView('formDraft', (data) => data.get());

const { t } = useI18n();
const { tn } = useI18nUtils();
const diffCounts = computed(() => {
  const { updatedDatasets, newProperties } = datasetDiff.counts;
  return newProperties === 0
    ? tn('diffCounts.datasetsOnly', updatedDatasets)
    : t('diffCounts.newProperties.full', {
      entityLists: tn('diffCounts.newProperties.entityLists', updatedDatasets),
      properties: tn('diffCounts.newProperties.properties', newProperties)
    });
});
</script>

<style lang="scss">
@import '../../../assets/scss/variables';

#form-edit-entities {
  .dataset-summary { margin-top: -$padding-top-expandable-row; }
}

#form-edit-entities-diff-counts { margin-top: 10px; }
</style>

<i18n lang="json5">
{
  "en": {
    "datasetCount": "Submissions to this Form definition will update {count} Entity List. | Submissions to this Form definition will update {count} Entity Lists.",
    "diffCounts": {
      "datasetsOnly": "Publishing this draft will update {count} Entity List. | Publishing this draft will update {count} Entity Lists.",
      "newProperties": {
        "full": "Publishing this draft will update {entityLists} and create {properties}.",
        "entityLists": "{count} Entity List | {count} Entity Lists",
        "properties": "{count} property | {count} properties"
      }
    },
    // "Properties" refers to Entity properties.
    "cannotDeleteProperties": "Properties cannot be deleted.",
    // "Definition" refers to a Form Definition.
    "notEntityRelated": "This definition does not update any Entities.",
    "whatAreEntities": "What are Entities?"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "es": {
    "whatAreEntities": "¿Qué son las entidades?"
  },
  "fr": {
    "datasetCount": "Publier cette ébauche mettra à jour {count} liste d'entités | Publier cette ébauche mettra à jour {count} listes d'entités | Publier cette ébauche mettra à jour {count} liste(s) d'entités",
    "diffHasNew": "De nouvelles Listes d'Entités et/ou propriétés seront créées",
    "notEntityRelated": "Cette définition ne met pas à jour d'Entités.",
    "whatAreEntities": "Que sont les Entités ?"
  },
  "it": {
    "datasetCount": "La pubblicazione di questa bozza aggiornerà {count}Elenco delle entità | La pubblicazione di questa bozza aggiornerà {count}Elenco delle entità | La pubblicazione di questa bozza aggiornerà {count}Elenco delle entità",
    "diffHasNew": "Nuove Liste Entità e/o proprietà saranno create.",
    "notEntityRelated": "Questa definizione non aggiorna alcuna entità.",
    "whatAreEntities": "Cosa sono le entità?"
  }
}
</i18n>
