<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <form-edit-section id="form-edit-entities" icon="database">
    <template #title>{{ $t('resource.entities') }}</template>
    <template v-if="datasetDiff.dataExists" #subtitle>
      {{ $tcn('datasetCount', datasetDiff.length) }}
    </template>
    <template #body>
      <template v-if="formDraft.entityRelated">
        <loading :state="datasetDiff.initiallyLoading"/>
        <dataset-summary is-draft/>
      </template>
      <p v-else>
        <span>{{ $t('notEntityRelated') }}</span>
        <sentence-separator/>
        <doc-link to="central-entities/">{{ $t('whatAreEntities') }}</doc-link>
      </p>
    </template>
  </form-edit-section>
</template>

<script setup>
import DatasetSummary from '../../dataset/summary.vue';
import DocLink from '../../doc-link.vue';
import FormEditSection from './section.vue';
import Loading from '../../loading.vue';
import SentenceSeparator from '../../sentence-separator.vue';

import { useRequestData } from '../../../request-data';

defineOptions({
  name: 'FormEditEntities'
});

const { formDraftDatasetDiff: datasetDiff, resourceView } = useRequestData();
const formDraft = resourceView('formDraft', (data) => data.get());
</script>

<style lang="scss">
@import '../../../assets/scss/variables';

#form-edit-entities {
  .dataset-summary { margin-top: -$padding-top-expandable-row; }
}
</style>

<i18n lang="json5">
{
  "en": {
    "datasetCount": "Submissions to this Form definition will update {count} Entity List | Submissions to this Form definition will update {count} Entity Lists",
    // "Definition" refers to a Form Definition.
    "notEntityRelated": "This definition does not update any Entities.",
    "whatAreEntities": "What are Entities?"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "es": {
    "whatAreEntities": "¿Qué son las entidades?"
  },
  "fr": {
    "datasetCount": "Publier cette ébauche mettra à jour {count} liste d'entités | Publier cette ébauche mettra à jour {count} listes d'entités | Publier cette ébauche mettra à jour {count} liste(s) d'entités",
    "diffHasNew": "De nouvelles Listes d'Entités et/ou propriétés seront créées",
    "notEntityRelated": "Cette définition ne met pas à jour d'Entités.",
    "whatAreEntities": "Que sont les Entités ?"
  },
  "it": {
    "datasetCount": "La pubblicazione di questa bozza aggiornerà {count}Elenco delle entità | La pubblicazione di questa bozza aggiornerà {count}Elenco delle entità | La pubblicazione di questa bozza aggiornerà {count}Elenco delle entità",
    "diffHasNew": "Nuove Liste Entità e/o proprietà saranno create.",
    "notEntityRelated": "Questa definizione non aggiorna alcuna entità.",
    "whatAreEntities": "Cosa sono le entità?"
  }
}
</i18n>
