<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <map-popup v-show="features != null" ref="popup" class="map-overlap-popup"
    @hide="$emit('hide')">
    <template #title><slot name="title"></slot></template>
    <template #body>
      <loading :state="odata.awaitingResponse"/>
      <template v-if="odata.dataExists">
        <div v-for="feature of features" :key="feature.id" class="feature" tabindex="0"
          @mouseenter="preview(feature)" @focus="preview(feature)"
          @mouseleave="preview(null)" @blur="preview(null)"
          @click="select(feature)" @keydown.enter="select(feature)">
          <div>
            <slot v-if="odata.has(feature.id)" name="feature" :feature="feature" :odata="odata.get(feature.id)"></slot>
            <template v-else>
              <span class="icon-trash" v-tooltip.sr-only></span>
              <span>{{ feature.id }}</span>
              <span class="sr-only">&nbsp;{{ $t('deletedMessage') }}</span>
            </template>
          </div>
          <div><span class="icon-angle-right"></span></div>
        </div>
      </template>
    </template>
  </map-popup>
</template>

<script setup>
import { useTemplateRef, watch } from 'vue';

import Loading from '../loading.vue';
import MapPopup from './popup.vue';

import { odataLiteral } from '../../util/odata';
import { useRequestData } from '../../request-data';

defineOptions({
  name: 'MapOverlapPopup'
});
const props = defineProps({
  features: Array,
  odataUrl: {
    type: Function,
    required: true
  }
});
const emit = defineEmits(['hide', 'preview', 'select']);

const { createResource } = useRequestData();
const odata = createResource('odata', () => ({
  transformResponse: ({ data }) =>
    data.value.reduce((map, x) => map.set(x.__id, x), new Map())
}));

const fetchData = () => {
  const { odataUrl } = props;
  const url = odataUrl({
    $filter: props.features.map(({ id }) => `__id eq ${odataLiteral(id)}`)
      .join(' or '),
    $wkt: true
  });
  odata.request({ url }).catch(() => { emit('hide'); });
};
watch(
  () => props.features,
  (features) => {
    if (features != null)
      fetchData();
    else
      odata.reset();
  }
);

const select = (feature, preview = false) => {
  const x = odata.get(feature.id);
  if (x != null) emit(preview ? 'preview' : 'select', { feature, odata: x });
};
const popup = useTemplateRef('popup');
const preview = (feature) => {
  if (feature != null)
    select(feature, true);
  // Selecting a feature will end up hiding this component, which will trigger
  // a mouseleave or blur event. We need to ignore that event: otherwise, it
  // would undo the selection. That's why we check whether the component is
  // visible.
  else if (popup.value.el.clientHeight !== 0)
    emit('preview', null);
};
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

.map-overlap-popup {
  .feature {
    display: flex;
    align-items: center;
    justify-content: space-between;
    column-gap: 16px;

    $padding-inline: 6px;
    padding: 8px $padding-inline;
    margin-inline: -$padding-inline;

    > :first-child { @include text-overflow-ellipsis; }

    > :last-child {
      color: #1c1b1f;
      flex-shrink: 0;
      font-size: 20px;
      padding-right: 3px;
    }

    &:hover, &:focus-within {
      background-color: $color-action-background;
      border-radius: 4px;

      &, & > :last-child { color: #fff; }
    }
  }

  .icon-trash { margin-right: $margin-right-icon; }
}
</style>

<i18n lang="json5">
{
  "en": {
    // @transifexKey component.AuditRow.deletedMessage
    "deletedMessage": "This resource has been deleted."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "deletedMessage": "Tento zdroj byl smazán."
  },
  "de": {
    "deletedMessage": "Diese Ressource wurde gelöscht."
  },
  "es": {
    "deletedMessage": "Este recurso ha sido borrado."
  },
  "fr": {
    "deletedMessage": "Cette ressource a été supprimée."
  },
  "it": {
    "deletedMessage": "Questa risorsa è stata eliminata."
  },
  "ja": {
    "deletedMessage": "これは削除されました。"
  },
  "pt": {
    "deletedMessage": "Esse recurso foi deletado."
  },
  "sw": {
    "deletedMessage": "Rasimali hii imefutwa"
  },
  "zh": {
    "deletedMessage": "该资源已删除。"
  },
  "zh-Hant": {
    "deletedMessage": "該資源已被刪除。"
  }
}
</i18n>
