<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <modal id="public-link-revoke" :state="state" :hideable="!awaitingResponse"
    backdrop @hide="$emit('hide')">
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <div class="modal-introduction">
        <p>{{ $t('introduction[0]') }}</p>
        <p><strong>{{ $t('common.areYouSure') }}</strong></p>
      </div>
      <div class="modal-actions">
        <button type="button" class="btn btn-link" :aria-disabled="awaitingResponse"
          @click="$emit('hide')">
          {{ $t('action.noCancel') }}
        </button>
        <button type="button" class="btn btn-danger"
          :aria-disabled="awaitingResponse" @click="revoke">
          {{ $t('action.yesProceed') }} <spinner :state="awaitingResponse"/>
        </button>
      </div>
    </template>
  </modal>
</template>

<script setup>
import Modal from '../modal.vue';
import Spinner from '../spinner.vue';

import useRequest from '../../composables/request';
import { apiPaths } from '../../util/request';
import { noop } from '../../util/util';

defineOptions({
  name: 'PublicLinkRevoke'
});
const props = defineProps({
  state: Boolean,
  publicLink: Object
});
const emit = defineEmits(['hide', 'success']);

const { request, awaitingResponse } = useRequest();
const revoke = () => {
  request({ method: 'DELETE', url: apiPaths.session(props.publicLink.token) })
    .then(() => {
      emit('success', props.publicLink);
    })
    .catch(noop);
};
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a pop-up.
    "title": "Revoke Public Access Link",
    "introduction": [
      "You are about to revoke this Public Access Link. This means all attempts to submit data using the link will be denied, including records that have already been started."
    ]
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Odebrat veřejně přístupný odkaz",
    "introduction": [
      "Chystáte se odebrat tento veřejně přístupný odkaz. To znamená, že všechny pokusy o odeslání dat pomocí odkazu budou zamítnuty, včetně záznamů, které již byly spuštěny."
    ]
  },
  "de": {
    "title": "Öffentlichen Zugangslink widerrufen",
    "introduction": [
      "Sie sind dabei diesen öffentlichen Zugriffslink zu widerrufen. Das bedeutet, alle Versuche Daten über diesen Link zu übermitteln, werden abgewiesen, einschließlich Aufzeichnungen, die bereits begonnen wurden."
    ]
  },
  "es": {
    "title": "Revocar enlace de acceso público",
    "introduction": [
      "Está a punto de revocar este enlace de acceso público. Esto significa que cualquier intento de enviar datos utilizando el enlace será denegado, incluyendo los registros que ya han sido iniciados."
    ]
  },
  "fr": {
    "title": "Révoquer lien d'accès public",
    "introduction": [
      "Vous êtes sur le point de révoquer ce lien d'accès public. Toute tentative de soumission de données utilisant le lien sera refusée, y compris les formulaires qui ont déjà été commencés."
    ]
  },
  "id": {
    "title": "Cabut Tautan Akses Publik",
    "introduction": [
      "Anda hendak mencabut Tautan Akses Publik. Ini berarti semua usaha untuk mengirim data melalui tautan ini akan ditolak, termasuk catatan yang sudah dimulai."
    ]
  },
  "it": {
    "title": "Ritira Link con accesso pubblico",
    "introduction": [
      "Stai per revocare questo link di accesso pubblico. Ciò significa che tutti i tentativi di inviare dati utilizzando il collegamento verranno negati, inclusi i dati che sono già stati avviati."
    ]
  },
  "ja": {
    "title": "一般公開リンクの無効化",
    "introduction": [
      "一般公開リンクを無効化しようとしています。これにより、この一般公開リンクを用いた全てのデータの提出が出来なくなります。これには現在すでに入力が開始されたフォームの提出も含まれます。"
    ]
  },
  "pt": {
    "title": "Revogar link de acesso público",
    "introduction": [
      "Você está prestes a revogar esse link de acesso público. Isso significa que todas as tentativas de enviar dados usando esse link serão negadas, incluindo preenchimentos que já tenham sido iniciados."
    ]
  },
  "sw": {
    "title": "Batilisha Kiungo cha Ufikiaji wa Umma",
    "introduction": [
      "Unakaribia kubatilisha Kiungo hiki cha Ufikiaji wa Umma. Hii ina maana kwamba majaribio yote ya kuwasilisha data kwa kutumia kiungo yatakataliwa, ikiwa ni pamoja na rekodi ambazo tayari zimeanzishwa"
    ]
  },
  "zh": {
    "title": "撤销公开访问链接",
    "introduction": [
      "您即将撤销此公开访问链接。此后使用该链接提交数据时（包括已开始填写的记录），都将被拒绝。"
    ]
  },
  "zh-Hant": {
    "title": "撤銷公共訪問鏈接",
    "introduction": [
      "您即將撤銷此公共存取連結。這意味著所有使用該連結提交資料的嘗試都將被拒絕，包括已經開始的記錄。"
    ]
  }
}
</i18n>
