<!--
Copyright 2020 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <tr :class="htmlClass">
    <td class="display-name">
      <span v-tooltip.text>{{ publicLink.displayName }}</span>
    </td>
    <td class="once">
      {{ publicLink.once ? $t('common.yes') : $t('common.no') }}
    </td>
    <td class="access-link">
      <template v-if="publicLink.token == null">{{ $t('revoked') }}</template>
      <template v-else-if="form.dataExists">
        <selectable v-if="enketoId != null">{{ url }}</selectable>
        <template v-else>
          <span class="unavailable" aria-hidden="true" v-tooltip.sr-only>
            <span>{{ $t('unavailable.text') }}</span>
            <span class="icon-question-circle"></span>
          </span>
          <span class="sr-only">{{ $t('unavailable.title') }}</span>
        </template>
      </template>
    </td>
    <td>
      <button v-if="publicLink.token != null" type="button"
        class="btn btn-danger" @click="$emit('revoke', publicLink)">
        <span class="icon-times-circle"></span>{{ $t('action.revoke') }}&hellip;
      </button>
    </td>
  </tr>
</template>

<script>
import Selectable from '../selectable.vue';

import { useRequestData } from '../../request-data';

export default {
  name: 'PublicLinkRow',
  components: { Selectable },
  props: {
    publicLink: {
      type: Object,
      required: true
    },
    highlighted: Number
  },
  emits: ['revoke'],
  setup() {
    // The component does not assume that this data will exist when the
    // component is created.
    const { form } = useRequestData();
    return { form };
  },
  computed: {
    htmlClass() {
      return {
        'public-link-row': true,
        success: this.publicLink.id === this.highlighted
      };
    },
    enketoId() {
      return this.publicLink.once ? this.form.enketoOnceId : this.form.enketoId;
    },
    url() {
      const encodedId = encodeURIComponent(this.enketoId);
      return `${window.location.origin}/f/${encodedId}?st=${this.publicLink.token}`;
    }
  }
};
</script>

<style lang="scss">
@import '../../assets/scss/mixins';

.public-link-row {
  .table tbody & td { vertical-align: middle; }
  .display-name { @include text-overflow-ellipsis; }
  .icon-question-circle { margin-left: 5px; }
}
</style>

<i18n lang="json5">
{
  "en": {
    "action": {
      "revoke": "Revoke"
    },
    // This text is shown for a Public Access Link that has been revoked. The
    // text appears on its own and is not part of a longer sentence.
    "revoked": "Revoked",
    "unavailable": {
      // This text is shown for a Public Access Link that is not available yet.
      "text": "Not available yet",
      "title": "Public Access Link is not available yet. It has not finished being processed. Please refresh later and try again."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "action": {
      "revoke": "Odebrat"
    },
    "revoked": "Odebrán",
    "unavailable": {
      "text": "Už není dostupný",
      "title": "Veřejně přístupný odkaz už není k dispozici. Zpracování se nedokončilo. Aktualizujte prosím později a zkuste to znovu."
    }
  },
  "de": {
    "action": {
      "revoke": "Widerrufen"
    },
    "revoked": "Widerrufen",
    "unavailable": {
      "text": "Noch nicht verfügbar",
      "title": "Öffentlicher Zugangslink noch nicht verfügbar. Er wurde noch nicht vollständig verarbeitet. Bitte aktualisieren Sie später und versuchen Sie es erneut."
    }
  },
  "es": {
    "action": {
      "revoke": "Revocar"
    },
    "revoked": "Revocado",
    "unavailable": {
      "text": "Todavía no disponible",
      "title": "El enlace de acceso público aún no está disponible. No se ha terminado de procesar. Por favor actualice más tarde y vuelva a intentarlo."
    }
  },
  "fr": {
    "action": {
      "revoke": "Révoquer"
    },
    "revoked": "Révoqué",
    "unavailable": {
      "text": "Pas encore disponible",
      "title": "Le lien d'accès public n'est pas encore disponible. Il n'a pas encore été traité. Veuillez rafraîchir plus tard et réessayer."
    }
  },
  "id": {
    "action": {
      "revoke": "Cabut"
    },
    "revoked": "Dicabut",
    "unavailable": {
      "text": "Belum tersedia",
      "title": "Tautan Akses Publik belum tersedia. Tautan belum selesai diproses. Silakan muat ulang dan coba lagi nanti."
    }
  },
  "it": {
    "action": {
      "revoke": "Revocare"
    },
    "revoked": "Revocato",
    "unavailable": {
      "text": "Non ancora disponibile",
      "title": "Il link di accesso pubblico non è ancora disponibile. L'elaborazione non è terminata. Riaggiorna più tardi e riprova."
    }
  },
  "ja": {
    "action": {
      "revoke": "無効化する"
    },
    "revoked": "無効",
    "unavailable": {
      "text": "まだ利用できません。",
      "title": "一般公開リンクはまだ利用できません。処理が終了していません。後ほどページを更新し、もう一度試して下さい。"
    }
  },
  "pt": {
    "action": {
      "revoke": "Revogar"
    },
    "revoked": "Revogado",
    "unavailable": {
      "text": "Não disponível ainda",
      "title": "O link de acesso público não está disponível ainda. Ele não terminou de ser processado. Por favor atualize a página mais tarde e tente novamente."
    }
  },
  "sw": {
    "action": {
      "revoke": "Batilisha"
    },
    "revoked": "Imebatilishwa",
    "unavailable": {
      "text": "Haipatikani bado",
      "title": "Kiungo cha Ufikiaji wa Umma bado hakipatikani. Haijamaliza kuchakatwa. Tafadhali onyesha upya baadaye na ujaribu tena."
    }
  },
  "zh": {
    "action": {
      "revoke": "撤销"
    },
    "revoked": "已撤销",
    "unavailable": {
      "text": "暂时不可用",
      "title": "公开访问链接尚不可用，仍在处理中。请稍后刷新重试。"
    }
  },
  "zh-Hant": {
    "action": {
      "revoke": "撤銷"
    },
    "revoked": "已撤銷",
    "unavailable": {
      "text": "還不可用",
      "title": "公共訪問連結尚不可用。它尚未完成處理。請稍後刷新並重試。"
    }
  }
}
</i18n>
