<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <form-edit-section icon="pencil">
    <template #title>{{ $t('title') }}</template>
    <template #subtitle>{{ $t('subtitle') }}</template>
    <template #body>
      <button id="form-edit-create-draft-button" type="button"
        class="btn btn-primary" :aria-disabled="awaitingResponse"
        @click="create">
        <span class="icon-pencil"></span>{{ $t('action.create') }}
        <spinner :state="awaitingResponse"/>
      </button>
      <p>{{ $t('toMakeChanges') }}</p>
      <p>{{ $t('noEffectUntilPublish') }}</p>
    </template>
  </form-edit-section>
</template>

<script setup>
import { inject } from 'vue';

import FormEditSection from './section.vue';
import Spinner from '../../spinner.vue';

import useRequest from '../../../composables/request';
import { apiPaths } from '../../../util/request';
import { noop } from '../../../util/util';

defineOptions({
  name: 'FormEditCreateDraft'
});
const emit = defineEmits(['success']);

const { request, awaitingResponse } = useRequest();
const projectId = inject('projectId');
const xmlFormId = inject('xmlFormId');
const create = () => {
  request({
    method: 'POST',
    url: apiPaths.formDraft(projectId, xmlFormId)
  })
    .then(() => { emit('success'); })
    .catch(noop);
};
</script>

<style lang="scss">
#form-edit-create-draft-button {
  font-size: 14px;

  ~ p { color: #666; }
  + p { margin-block: 3px 0; }
}
</style>

<i18n lang="json5">
{
  "en": {
    // This refers to the draft version of a Form.
    "title": "Draft version",
    "subtitle": "No active Draft for this Form",
    "action": {
      // @transifexKey component.FormHead.draftNav.action.create
      "create": "Create a new Draft"
    },
    // This text is shown below a button with the text "Create a new Draft".
    "toMakeChanges": "to make changes to this Form or its attachments.",
    "noEffectUntilPublish": "The published version will not be affected until you publish your Draft."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "action": {
      "create": "Vytvořit nový koncept"
    }
  },
  "de": {
    "title": "Entwurfsversion",
    "subtitle": "Kein aktiver Entwurf für dieses Formular",
    "toMakeChanges": "um Änderungen an diesem Formular oder seinen Anlagen vorzunehmen.",
    "noEffectUntilPublish": "Die veröffentlichte Version wird nicht beeinflusst, bis Sie Ihren Entwurf veröffentlichen.",
    "action": {
      "create": "Neuen Entwurf erstellen"
    }
  },
  "es": {
    "title": "Versión borrador",
    "subtitle": "No hay borrador activo para este formulario",
    "toMakeChanges": "para realizar cambios en este formulario o en sus anexos.",
    "noEffectUntilPublish": "La versión publicada no se verá afectada hasta que publique su Borrador.",
    "action": {
      "create": "Crear un nuevo borrador"
    }
  },
  "fr": {
    "title": "Version de l'ébauche",
    "subtitle": "Pas d'ébauche active pour ce formulaire",
    "toMakeChanges": "pour modifier ce Formulaire ou ses fichiers joints",
    "noEffectUntilPublish": "La version publiée ne sera pas affectée tant que vous n'aurez pas publié votre ébauche.",
    "action": {
      "create": "Créer une nouvelle ébauche"
    }
  },
  "id": {
    "action": {
      "create": "Buat draf baru"
    }
  },
  "it": {
    "title": "Versione bozza",
    "subtitle": "Nessuna bozza attiva per questo formulario",
    "toMakeChanges": "per apportare modifiche al presente Formulario o ai suoi allegati.",
    "noEffectUntilPublish": "La versione pubblicata non verrà modificata fino alla pubblicazione della bozza.",
    "action": {
      "create": "Crea una nuova bozza"
    }
  },
  "ja": {
    "action": {
      "create": "新規下書きの作成"
    }
  },
  "pt": {
    "title": "Versão Rascunho",
    "subtitle": "Não há Rascunho ativo para esse Formulário",
    "toMakeChanges": "para alterar esse Formulário ou seus anexos.",
    "noEffectUntilPublish": "A versão publicada não será afetada até que você publique o seu Rascunho.",
    "action": {
      "create": "Criar um novo rascunho"
    }
  },
  "sw": {
    "action": {
      "create": "Unda Rasimu mpya"
    }
  },
  "zh": {
    "title": "草稿版本",
    "subtitle": "此表单无活跃草稿",
    "toMakeChanges": "以修改此表单或其附件。",
    "noEffectUntilPublish": "在您发布草稿之前，已发布版本不会受到影响。",
    "action": {
      "create": "创建新草稿"
    }
  },
  "zh-Hant": {
    "title": "草稿版本",
    "subtitle": "此表格無活動草稿",
    "toMakeChanges": "以變更本表格或其附件。",
    "noEffectUntilPublish": "在您發布草稿之前，已發佈的版本不會受到影響。",
    "action": {
      "create": "建立新草稿"
    }
  }
}
</i18n>
