<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="form-edit-def" class="container">
    <div class="row form-edit-def-header">
      <div class="col-xs-6">
        <i18n-t keypath="title" tag="div" class="form-edit-section-title">
          <template #version>
            <form-version-string :version="formDraft.version"/>
          </template>
        </i18n-t>

        <div v-if="changed" class="form-edit-section-subtitle">{{ $t('changed') }}</div>
        <div v-else class="form-edit-section-subtitle">{{ $t('subtitle') }}</div>
      </div>
      <div class="col-xs-6 text-right">
        <form-version-def-dropdown :version="formDraft" outlined
            @view-xml="viewXml.show()"/>
      </div>
    </div>
    <div class="row form-edit-def-upload">
      <form-upload @success="afterUpload"/>
    </div>
  </div>

  <form-version-view-xml v-bind="viewXml" @hide="viewXml.hide()"/>
</template>

<script setup>
import { computed, defineAsyncComponent } from 'vue';

import FormVersionDefDropdown from '../../form-version/def-dropdown.vue';
import FormVersionString from '../../form-version/string.vue';
import FormUpload from '../upload.vue';

import { loadAsync } from '../../../util/load-async';
import { modalData } from '../../../util/reactivity';
import { useRequestData } from '../../../request-data';

defineOptions({
  name: 'FormEditDef'
});

const emits = defineEmits(['afterUpload']);
const { form, resourceView } = useRequestData();
const formDraft = resourceView('formDraft', (data) => data.get());

const changed = computed(() =>
  form.dataExists && form.publishedAt != null && formDraft.hash !== form.hash);

const FormVersionViewXml = defineAsyncComponent(loadAsync('FormVersionViewXml'));
const viewXml = modalData('FormVersionViewXml');

const afterUpload = () => {
  emits('afterUpload');
};

</script>

<style lang="scss">
#form-edit-def {
  width: 100%;
  .form-edit-def-header .col-xs-6 { padding: 0; }
  .form-edit-def-upload { margin-top: 10px; }
}
</style>

<i18n lang="json5">
{
  "en": {
    "uploadSection": {
      // @transifexKey component.FormNew.title.update
      // This is the title at the top of a section.
      "title": "Upload New Form Definition"
    },
    "title": "Draft version: {version}",
    // This refers to the draft version of a Form.
    "subtitle": "Uploaded",
    // This refers to the draft version of a Form.
    "changed": "Changed from published version",
    // This is shown for a Form version.
    "versionName": "Version name: {name}",
    "action": {
      "upload": "Upload new Form Definition"
    },
    // This text is shown above a list of items that are part of the Form
    // Definition.
    "withinDef": "Within this Form Definition:"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "subtitle": "Hochgeladen",
    "changed": "Geändert gegenüber der veröffentlichten Version",
    "versionName": "Versionsname:{name}",
    "action": {
      "upload": "Neue Formulardefinition hochladen"
    },
    "withinDef": "Innerhalb dieser Formulardefinition:",
    "title": "Entwurfsversion"
  },
  "es": {
    "subtitle": "Subido",
    "changed": "Cambiado respecto a la versión publicada",
    "versionName": "Nombre de la versión: {name}",
    "action": {
      "upload": "Cargar nueva definición de formulario"
    },
    "withinDef": "Dentro de esta definición de formulario:",
    "title": "Versión borrador"
  },
  "fr": {
    "subtitle": "Téléversée",
    "changed": "Différente de la version publiée",
    "versionName": "Nom de version : {name}",
    "action": {
      "upload": "Téléverser une nouvelle définition de formulaire"
    },
    "withinDef": "Dans cette définition de formulaire",
    "title": "Version de l'ébauche"
  },
  "it": {
    "subtitle": "Caricati",
    "changed": "Modificato rispetto alla versione pubblicata",
    "versionName": "Nome della versione: {name}",
    "action": {
      "upload": "Carica la nuova definizione del formulario"
    },
    "withinDef": "All'interno di questa definizione del formulario:",
    "title": "Versione bozza"
  },
  "pt": {
    "subtitle": "Carregado",
    "changed": "Mudanças em relação à versão publicada",
    "versionName": "Nome da versão: {name}",
    "action": {
      "upload": "Carregar nova Definição do Formulário"
    },
    "withinDef": "Nesta Definição de Formulário:",
    "title": "Versão Rascunho"
  },
  "zh": {
    "subtitle": "已上传",
    "changed": "自发布版本以来",
    "versionName": "版本名称：{name}",
    "action": {
      "upload": "上传新表单定义"
    },
    "withinDef": "在此表单定义中：",
    "title": "草稿版本"
  },
  "zh-Hant": {
    "subtitle": "已上傳",
    "changed": "與發布版本相比有變更",
    "versionName": "版本名稱：{name}",
    "action": {
      "upload": "上傳新表單定義"
    },
    "withinDef": "在此表格定義內：",
    "title": "草稿版本"
  }
}
</i18n>
