<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <form-edit-section id="form-edit-def" no-border>
    <template #title>
      <i18n-t keypath="title">
        <template #version>
          <form-version-string :version="formDraft.version"/>
        </template>
      </i18n-t>
    </template>
    <template #subtitle>{{ $t('subtitle') }}</template>
    <template v-if="changed" #tag>{{ $t('changed') }}</template>
    <template #actions>
      <enketo-preview :form-version="formDraft" outlined/>
      <form-version-def-dropdown :version="formDraft" outlined @view-xml="viewXml.show()"/>
    </template>
    <template #body>
      <div>
        <div class="form-edit-section-body">
          <form-upload @success="afterUpload"/>
        </div>
      </div>
    </template>
  </form-edit-section>

  <form-version-view-xml v-bind="viewXml" @hide="viewXml.hide()"/>
</template>

<script setup>
import { computed, defineAsyncComponent } from 'vue';

import EnketoPreview from '../../enketo/preview.vue';
import FormEditSection from './section.vue';
import FormVersionDefDropdown from '../../form-version/def-dropdown.vue';
import FormUpload from '../upload.vue';
import FormVersionString from '../../form-version/string.vue';

import { loadAsync } from '../../../util/load-async';
import { modalData } from '../../../util/reactivity';
import { useRequestData } from '../../../request-data';

defineOptions({
  name: 'FormEditDef'
});

const emits = defineEmits(['afterUpload']);
const { form, resourceView } = useRequestData();
const formDraft = resourceView('formDraft', (data) => data.get());

const changed = computed(() =>
  form.dataExists && form.publishedAt != null && formDraft.hash !== form.hash);

const FormVersionViewXml = defineAsyncComponent(loadAsync('FormVersionViewXml'));
const viewXml = modalData('FormVersionViewXml');

const afterUpload = () => {
  emits('afterUpload');
};

</script>

<style lang="scss">
#form-edit-def .form-edit-section-actions .form-version-def-dropdown { margin-left: 5px; }
</style>

<i18n lang="json5">
{
  "en": {
    // This is shown for the Draft Form. {version} is the version of the Form defined in its definition.
    "title": "Draft version: {version}",
    // This refers to the draft version of a Form.
    "subtitle": "Uploaded",
    // This refers to the draft version of a Form.
    "changed": "Changed from published version"
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "subtitle": "Hochgeladen",
    "changed": "Geändert gegenüber der veröffentlichten Version"
  },
  "es": {
    "subtitle": "Subido",
    "changed": "Cambiado respecto a la versión publicada"
  },
  "fr": {
    "title": "Version de de l'ébauche: {version}",
    "subtitle": "Téléversée",
    "changed": "Différente de la version publiée"
  },
  "it": {
    "subtitle": "Caricati",
    "changed": "Modificato rispetto alla versione pubblicata"
  },
  "pt": {
    "subtitle": "Carregado",
    "changed": "Mudanças em relação à versão publicada"
  },
  "zh": {
    "subtitle": "已上传",
    "changed": "自发布版本以来"
  },
  "zh-Hant": {
    "subtitle": "已上傳",
    "changed": "與發布版本相比有變更"
  }
}
</i18n>
