<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div id="form-edit-draft-controls">
    <div class="title">{{ $t('title') }}</div>
    <div>
      <button id="form-edit-abandon-button" type="button" class="btn btn-danger-outlined"
        @click="$emit('abandon')">
        <span class="icon-trash"></span>{{ abandonText }}
      </button>
      <button id="form-edit-publish-button" type="button"
        class="btn btn-primary" @click="$emit('publish')">
        <span class="icon-star"></span>{{ $t('action.publish') }}
      </button>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { useRequestData } from '../../../request-data';

defineOptions({
  name: 'FormEditDraftControls'
});
defineEmits(['abandon', 'publish']);

const { form } = useRequestData();

const { t } = useI18n();
const abandonText = computed(() => (!form.dataExists
  ? ''
  : (form.publishedAt == null ? t('action.delete') : t('action.abandon'))));
</script>

<style lang="scss">
#form-edit-draft-controls {
  text-align: center;
  margin: 20px 0;

  .title {
    font-size: 16px;
    font-weight: bold;
    line-height: 1.2;
    margin-bottom: 20px;
  }

  #form-edit-publish-button { margin-left: 10px; }
}
</style>

<i18n lang="json5">
{
  "en": {
    // @transifexKey component.FormEditDraftControls.subtitle
    // This refers to the draft version of a Form.
    "title": "Ready to publish?",
    "action": {
      "delete": "Delete Form",
      // @transifexKey component.FormDraftStatus.actions.action.abandon
      "abandon": "Abandon Draft",
      // @transifexKey component.FormDraftStatus.actions.action.publish
      "publish": "Publish Draft"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "action": {
      "publish": "Publikovat koncept",
      "abandon": "Opustit koncept"
    }
  },
  "de": {
    "action": {
      "delete": "Formulare löschen",
      "publish": "Entwurf veröffentlichen",
      "abandon": "Entwurf verwerfen"
    }
  },
  "es": {
    "action": {
      "delete": "Borrar formulario",
      "publish": "Publicar borrador",
      "abandon": "Abandonar borrador"
    }
  },
  "fr": {
    "action": {
      "delete": "Supprimer le formulaire",
      "publish": "Publier l'ébauche",
      "abandon": "Abandonner l'ébauche"
    },
    "title": "Prêt à publier?"
  },
  "id": {
    "action": {
      "publish": "Terbitkan Draf",
      "abandon": "Buang Draf"
    }
  },
  "it": {
    "action": {
      "delete": "Cancellare il formulario",
      "publish": "Pubblicare la bozza",
      "abandon": "Abbandonare la bozza"
    }
  },
  "ja": {
    "action": {
      "publish": "下書きの公開",
      "abandon": "下書きの削除"
    }
  },
  "pt": {
    "action": {
      "delete": "Excluir Formulário",
      "publish": "Publicar rascunho",
      "abandon": "Abandonar rascunho"
    }
  },
  "sw": {
    "action": {
      "publish": "Chapisha Rasimu",
      "abandon": "Achana na Rasimu"
    }
  },
  "zh": {
    "action": {
      "delete": "删除表单",
      "publish": "发布草稿",
      "abandon": "放弃草稿"
    }
  },
  "zh-Hant": {
    "action": {
      "delete": "刪除表單",
      "publish": "發布草稿",
      "abandon": "放棄草案"
    }
  }
}
</i18n>
