<!--
Copyright 2025 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <form-edit-section id="form-edit-published-version" no-border>
    <template #title>
      <i18n-t keypath="title">
        <template #version>
          <form-version-string :version="form.version"/>
        </template>
      </i18n-t>
    </template>
    <template #subtitle>
      <i18n-t keypath="subtitle.published">
        <template #dateTime>
          <date-time :iso="form.publishedAt"/>
        </template>
      </i18n-t>
    </template>
  </form-edit-section>
</template>

<script setup>
import DateTime from '../../date-time.vue';
import FormEditSection from './section.vue';
import FormVersionString from '../../form-version/string.vue';

import { useRequestData } from '../../../request-data';

defineOptions({
  name: 'FormEditPublishedVersion'
});

// The component assumes that this data will exist when the component is
// created.
const { form } = useRequestData();
</script>

<i18n lang="json5">
{
  "en": {
    // This refers to the current version of a Form. {version} is the version of the published Form, defined in its definition.
    "title": "Current version: {version}",
    "subtitle": {
      // This shows the date and time at which the current version of the Form
      // was published, for example: "Published 2020/01/01 01:23". {dateTime}
      // may show a formatted date like "2020/01/01", or it may use a word like
      // "today", "yesterday", or "Sunday".
      "published": "Published {dateTime}"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "de": {
    "subtitle": {
      "published": "Veröffentlicht {dateTime}"
    }
  },
  "es": {
    "subtitle": {
      "published": "Publicado en {dateTime}"
    }
  },
  "fr": {
    "title": "Version courante: {version}",
    "subtitle": {
      "published": "Publiée {dateTime}"
    }
  },
  "it": {
    "subtitle": {
      "published": "Pubblicato {dateTime}"
    }
  },
  "pt": {
    "subtitle": {
      "published": "Publicado em {dateTime}"
    }
  },
  "zh": {
    "subtitle": {
      "published": "{dateTime}已发布"
    }
  },
  "zh-Hant": {
    "subtitle": {
      "published": "{dateTime}已發布"
    }
  }
}
</i18n>
