<template>
  <form-edit-section id="form-edit-web-form" no-border>
    <template #title>{{ $t('title') }}</template>
    <template #body>
      <i18n-t tag="p" keypath="description.full" class="form-edit-web-form-description">
        <template #learnMore>
          <doc-link to="web-forms-intro#features-not-yet-supported">{{ $t('description.learnMore') }}</doc-link>
        </template>
      </i18n-t>
      <radio-field v-model="webformsEnabled" :options="options"
        class="form-edit-web-form-options" :disabled="awaitingResponse"
        :disabled-message="$t('common.updateInProgress')"
        @update:model-value="update"/>
    </template>
  </form-edit-section>
</template>

<script setup>
import { computed, inject, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import DocLink from '../../doc-link.vue';
import FormEditSection from './section.vue';
import RadioField from '../../radio-field.vue';

import useRequest from '../../../composables/request';
import { apiPaths } from '../../../util/request';
import { useRequestData } from '../../../request-data';

defineOptions({
  name: 'FormEditWebForm'
});

const projectId = inject('projectId');
const xmlFormId = inject('xmlFormId');

const { resourceView } = useRequestData();
const formDraft = resourceView('formDraft', (data) => data.get());

const { request, awaitingResponse } = useRequest();

// formDraft exists and is defined.
const webformsEnabled = ref(formDraft.webformsEnabled);

const { t } = useI18n();
const { alert } = inject('container');


const options = computed(() => [
  { value: true, text: `ODK Web Forms (${t('common.recommended')})` },
  { value: false, text: t('common.useEnketo') }
]);

const update = (newVal) => {
  request.patch(
    apiPaths.form(projectId, xmlFormId),
    { webformsEnabled: newVal }
  )
    .then(() => {
      formDraft.webformsEnabled = newVal;
      alert.success(t('alert.settingSaved'));
    })
    .catch(() => {
      webformsEnabled.value = formDraft.webformsEnabled;
    });
};
</script>

<style lang="scss">
@import '../../../assets/scss/variables';

#form-edit-web-form {
  background-color: $color-success-light;
  border-radius: 12px;
  padding: 20px;

  .form-edit-web-form-description {
    margin-bottom: 18px;
    max-width: unset;
  }

  .form-edit-web-form-options {
    margin-top: 12px;
    display: inline;

    .radio {
      margin-bottom: 6px;
      margin-top: 6px;
      padding-left: 20px;
      width: max-content;
    }
  }
}
</style>

<i18n lang="json5">
{
  "en": {
    "title": "New default web form experience",
    "description": {
      "full": "Newly created Forms now use the ODK Web Forms experience by default for previews, web submissions and submission editing. Some advanced form features may not yet be fully supported, {learnMore}.",
      "learnMore": "learn more"
    },
    "alert": {
      "settingSaved": "Draft Form setting saved."
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "fr": {
    "title": "Nouvelle expérience de formulaire web par défaut",
    "description": {
      "full": "Les formulaires nouvellement créés utilisent désormais par défaut l'interface ODK Web Forms pour les aperçus, les soumissions web et la modification des soumissions. Certaines fonctionnalités avancées des formulaires ne sont pas encore disponibles, {learnMore}.",
      "learnMore": "en savoir plus."
    },
    "alert": {
      "settingSaved": "Paramètres de l'ébauche enregistrés."
    }
  }
}
</i18n>
