name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'
  pull_request:

jobs:
  check-and-build:
    name: 'Static check and build'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: sudo apt-get install shellcheck
    - run: ./bin/check-scripts.sh
    - run: ./bin/check-for-large-files.sh
    - run: ./bin/check-images.sh
    - uses: actions/setup-node@v6
      id: setup-node
      with:
        node-version-file: package.json
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run lint -w=@getodk/central-frontend
    - run: ./bin/check-bundle-size.js

    # ids, keys, paths must all match the values in actions/restore-node
    - uses: 'actions/cache/save@v6'
      id: cache-install
      with:
        path: |
          node_modules
          **/node_modules
        key: install-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json', '.npmrc', '.github/workflows/*.yml', 'packages/*/package.json', 'packages/*/package-lock.json') }}

    - uses: 'actions/cache/save@v6'
      id: cache-build
      with:
        path: |
          dist
          packages/*/dist
        key: build-${{ github.sha }}
    - name: Upload Release Artefact
      if: github.ref_type == 'tag'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        tar -cvzf dist-${{ github.ref_name }}.tar.gz dist/
        echo "Uploading dist bundle..."
        gh release upload ${{ github.ref_name }} dist-${{ github.ref_name }}.tar.gz
        echo "Upload complete."

  test-central-app:
    name: 'Test central app'
    needs:
    - check-and-build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/restore-node
    - run: npm run test -w=@getodk/central-frontend
