name: Tests

on:
  push:
  pull_request:

jobs:
  playwright-install-azure:
    strategy:
      fail-fast: false
      matrix:
        x: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
        y: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get remove --purge man-db
    - uses: actions/checkout@v6
    - name: Set node version
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
    - run: npm ci
    - run: sudo apt-get update
    - run: npx playwright install --with-deps chromium-headless-shell

  playwright-install-no-azure:
    strategy:
      fail-fast: false
      matrix:
        x: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
        y: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get remove --purge man-db
    - uses: actions/checkout@v6
    - name: Set node version
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
    - run: npm ci
    - name: remove azure ubuntu mirrors
      run: |
        sudo sed \
             -i \
             -e '/archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:2/priority:0/' \
             -e '/azure.archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:0/priority:1/' \
             -e '/security.ubuntu.com\/ubuntu\/\tpriority/ s/priority:3/priority:2/' \
             /etc/apt/apt-mirrors.txt
    - run: sudo apt-get update
    - run: npx playwright install --with-deps chromium-headless-shell
