name: ODK Web Forms CI

on:
  workflow_call:

# Automatically cancel older in-progress jobs on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

env:
  TZ: 'America/Phoenix'
  LOCALE_ID: 'en-US'

jobs:

  odk-common:
    name: 'common'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 2

    strategy:
      fail-fast: false
      matrix:
        target: ['Node']
        node-version: ['24.16.0']
        include:
          - target: 'Web'
            node-version: '24.16.0'
            browser: chromium
          - target: 'Web'
            node-version: '24.16.0'
            browser: firefox
          - target: 'Web'
            node-version: '24.16.0'
            browser: webkit

    steps:
      - uses: 'actions/checkout@v6'

      - uses: 'volta-cli/action@v5'
        with:
          node-version: '${{ matrix.node-version }}'

      - uses: 'actions/cache@v6'
        id: cache-install
        with:
          path: |
            node_modules
            **/node_modules
          key: install-${{ matrix.node-version }}-${{ hashFiles('package-lock.json', '.npmrc', '.github/workflows/*.yml', 'packages/*/package.json', 'packages/*/package-lock.json') }}

      - uses: 'actions/cache@v6'
        id: cache-build
        with:
          path: |
            dist
            packages/*/dist
          key: build-${{ github.sha }}
          fail-on-cache-miss: true

      - name: 'npm ci'
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: npm ci

      - if: ${{ matrix.target == 'Node' }}
        run: 'npm run test:types -w packages/common'

      - if: ${{ matrix.target == 'Node' }}
        run: 'npm run test-node:jsdom -w packages/common'

      - if: ${{ matrix.target == 'Web' }}
        run: 'npx playwright install ${{ matrix.browser }} --with-deps'

      - if: ${{ matrix.target == 'Web' }}
        run: 'npm run test-browser:${{ matrix.browser }} -w packages/common'

  xforms-engine:
    name: 'xforms-engine'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 3

    strategy:
      fail-fast: false
      matrix:
        target: ['Node']
        node-version: ['24.16.0']
        include:
          - target: 'Web'
            node-version: '24.16.0'
            browser: chromium
          - target: 'Web'
            node-version: '24.16.0'
            browser: firefox
          - target: 'Web'
            node-version: '24.16.0'
            browser: webkit

    steps:
      - uses: 'actions/checkout@v6'

      - uses: 'volta-cli/action@v5'
        with:
          node-version: '${{ matrix.node-version }}'

      - uses: 'actions/cache@v6'
        id: cache-install
        with:
          path: |
            node_modules
            **/node_modules
          key: install-${{ matrix.node-version }}-${{ hashFiles('package-lock.json', '.npmrc', '.github/workflows/*.yml', 'packages/*/package.json', 'packages/*/package-lock.json') }}
      - uses: 'actions/cache@v6'
        id: cache-build
        with:
          path: |
            dist
            packages/*/dist
          key: build-${{ github.sha }}
          fail-on-cache-miss: true

      - name: 'npm ci'
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: npm ci

      - if: ${{ matrix.target == 'Node' }}
        run: |
          npm run test:types -w=packages/xforms-engine
          npm run test-node:jsdom -w=packages/xforms-engine
          npm run integration-test-node:jsdom -w=packages/xforms-engine

      - if: ${{ matrix.target == 'Web' }}
        run: |
          npx playwright install ${{ matrix.browser }} --with-deps
          npm run test-browser:${{ matrix.browser }} -w=packages/xforms-engine
          npm run integration-test-browser:${{ matrix.browser }} -w=packages/xforms-engine

  xpath:
    name: 'xpath'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 2

    strategy:
      fail-fast: false
      matrix:
        target: ['Node']
        node-version: ['24.16.0']
        include:
          - target: 'Web'
            node-version: '24.16.0'
            browser: chromium
          - target: 'Web'
            node-version: '24.16.0'
            browser: firefox
          - target: 'Web'
            node-version: '24.16.0'
            browser: webkit

    steps:
      - uses: 'actions/checkout@v6'

      - uses: 'volta-cli/action@v5'
        with:
          node-version: '${{ matrix.node-version }}'

      - uses: 'actions/cache@v6'
        id: cache-install
        with:
          path: |
            node_modules
            **/node_modules
          key: install-${{ matrix.node-version }}-${{ hashFiles('package-lock.json', '.npmrc', '.github/workflows/*.yml', 'packages/*/package.json', 'packages/*/package-lock.json') }}
      - uses: 'actions/cache@v6'
        id: cache-build
        with:
          path: |
            dist
            packages/*/dist
          key: build-${{ github.sha }}
          fail-on-cache-miss: true

      - name: 'npm ci'
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: npm ci

      - if: ${{ matrix.target == 'Node' }}
        run: 'npm run test:types -w=packages/xpath'

      - if: ${{ matrix.target == 'Node' }}
        run: 'npm run test-node:jsdom -w=packages/xpath'

      - if: ${{ matrix.target == 'Web' }}
        run: 'npx playwright install ${{ matrix.browser }} --with-deps'

      - if: ${{ matrix.target == 'Web' }}
        run: 'npm run test-browser:${{ matrix.browser }} -w=packages/xpath'

  web-forms:
    name: 'web-forms'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 2

    strategy:
      fail-fast: false
      matrix:
        target: ['Node']
        node-version: ['24.16.0']
        include:
          - target: 'Web'
            node-version: '24.16.0'
            browser: chromium
          - target: 'Web'
            node-version: '24.16.0'
            browser: firefox
          - target: 'Web'
            node-version: '24.16.0'
            browser: webkit

    steps:
      - uses: 'actions/checkout@v6'

      - uses: 'volta-cli/action@v5'
        with:
          node-version: '${{ matrix.node-version }}'

      - uses: 'actions/cache@v6'
        id: cache-install
        with:
          path: |
            node_modules
            **/node_modules
          key: install-${{ matrix.node-version }}-${{ hashFiles('package-lock.json', '.npmrc', '.github/workflows/*.yml', 'packages/*/package.json', 'packages/*/package-lock.json') }}
      - uses: 'actions/cache@v6'
        id: cache-build
        with:
          path: |
            dist
            packages/*/dist
          key: build-${{ github.sha }}
          fail-on-cache-miss: true

      - name: 'npm ci'
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: npm ci

      - if: ${{ matrix.target == 'Node' }}
        run: 'npm run test:types -w=packages/web-forms'

      - if: ${{ matrix.target == 'Node' }}
        run: 'npm run test-node:jsdom -w=packages/web-forms'

      - if: ${{ matrix.target == 'Web' }}
        run: 'npx playwright install ${{ matrix.browser }} --with-deps'

      - if: ${{ matrix.target == 'Web' && matrix.browser != 'webkit' }}
        run: 'npm run test-browser:${{ matrix.browser }} -w=packages/web-forms'
